"""TOEIC frequent vocabulary (600 / 700 / 800 target), with example sentences.

Vetted for spelling and meaning; Japanese kept concise. Examples are written
to use the word naturally at a TOEIC-appropriate level. Duplicates against the
base seed (app/seed_data.py) are skipped automatically at load time.

Notable corrections from the source list:
- "incidence" : 発声 → 発生(率) (typo fixed)
- "estate"    : 財産 → 財産・不動産
- "bear"      : 産む → 耐える・(子を)産む

Format: (english, japanese, part_of_speech, example)
"""

from __future__ import annotations

TOEIC_WORDS: list[tuple[str, str, str, str]] = [
    # ===== 600点レベル =====
    ("accommodate", "収容する・宿泊させる", "動詞",
     "The hotel can accommodate 500 guests."),
    ("accounting", "会計・経理", "名詞",
     "She works in the accounting department."),
    ("actually", "実際に・本当は", "副詞", "Actually, I disagree with that."),
    ("additional", "追加の", "形容詞", "There is no additional charge."),
    ("administration", "管理・運営・行政", "名詞",
     "He works in hospital administration."),
    ("advance", "前進・進める", "名詞/動詞", "Please pay in advance."),
    ("advertising", "広告", "名詞", "We increased our advertising budget."),
    ("afford", "余裕がある", "動詞", "We can't afford a new car."),
    ("analyst", "分析者・アナリスト", "名詞", "She is a financial analyst."),
    ("annual", "年1回の・毎年の", "形容詞", "We hold an annual meeting."),
    ("appear", "現れる・〜に見える", "動詞", "He appears to be tired."),
    ("applicant", "応募者・志願者", "名詞", "We interviewed five applicants."),
    ("appreciate", "高く評価する・感謝する", "動詞", "I appreciate your help."),
    ("architect", "建築家", "名詞",
     "The architect designed a modern office."),
    ("attract", "引き付ける", "動詞", "The event attracted many visitors."),
    ("cater", "料理を提供する", "動詞", "They cater for large events."),
    ("compare", "比較する", "動詞", "Let's compare the two plans."),
    ("complicated", "複雑な", "形容詞", "This is a complicated problem."),
    ("concern", "関係する・心配・懸念", "名詞/動詞",
     "Safety is our main concern."),
    ("conference", "会議", "名詞",
     "She attended an international conference."),
    ("consumer", "消費者", "名詞", "Consumer demand is rising."),
    ("contract", "契約・契約書", "名詞", "We signed a two-year contract."),
    ("current", "現在の", "形容詞", "What is your current address?"),
    ("decide", "決定する", "動詞", "We need to decide today."),
    ("delay", "遅らせる・遅延", "動詞/名詞", "The flight was delayed."),
    ("delighted", "喜んで", "形容詞", "I'm delighted to meet you."),
    ("designate", "指名する・指定する", "動詞",
     "This is a designated smoking area."),
    ("develop", "発達させる・開発する", "動詞", "We developed a new app."),
    ("donate", "寄付する", "動詞", "They donated money to charity."),
    ("eliminate", "取り除く・排除する", "動詞", "We must eliminate waste."),
    ("encourage", "励ます・促進する", "動詞",
     "We encourage employees to learn."),
    ("enroll", "登録する・入学する", "動詞",
     "She enrolled in an English course."),
    ("estate", "財産・不動産", "名詞", "He works in real estate."),
    ("exceed", "超える", "動詞", "Sales exceeded our expectations."),
    ("except", "〜を除いて", "前置詞", "We work every day except Sunday."),
    ("executive", "経営幹部・役員", "名詞", "She is a senior executive."),
    ("exhibit", "展示する", "動詞", "The museum exhibits modern art."),
    ("expect", "予期する・期待する", "動詞", "We expect good results."),
    ("expertise", "専門知識", "名詞", "He has expertise in marketing."),
    ("explain", "説明する", "動詞", "Please explain the process."),
    ("facility", "設備・施設", "名詞", "The factory has modern facilities."),
    ("fail", "失敗する・しそこなう", "動詞", "Don't fail to call me."),
    ("fee", "料金・手数料", "名詞", "There is a small service fee."),
    ("figure", "数字・図・人物", "名詞", "Sales figures improved."),
    ("frequent", "頻繁な", "形容詞", "He is a frequent traveler."),
    ("further", "さらなる・さらに", "形容詞/副詞",
     "We need further information."),
    ("handle", "扱う・処理する・取っ手", "動詞/名詞",
     "She handles customer complaints."),
    ("identification", "身分証明", "名詞", "Please show identification."),
    ("include", "含む", "動詞", "The price includes tax."),
    ("inquire", "問い合わせる", "動詞",
     "I'd like to inquire about the job."),
    ("instantly", "すぐに・即座に", "副詞", "The page loads instantly."),
    ("insurance", "保険", "名詞", "Do you have travel insurance?"),
    ("invest", "投資する", "動詞", "They invested in new technology."),
    ("invite", "招待する", "動詞", "We invited all the clients."),
    ("involve", "含む・巻き込む", "動詞", "The job involves travel."),
    ("manufacture", "製造する", "動詞", "They manufacture car parts."),
    ("miss", "逃す・取りそこなう", "動詞", "Don't miss the deadline."),
    ("notice", "気づく・通知", "動詞/名詞", "I didn't notice the error."),
    ("offer", "提供する・申し出", "動詞/名詞", "They offered me a job."),
    ("owe", "借りがある・負っている", "動詞", "I owe you ten dollars."),
    ("passenger", "乗客", "名詞", "The plane carries 200 passengers."),
    ("plenty", "たくさん・豊富", "名詞", "We have plenty of time."),
    ("preservation", "保存・維持", "名詞", "Food preservation is important."),
    ("proceed", "進む・続行する", "動詞", "Please proceed to gate 5."),
    ("promote", "昇進させる・促進する", "動詞",
     "She was promoted to manager."),
    ("prosperous", "繁栄する", "形容詞", "It was a prosperous year."),
    ("publicity", "宣伝・世間の注目", "名詞",
     "The product got good publicity."),
    ("remind", "思い出させる", "動詞", "Please remind me later."),
    ("remove", "取り除く・移動させる", "動詞", "Please remove your shoes."),
    ("replacement", "交換・後任", "名詞", "We ordered a replacement part."),
    ("representative", "代表・担当者", "名詞",
     "A sales representative will call you."),
    ("result", "結果", "名詞", "The result was positive."),
    ("review", "見直す・批評する", "動詞/名詞",
     "Please review the document."),
    ("severe", "厳しい・ひどい", "形容詞", "She has a severe headache."),
    ("shipment", "発送・出荷", "名詞", "The shipment arrived late."),
    ("shortage", "不足", "名詞", "There is a labor shortage."),
    ("store", "蓄える・店", "動詞/名詞", "Store the files safely."),
    ("survey", "調査・概観する", "名詞/動詞",
     "We conducted a customer survey."),
    ("transportation", "輸送・交通機関", "名詞",
     "Public transportation is cheap here."),
    ("voucher", "クーポン・引換券", "名詞",
     "Use this voucher for a discount."),
    ("workplace", "職場", "名詞", "Safety in the workplace is vital."),
    ("workshop", "作業場・講習会", "名詞", "I attended a writing workshop."),

    # ===== 700点レベル =====
    ("acquisition", "獲得・買収", "名詞",
     "The acquisition was completed last year."),
    ("admit", "認める・入れる", "動詞", "He admitted his mistake."),
    ("annex", "別館・付加する", "名詞/動詞",
     "The library annex opens in May."),
    ("appliance", "電気製品・器具", "名詞", "We sell kitchen appliances."),
    ("appropriately", "適切に", "副詞", "Please dress appropriately."),
    ("approximately", "おおよそ", "副詞", "It costs approximately $50."),
    ("aspect", "面・側面", "名詞", "Consider every aspect of the plan."),
    ("auditorium", "講堂・観客席", "名詞",
     "The auditorium seats 1,000 people."),
    ("bid", "入札・値をつける", "名詞/動詞", "They made a high bid."),
    ("brochure", "パンフレット", "名詞", "Please take a brochure."),
    ("candidate", "候補者", "名詞", "She is a strong candidate."),
    ("cardboard", "厚紙・段ボール", "名詞",
     "Pack the books in a cardboard box."),
    ("checkup", "健康診断・点検", "名詞", "I have a yearly checkup."),
    ("commend", "称賛する・推薦する", "動詞",
     "The manager commended her work."),
    ("cuisine", "料理・料理法", "名詞", "I love Italian cuisine."),
    ("deficit", "赤字・不足", "名詞", "The company reported a deficit."),
    ("demand", "要求・需要", "名詞/動詞",
     "Demand for the product is high."),
    ("discard", "捨てる・処分する", "動詞", "Please discard old files."),
    ("eligible", "資格がある・適格な", "形容詞",
     "You are eligible for a discount."),
    ("embarrassing", "恥ずかしい・やっかいな", "形容詞",
     "It was an embarrassing mistake."),
    ("enthusiastic", "熱心な", "形容詞", "The team is enthusiastic."),
    ("exclusive", "独占的な・高級な", "形容詞",
     "This is an exclusive offer."),
    ("expedite", "促進する・はかどらせる", "動詞",
     "We will expedite your order."),
    ("expire", "期限が切れる", "動詞", "My passport will expire soon."),
    ("extinguish", "消す", "動詞", "Please extinguish all flames."),
    ("facilitate", "容易にする・促進する", "動詞",
     "The tool facilitates teamwork."),
    ("hallway", "廊下・玄関", "名詞", "The office is down the hallway."),
    ("handout", "配布資料", "名詞", "Please take a handout."),
    ("inventory", "在庫・目録", "名詞", "We take inventory every month."),
    ("justify", "正当化する", "動詞", "Can you justify the cost?"),
    ("lottery", "宝くじ・抽選", "名詞", "She won the lottery."),
    ("novice", "初心者", "名詞", "He is a novice at golf."),
    ("obliged", "義務がある・感謝して", "形容詞", "I'm much obliged to you."),
    ("outdated", "時代遅れの", "形容詞", "The software is outdated."),
    ("oval", "楕円形の", "形容詞", "The table is oval."),
    ("pedestrian", "歩行者", "名詞", "Watch out for pedestrians."),
    ("plumber", "配管工", "名詞", "We called a plumber."),
    ("pottery", "陶器", "名詞", "She makes pottery as a hobby."),
    ("premise", "前提・(複)敷地", "名詞", "No smoking on the premises."),
    ("property", "財産・不動産・特性", "名詞", "He owns property abroad."),
    ("pursue", "追求する・従事する", "動詞",
     "She pursued a career in law."),
    ("reference", "参照・推薦状", "名詞", "Please provide a reference."),
    ("relief", "安心・救援", "名詞", "It was a great relief."),
    ("retrieve", "取り戻す・回収する", "動詞", "I retrieved the lost file."),
    ("shopper", "買い物客", "名詞", "The mall was full of shoppers."),
    ("slate", "石板・候補者名簿", "名詞", "He was added to the slate."),
    ("souvenir", "土産・記念品", "名詞", "I bought a souvenir."),
    ("speculate", "推測する・思索する", "動詞",
     "Analysts speculate about prices."),
    ("standstill", "停止・行き詰まり", "名詞",
     "Traffic came to a standstill."),
    ("stroll", "散歩する・ぶらつく", "動詞",
     "We strolled along the beach."),
    ("subsidiary", "子会社・補助の", "名詞/形容詞",
     "It is a subsidiary of a big firm."),
    ("substitute", "代わり・代える", "名詞/動詞",
     "Use honey as a substitute for sugar."),
    ("superb", "すばらしい・壮麗な", "形容詞", "The view was superb."),
    ("superintendent", "管理者・監督", "名詞",
     "The building superintendent fixed it."),
    ("supplement", "補足・付録・補う", "名詞/動詞",
     "Take a vitamin supplement."),
    ("surpass", "上回る・まさる", "動詞",
     "Sales surpassed last year's figures."),
    ("surrounding", "周囲の", "形容詞", "Explore the surrounding area."),
    ("suspicion", "疑い・容疑", "名詞", "He acted without suspicion."),
    ("swiftly", "迅速に", "副詞", "The team responded swiftly."),
    ("tariff", "関税・料金表", "名詞", "The government raised tariffs."),
    ("thaw", "解ける・打ち解ける", "動詞", "The ice began to thaw."),
    ("timepiece", "時計", "名詞", "This watch is a fine timepiece."),
    ("token", "しるし・記念品", "名詞",
     "Please accept this as a token of thanks."),
    ("tolerate", "我慢する・大目に見る", "動詞",
     "I can't tolerate rudeness."),
    ("transfer", "移す・転勤・移動", "動詞/名詞",
     "He was transferred to Osaka."),
    ("transparent", "透明な・分かりやすい", "形容詞",
     "We aim for transparent pricing."),
    ("tuition", "授業料・教授", "名詞", "Tuition has increased this year."),
    ("turbulent", "荒れた・激しい", "形容詞", "It was a turbulent flight."),
    ("turnout", "出席者数・人出", "名詞", "There was a large turnout."),
    ("unanimous", "満場一致の", "形容詞", "The vote was unanimous."),
    ("unearth", "発掘する・明るみに出す", "動詞",
     "They unearthed ancient coins."),
    ("uniformity", "均一・画一", "名詞", "We aim for uniformity in quality."),
    ("utensil", "用具・台所用品", "名詞", "Wash the kitchen utensils."),
    ("utilization", "利用・活用", "名詞",
     "We improved resource utilization."),
    ("vacant", "空いている・空の", "形容詞", "The seat is vacant."),
    ("valid", "有効な・正当な", "形容詞",
     "The ticket is valid for a month."),
    ("vaporize", "蒸発させる", "動詞", "Heat will vaporize the liquid."),
    ("vendor", "売り主・行商人", "名詞",
     "We changed our software vendor."),
    ("venue", "会場・開催地", "名詞", "The venue holds 2,000 people."),
    ("vice", "悪・副〜", "名詞", "She is the vice president."),
    ("virtue", "美徳・長所", "名詞", "Patience is a virtue."),
    ("warehouse", "倉庫・貯蔵所", "名詞",
     "The goods are in the warehouse."),
    ("warning", "警告", "名詞", "We received a warning."),
    ("warrant", "令状・根拠・正当化する", "名詞/動詞",
     "The case warrants attention."),
    ("welfare", "福祉", "名詞",
     "The company cares about employee welfare."),
    ("wheelbarrow", "手押し一輪車", "名詞",
     "He moved the soil in a wheelbarrow."),
    ("wilderness", "荒野", "名詞", "They hiked through the wilderness."),
    ("withstand", "耐える・抵抗する", "動詞",
     "The bridge can withstand earthquakes."),
    ("zeal", "熱意・熱心", "名詞", "She works with great zeal."),
    ("zealous", "熱心な・熱狂的な", "形容詞", "He is a zealous supporter."),
    ("zenith", "頂点・絶頂", "名詞", "The company reached its zenith."),

    # ===== 800点レベル =====
    ("abridged", "要約された", "形容詞",
     "This is an abridged version of the report."),
    ("accomplished", "熟練した・完成した", "形容詞",
     "She is an accomplished pianist."),
    ("acknowledgement", "承認・受領通知", "名詞",
     "We sent an acknowledgement of receipt."),
    ("aging", "老化・熟成", "名詞", "The population is aging."),
    ("alert", "警戒した・警報", "形容詞/名詞",
     "Stay alert during the drill."),
    ("allergy", "アレルギー", "名詞", "I have a peanut allergy."),
    ("appetizer", "前菜", "名詞", "We ordered an appetizer."),
    ("applause", "拍手・称賛", "名詞",
     "The speech received loud applause."),
    ("assorted", "各種詰め合わせの", "形容詞",
     "She bought a box of assorted chocolates."),
    ("attire", "服装", "名詞", "Business attire is required."),
    ("austere", "厳しい・質素な", "形容詞", "He led an austere life."),
    ("avid", "熱心な・貪欲な", "形容詞", "She is an avid reader."),
    ("ban", "禁止・禁止する", "名詞/動詞", "They banned smoking indoors."),
    ("bear", "耐える・(子を)産む", "動詞", "I can't bear the noise."),
    ("boost", "押し上げる・増大", "動詞/名詞",
     "The ad gave sales a boost."),
    ("breathtakingly", "息をのむほど", "副詞",
     "The view was breathtakingly beautiful."),
    ("bulk", "大量・かさ", "名詞", "We buy paper in bulk."),
    ("burst", "破裂する", "動詞", "The water pipe burst."),
    ("bypass", "バイパス・迂回する", "名詞/動詞",
     "We bypassed the city center."),
    ("carrier", "運送業者・運搬人", "名詞",
     "The carrier delivered the package."),
    ("certified", "公認の・保証された", "形容詞",
     "She is a certified accountant."),
    ("chronic", "慢性の・長引く", "形容詞", "He has chronic back pain."),
    ("circulation", "循環・発行部数", "名詞",
     "The magazine has a wide circulation."),
    ("cite", "引用する", "動詞", "He cited several studies."),
    ("colossal", "巨大な", "形容詞", "It was a colossal mistake."),
    ("commerce", "商業・貿易", "名詞", "E-commerce is growing fast."),
    ("compliance", "順守", "名詞", "We ensure compliance with the rules."),
    ("confidential", "機密の", "形容詞", "This document is confidential."),
    ("consistent", "一貫した・矛盾のない", "形容詞",
     "Her work is consistent."),
    ("correspondent", "特派員", "名詞", "He is a foreign correspondent."),
    ("courteous", "礼儀正しい", "形容詞", "The staff were courteous."),
    ("craven", "臆病な", "形容詞", "It was a craven decision."),
    ("culinary", "料理の", "形容詞", "She has culinary skills."),
    ("deposit", "預金する・手付金", "動詞/名詞", "I deposited the check."),
    ("distinctive", "独特の・特色のある", "形容詞",
     "The brand has a distinctive logo."),
    ("distinguished", "著名な・優れた", "形容詞",
     "He is a distinguished professor."),
    ("drowsiness", "眠気", "名詞", "This medicine may cause drowsiness."),
    ("enthusiasm", "熱意・熱中", "名詞", "She spoke with enthusiasm."),
    ("entrepreneur", "起業家", "名詞",
     "He is a successful entrepreneur."),
    ("exceptional", "例外的な・優れた", "形容詞",
     "Her work is exceptional."),
    ("exonerate", "無罪にする・免除する", "動詞",
     "The court exonerated him."),
    ("exponentially", "指数関数的に", "副詞", "Data grew exponentially."),
    ("fabulous", "すばらしい・途方もない", "形容詞",
     "We had a fabulous time."),
    ("faculty", "能力・学部", "名詞", "He joined the science faculty."),
    ("former", "前の・以前の", "形容詞", "She is a former colleague."),
    ("fragile", "壊れやすい・もろい", "形容詞",
     "Handle the box; it's fragile."),
    ("halt", "停止する・立ち止まる", "動詞", "Production was halted."),
    ("hectic", "多忙な・てんてこ舞いの", "形容詞", "I had a hectic week."),
    ("inclement", "荒れ模様の・厳しい", "形容詞",
     "The game was canceled due to inclement weather."),
    ("informative", "有益な・教育的な", "形容詞",
     "The lecture was very informative."),
    ("inherit", "受け継ぐ・相続する", "動詞", "She inherited the house."),
    ("initiative", "主導権・新提案", "名詞", "He took the initiative."),
    ("inn", "宿屋・小ホテル", "名詞", "We stayed at a small inn."),
    ("incidence", "発生・発生率", "名詞",
     "The incidence of flu rose this winter."),
    ("intermission", "休憩時間・幕あい", "名詞",
     "Let's get drinks during the intermission."),
    ("introductory", "入門の・序の", "形容詞",
     "This is an introductory course."),
    ("leading", "主要な・先導する", "形容詞", "It is a leading company."),
    ("locksmith", "錠前屋・かぎ屋", "名詞", "We called a locksmith."),
    ("lure", "誘惑・おびき寄せる", "名詞/動詞",
     "Low prices lure customers."),
    ("malfunction", "故障・機能不全", "名詞",
     "A malfunction stopped the line."),
    ("mortgage", "住宅ローン・抵当", "名詞", "They took out a mortgage."),
    ("noteworthy", "注目すべき", "形容詞",
     "It was a noteworthy achievement."),
    ("nursery", "保育園・託児所", "名詞",
     "She left her child at the nursery."),
    ("outlay", "支出・経費", "名詞",
     "The project requires a large outlay."),
    ("overhaul", "分解点検する・徹底見直し", "動詞",
     "We overhauled the system."),
    ("paralegal", "弁護士補助員", "名詞", "She works as a paralegal."),
    ("patent", "特許", "名詞", "They filed a patent."),
    ("patronage", "ひいき・後援・愛顧", "名詞",
     "Thank you for your patronage."),
    ("peer", "同僚・仲間", "名詞", "He is respected by his peers."),
    ("physician", "医師・内科医", "名詞", "Consult your physician."),
    ("plush", "豪華な・ぜいたくな", "形容詞",
     "They stayed in a plush hotel."),
    ("prescription", "処方箋", "名詞", "I need a prescription refill."),
    ("proofreader", "校正者", "名詞", "A proofreader checked the text."),
    ("posture", "姿勢・態度", "名詞",
     "Good posture prevents back pain."),
    ("regulate", "規制する・調整する", "動詞",
     "The agency regulates the market."),
    ("regimen", "養生法・規定", "名詞",
     "She follows a strict fitness regimen."),
    ("resume", "再開する・履歴書", "動詞/名詞",
     "Work will resume on Monday."),
    ("seasoned", "経験豊かな・味付けした", "形容詞",
     "He is a seasoned negotiator."),
    ("skyrocket", "急騰する", "動詞", "Prices skyrocketed last month."),
    ("spare", "予備の・割く・惜しむ", "形容詞/動詞",
     "Do you have a spare key?"),
    ("stagnant", "停滞した・よどんだ", "形容詞",
     "The economy is stagnant."),
    ("stunning", "見事な・衝撃的な", "形容詞", "The dress is stunning."),
    ("surgical", "外科の", "形容詞", "She needs surgical treatment."),
    ("tidy", "整った・きちんとした", "形容詞", "Keep your desk tidy."),
    ("trim", "刈り込む・整える", "動詞", "He trimmed the hedge."),
    ("typo", "誤植", "名詞", "There's a typo in the title."),
    ("unwilling", "気が進まない", "形容詞", "She was unwilling to help."),
    ("valuable", "貴重な・高価な", "形容詞", "This is valuable advice."),
    ("verification", "確認・証明", "名詞",
     "Please complete identity verification."),
    ("veterinarian", "獣医", "名詞",
     "We took the dog to the veterinarian."),
    ("waive", "放棄する・免除する", "動詞", "They waived the fee."),
    ("welder", "溶接工", "名詞", "The welder repaired the frame."),
    ("wildlife", "野生生物", "名詞", "The park protects wildlife."),
    ("wring", "絞る・ねじる", "動詞", "Wring out the wet towel."),
]
