"""Initial content: ~100 TOEIC-level words and ~50 useful phrases.

Tuned to roughly TOEIC 500–800. Loaded once on first run; you (or the AI)
can keep adding more over time. Format:
    WORDS:    (english, japanese, part_of_speech, example)
    PHRASES:  (english, japanese, scene)
"""

from __future__ import annotations

WORDS: list[tuple[str, str, str, str]] = [
    # --- Business / work ---
    ("achieve", "達成する", "動詞", "We achieved our quarterly target."),
    ("acquire", "獲得する・買収する", "動詞", "The firm acquired a startup."),
    ("agenda", "議題", "名詞", "Let's review the meeting agenda."),
    ("allocate", "割り当てる", "動詞", "We allocated a budget for training."),
    ("appoint", "任命する", "動詞", "She was appointed as manager."),
    ("approve", "承認する", "動詞", "The board approved the plan."),
    ("assign", "割り当てる・任せる", "動詞", "I was assigned a new project."),
    ("attend", "出席する", "動詞", "Please attend the briefing at 10."),
    ("budget", "予算", "名詞", "The project is over budget."),
    ("colleague", "同僚", "名詞", "My colleague helped with the report."),
    ("commute", "通勤する", "動詞", "I commute by train every day."),
    ("conduct", "行う・実施する", "動詞", "We conducted a survey last month."),
    ("confirm", "確認する", "動詞", "Please confirm your attendance."),
    ("consider", "考慮する", "動詞", "We will consider your proposal."),
    ("deadline", "締め切り", "名詞", "The deadline is next Friday."),
    ("deliver", "届ける・実現する", "動詞", "We delivered the goods on time."),
    ("department", "部署", "名詞", "She works in the sales department."),
    ("estimate", "見積もる", "動詞", "We estimate the cost at $5,000."),
    ("expense", "経費", "名詞", "Please submit your expense report."),
    ("forecast", "予測", "名詞", "The sales forecast looks strong."),
    ("invoice", "請求書", "名詞", "I will send the invoice today."),
    ("negotiate", "交渉する", "動詞", "We negotiated a better price."),
    ("objective", "目標", "名詞", "Our main objective is growth."),
    ("postpone", "延期する", "動詞", "The meeting was postponed."),
    ("priority", "優先事項", "名詞", "Safety is our top priority."),
    ("proposal", "提案", "名詞", "They rejected our proposal."),
    ("recruit", "採用する", "動詞", "We need to recruit engineers."),
    ("reimburse", "払い戻す", "動詞", "The company will reimburse travel costs."),
    ("revenue", "収益", "名詞", "Revenue grew by ten percent."),
    ("schedule", "予定・予定する", "名詞/動詞", "Let's schedule a call."),
    ("submit", "提出する", "動詞", "Submit the form by Monday."),
    ("supervisor", "上司", "名詞", "Ask your supervisor for approval."),
    # --- General / TOEIC core ---
    ("available", "利用可能な", "形容詞", "The report is available online."),
    ("appropriate", "適切な", "形容詞", "Choose an appropriate response."),
    ("benefit", "利益・恩恵", "名詞", "The plan offers many benefits."),
    ("complaint", "苦情", "名詞", "We received a customer complaint."),
    ("convenient", "便利な", "形容詞", "Is Monday convenient for you?"),
    ("decline", "断る・減少する", "動詞", "Sales declined last quarter."),
    ("efficient", "効率的な", "形容詞", "This is a more efficient method."),
    ("eventually", "最終的に", "副詞", "We eventually found a solution."),
    ("expand", "拡大する", "動詞", "They plan to expand overseas."),
    ("familiar", "よく知っている", "形容詞", "I'm familiar with this software."),
    ("frequently", "頻繁に", "副詞", "He frequently travels abroad."),
    ("guarantee", "保証する", "動詞", "We guarantee fast delivery."),
    ("immediately", "すぐに", "副詞", "Please reply immediately."),
    ("improve", "改善する", "動詞", "We need to improve quality."),
    ("increase", "増加・増やす", "名詞/動詞", "Sales increased by 10%."),
    ("indicate", "示す", "動詞", "The data indicates a trend."),
    ("influence", "影響を与える", "動詞", "Prices influence demand."),
    ("maintain", "維持する", "動詞", "We must maintain the equipment."),
    ("notify", "通知する", "動詞", "Notify me of any changes."),
    ("obtain", "得る", "動詞", "You must obtain a permit."),
    ("occasion", "機会・場合", "名詞", "On this occasion, we celebrate."),
    ("participate", "参加する", "動詞", "Everyone can participate."),
    ("perform", "行う・性能を発揮する", "動詞", "The team performed well."),
    ("permanent", "永続的な", "形容詞", "She got a permanent position."),
    ("previous", "以前の", "形容詞", "Refer to the previous email."),
    ("provide", "提供する", "動詞", "We provide 24/7 support."),
    ("purchase", "購入する", "動詞", "He purchased a new laptop."),
    ("recommend", "勧める", "動詞", "I recommend this restaurant."),
    ("reduce", "減らす", "動詞", "We need to reduce costs."),
    ("reliable", "信頼できる", "形容詞", "He is a reliable partner."),
    ("require", "必要とする", "動詞", "This job requires English."),
    ("respond", "応答する", "動詞", "Please respond by email."),
    ("responsible", "責任がある", "形容詞", "She is responsible for sales."),
    ("significant", "重要な・著しい", "形容詞", "There was a significant change."),
    ("sufficient", "十分な", "形容詞", "We have sufficient resources."),
    ("temporary", "一時的な", "形容詞", "This is a temporary fix."),
    ("various", "さまざまな", "形容詞", "We offer various options."),
    # --- Travel / daily life ---
    ("aboard", "搭乗して", "副詞", "Welcome aboard the flight."),
    ("boarding", "搭乗", "名詞", "Boarding begins at gate 12."),
    ("currency", "通貨", "名詞", "Where can I exchange currency?"),
    ("customs", "税関", "名詞", "Please proceed to customs."),
    ("departure", "出発", "名詞", "The departure was delayed."),
    ("destination", "目的地", "名詞", "What's your final destination?"),
    ("luggage", "手荷物", "名詞", "My luggage is missing."),
    ("reservation", "予約", "名詞", "I have a dinner reservation."),
    ("receipt", "領収書", "名詞", "Can I have a receipt, please?"),
    ("refund", "返金", "名詞", "I'd like a refund for this."),
    # --- IT / software / AI ---
    ("compile", "コンパイルする", "動詞", "The code won't compile."),
    ("deploy", "展開・デプロイする", "動詞", "We deploy every Friday."),
    ("debug", "デバッグする", "動詞", "I spent hours debugging this."),
    ("dependency", "依存関係", "名詞", "Install the dependencies first."),
    ("feature", "機能", "名詞", "This feature is experimental."),
    ("framework", "フレームワーク", "名詞", "We use a web framework."),
    ("implement", "実装する", "動詞", "Let's implement the API."),
    ("issue", "課題・問題", "名詞", "I opened an issue on GitHub."),
    ("query", "問い合わせ・クエリ", "名詞", "The query is too slow."),
    ("repository", "リポジトリ", "名詞", "Clone the repository first."),
    ("request", "要求・リクエスト", "名詞", "The request timed out."),
    ("threshold", "しきい値", "名詞", "Set a higher threshold."),
    ("validate", "検証する", "動詞", "Validate the input first."),
    ("prompt", "指示・プロンプト", "名詞", "Write a clearer prompt."),
    ("inference", "推論", "名詞", "Inference runs on the GPU."),
    ("dataset", "データセット", "名詞", "We trained on a large dataset."),
    ("optimize", "最適化する", "動詞", "Optimize the loop for speed."),
    ("scalable", "拡張可能な", "形容詞", "The system must be scalable."),
    # --- Mechanical / engineering ---
    ("assemble", "組み立てる", "動詞", "Assemble the parts carefully."),
    ("component", "部品", "名詞", "Replace the faulty component."),
    ("durable", "耐久性のある", "形容詞", "This material is very durable."),
    ("maintenance", "保守・整備", "名詞", "Regular maintenance is required."),
    ("vibration", "振動", "名詞", "The vibration caused the fault."),
    # --- Added batch 1 (TOEIC 500-800) ---
    ("accomplish", "成し遂げる", "動詞",
     "She accomplished the task ahead of schedule."),
    ("acknowledge", "認める・受領を知らせる", "動詞",
     "Please acknowledge receipt of this email."),
    ("anticipate", "予期する", "動詞", "We anticipate strong demand."),
    ("assess", "評価する・査定する", "動詞", "We need to assess the risks."),
    ("comprehensive", "包括的な", "形容詞",
     "We offer comprehensive support."),
    ("demonstrate", "実証する・示す", "動詞",
     "Let me demonstrate the feature."),
    ("distribute", "配布する", "動詞", "Please distribute the handouts."),
    ("enhance", "高める・強化する", "動詞",
     "This update enhances performance."),
    ("ensure", "確実にする", "動詞", "Ensure the door is locked."),
    ("essential", "不可欠な", "形容詞", "Sleep is essential for health."),
    ("evaluate", "評価する", "動詞",
     "We evaluate each proposal carefully."),
    ("inquiry", "問い合わせ", "名詞", "Thank you for your inquiry."),
    ("mandatory", "必須の", "形容詞", "Attendance is mandatory."),
    ("outstanding", "傑出した・未払いの", "形容詞",
     "He did an outstanding job."),
    ("procedure", "手順", "名詞", "Follow the safety procedure."),
    ("prohibit", "禁止する", "動詞", "Smoking is prohibited here."),
    ("recipient", "受取人", "名詞",
     "The recipient signed for the package."),
    ("relevant", "関連する", "形容詞",
     "Please provide relevant documents."),
    ("itinerary", "旅程", "名詞", "Here is your travel itinerary."),
    ("vacancy", "空室・欠員", "名詞",
     "Do you have any vacancies tonight?"),
    ("fare", "運賃", "名詞", "The train fare went up."),
    ("baggage", "手荷物", "名詞",
     "Please don't leave your baggage unattended."),
    ("latency", "遅延・レイテンシ", "名詞",
     "The server has high latency."),
    ("deprecated", "非推奨の", "形容詞",
     "This method is deprecated."),
    ("rollback", "ロールバック・戻すこと", "名詞",
     "We performed a rollback after the bug."),
    ("concurrency", "並行性", "名詞",
     "Concurrency bugs are hard to find."),
    ("friction", "摩擦", "名詞",
     "Oil reduces friction between parts."),
    ("calibrate", "較正する", "動詞",
     "Calibrate the sensor before use."),
    ("lubricate", "潤滑する", "動詞",
     "Lubricate the moving parts regularly."),
    ("tolerance", "公差・許容差", "名詞",
     "The part is within tolerance."),
]

PHRASES: list[tuple[str, str, str]] = [
    # --- 外国人対応 / 道案内 ---
    ("Sorry, I didn't catch that.", "すみません、聞き取れませんでした。", "外国人対応"),
    ("Could you speak more slowly, please?",
     "もう少しゆっくり話してもらえますか？", "外国人対応"),
    ("Excuse me, may I get through?", "すみません、通してください。", "外国人対応"),
    ("Go straight and turn at the third corner.",
     "まっすぐ行って3つ目の角を曲がってください。", "外国人対応"),
    ("It's about a five-minute walk from here.",
     "ここから歩いて5分ほどです。", "外国人対応"),
    ("I'm sorry, I'm not from around here.",
     "すみません、この辺りの者ではないんです。", "外国人対応"),
    ("Let me show you on the map.", "地図でお見せしますね。", "外国人対応"),
    ("You can take the subway from over there.",
     "あそこから地下鉄に乗れますよ。", "外国人対応"),
    ("Could you say that one more time?",
     "もう一度言ってもらえますか？", "外国人対応"),
    ("I can understand a little English.",
     "英語は少しなら分かります。", "外国人対応"),
    # --- 日常 ---
    ("It depends on the situation.", "状況によります。", "日常"),
    ("That works for me.", "それで大丈夫です。", "日常"),
    ("Let me think about it.", "少し考えさせてください。", "日常"),
    ("No worries.", "気にしないで。", "日常"),
    ("I really appreciate it.", "本当に感謝します。", "日常"),
    ("Just in case.", "念のため。", "日常"),
    ("Take your time.", "ゆっくりでいいですよ。", "日常"),
    ("It's up to you.", "あなた次第です。", "日常"),
    # --- ご近所 / スーパー ---
    ("Nice weather today, isn't it?", "今日はいい天気ですね。", "ご近所"),
    ("Have you lived here long?", "ここに長くお住まいですか？", "ご近所"),
    ("Where can I find the dairy section?",
     "乳製品売り場はどこですか？", "スーパー"),
    ("Is this on sale?", "これはセール中ですか？", "スーパー"),
    ("Do you have this in stock?", "これは在庫がありますか？", "スーパー"),
    ("I'm just looking, thanks.", "見ているだけです、ありがとう。", "買い物"),
    # --- レストラン ---
    ("Could I see the menu, please?", "メニューを見せてください。", "レストラン"),
    ("I'll have the same.", "私も同じものを。", "レストラン"),
    ("Can we get the check, please?", "お会計をお願いします。", "レストラン"),
    ("Is this dish spicy?", "この料理は辛いですか？", "レストラン"),
    ("I have a food allergy.", "食物アレルギーがあります。", "レストラン"),
    # --- ホテル / 出入国 ---
    ("I have a reservation under my name.",
     "私の名前で予約しています。", "ホテル"),
    ("What time is check-out?", "チェックアウトは何時ですか？", "ホテル"),
    ("Could I have a wake-up call at seven?",
     "7時にモーニングコールをお願いできますか？", "ホテル"),
    ("I'm here for sightseeing for one week.",
     "観光で1週間滞在します。", "出入国"),
    ("Where can I claim my baggage?",
     "手荷物はどこで受け取れますか？", "出入国"),
    ("I have nothing to declare.", "申告するものはありません。", "出入国"),
    # --- ビジネス / 会議 ---
    ("Let's circle back on this.", "この件はまた後で話しましょう。", "ビジネス"),
    ("Could you walk me through it?", "順を追って説明してくれますか？", "ビジネス"),
    ("I'll get back to you shortly.", "すぐに折り返します。", "ビジネス"),
    ("Let's keep it brief.", "手短にしましょう。", "会議"),
    ("Can everyone see my screen?", "画面は見えていますか？", "会議"),
    ("Let's table this for now.", "これは一旦保留にしましょう。", "会議"),
    ("Just to recap,", "要点をまとめると、", "会議"),
    ("Can you hear me okay?", "声は聞こえていますか？", "会議"),
    # --- IT / 開発 ---
    ("The build is failing again.", "またビルドが失敗しています。", "IT開発"),
    ("Let me check the logs.", "ログを確認します。", "IT開発"),
    ("It works on my machine.", "私の環境では動きます。", "IT開発"),
    ("Can you review my pull request?",
     "プルリクエストをレビューしてもらえますか？", "IT開発"),
    ("Let's roll it back.", "ロールバックしましょう。", "IT開発"),
    # --- AIへの指示 ---
    ("Summarize this in three bullet points.",
     "3つの箇条書きで要約して。", "AI指示"),
    ("Explain it like I'm a beginner.",
     "初心者にも分かるように説明して。", "AI指示"),
    ("Give me a concrete example.", "具体例をください。", "AI指示"),
    ("Rewrite this more naturally.", "もっと自然に書き直して。", "AI指示"),
]
