# ruff: noqa: E501
"""服飾・生地・ファッション・縫製機器・色彩の新ドメイン(2026-09-13・authored by Claude)。
ユーザー提起「服飾用語、服の種類、生地の種類、ファッション用語、縫製機器の種類、
色の種類（欧米、日本古来の色）」を受け、2026-09-09セッションでスコープだけ
残っていたバックログ項目を執筆。5つの新規ドメイン(服飾/生地/ファッション/
縫製機器/色彩)を追加する。手芸(62語)・アパレル産業(13語)ドメインの既存語
(bobbin, seam ripper, sewing pattern, notions, fast fashion 等)と重複しない
よう確認済み。

No app / OpenAI API calls — hand-written、inserted directly into SQLite.
Duplicates skipped by english (lowercased) against the full live `words` table.

Run:  python scripts/add_fashion_textile_color_2026_09_13.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.database import db  # noqa: E402

WORDS: list[tuple[str, str, str, str, str, str]] = [
    ('trench coat', 'ダブルの前立てとベルトが特徴の、防水加工されたコットン素材のロングコート。', '名詞', 'She wrapped her beige trench coat tightly against the autumn drizzle.', '服飾', '550'),
    ('jumpsuit', '上下がひと続きになった、つなぎ服。', '名詞', 'She wore a sleek black jumpsuit to the cocktail party.', '服飾', '550'),
    ('tunic', '腰からひざ丈程度まである、ゆったりとした丈長めの上着。', '名詞', 'She paired a flowy tunic with leggings for a comfortable yet stylish look.', '服飾', '500'),
    ('blazer', 'スーツの上着ほど格式張らないが、テーラード仕立てのしっかりした上着。', '名詞', 'He threw on a navy blazer over his t-shirt to look a bit more polished.', '服飾', '500'),
    ('parka', 'フードと厚い裏地が付いた、防寒・防風性の高い丈の長い上着。和製英語の「パーカー」（薄手のフード付きトップス、英語ではhoodieと呼ぶ）とは異なり、本来は極寒地仕様の防寒着を指す。', '名詞', 'The explorers wore fur-lined parkas to survive the Arctic winds.', '服飾', '600'),
    ('poncho', '中央に頭を通す穴を開けただけの、一枚布からなる袖のない外套。', '名詞', 'She threw on a wool poncho to keep warm on the chilly evening.', '服飾', '500'),
    ('kimono', '直線的に裁断した布を体に巻きつけ、帯で留めて着る日本の伝統的な民族衣装。英語でもkimonoとして広く通用する借用語になっている。', '名詞', 'She wore a silk kimono decorated with a delicate cherry blossom pattern.', '服飾', '550'),
    ('hakama', '着物の上から腰に着ける、ひだの入った日本の伝統的な袴。剣道や弓道などの武道の稽古着としても広く用いられる。', '名詞', 'The kendo practitioners bowed before putting on their hakama.', '服飾', '700'),
    ('sari', '一枚の長い布を体に巻きつけて着る、南アジアの女性の伝統的な衣装。', '名詞', 'She draped the silk sari elegantly over one shoulder before the wedding.', '服飾', '650'),
    ('cheongsam', '立ち襟と体にぴったり沿ったシルエットが特徴の、中国発祥の女性用ドレス。旗袍(チーパオ)とも呼ばれる。', '名詞', 'She wore an embroidered cheongsam with a high slit at the annual gala.', '服飾', '700'),
    ('dirndl', 'ぴったりしたボディスと、ふんわりしたスカート、エプロンを組み合わせた、ドイツ・オーストリア南部の伝統的な女性用衣装。', '名詞', 'She wore a traditional dirndl to the Oktoberfest celebration.', '服飾', '700'),
    ('lederhosen', '革製の半ズボンで、サスペンダーが付いた、ドイツ・オーストリア南部の伝統的な男性用衣装。', '名詞', 'He put on a pair of leather lederhosen for the folk festival.', '服飾', '700'),
    ('kilt', 'ひだの入った、格子柄(タータン)の毛織物でできたスコットランドの伝統的な男性用スカート。', '名詞', "He wore his family's tartan kilt proudly at the Highland games.", '服飾', '600'),
    ('culottes', '一見スカートのように見えるが、実際には両脚が分かれている、ゆったりとしたズボン。', '名詞', 'She chose a pair of wide-leg culottes for a look that felt both dressy and easy to move in.', '服飾', '600'),
    ('dungarees', '胸当てと肩ひもが付いた、デニム地などで作られるゆったりしたつなぎズボン。米語のoverallsに近いが、主に英式の呼び方。', '名詞', 'The gardener wore a pair of denim dungarees to protect his clothes from dirt.', '服飾', '600'),
    ('overalls', '胸当てと肩ひもが付いた、作業用または普段着として着るゆったりしたつなぎズボン。米式の呼び方。', '名詞', "The farmer's overalls were faded from years of work in the sun.", '服飾', '500'),
    ('romper', '上下がひと続きになった、ショートパンツ丈のつなぎ服。', '名詞', 'The toddler looked adorable in a striped cotton romper.', '服飾', '550'),
    ('camisole', '肩ひもが細く、袖のない、体にフィットする女性用の薄手の上着や下着。', '名詞', 'She wore a silk camisole under her sheer blouse.', '服飾', '600'),
    ('caftan', 'ゆったりとした、丈の長い一枚布のような上着。中東・北アフリカ発祥で、現在はビーチウェアとしても人気がある。', '名詞', 'She slipped on a flowing caftan over her swimsuit at the beach resort.', '服飾', '700'),
    ('sarong', '一枚の長方形の布を腰に巻きつけて着る、東南アジア発祥の巻きスカート状の衣服。', '名詞', 'He wrapped a colorful sarong around his waist after swimming.', '服飾', '600'),
    ('waistcoat', '袖のない、前開きの上着で、シャツとジャケットの間に着るもの。米語ではvestと呼ばれる。', '名詞', 'He completed his three-piece suit with a matching waistcoat.', '服飾', '550'),
    ('cloak', '肩から羽織る、袖のない丈の長いゆったりとした外套。', '名詞', 'The wizard in the story wore a long cloak with a hood.', '服飾', '500'),
    ('shawl', '肩や頭にかけて羽織る、大判の一枚布。', '名詞', 'She wrapped a knitted shawl around her shoulders against the evening chill.', '服飾', '500'),
    ('stole', '肩にかけて着る、細長い形の毛皮や布製の肩掛け。フォーマルな装いによく合わせられる。', '名詞', 'She draped a fur stole over her evening gown.', '服飾', '600'),
    ('turtleneck', '首にぴったり沿って高く立ち上がった襟が付いた、伸縮性のあるトップス。', '名詞', 'He layered a black turtleneck under his blazer for a sleek autumn look.', '服飾', '500'),
    ('polo shirt', '襟と数個のボタンが付いた、半袖の編み地のシャツ。', '名詞', 'He wore a crisp white polo shirt for the golf tournament.', '服飾', '450'),
    ('henley shirt', '襟がなく、胸元に数個のボタンが並んだプルオーバー式のシャツ。', '名詞', 'He rolled up the sleeves of his gray henley shirt before starting the yard work.', '服飾', '600'),
    ('leggings', '脚全体にぴったりと沿う、伸縮性の高い薄手のパンツ。', '名詞', 'She wore black leggings under her tunic for extra warmth.', '服飾', '450'),
    ('capri pants', 'ふくらはぎの途中までの丈で仕立てられた、女性用のぴったりしたパンツ。', '名詞', 'She paired cropped capri pants with a simple white blouse for a summer outing.', '服飾', '550'),
    ('bermuda shorts', 'ひざのすぐ上あたりまでの丈がある、比較的フォーマルにも着られる短パン。', '名詞', 'He wore tailored bermuda shorts with a button-down shirt for the garden party.', '服飾', '550'),
    ('cargo pants', '太もも部分などに大きなポケットが複数付いた、丈夫な作りのパンツ。', '名詞', 'He stuffed his phone and keys into the side pocket of his cargo pants.', '服飾', '500'),
    ('chinos', 'コットンのツイル地で作られた、比較的きちんとした印象のカジュアルなパンツ。', '名詞', 'He wore tan chinos and a blazer for the semi-formal dinner.', '服飾', '550'),
    ('pinafore', '袖のない、他の服の上から重ねて着るワンピース状の衣服。エプロンドレスとも呼ばれる。', '名詞', 'The little girl wore a pinafore over her plaid school dress.', '服飾', '650'),
    ('sundress', '肩ひもが細く、袖のない、夏向けの軽やかなワンピース。', '名詞', 'She wore a light floral sundress to the outdoor summer festival.', '服飾', '500'),
    ('cocktail dress', '膝丈前後で、イブニングドレスよりもややカジュアルなフォーマルシーン向けのドレス。', '名詞', 'She chose a little black cocktail dress for the office holiday party.', '服飾', '600'),
    ('ball gown', 'スカート部分がふんわりと大きく広がった、豪華で丈の長いフォーマルドレス。', '名詞', 'She twirled across the dance floor in a sparkling ball gown.', '服飾', '600'),
    ('pencil skirt', '裾に向かってまっすぐ、体の線に沿った細身のシルエットのスカート。', '名詞', 'She wore a fitted pencil skirt with a tucked-in blouse to the interview.', '服飾', '550'),
    ('a-line skirt', 'ウエストから裾にかけてアルファベットの「A」の形のように緩やかに広がるスカート。', '名詞', 'The a-line skirt flattered nearly every body shape, which is why it stayed popular for decades.', '服飾', '550'),
    ('pleated skirt', '縦方向に規則正しいひだ(プリーツ)を畳んで作られたスカート。', '名詞', 'The school uniform included a navy pleated skirt.', '服飾', '500'),
    ('tuxedo', '黒(または濃紺)の上下に、シルクの襟が付いた男性用のフォーマルな夜会服。', '名詞', "He rented a tuxedo for his best friend's wedding.", '服飾', '550'),
    ('bolero', 'ウエストより短い丈の、前を閉じずに羽織る小さなジャケット。', '名詞', 'She wore a lace bolero over her sleeveless dress for the ceremony.', '服飾', '650'),
    ('gilet', '袖のない、前開きの軽い上着。ベストよりもアウトドア向けの厚手素材で作られることが多い。', '名詞', 'He layered a quilted gilet over his sweater for the chilly hike.', '服飾', '700'),
    ('anorak', 'フードが付いた、防水・防風性のあるプルオーバー式の上着。', '名詞', 'She zipped up her anorak before heading out into the sleet.', '服飾', '650'),
    ('windbreaker', '軽量で、風を通しにくい素材で作られたスポーティーな上着。', '名詞', 'He pulled on a windbreaker before jogging along the windy coastline.', '服飾', '500'),
    ('duffle coat', 'トグル(棒状の留め具)とループで前を留める、フード付きの厚手ウールコート。', '名詞', 'He toggled up his duffle coat against the winter wind.', '服飾', '650'),
    ('peacoat', 'ダブルの前立てと大きな襟が特徴の、厚手ウール製の短めの防寒コート。元は海軍の水兵用の制式コートに由来する。', '名詞', "The sailor's peacoat kept him warm on the deck during the storm.", '服飾', '600'),
    ('corset', '紐やホック、骨組みでウエストを細く締め、体の線を整えるための下着。', '名詞', "The costume department laced up the actress's corset before the scene.", '服飾', '650'),
    ('bustier', '肩ひもがなく、胸から腰までを覆う体にフィットしたトップス。フォーマルウェアやランジェリーとして着られる。', '名詞', 'She wore a satin bustier as the base layer of her formal gown.', '服飾', '700'),
    ('cotton', 'ワタの実から採れる繊維、またはその繊維から作られる布地。通気性が良く肌触りが柔らかい。', '名詞', 'She prefers cotton shirts because they feel soft and breathe well in summer.', '生地', '400'),
    ('silk', 'カイコの繭からとれる繊維で織られる、なめらかで光沢のある高級な布地。', '名詞', 'The scarf was woven from pure silk and felt cool against her skin.', '生地', '450'),
    ('wool', '羊などの動物の毛から作られる、保温性の高い繊維や布地。', '名詞', 'He wore a thick wool sweater to stay warm during the winter hike.', '生地', '450'),
    ('denim', '斜めの綾織り(綾織)で織られた、丈夫な綿織物。ジーンズの生地として広く知られる。', '名詞', 'Her denim jacket had faded to a light blue after years of wear.', '生地', '500'),
    ('linen', '亜麻(あま)の茎から採れる繊維で織られる、通気性が良く涼しい肌触りの布地。', '名詞', 'She wore a linen dress that kept her cool in the summer heat.', '生地', '500'),
    ('tweed', 'ざっくりとした風合いを持つ、太い毛糸で織られた厚手のウール織物。', '名詞', 'He wore a tweed jacket with elbow patches to the countryside lecture.', '生地', '650'),
    ('chiffon', '薄く透け感のある、軽やかで柔らかい織物。パーティードレスやスカーフによく使われる。', '名詞', 'The evening gown was made of layers of flowing chiffon.', '生地', '650'),
    ('corduroy', '縦方向に畝(うね)状の畝(コード)が並んだ、厚手の綿織物。', '名詞', 'He wore brown corduroy trousers that made a soft rustling sound as he walked.', '生地', '650'),
    ('velvet', '短く密集した毛羽(パイル)を持つ、なめらかで光沢のある織物。', '名詞', 'She wore a deep red velvet dress to the winter gala.', '生地', '550'),
    ('satin', 'たて糸を多く表面に浮かせる繻子織り(しゅすおり)で織られた、光沢の強い滑らかな織物。', '名詞', "The bride's gown was crafted from ivory satin.", '生地', '600'),
    ('organza', 'シルクや化学繊維で作られる、薄くて張りのある透け感のある織物。', '名詞', 'Layers of stiff organza gave the ball gown its dramatic volume.', '生地', '700'),
    ('taffeta', 'たて糸とよこ糸をきっちり平織りにした、張りがあり少しかさかさとした光沢のある織物。', '名詞', 'Her petticoat was made of crisp taffeta that rustled with every step.', '生地', '750'),
    ('brocade', '金銀の糸などを使い、浮き織りで華やかな模様を織り出した豪華な織物。', '名詞', "The emperor's robe was woven from gold brocade depicting dragons.", '生地', '750'),
    ('damask', '光沢の違いによって模様を浮かび上がらせる、地紋織りの豪華な織物。', '名詞', 'The formal tablecloth was made of white damask with a woven floral pattern.', '生地', '750'),
    ('gabardine', '細かい斜めの綾目が表面に出る、密に織られた丈夫なウールまたは綿の織物。', '名詞', 'His raincoat was made of tightly woven gabardine that repelled light drizzle.', '生地', '700'),
    ('flannel', '軽く起毛させた、柔らかく暖かい風合いの綿またはウールの織物。', '名詞', 'He pulled on a soft flannel shirt before heading out into the cold.', '生地', '550'),
    ('fleece', 'ポリエステルなどの化学繊維で作られる、軽くて保温性の高いふわふわした生地。', '名詞', 'She zipped up her fleece jacket before stepping outside.', '生地', '500'),
    ('spandex', '非常に高い伸縮性を持つ合成繊維。ライクラという商品名でも知られる。', '名詞', 'The leggings were blended with spandex for a snug, stretchy fit.', '生地', '600'),
    ('rayon', '木材パルプなどの天然セルロースを原料に作られる、絹に似た光沢を持つ半合成繊維。', '名詞', "The blouse was made of rayon, giving it a silky drape at a fraction of silk's price.", '生地', '650'),
    ('cashmere', 'カシミアヤギの柔らかい下毛から作られる、非常に軽くて暖かい高級繊維。', '名詞', 'She treated herself to a soft cashmere sweater for the winter.', '生地', '650'),
    ('mohair', 'アンゴラヤギの毛から作られる、光沢があり毛足の長いふわふわした繊維。', '名詞', 'The blanket was woven from fluffy mohair that felt warm to the touch.', '生地', '700'),
    ('angora', 'アンゴラウサギの毛から作られる、非常に柔らかくふわふわした繊維。', '名詞', 'The mittens were lined with soft angora for extra warmth.', '生地', '700'),
    ('alpaca wool', '南米原産のアルパカの毛から作られる、軽くて暖かく光沢のある繊維。', '名詞', 'The scarf was woven from alpaca wool sourced from the Andes.', '生地', '700'),
    ('suede', '革の裏側を起毛させて作る、柔らかくビロードのような手触りの革。', '名詞', 'He polished his suede shoes gently with a special brush.', '生地', '600'),
    ('muslin', '平織りの薄手で目の粗い綿織物。試作用の仮縫い生地としても使われる。', '名詞', "The dressmaker first cut a muslin mockup to test the pattern's fit.", '生地', '700'),
    ('lace', '糸を編んだり結んだりして作る、透かし模様のある繊細な布地。', '名詞', 'The wedding veil was trimmed with delicate handmade lace.', '生地', '500'),
    ('tulle', '非常に薄く、網目の細かいチュール生地。バレエの衣装やベールなどに使われる。', '名詞', "Layers of soft pink tulle made up the ballerina's tutu.", '生地', '700'),
    ('mesh', '糸や繊維を格子状・網目状に編んだり織ったりして作る、通気性の高い生地。', '名詞', 'The running shoes had a breathable mesh upper to keep his feet cool.', '生地', '500'),
    ('herringbone', 'V字型の模様が連続して並ぶ、ニシンの骨に似た綾織りの柄。', '名詞', 'He chose a gray herringbone coat for a subtly textured, classic look.', '生地', '700'),
    ('houndstooth', '犬の牙のようなギザギザした形が交互に並ぶ、白黒などの2色の織り柄。', '名詞', 'She wore a classic houndstooth blazer to the meeting.', '生地', '700'),
    ('plaid', '縦横に交差する縞模様を組み合わせた格子柄、またはその柄の織物。', '名詞', 'He wore a red and black plaid flannel shirt on the camping trip.', '生地', '500'),
    ('tartan', 'スコットランドの氏族(クラン)ごとに定められた、伝統的な格子柄。', '名詞', "The kilt was woven in his clan's official tartan pattern.", '生地', '650'),
    ('seersucker', '所々にしわを寄せて織り、肌に張り付きにくく涼しい着心地にした軽い綿織物。', '名詞', 'He wore a light blue seersucker suit during the humid summer months.', '生地', '750'),
    ('terrycloth', '輪状の毛羽(ループパイル)を密に織り込んだ、吸水性の高い綿織物。', '名詞', 'She wrapped herself in a terrycloth bathrobe after the shower.', '生地', '650'),
    ('chambray', 'たて糸に色糸、よこ糸に白糸を使って織る、デニムに似た軽い平織りの綿織物。', '名詞', 'He wore a light blue chambray shirt that looked similar to denim but felt much lighter.', '生地', '700'),
    ('poplin', 'たて糸を細く、よこ糸を太くして織ることで、細かい横畝を出した平織りの綿織物。', '名詞', 'He wore a crisp white poplin shirt tucked into his suit trousers.', '生地', '650'),
    ('twill', 'たて糸とよこ糸を1本ずつずらして交差させ、斜めの畝模様を作る織り方、またはその織物。', '名詞', 'The chinos were made from a sturdy cotton twill.', '生地', '600'),
    ('jacquard', '専用の織機を使い、糸の組み合わせによって複雑な柄を織り出した織物。', '名詞', 'The upholstery was covered in an intricate floral jacquard.', '生地', '750'),
    ('batik', '溶かした蝋(ろう)で布に模様を描き、染めない部分を防染してから染色する伝統的な技法、またはその布。', '名詞', 'She bought a hand-dyed batik sarong at the local market in Java.', '生地', '700'),
    ('ikat', '織る前の糸をあらかじめ部分的に染め分け、独特のかすれた模様を織り出す絣(かすり)染織の技法。', '名詞', 'The wall hanging featured a bold ikat pattern woven in deep indigo and cream.', '生地', '750'),
    ('warp thread', '機(はた)にまっすぐ張られ、よこ糸と交差させながら布を織り上げる、縦方向の糸。', '名詞', 'The weaver carefully strung each warp thread onto the loom before starting.', '生地', '700'),
    ('weft thread', 'たて糸の間を左右に通されて交差する、横方向の糸。', '名詞', 'The shuttle carried the weft thread back and forth across the loom.', '生地', '700'),
    ('weave', 'たて糸とよこ糸を交差させて布を作ること、またはその織り方。', '名詞・動詞', 'The scarf had a loose, open weave that let light pass through it.', '生地', '500'),
    ('knit', '1本の糸をループ状に絡めて作る、伸縮性のある編み地、またはそれを編むこと。', '名詞・動詞', 'The sweater was made from a soft knit that stretched comfortably.', '生地', '500'),
    ('nonwoven', '糸を織ったり編んだりせず、繊維を絡み合わせたり接着したりして直接シート状にした布地。', '形容詞', 'The face mask was made of a nonwoven fabric layered for extra filtration.', '生地', '750'),
    ('nap', '織物や編み地の表面に立ち上がる、細かい毛羽の向き。', '名詞', 'The tailor made sure every panel of velvet was cut with the nap running the same direction.', '生地', '700'),
    ('haute couture', '一点ずつ手作業で仕立てる、最高級のオーダーメイドの高級服、またはその業界。フランスの厳格な基準を満たした限られたメゾンだけが名乗ることを許される。', '名詞', 'The designer unveiled her latest haute couture collection at Paris Fashion Week.', 'ファッション', '750'),
    ('prêt-à-porter', '既製服、レディメイドの服。オートクチュールとは異なり、標準サイズであらかじめ量産される衣服。', '名詞', 'The label launched a prêt-à-porter line that was more affordable than its couture collection.', 'ファッション', '750'),
    ('ready-to-wear', '採寸なしで、標準サイズであらかじめ縫製・量産されている衣服を指す語。', '形容詞', 'She bought a ready-to-wear suit instead of having one custom tailored.', 'ファッション', '600'),
    ('silhouette', '衣服全体の輪郭・シルエット。体のラインをどう見せるかという全体的な形。', '名詞', "The designer's new collection featured a slim, elongated silhouette.", 'ファッション', '600'),
    ('capsule collection', '少数の厳選されたアイテムだけで構成され、互いに組み合わせやすく作られた限定コレクション。', '名詞', 'The brand released a small capsule collection in collaboration with the artist.', 'ファッション', '700'),
    ('catwalk', 'ファッションショーで、モデルが服を披露しながら歩く細長い舞台。', '名詞', "The models strutted down the catwalk in the designer's latest creations.", 'ファッション', '550'),
    ('fashion week', 'デザイナーが次のシーズンのコレクションを発表する、定期的に開催されるファッション業界のイベント。', '名詞', 'Buyers from around the world flocked to New York Fashion Week to see the new collections.', 'ファッション', '550'),
    ('streetwear', 'スニーカーカルチャーやヒップホップなど、街中のカジュアルな文化から生まれたファッションのジャンル。', '名詞', "The brand's streetwear designs became especially popular among younger shoppers.", 'ファッション', '600'),
    ('minimalism', '余計な装飾を削ぎ落とし、シンプルな形と色でまとめるファッションのスタイル。', '名詞', 'Her minimalism was reflected in a wardrobe of plain, neutral-colored pieces.', 'ファッション', '650'),
    ('maximalism', '色・柄・装飾を惜しみなく重ね合わせる、大胆で華やかなファッションのスタイル。', '名詞', "The designer's maximalism was on full display, with clashing prints layered on top of each other.", 'ファッション', '700'),
    ('athleisure', '運動用のウェアを普段着としても着こなす、スポーツウェアとカジュアルウェアを融合させたファッションのジャンル。', '名詞', 'Leggings and sneakers became staples of the athleisure trend.', 'ファッション', '700'),
    ('normcore', 'あえて個性を主張しない、あっさりとした平凡な普段着を良しとするファッションの流行。', '名詞', 'Plain t-shirts and unremarkable jeans became emblematic of the normcore trend.', 'ファッション', '750'),
    ('vintage fashion', '過去の時代に作られ、その当時のスタイルを今に伝える古着や服飾品。', '名詞', 'She sourced most of her wardrobe from vintage fashion shops downtown.', 'ファッション', '600'),
    ('thrift store', '寄付された中古の衣服や品物を安価で販売する店。', '名詞', 'He found a barely-worn wool coat at the thrift store for a fraction of its retail price.', 'ファッション', '500'),
    ('upcycling', '不要になった衣服や素材を、より価値の高い新しい製品に作り替えること。', '名詞', 'The brand specializes in upcycling discarded denim into new jackets and bags.', 'ファッション', '700'),
    ('sustainable fashion', '環境や労働者への負荷をできるだけ抑えることを目指した、衣服の生産・消費のあり方。', '名詞', 'More brands are investing in sustainable fashion to reduce their environmental footprint.', 'ファッション', '700'),
    ('slow fashion', '大量生産・大量消費に頼らず、品質の高い衣服を長く使い続けることを重視する考え方。', '名詞', 'She embraced slow fashion by buying fewer, higher-quality garments that would last for years.', 'ファッション', '700'),
    ('trendsetter', '新しい流行を最初に取り入れ、周囲に広める影響力を持つ人。', '名詞', 'As a trendsetter, she was often photographed wearing looks before they became mainstream.', 'ファッション', '600'),
    ('fashionista', '最新の流行に敏感で、それを積極的に取り入れる、ファッションに熱心な人。', '名詞', 'The fashionistas in the front row wore some of the boldest outfits of the show.', 'ファッション', '600'),
    ('style icon', 'その装いのセンスが多くの人に手本とされ、憧れの対象となる人物。', '名詞', 'The actress became a style icon known for her effortless elegance.', 'ファッション', '600'),
    ('lookbook', 'ブランドの新作コレクションの着こなし例を写真でまとめた冊子やウェブページ。', '名詞', 'The brand released a lookbook showing how each piece could be styled for different occasions.', 'ファッション', '650'),
    ('fashion editorial', '雑誌などで、ストーリー性やテーマを持たせて撮影されたファッション写真の企画。', '名詞', "The magazine's fashion editorial was shot on location in the desert.", 'ファッション', '700'),
    ('accessorize', 'アクセサリーや小物を加えて、装い全体を仕上げたり引き立てたりすること。', '動詞', 'She accessorized her plain black dress with a statement necklace.', 'ファッション', '550'),
    ('layering', '複数の服を重ね着することで、見た目や体温調節を工夫するスタイリングの手法。', '名詞', 'Layering allowed her to stay warm indoors and remove a piece when she stepped outside into the sun.', 'ファッション', '550'),
    ('color block', 'はっきりとした色の面をいくつか組み合わせて、コントラストを強調するデザインの手法。', '名詞', 'The dress used a bold color block of orange and navy panels.', 'ファッション', '650'),
    ('statement piece', '装い全体の中で最も目を引き、印象を決定づける一点物のアイテム。', '名詞', 'The oversized gold earrings served as the statement piece of her outfit.', 'ファッション', '650'),
    ('wardrobe staple', '流行に左右されず、長く使い続けられる基本的な定番アイテム。', '名詞', 'A well-fitting white shirt is considered a wardrobe staple for almost everyone.', 'ファッション', '600'),
    ('capsule wardrobe', '少数の互いに組み合わせやすいアイテムだけで構成された、最小限のワードローブ。', '名詞', 'She reduced her closet to a capsule wardrobe of about thirty versatile pieces.', 'ファッション', '700'),
    ('personal stylist', '顧客一人ひとりの体型や好みに合わせて、服の選び方や着こなしを助言する専門家。', '名詞', 'She hired a personal stylist to help her prepare for the awards ceremony.', 'ファッション', '550'),
    ('couturier', 'オートクチュールの高級服を専門にデザイン・製作する仕立て師やデザイナー。', '名詞', 'The young couturier presented her debut collection to a select group of buyers.', 'ファッション', '750'),
    ('atelier', 'デザイナーや職人が服を制作する作業場・工房。', '名詞', 'Seamstresses in the atelier worked late into the night before the show.', 'ファッション', '700'),
    ('bespoke', '顧客一人ひとりの体型や希望に合わせて、一から仕立てられる注文服を指す語。', '形容詞', 'He ordered a bespoke suit that fit his shoulders perfectly.', 'ファッション', '700'),
    ('tailor-made', '特定の人の体型や要望に合わせて、専門の仕立て師が作った服を指す語。', '形容詞', 'She wore a tailor-made blazer that fit her perfectly.', 'ファッション', '600'),
    ('off-the-rack', '特別な採寸をせず、店にすでに並んでいる標準サイズの服を指す語。', '形容詞', 'He bought an off-the-rack suit and had the sleeves shortened slightly.', 'ファッション', '600'),
    ('pattern cutting', 'デザイン画をもとに、衣服のパーツごとの型紙を作り出す技術。', '名詞', 'She studied pattern cutting for two years before opening her own label.', 'ファッション', '700'),
    ('draping', '布をボディ(トルソー)に直接かけて、立体的に形を作りながらデザインを組み立てる技法。', '名詞', 'The designer preferred draping fabric directly on a dress form rather than sketching first.', 'ファッション', '700'),
    ('fitting', '仕立てた服が体に合っているかを確認し、必要な調整箇所を見極めるための試着。', '名詞', 'The bride had a final fitting a week before the wedding to adjust the hem.', 'ファッション', '550'),
    ('alteration', '既製服や仕立てた服の丈やサイズを、体に合わせて直す作業。', '名詞', 'She took the dress to a tailor for a small alteration to the hemline.', 'ファッション', '550'),
    ('trend forecasting', '色・素材・シルエットなどの流行の兆しを分析し、将来の傾向を予測する専門的な業務。', '名詞', "The agency's trend forecasting predicted that earthy tones would dominate the next season.", 'ファッション', '750'),
    ('fashion trend', 'ある一定の期間に多くの人々の間で広まる、服装やスタイルの流行。', '名詞', 'Oversized blazers became a major fashion trend that season.', 'ファッション', '500'),
    ('runway show', 'モデルがキャットウォークを歩いて新作コレクションを披露する、ファッションブランドのショー。', '名詞', 'The runway show ended with the designer taking a bow alongside her models.', 'ファッション', '600'),
    ('front row', 'ファッションショーの会場で、著名人や有力なバイヤー・編集者のために用意される最前列の席。', '名詞', "Celebrities filled the front row at the designer's highly anticipated show.", 'ファッション', '550'),
    ('fashion critic', 'ファッションショーやコレクションの出来栄えを評価し、記事として論評する専門家。', '名詞', "The fashion critic praised the collection's bold use of color but questioned its practicality.", 'ファッション', '650'),
    ('fashion blogger', '自身のブログやSNSを通じて、ファッションの情報やコーディネートを発信する個人。', '名詞', 'The fashion blogger reviewed the new collection for her thousands of followers.', 'ファッション', '600'),
    ('tailoring', '体にぴったり合うように、生地を裁断・縫製して衣服を仕立てる技術や職業。', '名詞', "The suit's excellent tailoring made it look far more expensive than it actually was.", 'ファッション', '600'),
    ('serger', '複数の針とループ状の糸を使い、布の裁断と端の始末(ロック始末)を同時に行うミシン。オーバーロックミシンとも呼ばれる。', '名詞', 'She finished the seam edges quickly using a serger.', '縫製機器', '700'),
    ('overlock machine', '布の端を糸でかがりながら裁断する、縫い代のほつれ止めに使うミシン。', '名詞', 'The factory used an overlock machine to prevent the fabric edges from fraying.', '縫製機器', '700'),
    ('presser foot', 'ミシンで縫う際に、針の周りで布を押さえて安定させる金属または樹脂製の部品。', '名詞', 'She swapped the standard presser foot for a zipper foot before sewing in the zipper.', '縫製機器', '600'),
    ('feed dog', 'ミシンの針板の下にあり、上下に動きながら布を一定の速さで送り出す、ギザギザの歯が付いた部品。', '名詞', 'The feed dog pulled the fabric steadily through the machine as she sewed.', '縫製機器', '700'),
    ('needle plate', 'ミシンの針が上下に通り抜ける穴が開いた、送り歯の上に取り付けられた金属の板。', '名詞', 'A tiny screw held the needle plate in place beneath the presser foot.', '縫製機器', '700'),
    ('bobbin case', '下糸を巻いたボビンを収め、ミシンの下側に取り付けて糸の張力を保つ小さな部品。', '名詞', 'He carefully inserted the bobbin case so the thread would feed at the correct tension.', '縫製機器', '700'),
    ('thread spool', '縫い糸を巻き付けておく、円筒形の芯や台。', '名詞', "She placed a fresh thread spool on the machine's spool pin.", '縫製機器', '500'),
    ('seam gauge', 'スライド式の目印が付いた、縫い代や裾の幅を素早く測るための小さな定規。', '名詞', 'She used a seam gauge to mark an even hem allowance all the way around the skirt.', '縫製機器', '650'),
    ("tailor's chalk", '布地に直接、後で消せる印を付けるための、平たい石鹸状またはチョーク状の道具。', '名詞', "She traced around the pattern piece with tailor's chalk before cutting the fabric.", '縫製機器', '650'),
    ("tailor's ham", 'ハムのような楕円形をした、体の曲線に合わせてアイロンをかけるための、詰め物入りの当て台。', '名詞', "She pressed the curved seam over a tailor's ham to preserve its rounded shape.", '縫製機器', '700'),
    ('pinking shears', '刃先がギザギザに波打っており、切った布端がほつれにくくなる裁ちばさみ。', '名詞', 'She trimmed the raw edge of the fabric with pinking shears to reduce fraying.', '縫製機器', '650'),
    ("dressmaker's shears", '片方の持ち手部分が布に沿って平らに近い形をした、生地を裁断するための大きな裁ちばさみ。', '名詞', "She cut the pattern pieces from the silk using her dressmaker's shears.", '縫製機器', '600'),
    ('dress form', '人体に近い形をした、洋裁で服を仮縫いしたりドレープを確認したりするための台。', '名詞', 'She pinned the muslin mockup onto the dress form to check the fit.', '縫製機器', '600'),
    ('thimble', '手縫いの際に、針で指を傷つけないよう指先にはめる、小さな筒状の防具。', '名詞', 'She wore a metal thimble on her middle finger while hand-stitching the hem.', '縫製機器', '600'),
    ('needle threader', '細い金属の輪などを使い、糸を針穴に通しやすくするための小さな道具。', '名詞', 'She used a needle threader because the eye of the needle was too small to see clearly.', '縫製機器', '600'),
    ('awl', '先端がとがった、布や革に小さな穴を開けるための細い錐(きり)状の道具。', '名詞', "He used an awl to punch a small hole for the leather strap's buckle.", '縫製機器', '700'),
    ('tracing wheel', 'ギザギザの歯車が付いた柄で、型紙の線を布に転写するための道具。', '名詞', 'She rolled a tracing wheel over the pattern to transfer the dart lines onto the fabric.', '縫製機器', '650'),
    ("dressmaker's pins", '先端が細く、生地を傷めにくいように設計された、洋裁用の待ち針。', '名詞', "She pinned the pattern to the fabric using a row of dressmaker's pins.", '縫製機器', '500'),
    ('zipper foot', 'ファスナーの務歯(むし)のすぐ横を縫えるように、片側が細くなった専用の押さえ金。', '名詞', "She switched to a zipper foot so she could stitch close to the zipper's teeth.", '縫製機器', '650'),
    ('buttonhole foot', '決まった長さのボタンホールを自動的に縫うために使う、専用の押さえ金。', '名詞', 'She attached a buttonhole foot to sew evenly sized holes down the front of the shirt.', '縫製機器', '700'),
    ('walking foot', '押さえ金自体にも生地を送る歯が付いており、複数の布地層を均等に送り出す押さえ金。', '名詞', "She used a walking foot to keep the quilt's three layers from shifting out of alignment.", '縫製機器', '700'),
    ('rotary cutter', '円形の刃を転がしながら生地をまっすぐ、または曲線状に裁断する道具。', '名詞', 'She glided the rotary cutter along the ruler to cut a perfectly straight strip of fabric.', '縫製機器', '600'),
    ('cutting mat', 'ロータリーカッターなどの刃から作業台を守る、自己修復性のある厚手のマット。', '名詞', 'She laid the fabric on a self-healing cutting mat before running the rotary cutter across it.', '縫製機器', '550'),
    ('pressing cloth', 'アイロンの熱から生地の表面を守るために、間に挟んで使う薄い布。', '名詞', 'She placed a pressing cloth over the wool before ironing it to avoid scorch marks.', '縫製機器', '650'),
    ('sewing kit', '針・糸・はさみ・ボタンなど、簡単な繕い物に必要な道具一式をまとめた小さな携帯用のセット。', '名詞', 'She kept a small sewing kit in her travel bag in case a button came loose.', '縫製機器', '450'),
    ('french curve', '様々な曲率の曲線が組み合わさった、型紙の襟ぐりや袖ぐりなどを描くための定規。', '名詞', 'She used a french curve to smooth out the armhole line on her pattern.', '縫製機器', '700'),
    ('pattern weight', '型紙を布の上に固定するために、待ち針の代わりに上から置いて使う小さな重り。', '名詞', 'She set pattern weights around the edges of the paper pattern instead of using pins.', '縫製機器', '600'),
    ('bodkin', '先端が丸く、片端に大きな穴が開いた長い針状の道具。ゴムひもや紐をカーテンやウエストのトンネルに通すのに使う。', '名詞', 'She threaded a bodkin with elastic and guided it through the waistband channel.', '縫製機器', '700'),
    ('needle', '手縫いやミシン縫いで糸を布に通すために使う、先端がとがった細い金属の道具。', '名詞', 'She threaded the needle before starting to hem the skirt by hand.', '縫製機器', '350'),
    ('zipper', 'かみ合う務歯(むし)をスライダーで開閉させ、衣服やかばんの開口部を留める金具。', '名詞', 'The zipper got stuck halfway up her jacket.', '縫製機器', '400'),
    ('button', '衣服の開口部を留めるために、糸で布に縫い付ける小さな円盤状の留め具。', '名詞', 'One button had popped off his shirt right before the interview.', '縫製機器', '300'),
    ('loop turner', '先端にフックの付いた細い棒状の道具。細く縫った布の筒を、裏返して表に返すのに使う。', '名詞', 'She used a loop turner to turn the narrow fabric tube right side out for the belt.', '縫製機器', '700'),
    ('seam roll', '細長い円筒形をした、袖や筒状の部分の縫い目にアイロンをかけるための詰め物入りの当て台。', '名詞', "She pressed the sleeve seam over a seam roll so the seam allowance wouldn't leave a mark on the front.", '縫製機器', '700'),
    ("tailor's clapper", 'アイロンをかけた直後の生地に押し当て、蒸気を閉じ込めて折り目や縫い目を平らに定着させる木製の道具。', '名詞', "She pressed the wool lapel with steam, then flattened it firmly with a tailor's clapper.", '縫製機器', '750'),
    ('treadle sewing machine', '電気を使わず、足元のペダルを踏んで弾み車を回し、その動力で針を動かす昔ながらのミシン。', '名詞', 'Her grandmother still used a treadle sewing machine that had been passed down for generations.', '縫製機器', '700'),
    ('buttonholer', '決まった形と長さのボタンホールを自動的に縫うための、ミシンに取り付ける付属装置。', '名詞', 'She attached a buttonholer to the machine to make sure every hole came out the same size.', '縫製機器', '700'),
    ('grommet', '布に開けた穴の縁を補強し、破れにくくするために取り付ける金属やプラスチックの輪。', '名詞', 'She punched a hole in the curtain and fastened a metal grommet around the edge.', '縫製機器', '650'),
    ('eyelet', '紐やレースを通すために布に開けられた、縁をかがったり金属で補強したりした小さな穴。', '名詞', 'She threaded the lace through each eyelet of the corset.', '縫製機器', '600'),
    ('velcro', '小さな鉤(かぎ)状とループ状の面ファスナーを組み合わせ、押し付けるだけで留められるようにした留め具。', '名詞', "The child's shoes had velcro straps instead of laces.", '縫製機器', '500'),
    ('elastic band', '伸び縮みする性質を持ち、ウエストや袖口などに縫い込んで使う細長い帯状の素材。', '名詞', 'She sewed an elastic band into the waistband so the pants would fit snugly.', '縫製機器', '450'),
    ('hook and eye', '小さな鉤(フック)と、それを受け止める輪(アイ)を組み合わせた、目立たない留め具。', '名詞', 'She fastened the top of the zipper with a small hook and eye.', '縫製機器', '650'),
    ('snap fastener', '凸型と凹型の2つの金属またはプラスチックの部品を、押し付けてかみ合わせて留める留め具。', '名詞', "The baby's onesie closed with a row of snap fasteners along the legs.", '縫製機器', '600'),
    ('interfacing', '襟やカフスなどの部分に張りを持たせるため、表地の裏に接着したり縫い付けたりする補強用の芯地。', '名詞', 'She ironed a layer of fusible interfacing onto the collar to keep it crisp.', '縫製機器', '700'),
    ('boning', 'コルセットやビスチェの形を保つために縫い込む、細く硬い帯状の芯材。かつては本物の鯨のひげが使われていた。', '名詞', 'The costume designer sewed steel boning into the corset to hold its shape.', '縫製機器', '700'),
    ('piping', '細い紐を布でくるみ、縫い目に挟み込んで縁取りとして仕立てる装飾用の細い帯。', '名詞', 'She added contrasting piping along the edge of the pillow cover.', '縫製機器', '650'),
    ('vermilion', '朱色に近い、鮮やかでやや黄みがかった赤色。かつては辰砂(しんしゃ)という鉱物から作られた顔料の色。', '名詞・形容詞', 'The temple gate was painted a striking vermilion.', '色彩', '700'),
    ('indigo', '藍色に近い、青と紫の中間のような深い青色。藍植物から採れる染料の色に由来する。', '名詞・形容詞', "Her jeans were dyed a deep indigo that hadn't faded much.", '色彩', '650'),
    ('crimson', '青みを帯びた、深く鮮やかな赤色。', '名詞・形容詞', 'The velvet curtains were a rich crimson color.', '色彩', '650'),
    ('turquoise', 'トルコ石のような、緑がかった明るい青色。', '名詞・形容詞', 'The Caribbean water looked almost turquoise near the shore.', '色彩', '600'),
    ('chartreuse', '黄色と緑の中間にあたる、明るく鮮やかな黄緑色。フランスのリキュールの色に由来する。', '名詞・形容詞', 'She painted one accent wall a bold chartreuse.', '色彩', '750'),
    ('magenta', '赤紫に近い、鮮やかなピンクがかった紫色。', '名詞・形容詞', 'The printer was low on magenta ink.', '色彩', '650'),
    ('ochre', '黄土色に近い、赤みや茶色みを帯びた黄色。土に含まれる鉱物顔料の色に由来する。', '名詞・形容詞', 'The cave walls were decorated with handprints made of ochre pigment.', '色彩', '700'),
    ('cerulean', '澄み切った空を思わせる、明るく涼しげな青色。', '名詞・形容詞', 'The sky turned a brilliant cerulean after the storm passed.', '色彩', '750'),
    ('teal', '青と緑を混ぜ合わせたような、落ち着いた深みのある青緑色。', '名詞・形容詞', 'She chose a teal sofa to add a calm accent color to the living room.', '色彩', '600'),
    ('maroon', '茶色みを帯びた、暗く深い赤色。栗(マロン)の色に由来する。', '名詞・形容詞', "The team's uniforms were maroon and gold.", '色彩', '650'),
    ('burgundy', '赤ワインを思わせる、暗く深みのある赤紫色。フランスのブルゴーニュ地方のワインの色に由来する。', '名詞・形容詞', 'He wore a burgundy tie that complemented his dark suit.', '色彩', '650'),
    ('mauve', '淡く灰色がかった紫色。世界初の合成染料によって作り出された色として知られる。', '名詞・形容詞', 'The bridesmaids wore dresses in a soft mauve.', '色彩', '700'),
    ('lilac', '淡く柔らかい、灰色がかった紫色。ライラックの花の色に由来する。', '名詞・形容詞', 'The garden was filled with lilac-colored blossoms in early spring.', '色彩', '600'),
    ('fuchsia', '鮮やかで濃いピンクがかった紫色。フクシアという花の色に由来する。', '名詞・形容詞', 'She painted her nails a bright fuchsia for the summer party.', '色彩', '700'),
    ('amber', 'はちみつのような、温かみのある黄褐色。琥珀(こはく)という宝石の色に由来する。', '名詞・形容詞', 'The traffic light glowed amber just before turning red.', '色彩', '600'),
    ('mustard', 'からし(マスタード)を思わせる、くすんだ黄色。', '名詞・形容詞', 'She wore a mustard-colored scarf that stood out against her gray coat.', '色彩', '600'),
    ('khaki', '土やほこりに近い、薄い黄褐色。もともと軍服の色として使われた。', '名詞・形容詞', 'The soldiers wore khaki uniforms suited for the desert terrain.', '色彩', '550'),
    ('taupe', 'グレーとブラウンが混ざり合ったような、落ち着いた中間色。', '名詞・形容詞', 'The living room walls were painted a warm taupe.', '色彩', '700'),
    ('ecru', '漂白していない生成りの糸や布に近い、薄いベージュがかった白色。', '名詞・形容詞', 'The wedding invitations were printed on ecru cardstock.', '色彩', '700'),
    ('charcoal', '炭のような、黒に近い濃い灰色。', '名詞・形容詞', 'He wore a charcoal suit to the business meeting.', '色彩', '550'),
    ('azure', '澄んだ空や地中海のような、鮮やかで明るい青色。', '名詞・形容詞', 'The villa overlooked an azure sea.', '色彩', '700'),
    ('aquamarine', '海水を思わせる、淡く澄んだ青緑色。宝石アクアマリンの色に由来する。', '名詞・形容詞', 'The pool water shimmered in aquamarine under the midday sun.', '色彩', '700'),
    ('viridian', '青みを帯びた、深く鮮やかな緑色。絵画用の顔料の色としても知られる。', '名詞・形容詞', 'The forest canopy was painted in shades of viridian.', '色彩', '750'),
    ('sepia', '古い写真を思わせる、赤みを帯びた茶褐色。イカ墨から作られた顔料の色に由来する。', '名詞・形容詞', 'The old family photograph had faded to a warm sepia tone.', '色彩', '650'),
    ('sienna', '赤みを帯びた黄褐色。イタリアの都市シエナ周辺で採れた土性顔料の色に由来する。', '名詞・形容詞', 'The desert cliffs glowed a warm sienna at sunset.', '色彩', '700'),
    ('puce', '赤みがかった、くすんだ暗い紫褐色。フランス語で「蚤(のみ)」を意味する語に由来するとされる。', '名詞・形容詞', 'The antique armchair was upholstered in a puce fabric that had darkened with age.', '色彩', '800'),
    ('scarlet', 'オレンジがかった、鮮やかで明るい赤色。', '名詞・形容詞', "The cardinal's feathers were a brilliant scarlet.", '色彩', '600'),
    ('ai-iro', '藍(あい)の葉を発酵させて作る染料で染めた、青みの強い濃い青色。日本で古くから着物や暖簾(のれん)の染色に使われてきた伝統色。', '名詞', 'The old workshop specialized in dyeing cotton cloth a deep ai-iro using fermented indigo leaves.', '色彩', '700'),
    ('kurenai', '紅花(べにばな)の花びらから採れる染料で染めた、鮮やかで濃い赤色。', '名詞', "The noblewoman's robe was dyed a vivid kurenai using precious safflower dye.", '色彩', '750'),
    ('sakura-iro', '桜の花びらを思わせる、ごく淡いピンク色。', '名詞', 'The kimono was dyed a delicate sakura-iro to celebrate the arrival of spring.', '色彩', '650'),
    ('nadeshiko-iro', '撫子(なでしこ)の花を思わせる、桜色よりもやや濃くやわらかいピンク色。', '名詞', 'The fabric swatch labeled nadeshiko-iro was a soft, slightly deeper pink than the sakura-iro sample beside it.', '色彩', '750'),
    ('yamabuki-iro', '山吹(やまぶき)の花を思わせる、鮮やかで濃い黄金色に近い黄色。', '名詞', 'The lacquerware was decorated with a border of yamabuki-iro that resembled gold leaf.', '色彩', '700'),
    ('moegi-iro', '芽吹いたばかりの若葱(わかねぎ)を思わせる、黄色みを帯びた明るい緑色。', '名詞', 'The spring kimono was dyed a fresh moegi-iro to suggest new plant growth.', '色彩', '700'),
    ('asagi-iro', '浅葱(あさつき)のような、緑がかった薄い青色。', '名詞', "The Shinsengumi's distinctive haori coats were dyed a pale asagi-iro.", '色彩', '700'),
    ('akane-iro', '茜(あかね)の根から採れる染料で染めた、黄みを帯びた深い赤色。夕焼け空の形容にもよく使われる。', '名詞', 'The poet described the evening sky as burning akane-iro just before sunset.', '色彩', '700'),
    ('shu-iro', '神社の鳥居や漆器によく使われる、やや黄みを帯びた鮮やかな朱色。', '名詞', 'The torii gates along the mountain path were all painted the same bright shu-iro.', '色彩', '650'),
    ('gunjo-iro', '藍銅鉱(らんどうこう)という鉱物から採れる顔料で作る、深みのある鮮やかな青色。日本画の岩絵具の代表的な色。', '名詞', "The folding screen's waves were painted in a deep gunjo-iro using traditional mineral pigment.", '色彩', '750'),
    ('ruri-iro', '瑠璃(るり、ラピスラズリ)という宝石を思わせる、深みのある青紫色。仏教では七宝の一つとされる。', '名詞', "The temple's ceiling was painted a deep ruri-iro dotted with gold stars.", '色彩', '750'),
    ('wakakusa-iro', '春に芽吹いたばかりの若草を思わせる、明るくやわらかな黄緑色。', '名詞', 'The meadow was covered in wakakusa-iro shoots just after the spring rain.', '色彩', '650'),
    ('uguisu-iro', '鶯(うぐいす)の羽を思わせる、灰色がかった落ち着いた黄緑色・茶緑色。', '名詞', 'The tea set was glazed in a muted uguisu-iro reminiscent of old bamboo groves.', '色彩', '700'),
    ('edo-murasaki', '青みを帯びた紫色。江戸で発展した紫根(しこん)染めの伝統に由来し、赤みの強い京紫と対比されることが多い。', '名詞', 'The obi was dyed in a cool-toned edo-murasaki that contrasted with the warmer kyo-murasaki sash beside it.', '色彩', '750'),
    ('kyo-murasaki', '赤みを帯びた紫色。京都で発展した染色の伝統に由来し、青みの強い江戸紫と対比されることが多い。', '名詞', "The kimono's kyo-murasaki lining had a warmer, redder tone than typical edo-murasaki dye.", '色彩', '750'),
    ('kinari-iro', '漂白や染色をしていない、生成りのままの木綿や絹の色に近い、薄い黄みを帯びた白色。', '名詞', 'The tablecloth was left in its natural kinari-iro instead of being bleached white.', '色彩', '650'),
    ('toki-iro', '鴇(とき)という鳥の風切羽を思わせる、ごく淡いピンク色。', '名詞', "The scarf was dyed a gentle toki-iro reminiscent of the crested ibis's feathers.", '色彩', '750'),
    ('ama-iro', '亜麻(あま)の繊維を思わせる、薄い黄みがかったベージュ色。英語の毛髪の色を表す表現にも用いられる。', '名詞', 'Her hair was often described as ama-iro, a soft flaxen shade between blonde and brown.', '色彩', '650'),
    ('fuji-iro', '藤(ふじ)の花房を思わせる、淡く上品な青紫色。', '名詞', 'Wisteria trellises draped in fuji-iro blossoms lined the garden path.', '色彩', '650'),
    ('sora-iro', '澄み渡った昼間の空を思わせる、明るく淡い青色。', '名詞', 'The children painted the summer sky a cheerful sora-iro.', '色彩', '550'),
    ('kuchiba-iro', '枯れて色づき始めた落ち葉を思わせる、くすんだ黄褐色。秋を表す色として古くから和歌にも詠まれてきた。', '名詞', 'The dyer mixed several pigments to achieve a subtle kuchiba-iro for the autumn textile line.', '色彩', '750'),
    ('tokiwa-iro', '松などの常緑樹の葉を思わせる、深く落ち着いた緑色。永遠に変わらないことを意味する「常磐」という言葉に由来する。', '名詞', 'The pine trees in the temple garden kept their tokiwa-iro needles throughout the winter.', '色彩', '750'),
    ('koki-hi', '深く濃い緋色(ひいろ)。飛鳥・奈良時代の位階制度において、最高位の色の一つとされたと伝えられる。', '名詞', 'Historians believe koki-hi was reserved for garments worn by only the highest-ranking court officials.', '色彩', '800'),
    ('sango-iro', '珊瑚(さんご)を思わせる、明るくやわらかいピンクがかったオレンジ色。', '名詞', 'The seashell bracelet was strung with beads in a warm sango-iro.', '色彩', '700'),
    ('karashi-iro', '和からしを思わせる、くすんだ黄色。', '名詞', 'The pillow was covered in a mustard-toned karashi-iro fabric.', '色彩', '700'),
    ('azuki-iro', '小豆(あずき)の皮を思わせる、暗い赤みを帯びた茶色。', '名詞', 'The lacquer bowl was finished in a deep azuki-iro that looked almost black in dim light.', '色彩', '700'),
]


def main() -> None:
    with db() as conn:
        existing = set()
        for r in conn.execute("SELECT english FROM words").fetchall():
            existing.add(r["english"].lower())
        inserted = 0
        skipped = 0
        for english, japanese, pos, example, domain, level in WORDS:
            if english.lower() in existing:
                skipped += 1
                continue
            conn.execute(
                "INSERT INTO words (english, japanese, part_of_speech, "
                "example, domain, level) VALUES (?, ?, ?, ?, ?, ?)",
                (english, japanese, pos, example, domain, level),
            )
            existing.add(english.lower())
            inserted += 1
        print("inserted=" + str(inserted) + " skipped=" + str(skipped))


if __name__ == "__main__":
    main()
