# ruff: noqa: E501  (data-heavy seed script: long phrase/word lines are fine)
"""Bulk-add curated phrases (+ the vocabulary they need), authored by Claude.

No app / OpenAI API calls — everything here is hand-written and inserted
directly into the SQLite DB. Duplicates are skipped by english (lowercased).

Run:  python scripts/add_phrases.py
      python scripts/add_phrases.py --missing-words   # report only
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.database import db  # noqa: E402

# --- phrases: scene -> [(english, japanese)] --------------------------------

PHRASES_BY_SCENE: dict[str, list[tuple[str, str]]] = {
    "日常会話": [
        ("How's it going?", "調子はどう？"),
        ("Long time no see.", "久しぶり。"),
        ("What have you been up to?", "最近どうしてた？"),
        ("I'm just hanging out.", "ちょっとのんびりしてるだけ。"),
        ("Take it easy.", "気楽にね／お大事に。"),
        ("Let me think about it.", "ちょっと考えさせて。"),
        ("It's up to you.", "あなた次第だよ。"),
        ("That works for me.", "それで大丈夫です。"),
        ("I'm running late.", "ちょっと遅れそう。"),
        ("Sorry to keep you waiting.", "お待たせしてごめんね。"),
        ("Never mind.", "気にしないで／何でもない。"),
        ("It doesn't matter.", "どっちでもいいよ。"),
        ("Suit yourself.", "好きにすれば。"),
        ("I can't help it.", "どうしようもないんだ。"),
        ("Let's call it a day.", "今日はこの辺にしよう。"),
        ("I'll catch up with you later.", "あとで合流するね。"),
        ("Could you do me a favor?", "お願いがあるんだけど。"),
        ("No worries.", "心配いらないよ。"),
        ("That makes sense.", "なるほど、筋が通ってる。"),
        ("I see what you mean.", "言いたいことは分かるよ。"),
        ("Just in case.", "念のため。"),
        ("Sooner or later.", "遅かれ早かれ。"),
        ("Keep me posted.", "進展があったら教えて。"),
        ("I'm on my way.", "今向かってるよ。"),
        ("Help yourself.", "ご自由にどうぞ。"),
        ("Make yourself at home.", "くつろいでね。"),
        ("It's not a big deal.", "大したことないよ。"),
        ("Let's keep in touch.", "連絡を取り合おうね。"),
        ("I owe you one.", "借りができたね／恩に着るよ。"),
        ("That's so kind of you.", "ご親切にどうも。"),
        ("Maybe some other time.", "また別の機会にね。"),
        ("I couldn't agree more.", "全く同感です。"),
        ("Don't get me wrong.", "誤解しないでね。"),
        ("Let's get started.", "さあ始めよう。"),
        ("I'm in the middle of something.", "今ちょっと取り込み中で。"),
        ("Can I get back to you?", "あとで返事してもいい？"),
        ("It slipped my mind.", "うっかり忘れてた。"),
        ("That rings a bell.", "それ、聞き覚えがある。"),
        ("I'm not in the mood.", "今その気分じゃないんだ。"),
        ("Better late than never.", "遅くてもやらないよりまし。"),
        ("Let's split the bill.", "割り勘にしよう。"),
        ("It's on me.", "ここは私のおごり。"),
        ("Speak of the devil.", "噂をすれば(影)。"),
        ("I'll keep that in mind.", "覚えておくね。"),
        ("Take care of yourself.", "体に気をつけてね。"),
    ],
    "ニュース": [
        ("The bill was passed by parliament.", "その法案は議会で可決された。"),
        ("Inflation is on the rise.", "インフレが上昇している。"),
        ("The economy is slowing down.", "景気が減速している。"),
        ("Stocks plunged on Monday.", "月曜に株価が急落した。"),
        ("The two nations reached a ceasefire.", "両国は停戦に達した。"),
        ("Officials called for an investigation.", "当局は調査を求めた。"),
        ("The death toll continues to rise.", "死者数が増え続けている。"),
        ("The central bank raised interest rates.", "中央銀行が金利を引き上げた。"),
        ("Voters head to the polls today.", "本日、有権者が投票に向かう。"),
        ("The president vowed to take action.", "大統領は行動を取ると誓った。"),
        ("A state of emergency was declared.", "非常事態が宣言された。"),
        ("Talks broke down over trade.", "貿易を巡り交渉が決裂した。"),
        ("The company announced mass layoffs.", "その企業は大規模な解雇を発表した。"),
        ("Authorities evacuated the area.", "当局はその地域を避難させた。"),
        ("The scandal sparked public outrage.", "そのスキャンダルは世論の怒りを招いた。"),
        ("Unemployment hit a record low.", "失業率が過去最低を記録した。"),
        ("The summit ended without a deal.", "首脳会談は合意なく終わった。"),
        ("Lawmakers debated the new policy.", "議員らは新政策を議論した。"),
        ("The storm left thousands without power.", "嵐で数千人が停電に陥った。"),
        ("The court overturned the ruling.", "裁判所はその判決を覆した。"),
        ("Protesters took to the streets.", "抗議者たちが街頭に繰り出した。"),
        ("The deal is subject to approval.", "その取引は承認を条件とする。"),
        ("Tensions are escalating in the region.", "その地域で緊張が高まっている。"),
        ("The report raised serious concerns.", "その報告は深刻な懸念を引き起こした。"),
        ("Exports fell sharply last quarter.", "前四半期、輸出が急減した。"),
        ("The measure aims to curb emissions.", "その措置は排出削減を目指す。"),
        ("A breakthrough was announced today.", "本日、画期的な進展が発表された。"),
        ("The suspect was taken into custody.", "容疑者は拘束された。"),
        ("Aid is being sent to the victims.", "被災者へ支援が送られている。"),
        ("The findings were published in a journal.", "その研究結果は学術誌に掲載された。"),
    ],
    "出入国・税関": [
        ("What's the purpose of your visit?", "訪問の目的は何ですか？"),
        ("I'm here on business.", "出張で来ました。"),
        ("I'm here for sightseeing.", "観光で来ました。"),
        ("How long will you be staying?", "どのくらい滞在しますか？"),
        ("I'll be staying for two weeks.", "2週間滞在します。"),
        ("Where are you staying?", "どこに滞在しますか？"),
        ("I'm staying at a hotel downtown.", "繁華街のホテルに泊まります。"),
        ("Do you have anything to declare?", "申告するものはありますか？"),
        ("I have nothing to declare.", "申告するものはありません。"),
        ("Please fill out this form.", "この用紙にご記入ください。"),
        ("May I see your passport?", "パスポートを見せてください。"),
        ("Here's my return ticket.", "これが帰りの航空券です。"),
        ("Could you open your bag, please?", "カバンを開けていただけますか？"),
        ("These are for personal use.", "これらは個人使用のためです。"),
        ("Is this within the duty-free limit?", "これは免税の範囲内ですか？"),
        ("Where can I claim my baggage?", "手荷物はどこで受け取れますか？"),
        ("My luggage didn't arrive.", "荷物が届きませんでした。"),
        ("I'd like to report a lost bag.", "荷物の紛失を届け出たいです。"),
        ("Which carousel is for flight 12?", "12便はどのターンテーブルですか？"),
        ("Please proceed to immigration.", "入国審査へお進みください。"),
        ("Step this way, please.", "こちらへどうぞ。"),
        ("Do I need to pay duty on this?", "これに関税はかかりますか？"),
        ("I'm just transiting.", "乗り継ぎ(トランジット)です。"),
        ("Where is the connecting flight gate?", "乗り継ぎ便のゲートはどこですか？"),
        ("Please remove your shoes and belt.", "靴とベルトを外してください。"),
        ("Put your laptop in a separate tray.", "ノートPCは別のトレイに入れてください。"),
        ("I'm carrying some medication.", "薬を持っています。"),
        ("Here is my customs declaration.", "これが私の税関申告書です。"),
        ("Enjoy your stay.", "良いご滞在を。"),
        ("Welcome back home.", "おかえりなさい。"),
    ],
    "ホテル": [
        ("I have a reservation under Tanaka.", "田中で予約しています。"),
        ("I'd like to check in, please.", "チェックインをお願いします。"),
        ("Do you have any vacancies tonight?", "今夜空室はありますか？"),
        ("Is breakfast included?", "朝食は含まれていますか？"),
        ("What time is checkout?", "チェックアウトは何時ですか？"),
        ("Could I have a wake-up call at six?", "6時にモーニングコールをお願いできますか？"),
        ("Can I leave my luggage here?", "荷物を預かってもらえますか？"),
        ("The air conditioning isn't working.", "エアコンが効きません。"),
        ("Could I get extra towels?", "タオルを追加でもらえますか？"),
        ("The room next door is very noisy.", "隣の部屋がとてもうるさいです。"),
        ("Is there free Wi-Fi in the room?", "部屋に無料Wi-Fiはありますか？"),
        ("Could you call me a taxi?", "タクシーを呼んでもらえますか？"),
        ("I'd like a non-smoking room.", "禁煙室をお願いします。"),
        ("Is there a safe in the room?", "部屋に金庫はありますか？"),
        ("Could you recommend a good restaurant nearby?", "近くで良いレストランを教えてもらえますか？"),
        ("I'd like to extend my stay by one night.", "1泊延長したいのですが。"),
        ("Can I have a late checkout?", "レイトチェックアウトはできますか？"),
        ("There's no hot water.", "お湯が出ません。"),
        ("Could you charge it to my room?", "部屋付けにしてもらえますか？"),
        ("I locked myself out of my room.", "部屋に鍵を置いたまま締め出されました。"),
        ("Where is the elevator?", "エレベーターはどこですか？"),
        ("Is there a laundry service?", "ランドリーサービスはありますか？"),
        ("Could I have a room with a view?", "眺めの良い部屋にできますか？"),
        ("The toilet is clogged.", "トイレが詰まっています。"),
        ("Can I check in early?", "早めにチェックインできますか？"),
        ("Do you offer airport shuttle service?", "空港送迎はありますか？"),
        ("I'd like to settle my bill.", "会計をお願いします。"),
        ("Could I get a receipt, please?", "領収書をもらえますか？"),
        ("Thank you for a wonderful stay.", "素敵な滞在をありがとう。"),
        ("Is there a fee for cancellation?", "キャンセル料はかかりますか？"),
    ],
    "レストラン・カフェ": [
        ("A table for two, please.", "2名でお願いします。"),
        ("Do you have a table by the window?", "窓際の席はありますか？"),
        ("Could we see the menu, please?", "メニューを見せてもらえますか？"),
        ("What do you recommend?", "おすすめは何ですか？"),
        ("What's today's special?", "本日のおすすめは何ですか？"),
        ("I'll have the same.", "私も同じものを。"),
        ("Could I have it without onions?", "玉ねぎ抜きにできますか？"),
        ("I'm allergic to nuts.", "ナッツアレルギーがあります。"),
        ("Is this dish spicy?", "この料理は辛いですか？"),
        ("Could I get a glass of water?", "お水を一杯もらえますか？"),
        ("How would you like your steak?", "ステーキの焼き加減は？"),
        ("Medium rare, please.", "ミディアムレアでお願いします。"),
        ("Could we have separate checks?", "お会計は別々にできますか？"),
        ("Can I get this to go?", "持ち帰りにできますか？"),
        ("Could I have the bill, please?", "お会計をお願いします。"),
        ("Does this contain any dairy?", "これに乳製品は入っていますか？"),
        ("I'd like a refill, please.", "おかわりをお願いします。"),
        ("Could you make it less salty?", "塩を控えめにできますか？"),
        ("Is service charge included?", "サービス料は含まれていますか？"),
        ("We're ready to order.", "注文をお願いします。"),
        ("Could we have a few more minutes?", "もう少し待ってもらえますか？"),
        ("This isn't what I ordered.", "これは注文したものと違います。"),
        ("Could I have a doggy bag?", "残りを持ち帰る袋をもらえますか？"),
        ("Keep the change.", "お釣りは取っておいてください。"),
        ("A latte to go, please.", "ラテをテイクアウトで。"),
        ("Could I have it decaf?", "カフェイン抜きにできますか？"),
        ("For here or to go?", "店内ですか、お持ち帰りですか？"),
        ("Is there a vegetarian option?", "ベジタリアン向けはありますか？"),
        ("The food was delicious, thank you.", "料理は美味しかったです、ありがとう。"),
        ("Could we get some napkins?", "紙ナプキンをもらえますか？"),
        ("Can I pay by card?", "カードで払えますか？"),
        ("Cheers!", "乾杯！"),
        ("My compliments to the chef.", "シェフに『美味しかった』とお伝えください。"),
        ("Could you split this into three?", "これを3つに分けてもらえますか？"),
        ("I'd like to make a reservation for tonight.", "今夜の予約をしたいのですが。"),
    ],
    "両替・買い物": [
        ("Where can I exchange money?", "どこで両替できますか？"),
        ("What's the exchange rate today?", "今日の為替レートはいくらですか？"),
        ("Could you break this bill?", "この紙幣をくずしてもらえますか？"),
        ("I'd like smaller bills, please.", "小さい紙幣にしてください。"),
        ("Is there a commission fee?", "手数料はかかりますか？"),
        ("How much is this?", "これはいくらですか？"),
        ("That's a bit too expensive.", "ちょっと高すぎます。"),
        ("Can you give me a discount?", "値引きしてもらえますか？"),
        ("Do you take credit cards?", "クレジットカードは使えますか？"),
        ("I'm just looking, thanks.", "見ているだけです、ありがとう。"),
        ("Could I try this on?", "試着してもいいですか？"),
        ("Do you have this in a larger size?", "これの大きいサイズはありますか？"),
        ("Do you have it in another color?", "別の色はありますか？"),
        ("Where is the fitting room?", "試着室はどこですか？"),
        ("It doesn't fit.", "サイズが合いません。"),
        ("I'll take it.", "これをください。"),
        ("Could I get a receipt?", "領収書をもらえますか？"),
        ("Can I get a refund?", "返金してもらえますか？"),
        ("I'd like to return this.", "これを返品したいです。"),
        ("Is this on sale?", "これはセール中ですか？"),
        ("Do you offer tax-free shopping?", "免税で買えますか？"),
        ("Could you gift-wrap this?", "贈り物用に包んでもらえますか？"),
        ("Where do I pay?", "どこで支払いますか？"),
        ("Keep the receipt just in case.", "念のため領収書を取っておいて。"),
        ("That's all for today.", "今日はこれで全部です。"),
        ("Can I pay in cash?", "現金で払えますか？"),
        ("Do you have a loyalty card?", "ポイントカードはありますか？"),
        ("Is the warranty included?", "保証は付いていますか？"),
        ("Could you hold this for me?", "これを取り置きしてもらえますか？"),
        ("Where are the shopping carts?", "ショッピングカートはどこですか？"),
    ],
    "道案内・観光": [
        ("Excuse me, how do I get to the station?", "すみません、駅へはどう行きますか？"),
        ("Is it within walking distance?", "歩いて行ける距離ですか？"),
        ("How long does it take on foot?", "歩いてどのくらいかかりますか？"),
        ("Go straight and turn left at the corner.", "まっすぐ行って角を左に曲がって。"),
        ("It's just around the corner.", "すぐその角を曲がったところです。"),
        ("It's across from the bank.", "銀行の向かいです。"),
        ("It's next to the post office.", "郵便局の隣です。"),
        ("You can't miss it.", "すぐ分かりますよ。"),
        ("Which bus goes downtown?", "どのバスが繁華街に行きますか？"),
        ("Where's the nearest subway station?", "最寄りの地下鉄駅はどこですか？"),
        ("Does this train stop at the museum?", "この電車は博物館に止まりますか？"),
        ("How much is a one-way ticket?", "片道切符はいくらですか？"),
        ("I'd like a round-trip ticket.", "往復切符をください。"),
        ("Where can I catch a taxi?", "どこでタクシーをつかまえられますか？"),
        ("Could you show me on the map?", "地図で示してもらえますか？"),
        ("I think I'm lost.", "道に迷ったみたいです。"),
        ("Is this the right way to the park?", "公園へはこの道で合っていますか？"),
        ("What time does it open?", "何時に開きますか？"),
        ("How much is the admission?", "入場料はいくらですか？"),
        ("Are there any guided tours?", "ガイドツアーはありますか？"),
        ("Can I take pictures here?", "ここで写真を撮ってもいいですか？"),
        ("Could you take a picture of us?", "私たちの写真を撮ってもらえますか？"),
        ("What's worth seeing around here?", "この辺で見る価値のあるものは？"),
        ("Is there an entrance fee?", "入場料はかかりますか？"),
        ("When is the last train?", "終電は何時ですか？"),
        ("Where is the tourist information center?", "観光案内所はどこですか？"),
        ("Do you have a map in English?", "英語の地図はありますか？"),
        ("How far is it from here?", "ここからどのくらいの距離ですか？"),
        ("Take the second exit.", "2番目の出口を出てください。"),
        ("It's a five-minute walk.", "歩いて5分です。"),
    ],
    "病院・病状": [
        ("I'd like to see a doctor.", "医者に診てもらいたいです。"),
        ("I don't feel well.", "気分が良くありません。"),
        ("I have a fever.", "熱があります。"),
        ("I have a headache.", "頭が痛いです。"),
        ("I have a sore throat.", "喉が痛いです。"),
        ("I've been coughing a lot.", "咳がひどく出ます。"),
        ("My stomach hurts.", "お腹が痛いです。"),
        ("I feel dizzy.", "めまいがします。"),
        ("I feel nauseous.", "吐き気がします。"),
        ("It hurts here.", "ここが痛いです。"),
        ("I twisted my ankle.", "足首をひねりました。"),
        ("I'm allergic to penicillin.", "ペニシリンにアレルギーがあります。"),
        ("I have high blood pressure.", "高血圧です。"),
        ("How many times a day should I take this?", "1日に何回飲めばいいですか？"),
        ("Are there any side effects?", "副作用はありますか？"),
        ("Could I have a prescription?", "処方箋をもらえますか？"),
        ("Where is the nearest pharmacy?", "最寄りの薬局はどこですか？"),
        ("I need to refill my medication.", "薬を追加でもらう必要があります。"),
        ("I've had this pain for three days.", "この痛みが3日続いています。"),
        ("Do I need to fast before the test?", "検査の前は絶食が必要ですか？"),
        ("Should I see a specialist?", "専門医に診てもらうべきですか？"),
        ("I think I caught a cold.", "風邪をひいたみたいです。"),
        ("Can I have a doctor's note?", "診断書をもらえますか？"),
        ("Is this covered by insurance?", "これは保険でカバーされますか？"),
        ("Please call an ambulance.", "救急車を呼んでください。"),
        ("I'm pregnant.", "妊娠しています。"),
        ("I feel short of breath.", "息切れがします。"),
        ("My vision is blurry.", "視界がぼやけます。"),
        ("I've lost my appetite.", "食欲がありません。"),
        ("I'm running out of my medicine.", "薬が切れそうです。"),
        ("Take this twice a day after meals.", "これを1日2回、食後に飲んでください。"),
        ("Rest and drink plenty of fluids.", "安静にして水分をたくさん取ってください。"),
        ("The wound is swollen.", "傷口が腫れています。"),
        ("I need a refill of my prescription.", "処方薬の追加が必要です。"),
        ("Where does it hurt the most?", "一番痛むのはどこですか？"),
    ],
    "警察・トラブル": [
        ("I'd like to report a theft.", "盗難を届け出たいです。"),
        ("My wallet was stolen.", "財布を盗まれました。"),
        ("Someone broke into my car.", "車に侵入されました。"),
        ("I lost my passport.", "パスポートをなくしました。"),
        ("Could you help me, please?", "助けてもらえますか？"),
        ("Please call the police.", "警察を呼んでください。"),
        ("I need to file a report.", "被害届を出す必要があります。"),
        ("I was pickpocketed on the train.", "電車でスリに遭いました。"),
        ("Where is the nearest police station?", "最寄りの交番／警察署はどこですか？"),
        ("Can I get a copy of the report?", "報告書の写しをもらえますか？"),
        ("I need it for my insurance.", "保険の手続きに必要なんです。"),
        ("I've been robbed.", "強盗に遭いました。"),
        ("My phone was snatched.", "スマホをひったくられました。"),
        ("I witnessed an accident.", "事故を目撃しました。"),
        ("There's been a car accident.", "交通事故が起きました。"),
        ("Is anyone hurt?", "誰かけがをしていますか？"),
        ("Could you contact my embassy?", "大使館に連絡してもらえますか？"),
        ("I don't speak the language well.", "言葉があまり話せません。"),
        ("Could you speak more slowly?", "もっとゆっくり話してもらえますか？"),
        ("This is an emergency.", "緊急事態です。"),
        ("I left my bag on the bus.", "バスにカバンを置き忘れました。"),
        ("Has anyone turned in a lost phone?", "なくした携帯の届けは出ていますか？"),
        ("I'd like to report a missing person.", "人の行方不明を届け出たいです。"),
        ("Someone is following me.", "誰かに付けられています。"),
        ("Please stay calm.", "落ち着いてください。"),
    ],
    "観光客対応": [
        ("Do you need any help?", "お手伝いしましょうか？"),
        ("Are you looking for something?", "何かお探しですか？"),
        ("Let me show you the way.", "道をご案内します。"),
        ("It's about ten minutes from here.", "ここから10分ほどです。"),
        ("You should take the JR line.", "JR線に乗るといいですよ。"),
        ("Would you like me to call a taxi?", "タクシーをお呼びしましょうか？"),
        ("I'm afraid I don't know.", "あいにく分かりません。"),
        ("Let me ask someone for you.", "誰かに聞いてあげます。"),
        ("This way, please.", "こちらへどうぞ。"),
        ("Be careful, the floor is wet.", "足元にご注意を、床が濡れています。"),
        ("You can use this app for directions.", "道案内にはこのアプリが使えますよ。"),
        ("The restroom is over there.", "お手洗いはあちらです。"),
        ("Enjoy your trip!", "良い旅を！"),
        ("Would you like a recommendation?", "おすすめをご紹介しましょうか？"),
        ("That temple is definitely worth a visit.", "あのお寺は一見の価値がありますよ。"),
        ("It might be crowded on weekends.", "週末は混むかもしれません。"),
        ("You can buy a ticket at the machine.", "券売機で切符が買えます。"),
        ("Do you need directions?", "道案内は必要ですか？"),
        ("Cash is safer to carry here.", "ここでは現金の方が安全ですよ。"),
        ("Watch your step.", "足元にお気をつけて。"),
        ("Would you like me to write it down?", "書いてあげましょうか？"),
        ("It's free of charge.", "無料ですよ。"),
        ("Please line up here.", "ここに並んでください。"),
        ("I hope you enjoy your stay.", "良いご滞在になりますように。"),
        ("Feel free to ask me anything.", "何でも遠慮なく聞いてください。"),
    ],
    "慣用句・引用": [
        ("Break a leg!", "頑張って！(成功を祈る)"),
        ("It's a piece of cake.", "朝飯前だよ。"),
        ("It costs an arm and a leg.", "とても高くつく。"),
        ("Bite the bullet.", "歯を食いしばって耐える。"),
        ("The ball is in your court.", "次はあなたの番(決断はあなた次第)。"),
        ("Don't beat around the bush.", "遠回しに言わないで。"),
        ("It's not rocket science.", "そんなに難しいことじゃない。"),
        ("Let the cat out of the bag.", "うっかり秘密を漏らす。"),
        ("Once in a blue moon.", "ごくまれに。"),
        ("Hit the nail on the head.", "まさに的を射ている。"),
        ("Cut to the chase.", "本題に入ろう。"),
        ("It's raining cats and dogs.", "土砂降りだ。"),
        ("Actions speak louder than words.", "行動は言葉より雄弁。"),
        ("The early bird catches the worm.", "早起きは三文の徳。"),
        ("Don't put all your eggs in one basket.", "一つに賭けすぎるな。"),
        ("When in Rome, do as the Romans do.", "郷に入っては郷に従え。"),
        ("Every cloud has a silver lining.", "どんな不幸にも良い面がある。"),
        ("A blessing in disguise.", "災い転じて福となす。"),
        ("Practice makes perfect.", "習うより慣れろ。"),
        ("Better safe than sorry.", "用心に越したことはない。"),
        ("Speak of the devil.", "噂をすれば影。"),
        ("Kill two birds with one stone.", "一石二鳥。"),
        ("That's the last straw.", "もう我慢の限界だ。"),
        ("Burn the midnight oil.", "夜更かしして勉強(仕事)する。"),
        ("Call it a day.", "今日はここまでにする。"),
        ("Under the weather.", "体調がすぐれない。"),
        ("Pull yourself together.", "気をしっかり持って。"),
        ("It's water under the bridge.", "もう済んだこと(水に流す)。"),
        ("Give it a shot.", "ためしにやってみて。"),
        ("Read between the lines.", "行間を読む。"),
        ("The grass is always greener on the other side.", "隣の芝は青い。"),
        ("Don't judge a book by its cover.", "見かけで判断するな。"),
        ("Time flies.", "光陰矢のごとし。"),
        ("Easy come, easy go.", "得やすいものは失いやすい。"),
        ("No pain, no gain.", "苦労なくして得るものなし。"),
    ],
    "宗教・古典": [
        ("Do unto others as you would have them do unto you.", "己の欲するところを人に施せ(黄金律)。"),
        ("The spirit is willing, but the flesh is weak.", "心は燃えても肉体は弱い。"),
        ("Ashes to ashes, dust to dust.", "塵は塵に、灰は灰に(葬送の句)。"),
        ("An eye for an eye.", "目には目を。"),
        ("Forbidden fruit.", "禁断の果実。"),
        ("A leap of faith.", "結果を恐れず信じて踏み出すこと。"),
        ("The promised land.", "約束の地。"),
        ("A good Samaritan.", "困った人を助ける親切な人。"),
        ("The writing on the wall.", "不吉な前兆。"),
        ("Patience is a virtue.", "忍耐は美徳。"),
        ("Pride comes before a fall.", "おごれる者久しからず。"),
        ("To thine own self be true.", "己自身に忠実であれ(シェイクスピア)。"),
        ("All that glitters is not gold.", "光るもの必ずしも金ならず。"),
        ("Brevity is the soul of wit.", "簡潔は機知の真髄。"),
        ("Vanity of vanities, all is vanity.", "空の空、すべては空(伝道の書)。"),
        ("Let there be light.", "光あれ。"),
        ("Turn the other cheek.", "もう一方の頬を向けよ(報復しない)。"),
        ("The meek shall inherit the earth.", "柔和な者は地を受け継ぐ。"),
        ("To err is human, to forgive divine.", "過つは人の常、許すは神の業。"),
        ("Cast the first stone.", "最初に石を投げる(真っ先に非難する)。"),
    ],
    "ビジネス": [
        ("Let's touch base next week.", "来週、状況を確認し合いましょう。"),
        ("I'll get back to you by end of day.", "本日中にご返信します。"),
        ("Let's circle back to that later.", "その件は後で戻りましょう。"),
        ("Can we push the meeting to three?", "会議を3時にずらせますか？"),
        ("I'll loop you in on the email.", "メールにあなたも加えておきます。"),
        ("Let's take this offline.", "この件は別途個別に話しましょう。"),
        ("We're on the same page.", "認識は一致しています。"),
        ("Let's keep it brief.", "手短にしましょう。"),
        ("Could you walk me through the numbers?", "数字を順を追って説明してもらえますか？"),
        ("Let's set up a call.", "電話会議を設定しましょう。"),
        ("I'll send you the minutes.", "議事録をお送りします。"),
        ("We need to meet the deadline.", "締め切りに間に合わせる必要があります。"),
        ("Let's prioritize the key tasks.", "重要なタスクを優先しましょう。"),
        ("I'm tied up all morning.", "午前中はずっと手が離せません。"),
        ("Let's follow up tomorrow.", "明日フォローしましょう。"),
        ("That's outside my area of expertise.", "それは私の専門外です。"),
        ("Let's run the numbers again.", "もう一度数字を計算しましょう。"),
        ("Can you cover for me?", "代わりに対応してもらえますか？"),
        ("I'll cc you on that.", "それについてはCcに入れます。"),
        ("Let's table this discussion.", "この議論は一旦保留にしましょう。"),
        ("We're behind schedule.", "予定より遅れています。"),
        ("Let's think outside the box.", "既成概念にとらわれず考えよう。"),
        ("I'll draft a proposal.", "提案書のたたき台を作ります。"),
        ("Please review and sign off.", "確認して承認をお願いします。"),
        ("Let's align on the next steps.", "次の手順をすり合わせましょう。"),
        ("That's a tough call.", "それは難しい判断ですね。"),
        ("Let's play it by ear.", "状況を見ながら進めましょう。"),
        ("I'll keep you in the loop.", "随時共有します。"),
        ("Let's wrap up the meeting.", "会議を締めくくりましょう。"),
        ("Thanks for your hard work.", "お疲れさまでした。"),
        ("Let's schedule a follow-up.", "次回の打ち合わせを設定しましょう。"),
        ("I appreciate the quick turnaround.", "迅速な対応に感謝します。"),
        ("Can we revisit the budget?", "予算を見直せますか？"),
        ("Let's get everyone on board.", "全員の合意を得ましょう。"),
        ("The deal fell through.", "その取引は流れてしまいました。"),
    ],
    "家庭の会話": [
        ("Dinner's ready!", "ご飯ができたよ！"),
        ("Can you set the table?", "食卓の準備をしてくれる？"),
        ("It's your turn to do the dishes.", "皿洗いはあなたの番だよ。"),
        ("Did you take out the trash?", "ゴミ出しした？"),
        ("Don't forget to do your homework.", "宿題を忘れないでね。"),
        ("Time to wake up!", "起きる時間だよ！"),
        ("Brush your teeth before bed.", "寝る前に歯を磨いてね。"),
        ("Could you turn down the TV?", "テレビの音を下げてくれる？"),
        ("I'm doing the laundry.", "洗濯をしているところ。"),
        ("Let's tidy up the living room.", "リビングを片付けよう。"),
        ("Who's picking up the kids?", "誰が子どもを迎えに行く？"),
        ("Dinner is on the table.", "夕飯はテーブルに置いてあるよ。"),
        ("Can you walk the dog?", "犬の散歩に行ってくれる？"),
        ("I'll be home late tonight.", "今夜は遅くなるよ。"),
        ("What's for dinner?", "夕飯は何？"),
        ("Help me carry the groceries.", "買い物を運ぶのを手伝って。"),
        ("Turn off the lights when you leave.", "出るときは電気を消してね。"),
        ("Make your bed, please.", "ベッドを整えてね。"),
        ("Stop fighting, you two.", "二人ともケンカはやめなさい。"),
        ("Dinner will be ready in ten minutes.", "夕飯はあと10分でできるよ。"),
        ("Could you pass the salt?", "塩を取ってくれる？"),
        ("I'll do the cooking tonight.", "今夜は私が料理するね。"),
        ("Hang up your coat.", "コートを掛けてね。"),
        ("Did you feed the cat?", "猫にエサあげた？"),
        ("Let's order in tonight.", "今夜は出前にしよう。"),
        ("Keep your voice down.", "声を小さくしてね。"),
        ("Wash your hands before eating.", "食べる前に手を洗って。"),
        ("I'm running to the store.", "ちょっと店に行ってくるね。"),
        ("Could you water the plants?", "植木に水をやってくれる？"),
        ("Good night, sleep tight.", "おやすみ、ぐっすりね。"),
    ],
    "友人の会話": [
        ("Let's grab a bite.", "軽く何か食べに行こう。"),
        ("Wanna hang out this weekend?", "週末遊ばない？"),
        ("What are you up to tonight?", "今夜どうするの？"),
        ("Let's catch up soon.", "近いうちに会って話そう。"),
        ("My treat this time.", "今回は私のおごりね。"),
        ("That's hilarious!", "それ超ウケる！"),
        ("No way, seriously?", "うそでしょ、マジで？"),
        ("I'm so down for that.", "それ、めっちゃ乗り気。"),
        ("Count me in.", "私も参加するよ。"),
        ("I'll pass this time.", "今回はやめておくよ。"),
        ("Let's hit the gym.", "ジムに行こう。"),
        ("Text me when you're free.", "暇になったら連絡して。"),
        ("It's been ages!", "本当に久しぶり！"),
        ("You nailed it!", "完璧だったね！"),
        ("Don't worry, I've got your back.", "心配しないで、味方だよ。"),
        ("Let's binge-watch something.", "何か一気見しようよ。"),
        ("I'm broke until payday.", "給料日まで金欠なんだ。"),
        ("Let's split the bill.", "割り勘にしよう。"),
        ("Are you free tomorrow?", "明日空いてる？"),
        ("Let's take a selfie.", "自撮りしよう。"),
        ("My bad.", "ごめん、私のミス。"),
        ("Chill out.", "落ち着いてよ。"),
        ("That's awesome!", "それ最高じゃん！"),
        ("Same here.", "私も同じ。"),
        ("Let's make it happen.", "実現させようよ。"),
        ("I'm running on empty.", "もうへとへとだよ。"),
        ("Catch you later.", "またあとでね。"),
        ("Hit me up anytime.", "いつでも連絡してね。"),
        ("Let's call it a night.", "今夜はお開きにしよう。"),
        ("You can crash at my place.", "うちに泊まっていいよ。"),
    ],
    "趣味": [
        ("I've taken up gardening.", "ガーデニングを始めたんだ。"),
        ("I'm growing tomatoes in my backyard.", "裏庭でトマトを育てているよ。"),
        ("The seedlings are sprouting.", "苗が芽を出してきた。"),
        ("I need to water the plants daily.", "毎日水やりが必要なんだ。"),
        ("It's time to prune the roses.", "バラの剪定の時期だ。"),
        ("I practice the piano every morning.", "毎朝ピアノを練習している。"),
        ("I'm learning a new piece.", "新しい曲を練習中なんだ。"),
        ("Let's play this duet together.", "この連弾を一緒に弾こう。"),
        ("I'm a bit rusty.", "ちょっと腕が鈍ってるよ。"),
        ("Could you turn the page for me?", "楽譜をめくってくれる？"),
        ("I love listening to jazz.", "ジャズを聴くのが好きなんだ。"),
        ("This melody is stuck in my head.", "このメロディーが頭から離れない。"),
        ("I went stargazing last night.", "昨夜、星を見に行ったよ。"),
        ("You can see the constellation clearly.", "その星座がはっきり見えるよ。"),
        ("I set up my telescope on the balcony.", "ベランダに望遠鏡を据えたんだ。"),
        ("The full moon is beautiful tonight.", "今夜は満月がきれいだ。"),
        ("I'm into astronomy these days.", "最近は天文学にはまってる。"),
        ("I'm reading a classic novel.", "古典小説を読んでいるところ。"),
        ("This author has a beautiful writing style.", "この作家は美しい文体だね。"),
        ("I couldn't put the book down.", "本を置けないほど夢中になった。"),
        ("Let's start a book club.", "読書会を始めようよ。"),
        ("I sketch in my free time.", "暇なときにスケッチをするんだ。"),
        ("I've been baking bread lately.", "最近パンを焼いているよ。"),
        ("I go hiking on weekends.", "週末はハイキングに行く。"),
        ("The harvest was good this year.", "今年は収穫が良かった。"),
        ("I repotted the herbs yesterday.", "昨日ハーブを植え替えた。"),
        ("This soil drains well.", "この土は水はけが良い。"),
        ("I'm composing a short tune.", "短い曲を作っているんだ。"),
        ("The orchestra is tuning up.", "オーケストラが音合わせをしている。"),
        ("I collect vinyl records.", "レコードを集めているんだ。"),
        ("Let's watch the meteor shower.", "流星群を見ようよ。"),
        ("I joined a choir.", "合唱団に入ったよ。"),
        ("My garden is in full bloom.", "庭が満開だよ。"),
        ("I'm trying watercolor painting.", "水彩画に挑戦している。"),
        ("Reading broadens the mind.", "読書は心を豊かにする。"),
    ],
    "禁止用語（注意喚起）": [
        ("Shut up!", "黙れ！〔とても無礼。使用は避ける〕"),
        ("Get lost!", "失せろ！〔強い拒絶。失礼〕"),
        ("That sucks.", "最悪だ。〔くだけた俗語。場面に注意〕"),
        ("What the hell?", "一体何だ？〔いらだち。丁寧な場では不適切〕"),
        ("Damn it!", "ちくしょう！〔軽い罵り。フォーマルでは避ける〕"),
        ("Knock it off!", "いいかげんにしろ！〔強い注意。乱暴〕"),
        ("You're an idiot.", "ばかだな。〔侮辱。相手を傷つける〕"),
        ("Mind your own business.", "余計なお世話だ。〔突き放す表現。失礼〕"),
        ("Give me a break.", "勘弁してよ。〔いらだち・皮肉〕"),
        ("That's none of your business.", "あなたには関係ない。〔冷たい・無礼〕"),
        ("Screw it.", "もうどうでもいい。〔投げやりな俗語。下品〕"),
        ("You'd better watch it.", "気をつけろよ。〔脅し気味。注意〕"),
        ("Cut the crap.", "ふざけるな／本題に入れ。〔下品。使用注意〕"),
        ("Back off!", "引っ込んでろ！〔威嚇的。失礼〕"),
        ("I don't give a damn.", "知ったことか。〔無関心を乱暴に表す。下品〕"),
    ],
    "その他": [
        ("Could you say that again?", "もう一度言ってもらえますか？"),
        ("How do you spell that?", "それはどう綴りますか？"),
        ("What does this word mean?", "この単語はどういう意味ですか？"),
        ("Could you speak up a little?", "もう少し大きな声でお願いできますか？"),
        ("I didn't catch that.", "聞き取れませんでした。"),
        ("Let me write it down.", "メモを取らせてください。"),
        ("How do you say this in English?", "これは英語で何と言いますか？"),
        ("Bless you.", "(くしゃみに)お大事に。"),
        ("Congratulations on your new job!", "新しい仕事おめでとう！"),
        ("Happy to help.", "喜んでお手伝いします。"),
        ("What a coincidence!", "なんて偶然！"),
        ("It's a small world.", "世間は狭いね。"),
        ("Better luck next time.", "次はうまくいくよ。"),
        ("I'm crossing my fingers.", "うまくいくよう祈ってるよ。"),
        ("Let's hope for the best.", "最善を願おう。"),
        ("That's a relief.", "ほっとしたよ。"),
        ("It's worth a try.", "やってみる価値はある。"),
        ("I'm not so sure about that.", "それはどうかな。"),
        ("Let me double-check.", "もう一度確認させて。"),
        ("Just to be on the safe side.", "念には念を入れて。"),
        ("Could you clarify what you mean?", "どういう意味か教えてもらえますか？"),
        ("That's beyond me.", "それは私には分からない。"),
        ("I'll take your word for it.", "あなたの言葉を信じるよ。"),
        ("Let's agree to disagree.", "意見の相違は認め合おう。"),
        ("Time will tell.", "時が経てば分かるよ。"),
    ],
}

# --- words: (english, japanese, pos, example, domain, level) ----------------
# Notable / likely-new vocabulary appearing in the phrases above. The inserter
# skips any english already present, so common words simply fall through.

WORDS: list[tuple[str, str, str, str, str, str]] = [
    ("declare", "申告する", "動詞", "Do you have anything to declare?", "旅行", "600"),
    ("customs", "税関", "名詞", "He was stopped at customs.", "旅行", "600"),
    ("baggage", "手荷物", "名詞", "Where can I claim my baggage?", "旅行", "600"),
    ("luggage", "荷物", "名詞", "My luggage didn't arrive.", "旅行", "600"),
    ("immigration", "入国審査", "名詞", "Please proceed to immigration.", "旅行", "700"),
    ("duty-free", "免税の", "形容詞", "Is this within the duty-free limit?", "旅行", "700"),
    ("carousel", "手荷物受取りの回転台", "名詞", "Which carousel is for flight 12?", "旅行", "800"),
    ("transit", "乗り継ぎ・通過", "名詞", "I'm just in transit.", "旅行", "700"),
    ("medication", "薬・投薬", "名詞", "I'm carrying some medication.", "医療", "700"),
    ("reservation", "予約", "名詞", "I have a reservation under Tanaka.", "旅行", "600"),
    ("vacancy", "空室", "名詞", "Do you have any vacancies tonight?", "旅行", "700"),
    ("checkout", "チェックアウト・会計", "名詞", "What time is checkout?", "旅行", "600"),
    ("non-smoking", "禁煙の", "形容詞", "I'd like a non-smoking room.", "旅行", "600"),
    ("clogged", "詰まった", "形容詞", "The toilet is clogged.", "旅行", "700"),
    ("shuttle", "送迎バス", "名詞", "Do you offer airport shuttle service?", "旅行", "700"),
    ("cancellation", "取り消し・解約", "名詞", "Is there a fee for cancellation?", "旅行", "700"),
    ("allergic", "アレルギーのある", "形容詞", "I'm allergic to nuts.", "医療", "700"),
    ("dairy", "乳製品", "名詞", "Does this contain any dairy?", "医療", "600"),
    ("refill", "おかわり・補充", "名詞", "I'd like a refill, please.", "旅行", "600"),
    ("decaf", "カフェイン抜きの", "形容詞", "Could I have it decaf?", "旅行", "700"),
    ("vegetarian", "菜食主義の", "形容詞", "Is there a vegetarian option?", "旅行", "600"),
    ("commission", "手数料", "名詞", "Is there a commission fee?", "ビジネス", "700"),
    ("discount", "割引", "名詞", "Can you give me a discount?", "買い物", "600"),
    ("refund", "返金", "名詞", "Can I get a refund?", "買い物", "600"),
    ("warranty", "保証", "名詞", "Is the warranty included?", "買い物", "700"),
    ("admission", "入場(料)", "名詞", "How much is the admission?", "旅行", "600"),
    ("round-trip", "往復の", "形容詞", "I'd like a round-trip ticket.", "旅行", "600"),
    ("one-way", "片道の", "形容詞", "How much is a one-way ticket?", "旅行", "600"),
    ("fever", "発熱", "名詞", "I have a fever.", "医療", "600"),
    ("dizzy", "めまいがする", "形容詞", "I feel dizzy.", "医療", "700"),
    ("nauseous", "吐き気がする", "形容詞", "I feel nauseous.", "医療", "800"),
    ("prescription", "処方箋", "名詞", "Could I have a prescription?", "医療", "700"),
    ("pharmacy", "薬局", "名詞", "Where is the nearest pharmacy?", "医療", "600"),
    ("symptom", "症状", "名詞", "Describe your symptoms.", "医療", "700"),
    ("side effect", "副作用", "名詞", "Are there any side effects?", "医療", "700"),
    ("ambulance", "救急車", "名詞", "Please call an ambulance.", "医療", "600"),
    ("swollen", "腫れた", "形容詞", "The wound is swollen.", "医療", "700"),
    ("appetite", "食欲", "名詞", "I've lost my appetite.", "医療", "700"),
    ("insurance", "保険", "名詞", "Is this covered by insurance?", "ビジネス", "600"),
    ("theft", "窃盗", "名詞", "I'd like to report a theft.", "法律", "700"),
    ("pickpocket", "スリ", "名詞", "I was pickpocketed on the train.", "法律", "700"),
    ("rob", "強盗する・奪う", "動詞", "I've been robbed.", "法律", "600"),
    ("witness", "目撃する・証人", "動詞", "I witnessed an accident.", "法律", "700"),
    ("embassy", "大使館", "名詞", "Could you contact my embassy?", "旅行", "700"),
    ("emergency", "緊急事態", "名詞", "This is an emergency.", "医療", "600"),
    ("inflation", "インフレ・物価上昇", "名詞", "Inflation is on the rise.", "ニュース", "700"),
    ("parliament", "議会", "名詞", "The bill was passed by parliament.", "ニュース", "700"),
    ("ceasefire", "停戦", "名詞", "The two nations reached a ceasefire.", "ニュース", "800"),
    ("investigation", "調査", "名詞", "Officials called for an investigation.", "ニュース", "700"),
    ("layoff", "解雇・一時解雇", "名詞", "The company announced mass layoffs.", "ビジネス", "700"),
    ("evacuate", "避難させる", "動詞", "Authorities evacuated the area.", "ニュース", "700"),
    ("scandal", "醜聞・不祥事", "名詞", "The scandal sparked public outrage.", "ニュース", "700"),
    ("outrage", "激しい怒り", "名詞", "The scandal sparked public outrage.", "ニュース", "800"),
    ("unemployment", "失業", "名詞", "Unemployment hit a record low.", "ニュース", "700"),
    ("summit", "首脳会談", "名詞", "The summit ended without a deal.", "ニュース", "700"),
    ("emissions", "排出(物)", "名詞", "The measure aims to curb emissions.", "ニュース", "700"),
    ("custody", "拘留・保護", "名詞", "The suspect was taken into custody.", "法律", "800"),
    ("suspect", "容疑者", "名詞", "The suspect was taken into custody.", "法律", "600"),
    ("deadline", "締め切り", "名詞", "We need to meet the deadline.", "ビジネス", "600"),
    ("agenda", "議題・予定表", "名詞", "What's on the agenda today?", "ビジネス", "700"),
    ("minutes", "議事録", "名詞", "I'll send you the minutes.", "ビジネス", "700"),
    ("proposal", "提案(書)", "名詞", "I'll draft a proposal.", "ビジネス", "600"),
    ("prioritize", "優先する", "動詞", "Let's prioritize the key tasks.", "ビジネス", "700"),
    ("turnaround", "対応の速さ・好転", "名詞", "I appreciate the quick turnaround.", "ビジネス", "800"),
    ("budget", "予算", "名詞", "Can we revisit the budget?", "ビジネス", "600"),
    ("expertise", "専門知識", "名詞", "That's outside my area of expertise.", "ビジネス", "700"),
    ("chores", "家事・雑用", "名詞", "I have a lot of chores today.", "口語", "600"),
    ("laundry", "洗濯(物)", "名詞", "I'm doing the laundry.", "口語", "600"),
    ("groceries", "食料品", "名詞", "Help me carry the groceries.", "口語", "600"),
    ("tidy", "片付ける・整った", "動詞", "Let's tidy up the living room.", "口語", "600"),
    ("seedling", "苗・実生", "名詞", "The seedlings are sprouting.", "教養", "800"),
    ("sprout", "芽を出す", "動詞", "The seedlings are sprouting.", "教養", "700"),
    ("prune", "剪定する", "動詞", "It's time to prune the roses.", "教養", "800"),
    ("harvest", "収穫", "名詞", "The harvest was good this year.", "教養", "600"),
    ("repot", "鉢を植え替える", "動詞", "I repotted the herbs yesterday.", "教養", "800"),
    ("soil", "土壌", "名詞", "This soil drains well.", "科学", "600"),
    ("telescope", "望遠鏡", "名詞", "I set up my telescope on the balcony.", "科学", "700"),
    ("constellation", "星座", "名詞", "You can see the constellation clearly.", "科学", "800"),
    ("astronomy", "天文学", "名詞", "I'm into astronomy these days.", "科学", "700"),
    ("meteor", "流星", "名詞", "Let's watch the meteor shower.", "科学", "700"),
    ("orchestra", "オーケストラ", "名詞", "The orchestra is tuning up.", "文学", "600"),
    ("choir", "合唱団", "名詞", "I joined a choir.", "文学", "700"),
    ("compose", "作曲する・構成する", "動詞", "I'm composing a short tune.", "文学", "700"),
    ("rusty", "(腕が)鈍った・錆びた", "形容詞", "I'm a bit rusty.", "口語", "700"),
    ("duet", "二重奏・連弾", "名詞", "Let's play this duet together.", "文学", "700"),
    ("classic", "古典・名作", "名詞", "I'm reading a classic novel.", "文学", "600"),
    ("idiom", "慣用句", "名詞", "English is full of idioms.", "教養", "700"),
    ("proverb", "ことわざ", "名詞", "That's an old proverb.", "教養", "700"),
    ("virtue", "美徳", "名詞", "Patience is a virtue.", "宗教", "700"),
    ("meek", "柔和な・おとなしい", "形容詞", "The meek shall inherit the earth.", "宗教", "800"),
    ("scripture", "聖典・聖句", "名詞", "He quoted from scripture.", "宗教", "800"),
    ("sermon", "説教", "名詞", "The priest gave a sermon.", "宗教", "700"),
    ("coincidence", "偶然の一致", "名詞", "What a coincidence!", "口語", "700"),
    ("clarify", "明確にする", "動詞", "Could you clarify what you mean?", "ビジネス", "700"),
    ("fragile", "壊れやすい", "形容詞", "This package is fragile.", "旅行", "700"),
    ("itinerary", "旅程", "名詞", "Here is our travel itinerary.", "旅行", "800"),
    ("souvenir", "土産", "名詞", "I bought a souvenir for my family.", "旅行", "600"),
    ("fare", "運賃", "名詞", "How much is the bus fare?", "旅行", "600"),
    ("escalate", "拡大する・激化する", "動詞", "Tensions are escalating in the region.", "ニュース", "800"),
    ("curb", "抑制する", "動詞", "The measure aims to curb emissions.", "ニュース", "800"),
    ("overturn", "覆す", "動詞", "The court overturned the ruling.", "法律", "800"),
    ("ruling", "判決・裁定", "名詞", "The court overturned the ruling.", "法律", "700"),
    ("wallet", "財布", "名詞", "My wallet was stolen.", "旅行", "600"),
    ("ankle", "足首", "名詞", "I twisted my ankle.", "医療", "600"),
    ("throat", "喉", "名詞", "I have a sore throat.", "医療", "600"),
    ("fluids", "水分・体液", "名詞", "Drink plenty of fluids.", "医療", "700"),
    ("specialist", "専門医", "名詞", "Should I see a specialist?", "医療", "700"),
    ("blurry", "ぼやけた", "形容詞", "My vision is blurry.", "医療", "700"),
    ("spicy", "辛い", "形容詞", "Is this dish spicy?", "旅行", "600"),
    ("hilarious", "とても面白い", "形容詞", "That's hilarious!", "口語", "700"),
    ("napkin", "紙ナプキン", "名詞", "Could we get some napkins?", "旅行", "600"),
    ("tray", "トレー・盆", "名詞", "Put your laptop in a separate tray.", "旅行", "600"),
    ("vinyl", "レコード盤", "名詞", "I collect vinyl records.", "文学", "700"),
    ("sketch", "スケッチする", "動詞", "I sketch in my free time.", "文学", "600"),
    ("bloom", "開花する", "動詞", "My garden is in full bloom.", "教養", "700"),
    ("herb", "ハーブ・香草", "名詞", "I repotted the herbs yesterday.", "教養", "600"),
    ("melody", "旋律", "名詞", "This melody is stuck in my head.", "文学", "600"),
    ("tune", "曲・調律する", "名詞", "I'm composing a short tune.", "文学", "600"),
    ("pregnant", "妊娠した", "形容詞", "I'm pregnant.", "医療", "600"),
    ("penicillin", "ペニシリン", "名詞", "I'm allergic to penicillin.", "医療", "700"),
    ("vacancy", "空室・欠員", "名詞", "Do you have any vacancies?", "旅行", "700"),
]


# --- insertion --------------------------------------------------------------

_WORD_RE = re.compile(r"[A-Za-z][A-Za-z'-]*")
_STOP = {
    "the", "a", "an", "and", "or", "but", "if", "of", "to", "in", "on", "at",
    "for", "with", "from", "by", "as", "is", "are", "was", "were", "be", "been",
    "do", "does", "did", "have", "has", "had", "will", "would", "can", "could",
    "should", "may", "might", "must", "i", "you", "he", "she", "it", "we",
    "they", "me", "him", "her", "us", "them", "my", "your", "his", "its", "our",
    "their", "this", "that", "these", "those", "here", "there", "what", "when",
    "where", "who", "how", "why", "not", "no", "yes", "so", "up", "out", "off",
    "down", "let", "lets", "please", "thanks", "thank", "ok", "okay", "im",
    "ill", "id", "ive", "dont", "cant", "wont", "isnt", "thats", "whats",
    "very", "just", "too", "more", "some", "any", "all", "one", "two", "get",
    "got", "go", "going", "like", "want", "need", "make", "made", "take",
    "see", "now", "today", "tonight", "good", "well", "back", "about", "over",
    "into", "than", "then", "again", "really", "much", "many", "us",
}


def _content_words(phrases: list[tuple[str, str]]) -> set[str]:
    out: set[str] = set()
    for en, _ in phrases:
        for tok in _WORD_RE.findall(en.lower()):
            w = tok.strip("'-")
            if len(w) >= 4 and w not in _STOP:
                out.add(w)
    return out


def report_missing() -> None:
    """Print content words used in the new phrases that are not yet in `words`
    and not covered by the WORDS list above (authoring aid)."""
    with db() as conn:
        existing = {
            r["english"].lower()
            for r in conn.execute("SELECT english FROM words").fetchall()
        }
    covered = {w[0].lower() for w in WORDS}
    all_phrases = [p for lst in PHRASES_BY_SCENE.values() for p in lst]
    missing = sorted(
        w for w in _content_words(all_phrases)
        if w not in existing and w not in covered
    )
    print(f"missing content words ({len(missing)}):")
    print(", ".join(missing))


def main() -> int:
    if "--missing-words" in sys.argv:
        report_missing()
        return 0

    with db() as conn:
        ph_existing = {
            r["english"].lower()
            for r in conn.execute("SELECT english FROM phrases").fetchall()
        }
        w_existing = {
            r["english"].lower()
            for r in conn.execute("SELECT english FROM words").fetchall()
        }

        ph_added = ph_skipped = 0
        for scene, items in PHRASES_BY_SCENE.items():
            for en, ja in items:
                if en.lower() in ph_existing:
                    ph_skipped += 1
                    continue
                conn.execute(
                    "INSERT INTO phrases (english, japanese, scene) "
                    "VALUES (?, ?, ?)",
                    (en, ja, scene),
                )
                ph_existing.add(en.lower())
                ph_added += 1

        w_added = w_skipped = 0
        for en, ja, pos, ex, domain, level in WORDS:
            if en.lower() in w_existing:
                w_skipped += 1
                continue
            conn.execute(
                "INSERT INTO words (english, japanese, part_of_speech, "
                "example, domain, level) VALUES (?, ?, ?, ?, ?, ?)",
                (en, ja, pos, ex, domain, level),
            )
            w_existing.add(en.lower())
            w_added += 1

    print(f"phrases: +{ph_added} (skipped {ph_skipped})")
    print(f"words:   +{w_added} (skipped {w_skipped})")
    with db() as conn:
        print("totals -> phrases:",
              conn.execute("SELECT COUNT(*) FROM phrases").fetchone()[0],
              "words:",
              conn.execute("SELECT COUNT(*) FROM words").fetchone()[0])
    return 0


if __name__ == "__main__":
    sys.exit(main())
