# ruff: noqa: E501  (data-heavy seed script: long word/phrase lines are fine)
"""動物学ニッチ6分野の一般語彙拡充(2026-09-09・B24タスク・authored by
Claude)。両生類(4→)/甲殻類(4→)/軟体動物(6→)/動物(魚類)(12→)/爬虫類(14→)/
動物園・植物園(12→)の6分野を6並列サブエージェントで下書き→統合。

各エージェントが既存DB全体との重複チェック済み。統合時に班をまたいだ
重複5件を解消(carapace=甲殻類を採用/爬虫類側は不採用、lateral line=
動物(魚類)を採用/両生類側は不採用、spawn=動物(魚類)を採用/軟体動物側は
不採用、brumation=爬虫類を採用/両生類側は不採用、vivarium=爬虫類を
採用/動物園・植物園側は不採用)。

No app / OpenAI API calls — hand-written、inserted directly into SQLite.
Duplicates skipped by english (lowercased) against the full live `words` table.

Run:  python scripts/add_zoology_niche_2026_09_09.py
仕上げ: relevel.pyは実行しない(add_math_advanced.pyと同じ理由。
一般分野の穴埋めのため元よりlevelは300-850程度の低め)。
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.database import db  # noqa: E402

WORDS: list[tuple[str, str, str, str, str, str]] = [
    ("axolotl", "アホロートル・ウーパールーパー", "名詞", "The axolotl can regenerate an entire limb within weeks, without leaving any scar tissue.", "両生類", "450"),
    ("caecilian", "アシナシイモリ", "名詞", "Caecilians look so much like large earthworms or snakes that many people don't even realize they are amphibians.", "両生類", "750"),
    ("tree frog", "アマガエル", "名詞", "Tree frogs have sticky pads on their toes that let them climb smooth leaves and glass with ease.", "両生類", "400"),
    ("poison dart frog", "ヤドクガエル", "名詞", "Indigenous hunters in South America once tipped their blowgun darts with the skin secretions of certain poison dart frogs.", "両生類", "450"),
    ("bullfrog", "ウシガエル", "名詞", "The bullfrog gets its name from its deep, low-pitched call, which resembles the bellow of a bull.", "両生類", "400"),
    ("glass frog", "ガラスガエル", "名詞", "In some glass frog species, you can see the heart beating right through the translucent skin of the belly.", "両生類", "600"),
    ("horned frog", "ツノガエル", "名詞", "With its huge mouth and horn-like ridges above the eyes, the horned frog ambushes almost anything that moves nearby.", "両生類", "600"),
    ("cane toad", "オオヒキガエル", "名詞", "Cane toads were brought to Australia in 1935 to control a beetle that was damaging sugar cane crops.", "両生類", "500"),
    ("midwife toad", "サンバガエル", "名詞", "The male midwife toad wraps the string of fertilized eggs around his hind legs and carries them on land until they are ready to hatch.", "両生類", "650"),
    ("Surinam toad", "コモリガエル", "名詞", "The female Surinam toad carries her eggs embedded in small pits on her back until fully formed young froglets emerge.", "両生類", "650"),
    ("Goliath frog", "ゴライアスガエル", "名詞", "The Goliath frog, found only in a few rivers in Cameroon and Equatorial Guinea, can weigh more than 3 kilograms.", "両生類", "550"),
    ("hellbender", "ヘルベンダー(アメリカオオサンショウウオ)", "名詞", "The hellbender breathes mostly through the wrinkled folds of skin along its sides rather than through its small lungs.", "両生類", "650"),
    ("mudpuppy", "マッドパピー", "名詞", "A mudpuppy keeps its bushy red external gills for its entire life and never leaves the water, even as an adult.", "両生類", "650"),
    ("leopard frog", "ヒョウガエル", "名詞", "The leopard frog is named for the dark, round spots scattered across its green or brown back.", "両生類", "500"),
    ("wood frog", "ウッドフロッグ(アメリカアカガエル)", "名詞", "In winter, up to about 70 percent of a wood frog's body water can turn to ice, and its heart stops beating entirely.", "両生類", "600"),
    ("African clawed frog", "アフリカツメガエル", "名詞", "The African clawed frog spends its entire life in water and uses the sharp claws on its hind feet to tear apart food.", "両生類", "600"),
    ("Japanese giant salamander", "オオサンショウウオ", "名詞", "The Japanese giant salamander has been protected as a special natural monument in Japan since 1952.", "両生類", "500"),
    ("fire-bellied toad", "チョウセンスズガエル", "名詞", "If threatened, the fire-bellied toad arches its back to flash the bright red-and-black warning colors on its belly.", "両生類", "550"),
    ("spring peeper", "スプリングピーパー", "名詞", "In much of eastern North America, the high-pitched calls of spring peepers are one of the first signs that winter is over.", "両生類", "550"),
    ("olm", "ホライモリ(オルム)", "名詞", "The olm has lost its eyes and its skin's pigment after millions of years of living in complete darkness.", "両生類", "700"),
    ("common frog", "ヨーロッパアカガエル", "名詞", "The common frog is one of the most familiar amphibians in Britain, often turning up in garden ponds every spring.", "両生類", "450"),
    ("spadefoot toad", "スキアシガエル", "名詞", "The spadefoot toad uses the hard, spade-shaped growth on each hind foot to dig backward into loose desert soil.", "両生類", "650"),
    ("natterjack toad", "ナタージャックヒキガエル", "名詞", "A thin yellow stripe running down its back makes the natterjack toad easy to tell apart from other British toads.", "両生類", "700"),
    ("tadpole", "オタマジャクシ", "名詞", "A tadpole breathes through gills and swims with a long tail, quite unlike the adult frog it will become.", "両生類", "350"),
    ("polliwog", "オタマジャクシ(米口語)", "名詞", "Kids at the summer camp spent an afternoon catching polliwogs in jars down by the creek.", "両生類", "550"),
    ("metamorphosis", "幼生から成体へと、体の構造や生活様式が劇的に変化する過程。両生類では、えら呼吸で水中生活を送るオタマジャクシが、肺呼吸を行い尾のない四肢動物へと姿を変える過程を指すことが多い。変態。", "名詞", "During metamorphosis, a tadpole gradually grows legs, loses its tail, and swaps its gills for lungs.", "両生類", "600"),
    ("froglet", "変態を終えて尾がほぼ消え、陸に上がったばかりの小さな幼いカエル。子ガエル。", "名詞", "Tiny froglets, each barely the size of a fingernail, hopped out of the pond in every direction.", "両生類", "550"),
    ("metamorph", "変態を終えて間もない、幼生の特徴から成体の姿へと移行したばかりの両生類の個体。カエルに限らずサンショウウオなどにも用いられる語。", "名詞", "Newly emerged wood frog metamorphs disperse from the pond into the surrounding forest in early summer.", "両生類", "750"),
    ("eft", "イモリの幼体が水中生活の幼生期を終えたのち、陸上で数年間過ごす中間段階の呼び名。特に北米のアカハライモリ類の朱色をした陸生幼体(レッドエフト)がよく知られる。エフト。", "名詞", "After a few years living on land as a bright orange eft, the eastern newt returns to the water and turns olive green.", "両生類", "700"),
    ("frogspawn", "カエルの卵塊", "名詞", "Every March, clumps of frogspawn appear floating near the surface of the garden pond.", "両生類", "500"),
    ("webbed feet", "指の間に水かきのある足。水中で泳ぐのに適応した多くのカエルやイモリに見られる。水かき足。", "名詞", "Frogs that spend most of their time in water tend to have larger webbed feet than tree-dwelling species.", "両生類", "450"),
    ("vocal sac", "オスのカエルが鳴くときに膨らませる、喉や口の脇にある伸縮性の袋。声を大きく響かせる共鳴装置として働く。鳴嚢(めいのう)。", "名詞", "When it calls, the male frog's vocal sac inflates like a balloon and helps carry the sound much farther.", "両生類", "650"),
    ("parotoid gland", "ヒキガエルなどの目の後ろにある、刺激を受けると苦みや毒性のある分泌液を出す一対の隆起した皮膚腺。耳腺(じせん)。", "名詞", "When a dog bites a toad, the parotoid glands behind its eyes release a bitter, toxic secretion.", "両生類", "750"),
    ("moist skin", "常に湿った状態に保たれている皮膚。両生類は皮膚呼吸を行うため、乾燥を防ぎ湿った皮膚を保つ必要がある。湿った皮膚。", "名詞", "A frog's moist skin allows it to absorb oxygen directly from the water or damp air around it.", "両生類", "500"),
    ("permeable skin", "水分や気体、時には化学物質までも通しやすい、透過性の高い皮膚。両生類の皮膚呼吸を可能にする一方、乾燥や汚染物質の影響も受けやすくする。透過性の高い皮膚。", "名詞", "Because of their permeable skin, frogs are especially sensitive to pollutants in water and soil.", "両生類", "700"),
    ("tympanum", "カエルの目のすぐ後ろにある、皮膚の下に見える円形の鼓膜。種によっては目より大きく、雌雄の識別に役立つこともある。鼓膜。", "名詞", "You can identify a frog species just by looking at the size and position of its tympanum.", "両生類", "750"),
    ("nictitating membrane", "目を保護するために横方向に開閉する、半透明の第三のまぶた。カエルなどが水中に潜る際に目を保護しながらある程度の視界を保つのに役立つ。瞬膜。", "名詞", "A frog can close its nictitating membrane over each eye while swimming underwater and still see reasonably well.", "両生類", "800"),
    ("croak", "カエルが出す、しわがれた低い鳴き声。また、その声で鳴くこと。(カエルが)鳴く、鳴き声。", "動詞・名詞", "Deep in the reeds, an unseen bullfrog let out a loud croak.", "両生類", "400"),
    ("amplexus", "カエルやヒキガエルの繁殖行動で、オスがメスの背中や脇にしっかりとしがみつき、メスが産卵すると同時に体外受精させる交尾姿勢。抱接(ほうせつ)。", "名詞", "During amplexus, the male frog clings tightly to the female's back for hours or even days until she releases her eggs.", "両生類", "800"),
    ("estivation", "乾燥や高温など夏季の厳しい環境をやり過ごすため、代謝を落として休眠する状態。乾期に地中に潜って粘液の繭を作り休眠するカエルなどに見られる。夏眠(かみん)。", "名詞", "Some desert frogs survive months of drought through estivation, wrapped in a cocoon of shed skin underground.", "両生類", "800"),
    ("mating call", "配偶相手を引き寄せるために出す鳴き声。多くのカエルではオスが鳴嚢を使って独特の求愛の鳴き声を出す。求愛の鳴き声。", "名詞", "Each frog species has its own distinctive mating call, which females use to find a partner of the right species.", "両生類", "500"),
    ("amphibious", "水中と陸上の両方で生活できる、または両方で活動できる性質を持つさま。両生類的な、水陸両生の。", "形容詞", "Frogs are amphibious animals, spending their early life in water and much of their adult life on land.", "両生類", "500"),
    ("chytrid fungus", "両生類の皮膚に寄生し、世界各地でカエルなど多くの両生類種の激減や絶滅の原因となってきた病原性の菌類。ツボカビ(壺黴)。", "名詞", "Since it was first identified in the late 1990s, chytrid fungus has been linked to population declines in hundreds of amphibian species around the world.", "両生類", "750"),
    ("warning coloration", "ヤドクガエルなど毒を持つ動物が、自分が危険であることを捕食者に知らせるために持つ鮮やかで目立つ体色。警告色。", "名詞", "The bright red and yellow patterns of a poison dart frog are a classic example of warning coloration.", "両生類", "600"),
    ("terrestrial", "水中ではなく陸上で生活する性質のさま。多くのカエルは幼生期を水中で過ごした後、変態して陸上生活を送るようになる。陸生の。", "形容詞", "Once metamorphosis is complete, most young frogs become fully terrestrial and rarely return to the water except to breed.", "両生類", "600"),
    ("aquatic", "水中で生活する性質のさま。オタマジャクシやアホロートルのように、一生の全て、または一部を水中で過ごす両生類は多い。水生の。", "形容詞", "The tadpole is entirely aquatic, but as an adult it will spend most of its time on land.", "両生類", "500"),
    ("semi-aquatic", "生活の一部を水中で、残りを陸上で送る性質のさま。イモリの多くは繁殖期に水中に戻り、それ以外の時期は陸上で過ごす半水生の生活を送る。半水生の。", "形容詞", "Most newts are semi-aquatic, living on land for much of the year but returning to ponds each spring to breed.", "両生類", "650"),
    ("reintroduction", "飼育下で繁殖させた個体を、かつて生息していた野生の生息地に再び放して個体群の回復を図る保全活動。絶滅危惧種のカエルなどで行われる。(野生への)再導入。", "名詞", "Conservationists hope a captive-breeding and reintroduction program can save the frog species from extinction in the wild.", "両生類", "700"),
    ("crayfish", "ザリガニ", "名詞", "The children spent the afternoon catching crayfish in the shallow stream.", "甲殻類", "400"),
    ("hermit crab", "ヤドカリ", "名詞", "A hermit crab moves into a new, bigger shell as its body grows.", "甲殻類", "400"),
    ("prawn", "エビ（中型・大型のもの。特にイギリス英語でよく使われる呼び方）", "名詞", "The menu offered grilled prawns with garlic and lemon.", "甲殻類", "450"),
    ("king crab", "タラバガニ", "名詞", "King crab legs are often served steamed with melted butter.", "甲殻類", "450"),
    ("blue crab", "ブルークラブ（北米大西洋岸などでとれる食用のカニ）", "名詞", "Blue crabs are the star ingredient in Maryland's famous crab cakes.", "甲殻類", "550"),
    ("snow crab", "ズワイガニ", "名詞", "Snow crab is prized for its sweet, delicate meat.", "甲殻類", "500"),
    ("mantis shrimp", "シャコ", "名詞", "A mantis shrimp can strike its prey with astonishing speed and force.", "甲殻類", "550"),
    ("krill", "オキアミ", "名詞", "Krill form massive swarms that can be seen from satellites.", "甲殻類", "500"),
    ("copepod", "海洋や淡水に広く生息する、体長数ミリ程度の小型甲殻類の一群。動物プランクトンの中心的な存在で、多くの魚介類の重要な餌となる。カイアシ類。", "名詞", "Copepods are considered one of the most abundant groups of animals in the ocean.", "甲殻類", "700"),
    ("water flea", "ミジンコ（水中を跳ねるように泳ぐ、体長数ミリの小型甲殻類）", "名詞", "Water fleas are often kept as live food for aquarium fish.", "甲殻類", "600"),
    ("woodlouse", "ワラジムシ（昆虫ではなく甲殻類に分類される陸生の生物）", "名詞", "You can often find a woodlouse hiding under damp logs or stones.", "甲殻類", "550"),
    ("pill bug", "オカダンゴムシ（刺激を受けると体を丸めるワラジムシの仲間）", "名詞", "When you touch a pill bug, it curls up into a tight little ball.", "甲殻類", "600"),
    ("coconut crab", "ヤシガニ", "名詞", "The coconut crab is the largest land-living arthropod in the world.", "甲殻類", "600"),
    ("spider crab", "クモガニ", "名詞", "The Japanese spider crab has the largest leg span of any arthropod.", "甲殻類", "600"),
    ("fiddler crab", "シオマネキ", "名詞", "The male fiddler crab has one enormous claw that it waves to attract females.", "甲殻類", "600"),
    ("ghost crab", "スナガニ", "名詞", "Ghost crabs dart across the beach so fast that they seem to vanish into the sand.", "甲殻類", "650"),
    ("spiny lobster", "イセエビ", "名詞", "Unlike true lobsters, spiny lobsters have long spiny antennae instead of large claws.", "甲殻類", "500"),
    ("langoustine", "ラングスティーヌ（ヨーロッパアカザエビ。ノルウェーロブスターとも呼ばれる）", "名詞", "Langoustine is often served simply grilled with a squeeze of lemon.", "甲殻類", "700"),
    ("crawdad", "ザリガニを指す、主に米国南部などで使われるくだけた言い方（標準的な語はcrayfish）", "名詞", "Down south, folks call crayfish \"crawdads\" and boil them by the bucketful.", "甲殻類", "650"),
    ("giant isopod", "ダイオウグソクムシ", "名詞", "The giant isopod is a deep-sea relative of the common woodlouse.", "甲殻類", "650"),
    ("brine shrimp", "ブラインシュリンプ（塩湖などの塩分濃度の高い水に生息する小型の甲殻類。観賞魚の生き餌として利用される）", "名詞", "Brine shrimp eggs can survive being completely dried out for years.", "甲殻類", "600"),
    ("pistol shrimp", "テッポウエビ", "名詞", "A pistol shrimp can snap its oversized claw fast enough to stun nearby prey.", "甲殻類", "650"),
    ("cleaner shrimp", "魚などの体表につく寄生虫や死んだ皮膚を取り除いて食べる、共生関係にあるエビの総称。掃除エビ。", "名詞", "Cleaner shrimp set up cleaning stations where fish line up to be groomed.", "甲殻類", "650"),
    ("dungeness crab", "ダンジネスクラブ（北米太平洋岸でとれる食用のカニ）", "名詞", "Dungeness crab season is a big event along the West Coast of the United States.", "甲殻類", "600"),
    ("stone crab", "ストーンクラブ（米国フロリダ沿岸などでとれる食用のカニ。はさみだけを外して海に戻す漁法で知られる）", "名詞", "Only the claws of the stone crab are harvested, and the rest of the crab is returned to the sea.", "甲殻類", "650"),
    ("mud crab", "マッドクラブ（東南アジアやオーストラリアの汽水域・マングローブ林に生息する大型の食用ガニ）", "名詞", "Mud crabs burrow into the soft mud of mangrove forests.", "甲殻類", "600"),
    ("tiger prawn", "ブラックタイガー（縞模様のある大型のエビ）", "名詞", "Tiger prawns get their name from the dark stripes on their shells.", "甲殻類", "500"),
    ("carapace", "甲羅（カニ・エビ・ロブスターなど甲殻類の頭部と胴体を覆う硬い殻）", "名詞", "A crab's carapace protects its internal organs from predators.", "甲殻類", "600"),
    ("cephalothorax", "エビ・カニなどの甲殻類やクモなどにみられる、頭部と胸部が一体化した体の部分。頭胸部。", "名詞", "In crabs, the head and thorax are fused into a single cephalothorax covered by the carapace.", "甲殻類", "750"),
    ("antennae", "昆虫や甲殻類などの頭部にある、触覚・嗅覚などを司る一対以上の突起状の感覚器官（antennaの複数形）。触角。", "名詞", "A lobster uses its long antennae to feel its way through dark water.", "甲殻類", "550"),
    ("compound eye", "多数の個眼と呼ばれる小さな視覚単位が集まってできた、昆虫や甲殻類などに見られる目。複眼。", "名詞", "A crab's compound eyes are made up of thousands of tiny individual lenses.", "甲殻類", "700"),
    ("eyestalk", "カニやエビなどで、目が可動性の柄の先についている構造。眼柄（がんぺい）。", "名詞", "A crab can move its eyestalks independently to look in different directions at once.", "甲殻類", "700"),
    ("swimmeret", "エビやロブスターなどの腹部にある、遊泳や(メスの場合は)卵を抱えるために使われる小さな一対の脚。遊泳脚。", "名詞", "A female lobster carries her eggs attached to the swimmerets under her tail.", "甲殻類", "800"),
    ("tail fan", "ロブスターやエビなどの腹部の末端にある、扇状に広がった尾の部分。素早く後方へ泳ぐ(テールフリップ)際に使われる。尾扇。", "名詞", "A lobster can snap its tail fan to shoot backward away from danger in an instant.", "甲殻類", "650"),
    ("rostrum", "エビやロブスターなどで、頭部の両目の間から前方に突き出た、棘のある尖った突起。額角（がっかく）。", "名詞", "The rostrum of a shrimp sticks out like a small, spiny sword between its eyes.", "甲殻類", "800"),
    ("exuvia", "昆虫や甲殻類などが脱皮の際に脱ぎ捨てる、抜け殻となった古い外皮。脱皮殻。", "名詞", "After molting, a crab leaves behind a perfectly shaped exuvia that looks like a ghost of itself.", "甲殻類", "800"),
    ("molting cycle", "甲殻類などが外骨格を定期的に脱ぎ替える、脱皮から次の脱皮までの一連の周期。脱皮周期。", "名詞", "A crab's molting cycle speeds up while it is young and slows down as it matures.", "甲殻類", "650"),
    ("autotomy", "外敵に襲われた際などに、危険を逃れるために自らの意思で体の一部(脚やはさみなど)を切り離す行動。多くは後の脱皮を経て再生される。自切。", "名詞", "A crab caught by a predator can escape through autotomy, sacrificing a claw to save its life.", "甲殻類", "750"),
    ("filter feeder", "水中を漂う微小なプランクトンや有機物を、体の一部でこし取るようにして食べる生物。ろ過摂食者。", "名詞", "Barnacles are filter feeders that use feathery legs to sweep tiny food particles from the water.", "甲殻類", "600"),
    ("decapod", "エビ・カニ・ロブスター・ヤドカリなど、5対(10本)の脚を持つ甲殻類の一群を指す分類名。十脚類、十脚目。", "名詞", "Crabs, shrimp, and lobsters are all decapods, meaning they have ten legs.", "甲殻類", "700"),
    ("scavenger", "動物の死骸や食べ残しなどをあさって食べる動物。腐肉食動物・掃除屋。", "名詞", "Crabs are opportunistic scavengers that will eat almost anything they find on the seafloor.", "甲殻類", "550"),
    ("bottom feeder", "水底付近で、沈んだ餌や有機物を探して食べる生物。底生摂食者。", "名詞", "Crabs are typical bottom feeders, scuttling along the seafloor in search of food.", "甲殻類", "550"),
    ("tide pool", "潮が引いた後、岩場のくぼみに海水が残ってできる小さな水たまり。潮だまり。", "名詞", "We spent the morning exploring tide pools full of tiny crabs and sea anemones.", "甲殻類", "500"),
    ("intertidal zone", "満潮時には海面下に沈み、干潮時には海面上に現れる、海岸の潮の満ち引きの影響を受ける区域。潮間帯。", "名詞", "Crabs and barnacles have evolved various ways to survive the harsh conditions of the intertidal zone.", "甲殻類", "650"),
    ("sessile", "フジツボのように、成体になると岩などに固着し、自力で移動しない生活様式の。固着性の。", "形容詞", "Barnacles are sessile as adults, spending their whole lives attached to a single spot.", "甲殻類", "750"),
    ("crab cake", "カニの身をパン粉や卵などと混ぜて成形し、焼いたり揚げたりした料理。特に米国メリーランド州の名物として知られる。クラブケーキ。", "名詞", "Maryland is famous for its crab cakes made with fresh blue crab meat.", "甲殻類", "500"),
    ("shrimp cocktail", "茹でたエビを、ケチャップとホースラディッシュなどを合わせた辛みのあるソースとともに冷やして供する前菜。シュリンプカクテル。", "名詞", "Shrimp cocktail is a classic starter at many seafood restaurants.", "甲殻類", "450"),
    ("scampi", "ラングスティーヌ(ヨーロッパアカザエビ)や車海老などの大きなエビを、ニンニクとバターやオリーブオイルで調理した料理、またはその食材となるエビ。スキャンピ。", "名詞", "Shrimp scampi is a simple dish of large shrimp cooked in garlic, butter, and white wine.", "甲殻類", "600"),
    ("bisque", "エビ・カニ・ロブスターなどの殻でだしを取り、なめらかに裏ごしして仕上げる、フランス料理の濃厚なクリームスープ。ビスク。", "名詞", "Lobster bisque is made by simmering the shells to extract a rich, deep flavor.", "甲殻類", "650"),
    ("soft-shell crab", "脱皮した直後、まだ新しい甲羅が十分に硬くなっていない状態のカニ。殻ごとまるごと調理して食べられる。ソフトシェルクラブ。", "名詞", "Soft-shell crab is harvested within hours of molting, before the new shell hardens.", "甲殻類", "600"),
    ("trout", "マス", "名詞", "We caught two rainbow trout in the mountain stream.", "動物(魚類)", "350"),
    ("carp", "コイ", "名詞", "Carp were introduced to rivers and lakes around the world and are now considered invasive in some regions.", "動物(魚類)", "400"),
    ("koi", "錦鯉(観賞用に色や模様が改良されたコイの一品種)", "名詞", "The garden pond was filled with colorful koi gliding slowly beneath the lily pads.", "動物(魚類)", "400"),
    ("pufferfish", "フグ", "名詞", "When threatened, a pufferfish inflates its body by rapidly swallowing water or air.", "動物(魚類)", "450"),
    ("anglerfish", "チョウチンアンコウ", "名詞", "The deep-sea anglerfish dangles a glowing lure above its mouth to attract unsuspecting prey.", "動物(魚類)", "550"),
    ("flounder", "ヒラメ・カレイの仲間(平たい体を持つ底生の魚)", "名詞", "The flounder lay almost invisible on the sandy seabed, its color matching the sand perfectly.", "動物(魚類)", "500"),
    ("mackerel", "サバ", "名詞", "Grilled mackerel seasoned with salt is a classic dish in Japanese home cooking.", "動物(魚類)", "450"),
    ("herring", "ニシン", "名詞", "Enormous schools of herring can stretch for miles across the open sea.", "動物(魚類)", "500"),
    ("cod", "タラ", "名詞", "Cod has long been one of the most heavily fished species in the North Atlantic.", "動物(魚類)", "450"),
    ("sea bass", "スズキ", "名詞", "Sea bass is a prized fish in Mediterranean cuisine, often grilled whole with herbs.", "動物(魚類)", "450"),
    ("piranha", "ピラニア", "名詞", "Movies often portray piranhas as vicious man-eaters, but most species are actually timid scavengers.", "動物(魚類)", "450"),
    ("betta", "ベタ(闘魚)", "名詞", "Male betta fish must be kept in separate tanks, since two males will fight fiercely if placed together.", "動物(魚類)", "500"),
    ("manta ray", "マンタ(オニイトマキエイ)", "名詞", "Manta rays glide gracefully through the water, filtering plankton through their huge open mouths.", "動物(魚類)", "500"),
    ("hammerhead shark", "シュモクザメ", "名詞", "The hammerhead shark's wide, flattened head allows it to scan a broad area of the seafloor for prey.", "動物(魚類)", "500"),
    ("great white shark", "ホホジロザメ", "名詞", "The great white shark is one of the ocean's top predators, capable of growing over six meters long.", "動物(魚類)", "450"),
    ("whale shark", "ジンベエザメ", "名詞", "The whale shark is the largest fish in the ocean, yet it feeds mainly on tiny plankton.", "動物(魚類)", "500"),
    ("tiger shark", "イタチザメ", "名詞", "Tiger sharks are sometimes called the garbage cans of the sea because they will eat almost anything.", "動物(魚類)", "550"),
    ("sardine", "イワシ", "名詞", "Fresh sardines grilled with just a bit of salt are a summer favorite in many coastal countries.", "動物(魚類)", "400"),
    ("snapper", "フエダイ", "名詞", "Red snapper is a popular choice on seafood menus, valued for its firm, mild flesh.", "動物(魚類)", "550"),
    ("grouper", "ハタ", "名詞", "The grouper is a large, solitary fish that ambushes prey from rocky crevices and reefs.", "動物(魚類)", "600"),
    ("tilapia", "ティラピア", "名詞", "Tilapia is one of the most widely farmed fish in the world because it grows quickly and tolerates crowded conditions.", "動物(魚類)", "500"),
    ("halibut", "オヒョウ", "名詞", "Halibut is a large flatfish valued for its firm, white flesh.", "動物(魚類)", "600"),
    ("sturgeon", "チョウザメ", "名詞", "Sturgeon roe is processed into caviar, one of the most expensive delicacies in the world.", "動物(魚類)", "650"),
    ("lungfish", "ハイギョ(肺魚)", "名詞", "The African lungfish can breathe air using a lung-like organ in addition to its gills.", "動物(魚類)", "700"),
    ("flying fish", "トビウオ", "名詞", "To escape predators, flying fish leap out of the water and glide through the air on their large, wing-like fins.", "動物(魚類)", "500"),
    ("parrotfish", "ブダイ", "名詞", "The parrotfish uses its beak-like fused teeth to scrape algae off the surface of coral.", "動物(魚類)", "600"),
    ("lionfish", "ミノカサゴ", "名詞", "The lionfish's striking red and white stripes warn predators of its venomous spines.", "動物(魚類)", "600"),
    ("moray eel", "ウツボ", "名詞", "The moray eel hides in crevices among the rocks, waiting to ambush passing fish.", "動物(魚類)", "550"),
    ("electric eel", "デンキウナギ", "名詞", "An electric eel can generate an electric shock strong enough to stun a horse.", "動物(魚類)", "550"),
    ("barracuda", "バラクーダ(オニカマス)", "名詞", "The barracuda's long, torpedo-shaped body allows it to reach impressive bursts of speed when chasing prey.", "動物(魚類)", "550"),
    ("marlin", "カジキ(マカジキ類)", "名詞", "The old fisherman battled a giant marlin for three days in Hemingway's novel The Old Man and the Sea.", "動物(魚類)", "500"),
    ("mahi-mahi", "シイラ", "名詞", "Mahi-mahi is a popular fish on restaurant menus, known for its firm texture and mild flavor.", "動物(魚類)", "600"),
    ("sunfish", "マンボウ", "名詞", "The ocean sunfish has a strange, almost flat body that looks like it is missing a tail.", "動物(魚類)", "650"),
    ("sawfish", "ノコギリエイ", "名詞", "The sawfish uses its long, tooth-lined snout to slash through schools of fish.", "動物(魚類)", "700"),
    ("stonefish", "オニダルマオコゼ", "名詞", "The stonefish is so well camouflaged among rocks and coral that it is almost impossible to spot.", "動物(魚類)", "750"),
    ("dorsal fin", "魚類の背中にあり、体が横に傾いたり回転したりするのを防いで姿勢を安定させる働きをするひれ。背びれ。", "名詞", "A shark's dorsal fin cutting through the surface of the water is one of the most iconic images in nature.", "動物(魚類)", "500"),
    ("tail fin", "魚の体の後端にあり、左右に振ることで前へ進む推進力を生み出す主要なひれ。尾びれ(尾鰭)。", "名詞", "A powerful sweep of the tail fin propels the tuna forward at remarkable speed.", "動物(魚類)", "500"),
    ("pectoral fin", "魚のえらのすぐ後ろ、体の両側に対になって生えているひれで、方向転換や停止、バランスの調整に使われる。胸びれ。", "名詞", "Fish use their pectoral fins like paddles to steer, brake, and hover in place.", "動物(魚類)", "550"),
    ("lateral line", "魚の体の側面を頭から尾にかけて走る、水の流れや振動、圧力の変化を感知する感覚器官の列。側線。", "名詞", "The lateral line allows a fish to sense the movement of nearby predators or prey even in murky or dark water.", "動物(魚類)", "700"),
    ("swim bladder", "魚の体内にある気体で満たされた袋状の器官で、内部の気体の量を調節することによって水中での浮き沈み(浮力)を制御する働きをする。浮き袋(鰾)。", "名詞", "By adjusting the amount of gas in its swim bladder, a fish can stay at a certain depth without constantly swimming.", "動物(魚類)", "650"),
    ("barbel", "ナマズなど一部の魚の口の周りに生えているひげ状の感覚器官で、味覚や嗅覚に優れ、濁った水の中で餌を探すのに役立つ。口ひげ(バーベル)。", "名詞", "A catfish uses its long barbels to feel and taste for food along the muddy riverbed.", "動物(魚類)", "700"),
    ("fish scale", "魚の皮膚の表面を覆っている硬い板状の組織で、体を保護する役割を持つ。うろこ(魚鱗)。", "名詞", "Fish scales are covered with a thin layer of slippery mucus that reduces friction as the fish swims.", "動物(魚類)", "400"),
    ("spawn", "魚などが水中に卵と精子を放出して繁殖行動を行う。(魚などが)産卵する。", "動詞", "Salmon swim upstream against strong currents to spawn in the same river where they were born.", "動物(魚類)", "500"),
    ("anadromous", "サケのように、通常は海で成長し、成熟すると産卵のために生まれた川へ遡って戻る習性を持つこと。遡河性の。", "形容詞", "Salmon are anadromous fish that spend most of their adult lives at sea before returning to freshwater to spawn.", "動物(魚類)", "800"),
    ("shoal", "群れをなして泳ぐ魚の集団を指す語。統率のとれた泳ぎ方をする集団を指すschoolと異なり、緩やかに集まっているだけの群れも含む、より広い意味で使われることが多い。(魚の)群れ。", "名詞", "A shoal of small silver fish darted away as the diver approached.", "動物(魚類)", "600"),
    ("bioluminescent", "生物が体内での化学反応によって自ら光を作り出す性質を持つこと。深海に生息する魚などに多く見られる。生物発光する。", "形容詞", "Many deep-sea fish are bioluminescent, using their own light to lure prey or find mates in total darkness.", "動物(魚類)", "700"),
    ("freshwater fish", "川や湖、池など塩分の少ない水域に生息する魚。淡水魚。", "名詞", "Carp and trout are common examples of freshwater fish found in rivers and lakes.", "動物(魚類)", "350"),
    ("saltwater fish", "海など塩分濃度の高い水域に生息する魚。海水魚(海産魚)。", "名詞", "Tuna and mackerel are saltwater fish that spend their entire lives in the ocean.", "動物(魚類)", "350"),
    ("coral reef fish", "サンゴ礁の周辺に生息し、その複雑な地形や生態系に依存して暮らす魚類の総称。サンゴ礁魚。", "名詞", "Coral reef fish tend to be extremely colorful, which may help them blend in among the reef or signal to other fish.", "動物(魚類)", "450"),
    ("roe", "食用にされる魚の卵、またはその卵の塊。イクラ(サケの卵)やタラコ(タラの卵)などに加工される。魚卵。", "名詞", "Salmon roe is a common topping for sushi in Japan, known as ikura.", "動物(魚類)", "600"),
    ("nautilus", "オウムガイ", "名詞", "The nautilus uses gas-filled chambers in its spiral shell to control its buoyancy in the water.", "軟体動物", "500"),
    ("cuttlefish", "コウイカ", "名詞", "A cuttlefish can change the color and texture of its skin in an instant to blend into its surroundings.", "軟体動物", "450"),
    ("slug", "ナメクジ", "名詞", "Slugs are essentially snails without a shell, or with only a small internal remnant of one.", "軟体動物", "400"),
    ("scallop", "ホタテガイ", "名詞", "Scallops are unusual among bivalves because they can swim by rapidly clapping their two shells together.", "軟体動物", "400"),
    ("abalone", "アワビ", "名詞", "Abalone is prized in many cuisines for its firm, slightly chewy texture and mild, briny flavor.", "軟体動物", "550"),
    ("nudibranch", "むき出しの鰓(えら)を持つ、色鮮やかなウミウシの一群。裸鰓類(らさいるい)。", "名詞", "Nudibranchs get their vivid colors and patterns from the food they eat, including sponges and other invertebrates.", "軟体動物", "700"),
    ("sea slug", "殻を持たない、または殻が退化した海生の巻貝の総称。ウミウシなど。", "名詞", "Not all sea slugs are as colorful as nudibranchs; some species are drab and easy to overlook.", "軟体動物", "550"),
    ("land snail", "陸生のカタツムリ", "名詞", "Land snails are most active on damp, cool evenings after rain.", "軟体動物", "450"),
    ("sea snail", "海に生息する巻貝", "名詞", "Sea snails come in an enormous range of shapes and sizes, from tiny periwinkles to large conchs.", "軟体動物", "450"),
    ("periwinkle", "タマキビ(食用にもなる小型の巻貝)", "名詞", "Periwinkles cling tightly to rocks along the shoreline to avoid being washed away by waves.", "軟体動物", "650"),
    ("limpet", "カサガイ(岩に張り付いて暮らす巻貝)", "名詞", "A limpet clamps its shell down onto a rock so tightly that it is almost impossible to pull off by hand.", "軟体動物", "600"),
    ("whelk", "エゾバイ(食用になる大型の巻貝)", "名詞", "Whelks are often boiled and served with vinegar as a seaside snack in the United Kingdom.", "軟体動物", "650"),
    ("chiton", "8枚の殻板が連なって背中を覆う、岩に張り付いて暮らす原始的な軟体動物。ヒザラガイ。", "名詞", "A chiton can curl up into a ball, like a pillbug, if it is knocked loose from its rock.", "軟体動物", "750"),
    ("giant clam", "オオシャコガイ(サンゴ礁にすむ大型の二枚貝)", "名詞", "The giant clam is the largest living bivalve, with some individuals weighing over 200 kilograms.", "軟体動物", "500"),
    ("conch", "ホラガイ(大きな螺旋状の殻を持つ巻貝)", "名詞", "A conch shell can be blown like a horn, producing a deep, resonant sound.", "軟体動物", "550"),
    ("cockle", "トリガイ(すしネタにもなる小型の二枚貝)", "名詞", "Cockles are small, ridged bivalves often gathered by hand at low tide.", "軟体動物", "550"),
    ("mollusk", "貝類やタコ、イカなどを含む、多くは石灰質の殻と外套膜を持つ無脊椎動物の総称。軟体動物。", "名詞", "Mollusks make up one of the largest groups of invertebrates, including snails, clams, and octopuses.", "軟体動物", "500"),
    ("ammonite", "アンモナイト(中生代に栄えた、渦巻き状の殻を持つ絶滅頭足類)", "名詞", "Ammonites were common in the world's oceans for hundreds of millions of years before going extinct.", "軟体動物", "550"),
    ("shipworm", "二枚貝の一種だが細長いミミズのような姿をし、木材に穴を掘って暮らす。フナクイムシ。", "名詞", "Despite its name and wormlike shape, a shipworm is actually a highly modified clam.", "軟体動物", "700"),
    ("sea angel", "殻を持たず、透明な体で羽ばたくように泳ぐ小型の巻貝。クリオネ。", "名詞", "The sea angel gets its name from the two wing-like flaps it beats to swim through icy water.", "軟体動物", "700"),
    ("giant squid", "ダイオウイカ(体長10メートルを超えることもある深海性の大型イカ)", "名詞", "For centuries, the giant squid was known mainly from carcasses that washed ashore or turned up in whale stomachs.", "軟体動物", "500"),
    ("colossal squid", "ダイオウホウズキイカ(ダイオウイカより体重が重いとされる深海性の大型イカ)", "名詞", "The colossal squid is shorter than the giant squid but far heavier, thanks to its bulky, muscular body.", "軟体動物", "600"),
    ("vampire squid", "コウモリダコ(深海に生息する原始的な頭足類)", "名詞", "Despite its frightening name, the vampire squid feeds mainly on drifting bits of dead organic matter, not blood.", "軟体動物", "600"),
    ("blue-ringed octopus", "ヒョウモンダコ(猛毒を持つ小型のタコ)", "名詞", "A blue-ringed octopus flashes bright blue rings across its skin as a warning when it feels threatened.", "軟体動物", "600"),
    ("flying squid", "水面から飛び出し、ひれと腕を広げて滑空することがあるイカの総称。トビイカなど。", "名詞", "Some species of flying squid can glide more than 30 meters over the ocean's surface to escape predators.", "軟体動物", "700"),
    ("bivalve", "アサリやハマグリなど、左右一対の殻を蝶番でつなげて持つ軟体動物の総称。二枚貝。", "名詞", "Bivalves such as clams and oysters have two hinged shells that they can open and close.", "軟体動物", "600"),
    ("cephalopod", "タコやイカ、オウムガイなどを含む、頭部から足(腕)が生えている軟体動物の総称。頭足類。", "名詞", "Cephalopods are considered the most intelligent invertebrates, capable of solving puzzles and using tools.", "軟体動物", "600"),
    ("gastropod", "カタツムリや多くの巻貝など、腹部にある筋肉質の足で移動する軟体動物の総称。腹足類。", "名詞", "Gastropods make up the largest and most diverse class of mollusks, including both land and sea species.", "軟体動物", "650"),
    ("tentacle", "触手", "名詞", "A squid's body has eight arms and two much longer tentacles used mainly for catching prey.", "軟体動物", "400"),
    ("radula", "貝や巻貝などが持つ、ヤスリのような細かい歯が並ぶ帯状の摂食器官。歯舌(しぜつ)。", "名詞", "A snail uses its radula like a tiny file to scrape algae off rocks and leaves.", "軟体動物", "750"),
    ("ink sac", "イカやタコが敵から逃げる際に墨を放出するための、体内にある袋状の器官。墨袋(すみぶくろ)。", "名詞", "When threatened, an octopus squeezes its ink sac to release a dark cloud that confuses predators.", "軟体動物", "650"),
    ("siphon", "海水を吸い込んだり噴き出したりするための、軟体動物の体にある管状の器官。貝の水管や、イカ・タコの漏斗(ろうと)などがこれにあたる。", "名詞", "A clam buried in the sand extends its siphon up to the surface to draw in water for feeding and breathing.", "軟体動物", "600"),
    ("sucker", "タコやイカの腕に並ぶ、獲物や物に吸い付くための丸い器官。吸盤。", "名詞", "An octopus can have more than a thousand suckers spread across its eight arms.", "軟体動物", "500"),
    ("operculum", "巻貝が殻の入り口をふさぐために持つ、ふた状の硬い器官。蓋(ふた)。", "名詞", "When a sea snail withdraws into its shell, it seals the opening shut with its operculum.", "軟体動物", "750"),
    ("mantle cavity", "軟体動物の外套膜(がいとうまく)に囲まれた体内の空間で、えらや排出口などが収まっている。外套腔(がいとうこう)。", "名詞", "Water flows through a clam's mantle cavity, passing over its gills so it can breathe and feed at the same time.", "軟体動物", "750"),
    ("cuttlebone", "コウイカの体内にある、軽くて多孔質な石灰質の殻。浮力の調整のほか、飼い鳥用のカルシウム源としても利用される。イカの甲。", "名詞", "A cuttlefish adjusts its buoyancy by changing the amount of gas and liquid inside its porous cuttlebone.", "軟体動物", "550"),
    ("byssus", "イガイなどの二枚貝が、岩などに体を固定するために足の腺から分泌する糸状の繊維。足糸(そくし)。", "名詞", "A mussel anchors itself to a rock or piling using tough, sticky threads called byssus.", "軟体動物", "800"),
    ("proboscis", "巻貝や昆虫などが持つ、細長く伸び縮みする管状の口器官。吻(ふん)。", "名詞", "A cone snail extends a long, flexible proboscis to strike prey from a distance.", "軟体動物", "650"),
    ("chromatophore", "イカやタコの皮膚にある、拡大・収縮することで体の色を素早く変化させる色素胞。", "名詞", "An octopus can change its skin color in less than a second by expanding and contracting thousands of chromatophores.", "軟体動物", "800"),
    ("filter feeding", "カキやアサリなどが、水を吸い込んでプランクトンや有機物をこしとって食べる摂食方法。ろ過摂食。", "名詞", "Oysters practice filter feeding, pumping large volumes of water through their gills to trap tiny particles of food.", "軟体動物", "600"),
    ("bioluminescence", "生物が体内での化学反応によって自ら光を発する現象。生物発光。", "名詞", "The firefly squid is famous for its bioluminescence, lighting up the coastal waters of Toyama Bay in Japan each spring.", "軟体動物", "650"),
    ("jet propulsion", "イカやタコなどが、体内に取り込んだ海水を勢いよく噴射する反動で移動する仕組み。ジェット推進。", "名詞", "Squid rely on jet propulsion for their fastest bursts of speed, some reaching over 30 kilometers per hour.", "軟体動物", "600"),
    ("regenerate", "失われた体の一部を再び作り出すこと。タコなど一部の軟体動物は、切れた腕を再生することができる。再生する。", "動詞", "An octopus can regenerate a lost arm, complete with fully functioning suckers, within a few months.", "軟体動物", "550"),
    ("slime trail", "カタツムリやナメクジが移動する際に体から分泌する粘液が地面に残す、光沢のある筋状の跡。", "名詞", "You can often tell a snail has passed by from the shiny slime trail it leaves behind on a leaf.", "軟体動物", "500"),
    ("debeard", "調理の前に、ムール貝などが持つ足糸(ひげのような部分)を手で取り除くこと。", "動詞", "Rinse and debeard the mussels under cold running water just before cooking them.", "軟体動物", "650"),
    ("calamari", "輪切りにして揚げるなどして調理したイカ料理。カラマリ。", "名詞", "The restaurant's fried calamari was served with a squeeze of lemon and a side of marinara sauce.", "軟体動物", "450"),
    ("squid ink", "イカの墨袋から採れる、黒く粘り気のある液体。料理の色付けや風味付けにも使われる。イカ墨。", "名詞", "Squid ink gives pasta and rice dishes a striking black color and a subtly briny flavor.", "軟体動物", "500"),
    ("mother-of-pearl", "貝殻の内側にある、虹色に輝く層。装飾品や螺鈿細工などに使われる。真珠層。", "名詞", "The old jewelry box was inlaid with mother-of-pearl that shimmered in shades of pink and blue.", "軟体動物", "550"),
    ("pearl", "貝の体内で作られる、丸く美しい光沢を持つ宝石。真珠。", "名詞", "A pearl forms when a mollusk coats a grain of sand or other irritant with layer after layer of nacre.", "軟体動物", "400"),
    ("anaconda", "アナコンダ", "名詞", "The green anaconda is one of the heaviest snakes in the world.", "爬虫類", "450"),
    ("boa constrictor", "ボアコンストリクター", "名詞", "A boa constrictor kills its prey by squeezing it until it can no longer breathe.", "爬虫類", "500"),
    ("monitor lizard", "オオトカゲ", "名詞", "The Komodo dragon is the largest species of monitor lizard.", "爬虫類", "500"),
    ("bearded dragon", "フトアゴヒゲトカゲ", "名詞", "When threatened, a bearded dragon puffs out the spiky skin under its chin to look larger.", "爬虫類", "500"),
    ("garter snake", "ガータースネーク", "名詞", "Garter snakes are among the most common snakes found in North American gardens.", "爬虫類", "500"),
    ("king cobra", "キングコブラ", "名詞", "The king cobra is the longest venomous snake in the world.", "爬虫類", "550"),
    ("sea turtle", "ウミガメ", "名詞", "Sea turtles return to the beach where they were born to lay their eggs.", "爬虫類", "400"),
    ("snapping turtle", "カミツキガメ", "名詞", "A snapping turtle has powerful jaws and a surprisingly long reach for its size.", "爬虫類", "550"),
    ("skink", "熱帯から温帯にかけて世界中に広く分布するトカゲの一群で、体表がなめらかで光沢のある鱗に覆われ、種によっては脚が退化しているものもいる。スキンク。", "名詞", "Skinks have smooth, glossy scales that make them look almost polished.", "爬虫類", "600"),
    ("gila monster", "北米南西部の砂漠地帯に生息する、世界に数少ない毒を持つトカゲの一種。動きは遅いが、咬まれると激しい痛みを伴う毒を持つ。アメリカドクトカゲ。", "名詞", "The Gila monster is one of only two venomous lizard species in the world.", "爬虫類", "650"),
    ("tuatara", "ニュージーランドにのみ生息する爬虫類で、見た目はトカゲに似るが独自の系統に属し、「生きた化石」と呼ばれる。ムカシトカゲ。", "名詞", "The tuatara is often called a living fossil because its lineage has changed little in millions of years.", "爬虫類", "700"),
    ("black mamba", "ブラックマンバ", "名詞", "The black mamba is named for the blue-black color inside its mouth, not the color of its skin.", "爬虫類", "550"),
    ("adder", "ヨーロッパに広く分布する小型の毒ヘビ。背中のジグザグ模様が特徴で、英名はアダー。", "名詞", "The adder is the only venomous snake native to the United Kingdom.", "爬虫類", "650"),
    ("copperhead", "北米東部に生息する毒ヘビの一種(マムシ亜科)。銅色をした頭部が名前の由来。コパーヘッド。", "名詞", "The copperhead gets its name from the reddish-brown color of its head.", "爬虫類", "650"),
    ("cottonmouth", "北米南東部の水辺に生息する毒ヘビの一種(マムシ亜科)。危険を感じると口を大きく開け、白い口の中を見せて威嚇することからこの名がある。別名ウォーターモカシン。", "名詞", "When threatened, a cottonmouth often opens its mouth wide to reveal the white lining inside.", "爬虫類", "650"),
    ("milk snake", "北米・中米に生息する無毒のヘビで、猛毒のサンゴヘビに似た鮮やかな縞模様を持つ種が多い。ミルクスネーク。", "名詞", "The milk snake's bright bands of red, black, and yellow mimic the pattern of venomous coral snakes.", "爬虫類", "600"),
    ("corn snake", "北米東部原産の無毒のヘビで、飼育のしやすさから世界的にペットとして人気が高い。コーンスネーク。", "名詞", "Corn snakes are often recommended as a good first pet snake for beginners.", "爬虫類", "550"),
    ("box turtle", "北米に生息するカメの一種で、甲羅の腹側(腹甲)が蝶番のように動き、頭や脚を引っ込めると甲羅を箱のように閉じられることが名前の由来。ハコガメ。", "名詞", "A box turtle can close its shell almost completely to protect itself from predators.", "爬虫類", "550"),
    ("painted turtle", "北米に広く生息するカメの一種で、甲羅の縁や首、脚に赤や黄色の鮮やかな模様が入ることが名前の由来。ペインテッドタートル。", "名詞", "The painted turtle is named for the bright red and yellow markings along the edges of its shell.", "爬虫類", "600"),
    ("leatherback turtle", "現生するカメの中で最大の種で、硬い甲羅を持たず、革のような厚い皮膚に覆われた甲羅を持つことが名前の由来。オサガメ。", "名詞", "The leatherback is the largest of all living turtle species.", "爬虫類", "600"),
    ("terrapin", "淡水や汽水域に生息する小型から中型のカメを指す語で、特に北米東部沿岸に生息するダイヤモンドバックテラピンなどを指すことが多い。テラピン。", "名詞", "Terrapins live in brackish coastal marshes, unlike sea turtles or freshwater turtles.", "爬虫類", "650"),
    ("horned lizard", "北米西部の乾燥地帯に生息するトカゲで、体に棘状の突起を持つ。ツノトカゲ。", "名詞", "Some species of horned lizard can squirt blood from their eyes to startle predators.", "爬虫類", "600"),
    ("anole", "中南米・カリブ海地域に生息する小型トカゲの一群で、多くの種のオスが喉の下に色鮮やかな「喉袋」を持ち、求愛や縄張り争いの際に広げて見せる。アノール(トカゲ)。", "名詞", "Male anoles extend their brightly colored throat fan, called a dewlap, to attract mates or warn off rivals.", "爬虫類", "600"),
    ("caiman", "カイマン", "名詞", "Caimans are smaller relatives of alligators found throughout Central and South America.", "爬虫類", "550"),
    ("gharial", "インド亜大陸のガンジス川などに生息するワニの仲間で、細長い吻を持ち、魚を捕らえるのに適している。ガビアル。", "名詞", "The gharial's long, narrow snout is specially adapted for catching fish.", "爬虫類", "650"),
    ("sidewinder", "北米の砂漠地帯に生息するガラガラヘビの一種で、体を斜めに巻きながら進む独特の移動法(サイドワインディング)で知られる。サイドワインダー。", "名詞", "The sidewinder moves across loose desert sand by throwing its body sideways in a looping motion.", "爬虫類", "650"),
    ("kingsnake", "北米に生息する無毒のヘビで、ガラガラヘビなど他の毒ヘビを捕食することがあることからこの名がついた。キングスネーク。", "名詞", "Kingsnakes have a strong resistance to the venom of rattlesnakes and other pit vipers.", "爬虫類", "550"),
    ("venom gland", "ヘビなどの毒を持つ動物が、毒液を作り、蓄えておく器官。毒腺。", "名詞", "A venomous snake's fangs are connected to venom glands located behind its eyes.", "爬虫類", "650"),
    ("plastron", "カメの体の腹側を覆う硬い甲羅(腹甲)。", "名詞", "A box turtle's plastron has a hinge that lets it close its shell almost completely.", "爬虫類", "650"),
    ("forked tongue", "ヘビやトカゲなどに見られる、先端が2つに分かれた舌。空気中のにおいの粒子を集め、獲物や周囲の状況を感知するのに使われる。", "名詞", "A snake flicks its forked tongue in and out to pick up scent particles from the air.", "爬虫類", "550"),
    ("basking", "変温動物が体温を上げるため、日なたで体を温める行動。日光浴。", "名詞", "Turtles are often seen basking on rocks and logs to raise their body temperature.", "爬虫類", "500"),
    ("brumation", "爬虫類など変温動物が、冬季に代謝を大きく落として行う休眠状態。哺乳類の冬眠とは異なり、水を飲むために一時的に目覚めることがある。", "名詞", "During brumation, a snake's metabolism slows dramatically, and it may not eat for months.", "爬虫類", "700"),
    ("oviparous", "母体内で子を育てず、卵を産んで殖える性質の。卵生の。", "形容詞", "Most reptiles are oviparous, laying eggs that hatch outside the mother's body.", "爬虫類", "700"),
    ("incubation", "卵を孵化に適した温度に保って温めること。孵卵。", "名詞", "In many reptile species, the incubation temperature determines whether the hatchlings will be male or female.", "爬虫類", "600"),
    ("constriction", "ヘビが獲物に体を巻きつけ、締め付けて窒息させる捕食方法。", "名詞", "Pythons and boas kill their prey through constriction rather than venom.", "爬虫類", "650"),
    ("slither", "ヘビなどが体をくねらせながら地面を這うように進むこと。", "動詞", "The snake slithered silently through the tall grass.", "爬虫類", "500"),
    ("antivenom", "毒ヘビなどに咬まれた際の治療に用いる、毒の作用を打ち消す血清。抗毒素。", "名詞", "Antivenom is made by injecting small, gradually increasing doses of venom into an animal such as a horse.", "爬虫類", "650"),
    ("snakebite", "ヘビに咬まれること。また、その咬み傷。蛇咬症。", "名詞", "If you get a venomous snakebite, you should seek medical help immediately instead of trying home remedies.", "爬虫類", "550"),
    ("rattle", "ガラガラヘビが尾の先で打ち鳴らす、警告のためのがらがらという音を出す器官、またはその音。", "名詞", "A rattlesnake shakes its rattle rapidly to warn potential threats to stay away.", "爬虫類", "550"),
    ("vivarium", "爬虫類や両生類などを飼育・展示するためのガラス張りの飼育設備や施設。", "名詞", "The vivarium was designed to recreate a humid rainforest environment for the tree frogs and geckos.", "爬虫類", "650"),
    ("herpetology", "爬虫類や両生類を対象とする動物学の一分野。爬虫両生類学。", "名詞", "She studied herpetology in college and now researches snake venom for a living.", "爬虫類", "750"),
    ("herpetologist", "爬虫類や両生類を専門に研究する学者。", "名詞", "A herpetologist at the zoo explained how the vipers regulate their body temperature.", "爬虫類", "750"),
    ("ambush predator", "物陰などに隠れてじっと動かずに待ち、獲物が近づいたところを一気に襲う捕食者。待ち伏せ型の捕食者。", "名詞", "A crocodile is a classic ambush predator, lying motionless near the water's edge until prey comes close.", "爬虫類", "600"),
    ("non-venomous", "咬んでも毒液を注入しない。毒を持たない。", "形容詞", "Most snake species in the world are non-venomous.", "爬虫類", "550"),
    ("tail autotomy", "トカゲなどが外敵に襲われた際、自ら尾を切り離して敵の注意をそらし、その隙に逃げる防御行動。", "名詞", "Many lizard species use tail autotomy to escape from predators, leaving the still-wriggling tail behind as a distraction.", "爬虫類", "750"),
    ("scute", "カメの甲羅やワニなどの体表を覆う、角質または骨質でできた硬い板状の鱗。", "名詞", "A turtle's carapace is covered with large, hard scutes rather than ordinary scales.", "爬虫類", "750"),
    ("egg clutch", "鳥や爬虫類などが一度にまとめて産む卵、またはその一群。", "名詞", "A single egg clutch from a sea turtle can contain more than a hundred eggs.", "爬虫類", "650"),
    ("pit viper", "目と鼻の間にある熱を感知する器官(ピット器官)を持つマムシ亜科の毒ヘビの総称。", "名詞", "Rattlesnakes, copperheads, and cottonmouths are all types of pit vipers native to North America.", "爬虫類", "700"),
    ("heat-sensing pit", "マムシ亜科の毒ヘビなどが持つ、獲物や外敵が発する熱(赤外線)を感知するための器官。", "名詞", "The heat-sensing pit allows a pit viper to detect prey by body heat alone, even in total darkness.", "爬虫類", "750"),
    ("safari park", "自動車や専用車両に乗ったまま、放し飼いにされた野生動物のエリアを見て回れる形式の動物園・テーマパーク。サファリパーク。", "名詞", "Visitors can drive their own cars through the safari park and watch lions roam freely.", "動物園・植物園", "550"),
    ("night safari", "本来は夜行性の動物を、日没後に開園して間近で観察できるようにした動物園・サファリパークの形態。ナイトサファリ。", "名詞", "The Night Safari lets visitors observe nocturnal animals like leopards and owls that are normally asleep during the day.", "動物園・植物園", "600"),
    ("guided tour", "専門のガイドの案内・解説を受けながら見学するツアー。ガイド付きツアー。", "名詞", "We booked a guided tour of the botanical garden to learn about its rare orchid collection.", "動物園・植物園", "450"),
    ("self-guided tour", "ガイドを伴わず、案内表示やパンフレット、音声ガイドなどを頼りに自分のペースで見学すること。セルフガイドツアー。", "名詞", "The zoo's app offers a self-guided tour with audio commentary for each exhibit.", "動物園・植物園", "500"),
    ("keeper talk", "飼育員が来園者の前で特定の動物について解説したり、餌やりの様子を見せたりする催し。キーパートーク。", "名詞", "During the keeper talk, the zookeeper explained how the elephants use their trunks to communicate.", "動物園・植物園", "600"),
    ("feeding time", "動物園や水族館で、飼育動物に餌を与える決まった時間帯。フィーディングタイム。", "名詞", "A crowd always gathers around the penguin pool at feeding time.", "動物園・植物園", "450"),
    ("feeding schedule", "各動物にいつ・何を・どれくらい与えるかを定めた餌やりの計画表。フィーディングスケジュール。", "名詞", "Keepers follow a strict feeding schedule to keep each animal's diet consistent.", "動物園・植物園", "550"),
    ("animal show", "動物園や水族館で、動物の能力や習性を来園者に見せるために行われる催し・パフォーマンス。アニマルショー。", "名詞", "The sea lion show is one of the aquarium's most popular animal shows.", "動物園・植物園", "500"),
    ("birds of prey show", "タカ・ワシ・フクロウなどの猛禽類が飛ぶ様子や狩りの技術を披露する屋外イベント。バードショー、猛禽類ショー。", "名詞", "At the birds of prey show, a trained falcon swooped just above the audience's heads.", "動物園・植物園", "600"),
    ("annual pass", "一年間、動物園や水族館に何度でも入場できる年間パスポート・年間会員券。アニュアルパス、年間パス。", "名詞", "We visit the zoo so often that buying an annual pass saves us a lot of money.", "動物園・植物園", "550"),
    ("behind-the-scenes tour", "普段は公開されていない飼育施設の裏側(調理場・治療室・繁殖施設など)を特別に案内してもらえるツアー。バックヤードツアー。", "名詞", "On the behind-the-scenes tour, we got to see the kitchen where the zookeepers prepare the animals' meals.", "動物園・植物園", "650"),
    ("animal encounter", "来園者が飼育員の監督のもとで特定の動物に間近で触れたり、餌を与えたりできる体験プログラム。アニマルエンカウンター。", "名詞", "During the animal encounter, children were allowed to gently touch the giant tortoise's shell.", "動物園・植物園", "600"),
    ("volunteer program", "動物園や植物園で、無償で解説・案内・環境整備などの活動を行う一般市民を募集・育成する取り組み。ボランティアプログラム。", "名詞", "She joined the zoo's volunteer program and now helps run the keeper talks on weekends.", "動物園・植物園", "600"),
    ("plant nursery", "苗木や苗、種子から植物を育て、庭園や畑などへ植え付けられる大きさになるまで管理する施設。植物の育苗場・ナーサリー。", "名詞", "The botanical garden grows many of its flowers from seed in its own plant nursery.", "動物園・植物園", "550"),
    ("animal nursery", "母親から育児放棄された赤ちゃん動物や、人工哺育が必要な幼獣を専門のスタッフが世話をする飼育施設。動物の育児室・ナーサリー。", "名詞", "The orphaned baby elephant was cared for around the clock in the zoo's animal nursery.", "動物園・植物園", "650"),
    ("zoo veterinarian", "動物園に勤務し、多種多様な野生動物の健康管理・診察・治療を専門に行う獣医師。動物園獣医。", "名詞", "The zoo veterinarian had to design a custom anesthesia plan for the giraffe's surgery.", "動物園・植物園", "650"),
    ("quarantine period", "動物園や水族館に新しく搬入した動物を、感染症を持ち込んでいないか確認するため、既存の個体群から一定期間隔離しておく期間。検疫期間。", "名詞", "New animals must complete a 30-day quarantine period before being introduced to the main exhibit.", "動物園・植物園", "650"),
    ("breeding program", "絶滅の危機にある種などを対象に、複数の動物園や施設が連携して個体数の回復や遺伝的多様性の維持を目指す組織的な繁殖の取り組み。繁殖プログラム。", "名詞", "The California condor's breeding program brought the species back from fewer than 30 individuals.", "動物園・植物園", "600"),
    ("species reintroduction", "動物園などで飼育・繁殖させた個体を、その種がかつて生息していた自然環境へ戻す取り組み。種の再導入。", "名詞", "The species reintroduction of the black-footed ferret relied heavily on captive breeding at zoos.", "動物園・植物園", "750"),
    ("wildlife sanctuary", "野生動物、あるいは保護が必要な動物のために設けられた、狩猟や開発から守られた保護区域・保護施設。野生動物保護区。", "名詞", "The elephants were moved to a wildlife sanctuary where hunting is strictly banned.", "動物園・植物園", "650"),
    ("wildlife rehabilitation center", "怪我をしたり病気になったり、親とはぐれたりした野生動物を一時的に保護し、治療・世話をして野生に戻すことを目的とする施設。野生動物リハビリテーションセンター。", "名詞", "The injured hawk was taken to a wildlife rehabilitation center to recover before being released.", "動物園・植物園", "750"),
    ("animal husbandry", "飼育下の動物の健康・栄養・繁殖・生活環境などを総合的に管理し、世話をする実践・技術全般。動物飼育管理、畜産技術。", "名詞", "Good animal husbandry means providing not just food and shelter, but also mental stimulation.", "動物園・植物園", "700"),
    ("hand-rearing", "母親が育児を放棄した、あるいは病弱で育てられない赤ちゃん動物を、人の手で哺乳瓶などを使って人工的に育てること。人工哺育。", "名詞", "Hand-rearing a baby gorilla requires round-the-clock feeding, much like caring for a human infant.", "動物園・植物園", "750"),
    ("exhibit designer", "動物の生態や来園者の視点を踏まえ、動物園・水族館の展示スペースのレイアウトや外観を計画・設計する専門職。展示デザイナー。", "名詞", "The exhibit designer studied the gorillas' behavior for months before drawing up plans for their new habitat.", "動物園・植物園", "750"),
    ("off-exhibit", "動物が治療・出産・繁殖・馴致などの理由で、一時的に一般公開されている展示エリアから外され、非公開の場所で管理されている状態。非展示の、展示外の。", "形容詞", "The panda is off-exhibit today while she recovers from a minor injury.", "動物園・植物園", "700"),
    ("reptile house", "ヘビ・トカゲ・カメなどの爬虫類を集めて展示する、温度・湿度が管理された動物園の建物。爬虫類館。", "名詞", "The reptile house is kept much warmer than the rest of the zoo to suit the cold-blooded animals inside.", "動物園・植物園", "600"),
    ("nocturnal house", "本来は夜行性の動物を昼間の来園時間帯でも活動している様子が見られるよう、昼夜の照明を逆転させて飼育・展示する動物園の建物。夜行性動物館。", "名詞", "Inside the nocturnal house, red lighting is used because most animals can't see that wavelength well.", "動物園・植物園", "650"),
    ("insectarium", "チョウ・カブトムシ・アリなど昆虫を専門に飼育・展示する動物園・水族館の付属施設。昆虫館。", "名詞", "The insectarium features a giant ant colony visible through a glass-walled tunnel.", "動物園・植物園", "750"),
    ("walk-through exhibit", "檻や仕切りで動物と来園者を隔てず、来園者自身が動物の生活空間の中を歩いて通り抜けられる形式の展示。ウォークスルー展示。", "名詞", "In the walk-through exhibit, lemurs sometimes hop right across the path in front of visitors.", "動物園・植物園", "600"),
    ("conservatory", "熱帯植物や珍しい植物を一年を通じて育てられるよう、ガラス張りで温度・湿度を管理した大規模な温室施設。コンサーバトリー(植物園の温室)。", "名詞", "The botanical garden's conservatory houses palm trees and orchids that couldn't survive the local winters outdoors.", "動物園・植物園", "700"),
    ("exotic species", "本来その地域には自然分布していない、外国や別の地域が原産の植物・動物の種。外来種、エキゾチック種。", "名詞", "The botanical garden's greenhouse specializes in exotic species from Southeast Asian rainforests.", "動物園・植物園", "600"),
    ("herbarium", "研究・記録のために採集した植物標本を、乾燥・押し葉にして分類・保管しておくための施設やコレクション。標本館、ハーバリウム(植物標本庫)。", "名詞", "Botanists at the garden's herbarium keep pressed samples of every plant species in the collection.", "動物園・植物園", "750"),
    ("pollinator garden", "ミツバチや蝶などの花粉を運ぶ生き物を呼び寄せ、その生息・繁殖を助けるために、蜜や花粉の豊富な植物を意図的に植えた庭。ポリネーターガーデン。", "名詞", "The botanical garden planted a pollinator garden full of lavender and coneflowers to attract bees and butterflies.", "動物園・植物園", "650"),
    ("hedge maze", "高く刈り込んだ生垣を通路の壁として配置し、出口を見つけながら歩いて楽しむ庭園の仕掛け。生垣の迷路、ヘッジメイズ。", "名詞", "Children love getting lost in the botanical garden's hedge maze during the summer festival.", "動物園・植物園", "650"),
    ("interactive exhibit", "ボタンを押したりレバーを操作したり、クイズに答えたりすることで、来園者が能動的に参加しながら学べるよう工夫された展示。体験型展示、インタラクティブ展示。", "名詞", "The interactive exhibit lets kids press a button to hear the different calls a wolf makes.", "動物園・植物園", "600"),
    ("viewing platform", "動物の生息エリアや景色を見下ろせるよう、来園者のために一段高く設けられた見学用のスペース。展望デッキ、ビューイングプラットフォーム。", "名詞", "From the viewing platform, you can look straight down into the elephants' watering hole.", "動物園・植物園", "550"),
    ("observation deck", "水槽や動物の生息エリアの様子をゆっくり観察できるよう設けられた、来園者用の見学スペース・展望台。観察デッキ。", "名詞", "The aquarium's underwater observation deck lets visitors watch sea turtles glide by at eye level.", "動物園・植物園", "550"),
    ("touch pool", "ヒトデやナマコ、小型のサメなど、人に危害を加えにくい海の生き物を来園者が実際に手で触れられるようにした浅い水槽。タッチプール。", "名詞", "Kids lined up to feel the rough skin of a starfish in the touch pool.", "動物園・植物園", "550"),
    ("underwater tunnel", "水槽の底や側面をトンネル状に通り抜けられるように作られた通路。頭上や左右をサメや魚が泳ぐ様子を見られる。海中トンネル、アンダーウォータートンネル。", "名詞", "Walking through the underwater tunnel, we had sharks swimming directly over our heads.", "動物園・植物園", "600"),
    ("moat", "動物の脱走を防ぎつつ、目障りな柵や檻を使わずに済むよう、飼育エリアの周囲に設けられた水堀や深い溝。堀、モート。", "名詞", "Instead of bars, a wide moat separates the lion enclosure from the visitor path.", "動物園・植物園", "550"),
    ("camera trap", "動物が近くを通ると赤外線センサーなどで自動的に作動し、無人で写真や動画を撮影する野生動物調査用のカメラ。カメラトラップ、自動撮影カメラ。", "名詞", "A camera trap in the forest exhibit captured rare footage of the red panda at night.", "動物園・植物園", "700"),
    ("tracking collar", "野生動物や再導入された個体の位置・移動範囲を把握するために首に装着する、電波発信機やGPSを内蔵した首輪。追跡用首輪、トラッキングカラー。", "名詞", "Before being released, the wolf was fitted with a tracking collar so researchers could monitor its movements.", "動物園・植物園", "700"),
    ("wildlife rescue", "怪我をした、弱っている、迷子になった野生動物を発見・保護し、必要な治療やケアにつなげる救助活動、またはそれを行う団体・施設。野生動物救助。", "名詞", "A local wildlife rescue picked up the injured owl and brought it to the zoo's veterinary clinic.", "動物園・植物園", "600"),
    ("release into the wild", "保護・治療・飼育下繁殖されていた動物を、自然の生息環境へ戻すこと。野生への放野・野生復帰。", "動詞句", "After months of rehabilitation, the sea turtle was finally released into the wild.", "動物園・植物園", "600"),
    ("poaching", "法律で保護されている野生動物を、許可なく違法に狩猟・捕獲すること。密猟。", "名詞", "Poaching for ivory has pushed several elephant populations to the brink of extinction.", "動物園・植物園", "600"),
    ("butterfly house", "自由に飛び回るチョウを間近で観察できるよう、蜜源となる植物を植えた温室状の施設。蝶館、バタフライハウス。", "名詞", "Hundreds of butterflies fly freely around visitors inside the butterfly house.", "動物園・植物園", "600"),
    ("butterfly garden", "チョウを引き寄せ、産卵・繁殖できるよう、蜜源植物や幼虫の食草を屋外に植えて造成した庭。バタフライガーデン。", "名詞", "The butterfly garden is planted with milkweed to support monarch butterflies through their whole life cycle.", "動物園・植物園", "550"),
    ("animal welfare", "飼育下の動物が身体的・精神的に良好な状態で暮らせているかどうかという観点、およびそれを向上させるための取り組み全般。動物福祉。", "名詞", "The zoo hired a full-time animal welfare specialist to assess the well-being of every species in its care.", "動物園・植物園", "600"),
    ("studbook", "動物園で飼育される特定の種について、個体ごとの血統・年齢・繁殖歴などを記録し、近親交配を避けながら繁殖計画を立てるために用いる台帳。血統台帳、スタッドブック。", "名詞", "Before pairing two pandas, keepers check the studbook to make sure the animals aren't closely related.", "動物園・植物園", "800"),
]


def main() -> None:
    with db() as conn:
        existing = {
            r["english"].lower()
            for r in conn.execute("SELECT english FROM words").fetchall()
        }
        inserted = 0
        skipped = 0
        for english, japanese, pos, example, domain, level in WORDS:
            if english.lower() in existing:
                skipped += 1
                continue
            conn.execute(
                "INSERT INTO words (english, japanese, part_of_speech, "
                "example, domain, level) VALUES (?, ?, ?, ?, ?, ?)",
                (english, japanese, pos, example, domain, level),
            )
            existing.add(english.lower())
            inserted += 1
        print(f"inserted={inserted} skipped={skipped}")


if __name__ == "__main__":
    main()
