# ruff: noqa: E501  (data-heavy seed script: long word/phrase lines are fine)
"""知的財産ドメインを4分割で新設(2026-09-09・B27改・authored by Claude)。
知的財産（一般）/知的財産（著作権）/知的財産（特許）/知的財産（米国）の
4分野を4並列サブエージェントで下書き→統合。元は2026-09-07提起のB27
「特許用語ドメイン新設」だったが、ユーザー指示で4分野に再構成。

各エージェントが既存DB全体との重複チェック済み。統合時に班をまたいだ
重複8件を解消(fair use=一般を採用、public domain=一般を採用、
royalty-free=一般を採用、infringement=一般を採用、statutory damages=
著作権を採用、terminal disclaimer=特許を採用、patent troll=特許を採用。
いずれも先に処理したファイル側を採用し、後発の重複は不採用)。

No app / OpenAI API calls — hand-written、inserted directly into SQLite.
Duplicates skipped by english (lowercased) against the full live `words` table.

Run:  python scripts/add_ip_domains_2026_09_09.py
仕上げ: relevel.pyは実行しない(add_math_advanced.pyと同じ理由)。
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.database import db  # noqa: E402

WORDS: list[tuple[str, str, str, str, str, str]] = [
    ("trademark", "商品やサービスを他人のものと区別するために用いられる文字・図形・記号・立体的形状・色彩またはそれらの組み合わせであり、登録することで指定した商品・サービスについて独占的に使用できる権利が生じる標章。商標。", "名詞", "The company registered its logo as a trademark to stop rivals from using a similar design.", "知的財産（一般）", "650"),
    ("trade secret", "企業が事業活動に有用な技術上または営業上の情報を秘密として管理し、一般に知られていないことによって競争上の価値を持つもの。製法・顧客リスト・製造ノウハウなどが該当し、特許と異なり登録や公開を伴わずに保護される。営業秘密。", "名詞", "Coca-Cola's exact recipe is one of the most famous trade secrets in the world.", "知的財産（一般）", "700"),
    ("industrial design", "工業製品の形状・模様・色彩またはこれらの結合であって、視覚を通じて美感を起こさせるもの。製品の外観そのものを保護対象とする点で、技術的な機能を保護する特許とは異なる。意匠。", "名詞", "The shape of the smartphone was registered as an industrial design to protect its distinctive look.", "知的財産（一般）", "720"),
    ("geographical indication", "ある産品の品質・評判・その他の特性が本質的にその産地に由来する場合に、その産地名を示すために用いられる表示。シャンパンやコーヒーの「ブルーマウンテン」のように、特定の地域で生産されたものにのみ使用が認められる。地理的表示(GI)。", "名詞", "Only sparkling wine produced in the Champagne region of France can legally use the geographical indication 'Champagne'.", "知的財産（一般）", "780"),
    ("trade name", "企業や個人が事業を営む際に使用する名称。商号。商品やサービスを識別する商標とは異なり、事業主体そのものを表す名称である点が特徴。", "名詞", "The restaurant operates under the trade name 'Golden Dragon' even though its official corporate name is different.", "知的財産（一般）", "700"),
    ("intellectual property rights", "特許権・商標権・著作権・意匠権など、人間の知的創造活動の成果に対して法律によって認められる権利の総称。単に「知的財産」と言う場合は成果物そのものを指すのに対し、この語は成果物にひもづく「権利」の側面を強調する。知的財産権。", "名詞", "The startup hired a lawyer to make sure its intellectual property rights were properly registered before launch.", "知的財産（一般）", "680"),
    ("exclusive right", "特許権者や著作権者など、権利者だけがその知的財産を利用・実施・複製・販売できる権利。他者は権利者の許諾なしにこれらの行為を行うことができない、知的財産権の中核をなす性質。排他的権利、独占的権利。", "名詞", "A patent grants the inventor an exclusive right to make and sell the invention for a limited period.", "知的財産（一般）", "720"),
    ("rights holder", "特許権・著作権・商標権などの知的財産権を保有している個人または法人。ライセンス契約や侵害訴訟の場面で、権利を行使する当事者として言及される。権利者、権利保有者。", "名詞", "Before using the photo commercially, you must get permission from the rights holder.", "知的財産（一般）", "700"),
    ("IP portfolio", "ある企業や個人が保有する特許・商標・意匠・著作権などの知的財産権をまとめた集合体。事業の価値や競争力を測る指標としても扱われる。知的財産ポートフォリオ。", "名詞", "The tech company built a large IP portfolio of patents to protect its core technologies.", "知的財産（一般）", "750"),
    ("intangible asset", "特許権・商標権・著作権・のれん・ブランド価値など、物理的な実体を持たないが経済的価値を持つ資産。工場や機械などの有形資産と対比される会計・経営上の概念。無形資産。", "名詞", "For many modern companies, intangible assets like patents and brand value are worth more than their physical property.", "知的財産（一般）", "750"),
    ("licensing", "知的財産権の権利者が、対価と引き換えに他者にその権利の利用を許諾する行為・仕組み。ライセンス供与。", "名詞", "The company earns significant revenue from licensing its technology to manufacturers overseas.", "知的財産（一般）", "680"),
    ("license agreement", "知的財産権の権利者(ライセンサー)が、対価を得て相手方(ライセンシー)にその権利の利用を許諾する条件を定めた契約書。使用範囲・期間・ロイヤリティなどが定められる。ライセンス契約。", "名詞", "The two companies signed a license agreement allowing the software to be used in Japan for five years.", "知的財産（一般）", "700"),
    ("licensor", "ライセンス契約において、自らが保有する知的財産権の利用を相手方に許諾する側の当事者。ライセンサー、実施許諾者。", "名詞", "As the licensor, the film studio retains ownership of the characters even after licensing them for merchandise.", "知的財産（一般）", "750"),
    ("licensee", "ライセンス契約において、対価を支払うことで相手方の知的財産権の利用を許諾される側の当事者。ライセンシー、実施権者。", "名詞", "The licensee must follow strict quality guidelines when producing goods under the licensed brand.", "知的財産（一般）", "750"),
    ("royalty", "特許・商標・著作権などの知的財産の利用に対して、ライセンシーがライセンサーに支払う対価。売上や利用量に応じた一定割合や、一定額で定められることが多い。ロイヤリティ、実施料。", "名詞", "The author receives a royalty of ten percent on every copy of the book sold.", "知的財産（一般）", "680"),
    ("royalty-free", "一度対価を支払えば、その後は追加のロイヤリティを支払うことなく繰り返し利用できる契約形態やライセンスの種類を表す語。フリー素材の写真や音楽のライセンスなどでよく使われる。ロイヤリティフリー。", "形容詞", "The website sells royalty-free stock photos that businesses can use in ads without paying extra fees per use.", "知的財産（一般）", "700"),
    ("assignment of rights", "特許権・著作権・商標権などの知的財産権を、対価と引き換えに、あるいは無償で、他者に完全に譲り渡すこと。利用を許諾するだけのライセンスと異なり、権利そのものの所有者が変わる点が特徴。権利の譲渡。", "名詞", "The inventor signed an assignment of rights that transferred ownership of the patent to his employer.", "知的財産（一般）", "800"),
    ("franchising", "商標やブランド、事業ノウハウを持つ企業(フランチャイザー)が、加盟店(フランチャイジー)に対してその使用と経営方法の提供を許諾し、対価としてロイヤリティ等を受け取る事業形態。フランチャイズ事業、フランチャイズ展開。", "名詞", "Franchising allowed the coffee chain to expand rapidly without opening every store itself.", "知的財産（一般）", "680"),
    ("know-how", "特定の技術や業務を効果的に行うために蓄積された、実践的な知識や技能。特許のように公開・登録されるものではなく、多くの場合は営業秘密として社内に保持される。ノウハウ。", "名詞", "The company's manufacturing know-how, built up over decades, is not something a rival can easily copy.", "知的財産（一般）", "650"),
    ("infringement", "特許権・商標権・著作権などの知的財産権を、権利者の許諾を得ずに利用・実施・複製すること。権利者はこれに対して差止めや損害賠償を求めることができる。侵害。", "名詞", "The court ruled that selling the imitation bags constituted trademark infringement.", "知的財産（一般）", "700"),
    ("counterfeiting", "他者の商標やブランドを無断で模倣した偽物の商品を製造・販売する行為。単なる著作権侵害や特許侵害と異なり、消費者を欺いて本物であるかのように売る点に特徴がある。模倣品の製造・販売、偽造。", "名詞", "Counterfeiting of luxury handbags costs brand owners billions of dollars every year.", "知的財産（一般）", "700"),
    ("piracy", "音楽・映画・ソフトウェアなどの著作物を、権利者の許諾を得ずに無断で複製・配布・販売する行為。海上での略奪行為を意味する語が転用されたもの。海賊行為、著作権侵害品の製造・流通。", "名詞", "Online piracy of movies remains a major concern for the film industry.", "知的財産（一般）", "650"),
    ("cease and desist letter", "知的財産権の侵害など、相手方の特定の行為の即時停止を求めて、権利者や弁護士が送付する正式な警告書面。訴訟を起こす前段階の措置として用いられることが多い。差止警告状。", "名詞", "The law firm sent a cease and desist letter demanding that the company stop selling the counterfeit products immediately.", "知的財産（一般）", "780"),
    ("IP litigation", "特許権・商標権・著作権などの知的財産権をめぐる紛争について、裁判所で争われる訴訟手続き。侵害の有無や損害賠償額、権利の有効性などが争点となる。知的財産訴訟。", "名詞", "IP litigation between the two smartphone makers dragged on for years in multiple countries.", "知的財産（一般）", "780"),
    ("IP enforcement", "権利者が、自らの特許権・商標権・著作権などが侵害されないよう監視し、侵害が見つかった場合に警告・交渉・訴訟などの手段によって権利を実際に行使すること。知的財産権の行使、権利行使。", "名詞", "The brand invested heavily in IP enforcement to keep counterfeit products off online marketplaces.", "知的財産（一般）", "780"),
    ("parallel import", "権利者が正規に流通させた商品が、権利者の意図しない別の国・地域を経由して輸入されること。偽物ではなく正規品である点で偽造品(counterfeit)とは異なるが、権利者が各国で価格差を設けている場合などに問題となる。並行輸入(品)。", "名詞", "The retailer sold parallel imports of the perfume at a much lower price than the official distributor.", "知的財産（一般）", "800"),
    ("fair use", "著作権で保護された著作物であっても、批評・報道・教育・研究などの目的で、一定の条件のもとであれば権利者の許諾なしに利用できるとする法理。特に米国著作権法で発達した概念。フェアユース。", "名詞", "Quoting a short passage from a book in a review is often considered fair use.", "知的財産（一般）", "720"),
    ("public domain", "著作権や特許権などの保護期間が満了した、または最初から保護の対象とならない、誰でも自由に利用できる状態にある著作物・発明・情報。パブリックドメイン、公有。", "名詞", "Once a book enters the public domain, anyone can reprint or adapt it without permission.", "知的財産（一般）", "650"),
    ("IP due diligence", "企業買収や投資、ライセンス契約などの前に、対象企業が保有する特許・商標・著作権などの知的財産権の有効性、権利関係、侵害リスクなどを調査・精査する手続き。知的財産デューデリジェンス。", "名詞", "Before acquiring the startup, the investor's lawyers conducted thorough IP due diligence to check for any patent disputes.", "知的財産（一般）", "820"),
    ("IP valuation", "特許権・商標権・著作権などの知的財産が持つ経済的価値を、金銭的に見積もる作業。企業買収やライセンス交渉、担保設定などの場面で必要とされる。知的財産評価。", "名詞", "IP valuation showed that the company's patent portfolio was worth more than its physical factories.", "知的財産（一般）", "800"),
    ("brand protection", "企業が自社のブランド名・ロゴ・商品デザインなどを、模倣品や商標侵害、不正競争などから守るために行う一連の取り組み。商標登録・監視・法的措置などを含む。ブランド保護。", "名詞", "The company set up a brand protection team to monitor online marketplaces for counterfeit products.", "知的財産（一般）", "700"),
    ("domain name dispute", "インターネット上のドメイン名が、既存の商標や企業名と同一・類似しており、他者が不正な目的(高額での転売や便乗など)で登録・使用していると主張される場合に生じる紛争。ドメイン名紛争。", "名詞", "The company won the domain name dispute after proving the registrant had no legitimate interest in the name.", "知的財産（一般）", "780"),
    ("WIPO", "知的財産権の国際的な保護と協力を促進するために設立された国際連合の専門機関。特許協力条約(PCT)やマドリッド協定議定書などの国際条約を管理する。世界知的所有権機関(WIPO)。", "名詞", "WIPO helps countries coordinate their patent and trademark systems through international treaties.", "知的財産（一般）", "700"),
    ("TRIPS Agreement", "世界貿易機関(WTO)の加盟国に対し、特許・商標・著作権・地理的表示など幅広い分野で共通の最低限の知的財産権保護基準を課す国際協定。知的所有権の貿易関連の側面に関する協定(TRIPS協定)。", "名詞", "The TRIPS Agreement requires WTO member countries to provide at least twenty years of patent protection.", "知的財産（一般）", "820"),
    ("Paris Convention", "特許・商標・意匠など「産業財産権」の国際的な保護を目的として1883年に締結された、知的財産分野で最も古い国際条約の一つ。内国民待遇や優先権制度などの基本原則を定める。パリ条約。", "名詞", "Thanks to the priority right under the Paris Convention, an inventor can file the same patent application in other member countries within twelve months.", "知的財産（一般）", "800"),
    ("Madrid Protocol", "一度の国際出願手続きによって、複数の国で商標の登録を求めることを可能にする国際条約。WIPOが運営する国際登録制度(マドリッド制度)の根拠となっている。マドリッド協定議定書。", "名詞", "Using the Madrid Protocol, the company registered its trademark in over 50 countries through a single application.", "知的財産（一般）", "830"),
    ("unfair competition", "他社の商品・営業と混同を生じさせる行為、他社の商標や商号を模倣する行為、営業秘密の不正取得など、公正とは言えない方法で競争上の利益を得ようとする行為全般を規制する法分野。個々の登録された知的財産権の侵害とは異なる枠組みで保護を与える。不正競争。", "名詞", "Copying a competitor's unregistered packaging design closely enough to confuse customers can amount to unfair competition.", "知的財産（一般）", "780"),
    ("IP audit", "企業が保有する特許・商標・著作権・営業秘密などの知的財産を洗い出し、その権利関係や管理状況、活用状況を定期的に点検・評価する社内的な手続き。知的財産監査。", "名詞", "The annual IP audit revealed that several trademarks had not been renewed on time.", "知的財産（一般）", "780"),
    ("well-known mark", "特定の国で正式に登録されていなくても、需要者の間で広く認識されているために、パリ条約などに基づき他者による無断使用や類似商標の登録から特別に保護される商標。周知商標、著名商標。", "名詞", "Even though the company had not registered its logo in that country, courts protected it as a well-known mark.", "知的財産（一般）", "800"),
    ("copyright holder", "著作物について著作権(複製権・翻案権など財産的な権利の束)を有し、その利用を許諾または禁止する権利を行使できる者。著作者本人とは限らず、著作権の譲渡・相続・職務著作の規定によって出版社や企業が著作権者となる場合もある。著作権者。", "名詞", "Before reprinting the illustration, the publisher contacted the copyright holder to obtain permission.", "知的財産（著作権）", "700"),
    ("copyright notice", "著作物の複製物などに表示される、©記号・最初の発行年・著作権者名からなる表示。かつて米国など方式主義を採る国では保護の要件だったが、ベルヌ条約は無方式主義を原則とするため、1989年に同条約へ加盟した米国でも1989年3月1日以降の著作物には表示は法的な必須要件ではなくなった。著作権表示。", "名詞", "The book's copyright notice reads: '© 2024 Jane Smith. All rights reserved.'", "知的財産（著作権）", "700"),
    ("copyright registration", "著作物について、著作権局(米国のU.S. Copyright Officeなど)に対して行う公的な登録手続き。ベルヌ条約下では著作権の発生自体には不要(無方式主義)だが、米国では侵害訴訟を提起するための前提条件になっているほか、法定損害賠償や弁護士費用の請求権を得るためにも登録が必要とされる。著作権登録。", "名詞", "Copyright registration is not required to own a copyright, but it strengthens your position in a lawsuit.", "知的財産（著作権）", "720"),
    ("work made for hire", "被用者が雇用の範囲内で作成した著作物、または独立の請負人が特定の9種類の著作物カテゴリ(集合著作物への寄稿・映画の一部・翻訳・補助著作物・編集物・教科書・試験問題など)について書面契約に基づき作成した著作物のうち、法律上、実際に創作した者ではなく雇用主または委託者が「著作者」とみなされるもの。米国著作権法上の職務著作。", "名詞", "Because the illustrations were created as work made for hire, the studio, not the freelance artist, owns the copyright.", "知的財産（著作権）", "780"),
    ("moral rights", "著作者が著作物に対して人格的利益として持つ権利の総称で、財産権である著作権(economic rights)とは別個に保護される。著作者であることを主張する氏名表示権、著作物の同一性を保持し無断で改変されない同一性保持権、未公表著作物を公表するかどうかを決める公表権などから成る。著作者人格権。", "名詞", "Even after selling the copyright, the artist retained moral rights and objected to the mural being painted over.", "知的財産（著作権）", "750"),
    ("derivative work", "既存の著作物(原著作物)を翻訳・編曲・映画化・翻案するなどして作成された、新たな創作性を含む著作物。原著作物の著作権者の許諾なく作成・利用すると翻案権侵害となりうるが、作成された二次的著作物自体にも独自の著作権が発生する。二次的著作物。", "名詞", "The movie adaptation of the novel is a derivative work that required a license from the author.", "知的財産（著作権）", "730"),
    ("adaptation right", "著作物を翻訳・編曲・変形・脚色・映画化するなどして二次的著作物を作成する権利。著作権者が専有する権利の一つであり、無許諾でこれを行うと侵害となる。日本の著作権法では翻案権(第27条)と呼ばれる。翻案権。", "名詞", "The publisher secured the adaptation right so it could turn the graphic novel into an animated series.", "知的財産（著作権）", "760"),
    ("public performance right", "著作物を公衆に対して上演・演奏・上映するなど、公の場で伝達することを著作権者が専有する権利。音楽の生演奏やコンサートでの再生、演劇の上演、映画館での上映などがこれにあたり、通常は著作権管理団体を通じてライセンス料が徴収される。上演権・演奏権。", "名詞", "Restaurants that play licensed background music must pay royalties covered by the public performance right.", "知的財産（著作権）", "760"),
    ("reproduction right", "著作物を印刷・録音・複写・デジタルコピーなどの方法で有形的に複製することを著作権者が専有する権利。著作権を構成する権利の中で最も基本的なものとされ、日本の著作権法では複製権(第21条)と呼ばれる。複製権。", "名詞", "Scanning the entire textbook and distributing it online violates the publisher's reproduction right.", "知的財産（著作権）", "740"),
    ("distribution right", "著作物の複製物を販売・貸与・譲渡などによって公衆に頒布することを著作権者が専有する権利。米国著作権法(17 U.S.C. §106(3))で認められる権利の一つで、この権利は最初の適法な販売によって消尽する(first-sale doctrine)という制約を受ける。頒布権・譲渡権。", "名詞", "Importing unauthorized copies for resale infringes the copyright owner's distribution right.", "知的財産（著作権）", "740"),
    ("fair dealing", "英国・カナダ・オーストラリアなど英連邦系の著作権法に見られる権利制限の枠組みで、研究・私的学習・批評・報道など、あらかじめ法律で限定的に列挙された目的の範囲内でのみ著作物の無許諾利用を認めるもの。米国のフェアユースのような包括的・柔軟な一般規定ではなく、対象となる目的が限定列挙されている点が特徴。フェアディーリング。", "名詞", "Under UK law, using a short clip for the purpose of criticism or review can be justified as fair dealing.", "知的財産（著作権）", "750"),
    ("Creative Commons", "著作権者が「一部の権利を留保する(Some Rights Reserved)」形で、一定の条件のもとで作品の利用・改変・再配布を事前に許諾するための標準化されたライセンス群、およびそれを提供する非営利団体。表示(BY)・非営利(NC)・改変禁止(ND)・継承(SA)などの要素を組み合わせた複数のライセンスがある。クリエイティブ・コモンズ。", "名詞", "The photo is licensed under Creative Commons, so you can reuse it as long as you credit the photographer.", "知的財産（著作権）", "680"),
    ("all rights reserved", "著作権者が著作物についてのあらゆる権利を留保しており、事前の個別の許諾なしにはいかなる複製・翻案・頒布等の利用も認めないことを示す著作権表示の定型句。かつては米州機構下のブエノスアイレス条約の方式主義国で保護を得るための表示として実務上使われていた。無断複製・転載禁止。", "名詞", "The back cover simply states 'Copyright 2024. All rights reserved.'", "知的財産（著作権）", "650"),
    ("Digital Millennium Copyright Act (DMCA)", "1998年に米国で制定された連邦法。インターネット上の著作権侵害への対応として、技術的保護手段(DRM等)を回避する行為の禁止、オンラインサービスプロバイダーが一定の要件を満たせば利用者の侵害行為について責任を免除される安全港(セーフハーバー)規定、および著作権者による削除通知(takedown notice)の制度などを定めた。デジタルミレニアム著作権法。", "名詞", "The video-sharing platform removed the clip after receiving a DMCA takedown notice from the record label.", "知的財産（著作権）", "700"),
    ("takedown notice", "著作権者またはその代理人が、侵害していると考えるコンテンツを削除するよう、ウェブサイトやオンラインサービスプロバイダーに対して送付する正式な通知。米国のDMCA第512条の下での手続きが代表的で、これを受け取ったプロバイダーが速やかに削除すればセーフハーバーの保護を維持できる。削除通知。", "名詞", "The photographer sent a takedown notice to the blog that had used her images without permission.", "知的財産（著作権）", "700"),
    ("counter-notice", "DMCAの削除通知によってコンテンツが削除された投稿者が、その削除は誤りであった、または自身に利用の権利があると主張して、コンテンツの復元をオンラインサービスプロバイダーに求めるために送付する反論通知。これが提出されると、プロバイダーは一定期間(米国法では10〜14営業日)経過後、再度の訴訟提起がない限りコンテンツを復元することができる。カウンター通知。", "名詞", "Believing the takedown was a mistake, the creator filed a counter-notice to get the video restored.", "知的財産（著作権）", "780"),
    ("safe harbor", "一定の要件(著作権者からの削除通知への迅速な対応、繰り返し侵害者への対処方針の整備など)を満たしたオンラインサービスプロバイダーが、利用者によるコンテンツの著作権侵害について金銭的な責任を免れることができるとする法的な仕組み。米国ではDMCA第512条に規定されている。セーフハーバー。", "名詞", "The platform's compliance with the notice-and-takedown process qualifies it for DMCA safe harbor protection.", "知的財産（著作権）", "760"),
    ("orphan work", "著作権による保護は存続しているものの、著作権者が誰であるか、または所在が不明で連絡が取れないために、利用許諾を得ることが事実上できない著作物。図書館や博物館などによるデジタルアーカイブ化を妨げる要因として問題視されており、EUは2012年の指令(Directive 2012/28/EU)で一定の要件下での利用を認める制度を導入した。孤児著作物。", "名詞", "The archive struggled to digitize thousands of orphan works because no rights holder could be identified.", "知的財産（著作権）", "800"),
    ("copyright infringement", "著作権者の許諾を得ずに、複製権・翻案権・頒布権など著作権法が著作権者に専有させている権利の対象となる行為を行うこと。損害賠償請求や差止請求、米国では法定損害賠償の対象となりうる。著作権侵害。", "名詞", "The company was sued for copyright infringement after using the song in an advertisement without a license.", "知的財産（著作権）", "700"),
    ("statutory damages", "著作権侵害訴訟において、原告が実際の損害額や侵害者の得た利益を立証する代わりに選択できる、法律であらかじめ定められた金額の損害賠償。米国著作権法では侵害1件につき750〜30,000ドル、故意による侵害の場合は裁判所の裁量で最大150,000ドルまで増額できると定められている。法定損害賠償。", "名詞", "Because actual damages were hard to prove, the plaintiff sought statutory damages instead.", "知的財産（著作権）", "800"),
    ("term of protection", "著作権法が著作物を保護する期間。多くの国ではベルヌ条約の最低基準に従い、著作者の死後一定年数(現在は日本・米国・EUなどで死後70年)まで保護し、その満了後にパブリックドメインとなると定めている。保護期間。", "名詞", "In most countries today, the term of protection for a literary work lasts for the author's life plus 70 years.", "知的財産（著作権）", "750"),
    ("copyright expiration", "著作物の保護期間が満了し、著作権による利用制限が消滅すること。これにより著作物はパブリックドメインとなり、誰でも自由に利用できるようになる。著作権の消滅・満了。", "名詞", "Copyright expiration on early Mickey Mouse cartoons has been a closely watched issue in U.S. copyright law.", "知的財産（著作権）", "720"),
    ("Berne Convention", "1886年にスイスのベルンで署名された、文学的及び美術的著作物の保護に関する国際条約。加盟国間で無方式主義(登録などの手続きなしに創作と同時に著作権が発生する原則)と内国民待遇を義務付け、現代の国際著作権保護制度の基礎となっている。米国は1989年に加盟した。ベルヌ条約。", "名詞", "Under the Berne Convention, copyright protection arises automatically upon creation, without any need for registration.", "知的財産（著作権）", "780"),
    ("first-sale doctrine", "著作権者の許諾を得て適法に販売された著作物の特定の複製物については、その後の転売・貸与・譲渡を著作権者がコントロールできなくなるという原則。1908年の米国連邦最高裁判決Bobbs-Merrill Co. v. Straus事件に由来し、頒布権を最初の適法な販売時点で消尽(exhaust)させる考え方として、米国著作権法(17 U.S.C. §109)に成文化されている。ファーストセール・ドクトリン(消尽理論)。", "名詞", "Thanks to the first-sale doctrine, you can legally resell a used book without asking the publisher for permission.", "知的財産（著作権）", "800"),
    ("transformative use", "原著作物をそのまま利用するのではなく、新たな表現・意味・メッセージ・目的を加えて別の価値を生み出すような利用の仕方。米国のフェアユース判断における4要素のうち「利用の目的及び性質」を検討する際の中心的な考慮要素とされ、変容性が高いほどフェアユースと認められやすくなる。変容的利用。", "名詞", "The court found the parody to be a transformative use because it commented on and criticized the original song.", "知的財産（著作権）", "800"),
    ("rights-managed", "画像・音楽・映像などの素材について、利用の目的・地域・期間・媒体・発行部数といった具体的な条件に応じて使用料が個別に設定され、その範囲を超えた利用には別途追加の許諾と支払いが必要となるライセンス形態。包括的に繰り返し利用できるロイヤリティフリーと対比される。ライツマネージド。", "名詞", "Because the photo was rights-managed, the magazine had to pay an additional fee to use it in a second country.", "知的財産（著作権）", "750"),
    ("digital watermark", "画像・音声・動画などのデジタルコンテンツに、著作権情報や利用者を識別するための情報を、目に見える形または人間には知覚しにくい形で埋め込む技術。不正コピーの発見や出所の追跡、著作権侵害の抑止を目的として利用される。電子透かし。", "名詞", "The stock photo agency embeds a digital watermark in preview images to discourage unauthorized use.", "知的財産（著作権）", "720"),
    ("digital rights management (DRM)", "電子書籍・音楽・映像・ソフトウェアなどのデジタルコンテンツについて、無断複製や不正なコピー・再配布を技術的に制限するための仕組みの総称。暗号化やアクセス制御、再生機器の制限などによって実現され、これを回避する行為は米国のDMCAなど多くの国の法律で禁止されている。デジタル著作権管理。", "名詞", "The e-book's digital rights management prevents it from being copied to more than one device.", "知的財産（著作権）", "700"),
    ("copyleft", "著作権(copyright)を利用しつつも、著作物を自由に利用・改変・再配布できるようにし、かつその改変物や派生物にも同じ自由な利用条件を引き継ぐことを義務付けるライセンスの考え方。GNU General Public License(GPL)などのフリーソフトウェアライセンスで採用されている。コピーレフト。", "名詞", "Because the software is released under a copyleft license, any modified version must also be shared under the same terms.", "知的財産（著作権）", "750"),
    ("CC0", "Creative Commonsが提供する、著作権者が自らの著作物についてあらゆる権利を法律上可能な最大限の範囲で放棄し、事実上パブリックドメインと同じ状態に置くための権利放棄ツール。表示(クレジット)すら求めない点で、他のCreative Commonsライセンスとは異なる。パブリックドメイン提供(CC0)。", "名詞", "The government agency released the dataset under CC0, allowing anyone to use it for any purpose without attribution.", "知的財産（著作権）", "720"),
    ("exclusive rights", "著作権者が著作物について専有的に有する一連の権利。複製権・翻案権・頒布権・上演権・展示権などから構成され、これらの権利に含まれる行為を無許諾で行う第三者を排除できる。専有権利。", "名詞", "Copyright grants the author a bundle of exclusive rights, including the right to reproduce and distribute the work.", "知的財産（著作権）", "730"),
    ("compulsory license", "著作権者の個別の許諾がなくても、法律で定められた条件(所定の料率での使用料の支払いなど)を満たせば、法律上当然に著作物の利用が認められる制度。米国著作権法第115条が定める、既発表の楽曲をカバーして録音・頒布するための強制許諾(メカニカル・ライセンス)が代表例。強制許諾。", "名詞", "Thanks to the compulsory license for cover songs, artists can record their own version of a published song by paying a set royalty.", "知的財産（著作権）", "820"),
    ("joint work", "2人以上の著作者が、それぞれの寄与を単一の全体の分割できない、あるいは相互依存的な部分として結合させる意図のもとで共同で創作した著作物。各共同著作者は原則としてその著作物全体について不可分の持分を有し、著作権の行使には他の共同著作者の同意を要する場合がある。共同著作物。", "名詞", "The song was registered as a joint work because both the composer and the lyricist contributed as co-authors.", "知的財産（著作権）", "760"),
    ("anonymous work", "著作物の複製物に著作者の氏名が全く表示されていない著作物。著作者が誰であるか特定できないため、多くの国の著作権法では保護期間の起算点を著作者の死亡時ではなく公表時に置くなど、通常の著作物とは異なる特則が適用される。無名著作物。", "名詞", "The pamphlet was published as an anonymous work, so its copyright term is calculated from the date of publication.", "知的財産（著作権）", "780"),
    ("pseudonymous work", "著作者が実名ではなく、一般に広く知られていないペンネーム(変名)を用いて公表した著作物。著作者本人が広く一般に認知されるまでは、無名著作物に準じて公表時を基準に保護期間が計算されることが多い。変名著作物。", "名詞", "The novel was originally published as a pseudonymous work under the name 'Currer Bell.'", "知的財産（著作権）", "800"),
    ("copyright troll", "自ら著作物を創作したり実質的に活用したりすることなく、他人の著作権を買い集めるなどして、インターネット上の軽微な著作権侵害を見つけては提訴すると威嚇し、和解金の獲得を主な収益源とする個人や企業を批判的に指す語。訴訟を実際に最後まで争うよりも、早期の示談を狙う点が特徴とされる。コピーライトトロール。", "名詞", "The blogger was targeted by a copyright troll demanding a quick settlement over a single reused image.", "知的財産（著作権）", "780"),
    ("collective work", "百科事典・雑誌・アンソロジーなど、それぞれが独立して著作物性を持つ複数の著作物を、素材の選択や配列に創作性を加えて一つにまとめた著作物。各構成要素の著作権とは別に、編集にあたって加えられた創作性の部分について独自の著作権が発生する。編集著作物・集合著作物。", "名詞", "A magazine issue is a collective work made up of many separately copyrighted articles and photographs.", "知的財産（著作権）", "800"),
    ("comprising", "特許クレーム(特許請求の範囲)で構成要素を列挙する際に用いる移行句(トランジションフレーズ)の一つ。列挙した要素に加えて他の要素を含むことを排除しない、開放的(オープンエンド)な限定を表す語。「~を含む」「~を備える」。", "動詞", "A mobile device comprising a housing, a display, and a rechargeable battery.", "知的財産（特許）", "650"),
    ("wherein", "特許クレームで、直前に述べた構成要素についてさらに限定・説明を加える際に用いる関係副詞。「~において」「~であって、その中で」と訳され、クレームの従属的な限定部分を導入する定型表現。", "副詞", "A battery pack comprising a housing and a cell disposed within the housing, wherein the cell is a lithium-ion cell.", "知的財産（特許）", "600"),
    ("said", "特許クレームで、先行して導入された構成要素を再度指し示す際に用いる法律文書特有の指示形容詞。「前記~」「当該~」と訳され、the とほぼ同義だが、先行詞との対応関係を明確にするために特許・契約書で慣用的に使われる。", "形容詞", "A container having a lid, wherein said lid is hingedly connected to said container.", "知的財産（特許）", "600"),
    ("whereby", "特許クレームで、先行する構成や工程がもたらす結果・作用を導入する際に用いる関係副詞。「それによって~」「その結果~」と訳され、しばしば「意図した結果」を述べるにとどまり、独立した限定要素とは認められないことがある語。", "副詞", "A locking mechanism comprising a latch and a spring biasing the latch into a locked position, whereby the door is retained in a closed position.", "知的財産（特許）", "650"),
    ("consisting of", "特許クレームで構成要素を列挙する際に用いる移行句の一つで、列挙した要素のみから成ることを表す閉鎖的(クローズド)な限定。列挙外の要素を含む対象は権利範囲から除外される。「~のみから成る」。", "動詞", "A cleaning composition consisting of water, a surfactant, and a fragrance.", "知的財産（特許）", "650"),
    ("consisting essentially of", "特許クレームの移行句のうち、列挙した要素に加え、発明の基本的・新規な特性に実質的な影響を与えない範囲の追加要素のみを許容する、開放的と閉鎖的の中間に位置する限定表現。「実質的に~のみから成る」。", "動詞", "An alloy consisting essentially of iron, chromium, and nickel, with incidental impurities.", "知的財産（特許）", "700"),
    ("means for", "特許クレームで、特定の構造を明示せず「~するための手段」として機能的に構成要素を記載する、ミーンズ・プラス・ファンクション(means-plus-function)形式のクレーム表現。米国特許法112条(f)により、明細書に記載された対応する構造及びその均等物に限定して解釈される。", "名詞", "A fastening apparatus comprising means for attaching a first panel to a second panel.", "知的財産（特許）", "700"),
    ("thereof", "特許クレーム・明細書で、直前に述べた名詞を指して「その~」「それの」という意味を表す形式的な副詞。冗長さを避けつつ先行詞との関係を明確にするために使われる法律文書特有の語。", "副詞", "The apparatus includes a housing and a cover portion thereof.", "知的財産（特許）", "600"),
    ("therein", "特許クレーム・明細書で、直前に述べた場所や構成要素を指して「その中に」「そこに」という意味を表す形式的な副詞。", "副詞", "A housing defining a chamber and a battery disposed therein.", "知的財産（特許）", "600"),
    ("plurality of", "特許クレームで「複数の~」を表す際に用いる定型表現。日常語の many や several と異なり、単に「2つ以上」であることのみを意味し、具体的な数を限定しない点が特徴。", "名詞", "A device comprising a plurality of sensors arranged around the perimeter of the housing.", "知的財産（特許）", "600"),
    ("at least one", "特許クレームで「少なくとも1つの~」を表す定型表現。単数(1個)であっても複数であっても要件を満たすことを明示し、a/an よりも数量の下限を厳密に規定する語。", "形容詞", "A filter assembly comprising at least one filter element removably mounted within a housing.", "知的財産（特許）", "550"),
    ("patent specification", "特許出願書類のうち、発明の技術内容を文章で説明する部分の総称。背景技術、発明の概要、詳細な説明、及びクレーム(特許請求の範囲)を含む。単に「明細書」と呼ぶこともあるが、米国実務ではクレームを含めた出願書類全体を指すことが多い。", "名詞", "The patent specification describes several embodiments of the invention before setting forth the claims.", "知的財産（特許）", "750"),
    ("prior art", "ある特許出願の出願日(または優先日)より前に公知となっていた技術・文献・製品などの総称。新規性(novelty)や進歩性・非自明性(non-obviousness)の判断基準となる。「先行技術」。", "名詞", "The examiner cited three references as prior art against the pending claims.", "知的財産（特許）", "750"),
    ("embodiment", "特許明細書において、クレームされた発明を具体化した個別の実施形態・実施例を指す語。特に最も推奨される実施形態を「好ましい実施形態(preferred embodiment)」と呼ぶ。", "名詞", "In one embodiment, the housing is made of aluminum, while in another embodiment, it is made of a polymer composite.", "知的財産（特許）", "700"),
    ("disclosure", "特許出願において、発明の内容を公衆に開示すること、またはその開示された内容自体を指す語。特許制度は発明の開示と引き換えに独占権を与えるという考え方(disclosure-for-exclusivity)に基づく。", "名詞", "The disclosure must be sufficiently detailed to enable others to practice the invention.", "知的財産（特許）", "700"),
    ("literal infringement", "被疑侵害品・方法が、特許クレームに記載された構成要素の全てを文言通り(そのまま)満たしている場合に成立する特許侵害の類型。均等論(doctrine of equivalents)による侵害と対比される。", "名詞", "Because the accused device contains every element recited in claim 1 exactly as written, the court found literal infringement.", "知的財産（特許）", "800"),
    ("doctrine of equivalents", "被疑侵害品・方法がクレームの文言を厳密には満たさなくても、各構成要素について実質的に同一の機能を、実質的に同一の方法で果たし、実質的に同一の結果を得ている場合に、なお特許侵害を認める米国判例法上の法理。「均等論」。", "名詞", "Even though the accused product used a slightly different material, the court applied the doctrine of equivalents because the substitution performed substantially the same function in substantially the same way.", "知的財産（特許）", "850"),
    ("claim", "特許出願・特許において、特許権によって保護される発明の範囲を文章で定義した部分。「特許請求の範囲」を構成する個々の項目。独立クレーム(independent claim)と従属クレーム(dependent claim)に分かれる。", "名詞", "Claim 1 recites a broad genus of the invention, while claims 2 through 5 add narrower limitations.", "知的財産（特許）", "700"),
    ("independent claim", "他のクレームを引用せず、それ自体で完結して発明の構成要素を記載するクレーム。特許請求の範囲の中で最も広い権利範囲を持つ基本的なクレーム。", "名詞", "Claim 1 is an independent claim reciting the essential elements of the invention without reference to any other claim.", "知的財産（特許）", "750"),
    ("dependent claim", "他の(独立または別の従属)クレームを引用し、そのクレームにさらに限定を追加する形式のクレーム。引用元のクレームの全ての構成要素を含み、権利範囲は引用元より狭くなる。", "名詞", "Claim 2, which depends from claim 1, further specifies that the housing is made of a fire-resistant material.", "知的財産（特許）", "750"),
    ("abstract of the disclosure", "特許出願書類の冒頭に付される、発明の技術内容を簡潔にまとめた要約部分。米国特許商標庁(USPTO)の規則では原則150語以内で記載することとされ、クレームの解釈には用いられない。", "名詞", "The abstract of the disclosure briefly summarizes the invention in no more than 150 words so that readers can quickly assess the technical field.", "知的財産（特許）", "750"),
    ("background of the invention", "特許明細書の冒頭部分で、発明が解決しようとする技術分野の現状や課題、従来技術の問題点を説明するセクション。「発明の背景」。", "名詞", "The background of the invention explains that existing fasteners tend to loosen under repeated vibration.", "知的財産（特許）", "700"),
    ("summary of the invention", "特許明細書の中で、詳細な説明に先立ち発明の要点・目的・利点を簡潔にまとめて紹介するセクション。「発明の概要」。", "名詞", "The summary of the invention provides a brief overview of the key aspects before the detailed description elaborates on each embodiment.", "知的財産（特許）", "700"),
    ("detailed description", "特許明細書の中核をなす部分で、図面を参照しながら発明の実施形態を具体的かつ詳細に説明するセクション。実施可能要件を満たすための最も重要な記載箇所。", "名詞", "The detailed description explains, with reference to Figures 1 through 4, how each component of the assembly interacts with the others.", "知的財産（特許）", "700"),
    ("reference numeral", "特許図面において、各構成要素を指し示すために付される番号。明細書の詳細な説明の本文中でも同じ番号が使われ、図面と文章を対応づける役割を持つ。「参照符号」「引用符号」。", "名詞", "Housing 10 includes a lid 12 and a latch 14, as shown by the reference numerals in Figure 2.", "知的財産（特許）", "750"),
    ("office action", "特許庁の審査官が出願を審査した結果を出願人に通知する公式文書。拒絶理由や許可(allowance)の通知などが含まれる。審査官からの応答文書全般を指す米国実務の用語。", "名詞", "In its first office action, the examiner rejected all pending claims as anticipated by a prior art reference.", "知的財産（特許）", "800"),
    ("patent examiner", "特許庁に所属し、特許出願の審査(新規性・進歩性・記載要件等の判断)を担当する公務員。「審査官」。", "名詞", "The patent examiner assigned to the application has expertise in mechanical engineering.", "知的財産（特許）", "750"),
    ("patent prosecution", "特許出願から特許付与(または拒絶確定)に至るまでの、特許庁との間の一連の手続き。刑事訴訟等を意味する一般的な prosecution(訴追)とは異なる、特許法特有の意味を持つ語。「特許審査手続」「出願手続」。", "名詞", "Patent prosecution can take several years, involving multiple rounds of office actions and responses before a patent is granted or the application is abandoned.", "知的財産（特許）", "800"),
    ("non-final rejection", "特許審査において、審査官が出願のクレームを拒絶する最初(または再度検討の機会がある)の通知。出願人は補正や意見書によって応答する機会が与えられ、最終拒絶(final rejection)とは異なり比較的柔軟な補正が認められる。", "名詞", "The non-final rejection cited two prior art references and rejected all ten claims as obvious.", "知的財産（特許）", "800"),
    ("final rejection", "特許審査において、通常は2回目以降に発行される、より確定的な拒絶理由通知。出願人による新たな補正の受理は審査官の裁量に委ねられ、応答手段が限定される。審判請求(appeal)や継続審査請求(RCE)などの対応が必要になることが多い。", "名詞", "After the final rejection, the applicant filed a request for continued examination along with a new set of amended claims.", "知的財産（特許）", "800"),
    ("notice of allowance", "特許審査において、審査官が出願のクレームを特許として認める(許可する)ことを出願人に通知する公式文書。所定の発行手数料を納付することで特許が発行される。", "名詞", "Upon receiving the notice of allowance, the applicant paid the issue fee and the patent was granted a few months later.", "知的財産（特許）", "800"),
    ("claim amendment", "特許審査の過程で、拒絶理由に対応するためなどにクレームの文言を追加・削除・変更すること。「クレーム補正」。補正の内容は審査経過(prosecution history)として記録され、後に均等論の適用範囲などに影響しうる。", "名詞", "The claim amendment added the limitation \"wherein the sensor is wireless\" to distinguish the invention from the cited prior art.", "知的財産（特許）", "750"),
    ("response to office action", "審査官が発行したオフィスアクション(拒絶理由通知等)に対して、出願人が期限内に提出する応答書面。クレームの補正(amendment)や拒絶理由に対する反論(remarks/arguments)を含む。", "名詞", "The response to office action argued that the cited reference failed to disclose one of the claimed elements.", "知的財産（特許）", "800"),
    ("patentability", "ある発明が特許として認められるための適格性。新規性(novelty)、進歩性・非自明性(non-obviousness)、有用性(utility)、記載要件等の全ての要件を満たしているかどうかを指す。「特許性」。", "名詞", "The examiner's search focused on assessing the patentability of the claimed combination of features.", "知的財産（特許）", "800"),
    ("novelty", "特許法上、その発明が出願前に先行技術として世に知られていなかったことを要求する特許要件。米国特許法35 U.S.C. §102に規定され、新規性が欠如していると審査官は「新規性欠如(anticipation)」を理由に拒絶する。", "名詞", "The examiner rejected the claim for lack of novelty, finding that a single prior art reference disclosed every element.", "知的財産（特許）", "750"),
    ("non-obviousness", "特許法上、その発明が当業者にとって先行技術から容易に想到できるものではないことを要求する特許要件。米国特許法35 U.S.C. §103に規定される。日本の特許法における「進歩性」に相当する概念。", "名詞", "The examiner argued that combining the two prior art references would have been obvious to a person having ordinary skill in the art, rejecting the claim for lack of non-obviousness.", "知的財産（特許）", "800"),
    ("utility requirement", "特許法上、その発明が何らかの具体的で実用的な効用(useful, specific, and credible utility)を持つことを要求する特許要件。米国特許法35 U.S.C. §101に規定される。「有用性要件」。", "名詞", "The examiner questioned whether the claimed compound satisfied the utility requirement, since the application did not identify any specific practical use.", "知的財産（特許）", "800"),
    ("patent pending", "特許出願が既に特許庁に係属中であり、まだ特許として成立していない状態を示す表示。この表示自体には法的な排他権はなく、他者の実施を差し止める効力を持たない。「特許出願中」。", "名詞", "The product packaging is marked \"patent pending,\" indicating that an application has been filed but no patent has yet issued.", "知的財産（特許）", "700"),
    ("patent application", "特許を取得するために特許庁へ提出する出願書類一式。明細書、クレーム、図面、要約書等から構成される。「特許出願」。", "名詞", "The inventor filed a patent application covering both the mechanical design and the control software of the device.", "知的財産（特許）", "700"),
    ("provisional application", "米国特許制度において、クレームや正式な審査を要さず、発明の開示を簡易かつ低コストで行うための出願形式。出願日から12か月以内に正式な出願(非仮出願)をしなければ失効する。「仮出願」。", "名詞", "The startup filed a provisional application to secure an early filing date before publicly demonstrating the product at a trade show.", "知的財産（特許）", "800"),
    ("continuation application", "先に出願された親出願(parent application)の明細書内容をそのまま引き継ぎつつ、異なるクレームで権利化を目指す出願形式。親出願で開示済みの範囲内で、新たな観点からのクレームを追求する際に用いられる。「継続出願」。", "名詞", "After the parent application issued with narrow claims, the applicant filed a continuation application seeking broader claim coverage based on the same disclosure.", "知的財産（特許）", "850"),
    ("patent term", "特許権が存続する期間。米国では原則として、非仮出願の出願日(最先の米国出願日)から20年間とされる。「特許存続期間」。", "名詞", "Because the invention was filed as a continuation, the patent term is measured from the filing date of the original parent application, not the continuation itself.", "知的財産（特許）", "800"),
    ("examiner interview", "特許審査手続の途中で、出願人(または代理人)が審査官と電話や対面、ビデオ会議等で直接協議する機会。拒絶理由への対応方針のすり合わせなどにより審査を効率化する目的で行われる。「審査官面接」。", "名詞", "The attorney requested an examiner interview to clarify the scope of the cited prior art before filing a formal response.", "知的財産（特許）", "800"),
    ("patent family", "同一の発明に基づき、優先権を主張して複数の国・地域に出願された一群の特許出願及び特許の総称。各国版の権利範囲や審査状況を比較する際の基本単位となる。", "名詞", "Before entering a new market, the company checked the patent family to see whether an equivalent patent had been granted in that jurisdiction.", "知的財産（特許）", "800"),
    ("freedom to operate", "ある製品や事業活動が、第三者の有効な特許権を侵害しないかどうかを事前に調査・分析すること。特許を取得できるかどうか(patentability)とは別の観点の調査。「実施の自由(度)」「FTO」。", "名詞", "Before launching the new product line, the company conducted a freedom to operate analysis to identify any third-party patents that might be infringed.", "知的財産（特許）", "850"),
    ("patent troll", "自ら特許発明を実施(製品化)せず、特許権の行使(侵害訴訟の提起やライセンス料の要求)のみを目的として特許を保有・行使する組織や個人を指す、批判的・軽蔑的な意味合いを持つ俗称。より中立的には非実施主体(non-practicing entity)と呼ばれる。", "名詞", "Critics accused the shell company of being a patent troll, since it manufactured nothing and instead sent infringement demand letters to hundreds of small businesses.", "知的財産（特許）", "750"),
    ("divisional application", "一つの特許出願に複数の発明が含まれているとして限定要求(restriction requirement)を受けた場合などに、選択されなかった発明を別の出願として分離・独立させたもの。「分割出願」。", "名詞", "In response to a restriction requirement, the applicant elected to pursue the mechanical claims in the parent application and filed a divisional application for the electrical claims.", "知的財産（特許）", "850"),
    ("continuation-in-part application", "先の出願(親出願)の開示内容を引き継ぎつつ、新たな技術内容(新規事項)を追加した出願形式。追加した新規事項に関するクレームの優先日は、追加部分を実際に開示した本出願の出願日となる。「一部継続出願」。", "名詞", "The inventor filed a continuation-in-part application that retained the original battery claims while adding new claims directed to a redesigned charging circuit disclosed for the first time.", "知的財産（特許）", "900"),
    ("restriction requirement", "一つの特許出願に、審査官が「独立した、あるいは明確に区別できる複数の発明」が含まれていると判断した場合に、出願人にいずれか一つの発明を選択して審査を進めるよう求める通知。「限定要求」。", "名詞", "The examiner issued a restriction requirement, finding that the mechanical apparatus claims and the method-of-manufacture claims constituted two independent inventions.", "知的財産（特許）", "850"),
    ("request for continued examination", "最終拒絶(final rejection)等を受けた出願について、新たな出願をすることなく、手数料を納付して同じ出願のまま審査を継続してもらうための請求手続き。「継続審査請求」「RCE」。", "名詞", "Rather than appeal the final rejection, the applicant filed a request for continued examination along with amended claims addressing the examiner's concerns.", "知的財産（特許）", "850"),
    ("terminal disclaimer", "自明性型二重特許(obviousness-type double patenting)の拒絶理由を解消するために、後願の特許の存続期間を先願の特許の満了日に合わせて短縮し、かつ両特許が同一の者によって所有・実施される限りにおいてのみ有効である旨を宣言する書面。「ターミナルディスクレーマー」。", "名詞", "To overcome the double patenting rejection, the applicant filed a terminal disclaimer tying the term of the later patent to the expiration date of the earlier one.", "知的財産（特許）", "900"),
    ("anticipation", "特許法上、クレームされた発明の全ての構成要素が単一の先行技術文献に開示されていることにより、新規性が否定される状態。「新規性欠如」「(先行技術による)先取り」。", "名詞", "The examiner rejected the claim on the ground of anticipation, pointing to a single patent that disclosed every limitation recited in the claim.", "知的財産（特許）", "800"),
    ("enablement requirement", "特許明細書が、当業者(person having ordinary skill in the art)が過度の試行錯誤を要さずにクレームされた発明を実施(製造・使用)できる程度に十分詳細に記載されていることを要求する記載要件。米国特許法35 U.S.C. §112(a)に規定される。「実施可能要件」。", "名詞", "The court invalidated the broad claims for failing to satisfy the enablement requirement, since the specification disclosed only a single narrow example.", "知的財産（特許）", "850"),
    ("written description requirement", "特許明細書が、クレームされた発明の全範囲について、出願時点で発明者がその発明を現に所有していたことを当業者に示せる程度に記載されていることを要求する記載要件。米国特許法35 U.S.C. §112(a)に規定され、実施可能要件とは区別される。「記載要件」。", "名詞", "The claim was found invalid for lack of written description, because the specification did not demonstrate that the inventor possessed the full genus being claimed.", "知的財産（特許）", "850"),
    ("claim construction", "訴訟や審査において、特許クレームの各文言が具体的にどのような意味・範囲を持つかを解釈すること。米国では原則として裁判官が法律問題として判断する。「クレーム解釈」。", "名詞", "The parties disputed the claim construction of the term \"substantially parallel,\" which the court ultimately resolved by reference to the specification and prosecution history.", "知的財産（特許）", "850"),
    ("prosecution history estoppel", "特許の審査過程(prosecution history)において、出願人がクレームを補正したり主張を行ったりして特定の権利範囲を放棄した場合、その放棄した範囲について後から均等論(doctrine of equivalents)を主張することを禁じる法理。「包袋禁反言」「審査経過禁反言」。", "名詞", "Because the patentee had narrowed the claim during prosecution to overcome a prior art rejection, prosecution history estoppel barred the patentee from asserting the doctrine of equivalents as to the surrendered subject matter.", "知的財産（特許）", "900"),
    ("non-practicing entity", "自らは特許発明を製品化・実施せず、主として特許権のライセンス供与や侵害訴訟による収益化を目的として特許を保有する主体。大学の技術移転機関なども含まれる、比較的中立的な呼称。「非実施主体」「NPE」。", "名詞", "The university's licensing office, though a non-practicing entity, was widely regarded as behaving differently from opportunistic patent trolls because it actively sought industry partners to commercialize the technology.", "知的財産（特許）", "800"),
    ("inventive step", "その発明が先行技術から当業者にとって自明でないことを要求する特許要件。欧州特許庁(EPO)や日本を含む多くの国・地域の特許制度で用いられる用語で、米国のnon-obviousness(非自明性)にほぼ相当する。「進歩性」。", "名詞", "The European examiner objected that the claimed combination lacked an inventive step over two combined prior art documents.", "知的財産（特許）", "800"),
    ("information disclosure statement", "米国特許出願人及びその代理人が、発明の特許性に重要と考えられる先行技術等の情報を審査官に開示するために提出する書面。出願人には米国特許商標庁に対する率直義務(duty of candor)があり、その履行の一環として提出される。「情報開示陳述書」「IDS」。", "名詞", "The applicant's attorney filed an information disclosure statement listing the foreign search reports received from the corresponding European application.", "知的財産（特許）", "850"),
    ("USPTO", "特許出願の審査・登録、商標登録、および登録後の当事者系レビュー等の行政手続を所管する、米国商務省(Department of Commerce)傘下の政府機関。日本の特許庁に相当するが、商標も同一機関が扱う点が特徴の米国特許商標庁。", "名詞", "Before an inventor can sue for infringement, the USPTO must first examine the application and grant the patent.", "知的財産（米国）", "750"),
    ("first-to-file system", "同一の発明について複数の出願人が競合した場合、実際に発明した時期の先後ではなく、特許庁への出願日の先後によって権利を付与する制度。2013年3月16日施行の米国発明法(AIA)により、それまでの先発明主義(first-to-invent)から移行して採用された先願主義。", "名詞", "Under the first-to-file system, filing a day earlier can matter more than who actually invented something first.", "知的財産（米国）", "800"),
    ("America Invents Act (AIA)", "2011年9月16日にオバマ大統領の署名により成立した米国特許制度の抜本改正法。先発明主義から先願主義への移行、当事者系レビュー(IPR)等の新たな登録後手続の創設、仮出願・先使用の抗弁の拡充などを盛り込んだ、正式名称リーヒ・スミス米国発明法。", "名詞", "The America Invents Act introduced entirely new ways to challenge a patent's validity at the USPTO instead of only in federal court.", "知的財産（米国）", "800"),
    ("inter partes review (IPR)", "第三者が既に登録された米国特許の有効性を、先行する特許・刊行物に基づく新規性・非自明性の欠如を理由として、連邦地裁ではなくUSPTO内のPTAB(特許審判部)に申し立てて争う登録後手続。AIAにより新設され2012年9月16日から利用可能になった当事者系レビュー。", "名詞", "Instead of waiting for a jury trial, the company filed an inter partes review to invalidate the patent at the PTAB.", "知的財産（米国）", "830"),
    ("Patent Trial and Appeal Board (PTAB)", "USPTO内に設置され、審査官による拒絶査定への審判(ex parte appeal)に加え、当事者系レビュー(IPR)や付与後レビュー(PGR)などの登録後手続を審理する行政審判組織。AIAにより2012年9月16日、旧・特許審判抵触部(BPAI)を改組して発足した特許審判部。", "名詞", "The patent owner appealed the examiner's rejection to the PTAB.", "知的財産（米国）", "820"),
    ("post-grant review (PGR)", "特許登録から9か月以内に限り、新規性・非自明性だけでなく記載要件や特許適格性を含むほぼ全ての無効理由を主張してPTABに提起できる登録後手続。AIAにより新設され、先願主義の下で成立した特許のみを対象とする付与後レビュー。", "名詞", "Because more than nine months had passed since the patent issued, the challenger could no longer file a post-grant review.", "知的財産（米国）", "850"),
    ("ex parte reexamination", "何人でも先行特許・刊行物を提出してUSPTOに特許の再審査を求めることができるが、申立人自身は審査官とのやり取りに継続して関与できない手続。1980年の法改正で導入され、IPR導入後も残っている単当事者系再審査。", "名詞", "The company filed a request for ex parte reexamination but had no further role once the USPTO reopened prosecution.", "知的財産（米国）", "860"),
    ("maintenance fee", "米国で発行された実用特許(utility patent)の権利を存続させるために、登録から3.5年・7.5年・11.5年の各節目で特許庁に納付しなければならない料金。納付を怠ると6か月の猶予期間の後、特許権が失効する維持年金。", "名詞", "The company forgot to pay the 7.5-year maintenance fee, and the patent lapsed before the license deal closed.", "知的財産（米国）", "800"),
    ("design patent", "物品の実用的な機能ではなく、装飾的な外観・形状・模様のみを保護対象とする米国特有の特許類型。実用特許とは異なり維持年金が不要で、登録から15年(2015年5月13日以降の出願)の存続期間を持つ意匠特許。", "名詞", "Apple famously relied on design patents, not utility patents, in much of its litigation over the iPhone's appearance.", "知的財産（米国）", "780"),
    ("plant patent", "種子ではなく接ぎ木や挿し木などの方法で無性繁殖させた、新規かつ他と区別できる植物の品種に与えられる米国特有の特許類型。塊茎植物や野生状態で発見された植物は対象外となる植物特許。", "名詞", "The breeder obtained a plant patent for a new rose variety that could only be propagated by cuttings, not by seed.", "知的財産（米国）", "820"),
    ("provisional patent application", "実体審査を受けず特許として成立することもないが、出願から12か月以内に正規の出願(non-provisional application)を行えば、その出願日を優先日として遡って主張できる、米国特有の簡易出願制度。仮出願。", "名詞", "Filing a provisional patent application let the startup claim an early priority date while it kept refining the invention.", "知的財産（米国）", "800"),
    ("trade dress", "商品や店舗の色彩・形状・配置・内装デザインなど、単語やロゴにとどまらない「見た目・イメージ全体」が出所を示す標識として機能する場合に、ランハム法の下で保護される米国商標法上の概念。トレードドレス。", "名詞", "The court found that the restaurant chain's distinctive interior decor qualified as protectable trade dress.", "知的財産（米国）", "830"),
    ("Lanham Act", "1946年に制定された、連邦レベルでの商標登録制度と、トレードドレスや虚偽広告に対する不正競争防止規定を定める米国商標法。正式名称はTrademark Act of 1946で、通称は提出議員フリッツ・G・ランハムに由来するランハム法。", "名詞", "The plaintiff sued for both trademark infringement and false advertising under the Lanham Act.", "知的財産（米国）", "810"),
    ("U.S. Copyright Office", "著作権の登録事務や著作権局長(Register of Copyrights)による政策助言・規則制定を担う、議会図書館(Library of Congress)に置かれた連邦機関。特許商標庁とは異なり商務省ではなく立法府に属する米国著作権局。", "名詞", "You are not required to register a work with the U.S. Copyright Office for copyright to exist, but registration is required before you can file an infringement lawsuit.", "知的財産（米国）", "750"),
    ("declaratory judgment action", "特許権侵害で訴えられるのを待つのではなく、実施予定の行為が非侵害または対象特許が無効であることの確認を求めて、実施者側(潜在的な被告)から先に連邦裁判所に提起する訴訟。ライセンス交渉が決裂した相手方や警告状を送りつけてくるパテント・トロールへの反撃手段として利用される確認判決訴訟。", "名詞", "Rather than wait to be sued, the company filed a declaratory judgment action asking the court to rule that its product did not infringe the patent.", "知的財産（米国）", "850"),
    ("Federal Circuit", "特許訴訟の控訴審を全米で独占的に管轄する、地理的管轄ではなく事件の種類(専門分野)によって管轄が定まる連邦控訴裁判所。1982年に関税特許控訴裁判所(CCPA)と請求裁判所控訴部を統合して新設された、正式名称米国連邦巡回区控訴裁判所。", "名詞", "Because patent appeals go only to the Federal Circuit, patent law has developed with far less regional variation than most other areas of federal law.", "知的財産（米国）", "800"),
    ("Markman hearing", "特許侵害訴訟において、争われているクレーム(請求項)の用語の意味を陪審に委ねず裁判官のみが法律問題として解釈・確定するために開かれる審理。1996年の連邦最高裁判決Markman v. Westview Instrumentsに由来するマークマン審理(クレーム解釈審理)。", "名詞", "The outcome of the Markman hearing effectively decided the case, since the judge's claim construction left little room for infringement.", "知的財産（米国）", "850"),
    ("submarine patent", "継続出願(continuation)を繰り返すなどして意図的に審査を長期化させ、対象技術が広く普及した後に初めて特許を成立(浮上)させることで、権利化前から気づかず使用していた事業者に高額なライセンス料を要求する戦術、またはそのようにして得られた特許。1995年以前、存続期間が登録日から17年だった時代に横行した潜水艦特許。", "名詞", "Jerome Lemelson became infamous for his submarine patents, which surfaced decades after the original filing and covered technology like bar-code scanners.", "知的財産（米国）", "870"),
    ("non-practicing entity (NPE)", "自らは特許発明に基づく製品の製造・販売やサービス提供を行わず、専ら特許権の行使によるライセンス収入や和解金の獲得を事業とする主体を指す中立的な用語。「パテント・トロール」の婉曲的・専門的な言い換えとして使われる非実施主体(NPE)。", "名詞", "Not every non-practicing entity is considered a troll; universities that license out research patents are also technically NPEs.", "知的財産（米国）", "800"),
    ("ITC exclusion order", "米国国際貿易委員会(ITC)が関税法337条に基づく調査の結果、特許・商標・著作権等の侵害品の輸入を認定した場合に発する、税関に対して該当製品の米国内への輸入を差し止めさせる行政命令。金銭賠償を命じる権限を持たない代わりに迅速な差止めを実現するITC排除命令。", "名詞", "Rather than suing in federal court, the company went to the ITC and obtained an exclusion order blocking the rival's products at the border.", "知的財産（米国）", "880"),
    ("Defend Trade Secrets Act (DTSA)", "州法に委ねられてきた営業秘密の保護に、初めて連邦レベルでの民事訴訟提起権を認めた2016年制定の連邦法。州境を越える事件を連邦裁判所で直接争えるようにし、一定の要件下で被告に事前通知せずに証拠を差し押さえる仮の差押命令も導入した営業秘密保護法。", "名詞", "Before the DTSA, a company had to rely entirely on state law to sue a former employee for stealing trade secrets.", "知的財産（米国）", "830"),
    ("Uniform Trade Secrets Act (UTSA)", "各州が個別に制定するための模範法として1979年に統一州法委員会(ULC)が起草し1985年に改訂された、営業秘密の定義や不正取得(misappropriation)の要件を定めるモデル法。ニューヨーク州など一部を除く大多数の州で州法として採択されている統一営業秘密法。", "名詞", "Most states base their trade secret statutes on the Uniform Trade Secrets Act, though the exact wording varies slightly from state to state.", "知的財産（米国）", "850"),
    ("Hatch-Waxman Act", "先発医薬品メーカーには規制審査で失われた期間を補うための特許存続期間の延長を認める一方、ジェネリック医薬品メーカーには簡略新薬申請(ANDA)により独自の臨床試験なしで承認取得を可能にするという、両者の利害を調整した1984年制定の医薬品特許関連法。正式名称Drug Price Competition and Patent Term Restoration Actであるハッチ・ワックスマン法。", "名詞", "Thanks to the Hatch-Waxman Act, a generic drug maker can rely on the brand-name manufacturer's safety data instead of repeating costly clinical trials.", "知的財産（米国）", "870"),
    ("Bayh-Dole Act", "連邦政府の資金提供を受けた研究から生まれた発明について、それ以前は原則として政府に帰属していた特許を、大学・非営利団体・中小企業が自ら保有し特許化・実用化できるようにした1980年制定の法律。米国の大学における技術移転(TLO)活動の法的基盤となったベイ・ドール法。", "名詞", "Before the Bayh-Dole Act, most inventions from federally funded university research ended up owned by the government and were rarely commercialized.", "知的財産（米国）", "860"),
    ("Principal Register", "USPTOが管理する商標登録簿のうち、識別力を備えた商標のみが登録され、5年間の継続使用後に「争えない(incontestable)」地位を得られるなど最も強力な法的保護が与えられる主登録簿。記述的な商標などがひとまず登録される補助登録簿(Supplemental Register)と対をなす。", "名詞", "Only marks registered on the Principal Register can later become incontestable under Section 15 of the Lanham Act.", "知的財産（米国）", "850"),
    ("incontestability", "連邦登録された商標が主登録簿への登録後、継続して5年間使用され、かつ一定の要件を満たした宣誓書(Section 15 declaration)を提出することで、記述性や優先使用のような一部の主張に基づく取消しから原則として保護される法的地位。ランハム法15条が定める(商標の)争えない地位。", "名詞", "Once a mark achieves incontestability, a challenger generally can no longer argue that it is merely descriptive.", "知的財産（米国）", "870"),
    ("Trademark Trial and Appeal Board (TTAB)", "商標登録出願の拒絶査定不服審判に加え、第三者による登録異議申立て(opposition)や既登録商標の取消請求(cancellation)を審理する、USPTO内に置かれた行政審判組織。特許分野のPTABに相当する商標審判部。", "名詞", "The rival company filed an opposition with the TTAB before the applicant's trademark could be registered.", "知的財産（米国）", "820"),
    ("Alice/Mayo test", "クレームが自然法則・自然現象・抽象的アイデアという特許を受けられない概念そのものに向けられているかを判断し、該当する場合はさらにそれを特許適格な発明に変換するだけの「発明的概念(inventive concept)」が付加されているかを検討するという、2段階の枠組みによって特許適格性(35 U.S.C. §101)を判断する連邦最高裁判例法理。2012年Mayo判決と2014年Alice判決に由来するアリス・メイオ・テスト。", "名詞", "Many software patents have been invalidated under the Alice/Mayo test for claiming nothing more than an abstract idea implemented on a generic computer.", "知的財産（米国）", "900"),
    ("American Rule", "訴訟の勝敗にかかわらず、原則として各当事者が自らの弁護士費用を負担するという米国民事訴訟の原則。特許訴訟では35 U.S.C. §285により「例外的な事案(exceptional case)」に限り敗訴当事者に相手方の弁護士費用の負担を命じることができる、米国訴訟制度上のアメリカン・ルール。", "名詞", "Under the American Rule, even a company that wins a patent lawsuit usually has to pay its own attorneys' fees.", "知的財産（米国）", "830"),
    ("patent marking", "特許権者が自社製品に特許番号(またはインターネット上の該当ページのURL)を表示することを、損害賠償請求の一部要件として位置づける米国特許法上の制度。表示を怠ると、侵害者に対して現実の通知(actual notice)がなされた後の損害しか請求できなくなる特許表示(パテントマーキング)。", "名詞", "Because the company had never bothered with patent marking, it could only recover damages for infringement that occurred after it sent a formal notice letter.", "知的財産（米国）", "870"),
    ("treble damages", "特許侵害が故意(willful)であったと認められた場合に、裁判所の裁量により、認定された損害額の最大3倍まで増額できる米国特許法上の懲罰的性格を持つ賠償制度。35 U.S.C. §284が定める増額賠償(トリブル・ダメージズ)。", "名詞", "The jury found the infringement was willful, and the judge used that finding to award treble damages.", "知的財産（米国）", "850"),
    ("assignor estoppel", "特許権を第三者に譲渡した発明者やその関係者が、譲渡後に譲渡先が保有するその特許の有効性を自ら争うことを禁じる衡平法上の法理。2021年の連邦最高裁判決Minerva Surgical v. Hologicで、譲渡時に譲渡人が実質的に主張していなかった内容にまで及ばないとの限定を付しつつ維持された譲渡人禁反言。", "名詞", "Because the inventor had assigned the patent to his former employer, assignor estoppel barred him from later arguing that the very same patent was invalid.", "知的財産（米国）", "930"),
    ("prior user rights", "他者が特許出願をする前から、当該発明を秘密裏に商業的に実施していた者に対し、後に成立したその特許の侵害訴訟において抗弁として実施の継続を認める制度。AIAにより2011年9月16日以降に成立した特許について、それまでビジネス方法特許に限られていた対象が全技術分野に拡大された先使用の抗弁(35 U.S.C. §273)。", "名詞", "The manufacturer had been using the process secretly for years before the patent was filed, so it invoked prior user rights as a defense.", "知的財産（米国）", "890"),
    ("micro entity", "USPTOへの出願・維持手数料について、通常の75%引きという大幅な減額を受けられる出願人の区分。個人の総所得が直近の世帯所得中央値の概ね3倍未満であることなど複数の要件を満たす必要がある、AIAにより2011年に新設された零細事業体。", "名詞", "As an independent inventor with modest income, she qualified for micro entity status and paid only a quarter of the standard USPTO fees.", "知的財産（米国）", "800"),
]


def main() -> None:
    with db() as conn:
        existing = {
            r["english"].lower()
            for r in conn.execute("SELECT english FROM words").fetchall()
        }
        inserted = 0
        skipped = 0
        for english, japanese, pos, example, domain, level in WORDS:
            if english.lower() in existing:
                skipped += 1
                continue
            conn.execute(
                "INSERT INTO words (english, japanese, part_of_speech, "
                "example, domain, level) VALUES (?, ?, ?, ?, ?, ?)",
                (english, japanese, pos, example, domain, level),
            )
            existing.add(english.lower())
            inserted += 1
        print(f"inserted={inserted} skipped={skipped}")


if __name__ == "__main__":
    main()
