# ruff: noqa: E501  (data-heavy seed script: long word/phrase lines are fine)
"""B23④ マニア向け5候補(2026-08-26・authored by Claude): 国際情勢/
インバウンド/AI拡充・フィジカルAI(新設)/人工衛星/電池・エネルギー(分割)。

5並列サブエージェントでドラフト後、AI・フィジカルAIと電池・エネルギーは
それぞれ2ドメインに分割(ユーザー指示)。DB全体でenglishが既存語と衝突する
ものは自動スキップ。

Run:  python scripts/add_niche_specialty.py
仕上げ: 投入後に `python scripts/relevel.py` と
        `python scripts/relevel_phrases.py` で難易度を再設定する。
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.database import db  # noqa: E402

WORDS: list[tuple[str, str, str, str, str, str]] = [
    # --- 国際情勢 ---
    ("sanctions regime", "ある国や勢力に経済的・外交的圧力をかけるために発動される制裁措置の枠組み全体を指す。対象国の資産凍結や貿易制限など複数の措置が組み合わされることが多い。", "名詞句", "The international community imposed a strict sanctions regime after the invasion.", "国際情勢", "800"),
    ("embargo", "特定の国や地域との貿易・輸出入を全面的または部分的に禁止する措置。武器や石油など特定品目に限定される場合と、全面的な通商禁止の場合がある。", "名詞", "The government lifted the decades-old trade embargo last year.", "国際情勢", "700"),
    ("asset freeze", "制裁対象となった個人・団体・国家が保有する銀行口座や不動産などの資産を、法的に凍結して使用や移転をできなくする措置。", "名詞句", "Western banks carried out an asset freeze on accounts linked to the sanctioned oligarch.", "国際情勢", "800"),
    ("export controls", "軍事転用の恐れがある技術や物品が特定の国へ流出するのを防ぐために、政府が輸出を許可制または禁止にする規制。", "名詞句", "New export controls restrict the sale of advanced chipmaking equipment to certain countries.", "国際情勢", "800"),
    ("sanctions evasion", "制裁対象国や企業が、第三国を経由した取引や偽装会社の利用などによって制裁措置の効果を意図的に回避する行為。", "名詞句", "Investigators uncovered a network used for sanctions evasion involving shell companies abroad.", "国際情勢", "850"),
    ("secondary sanctions", "制裁対象国と直接取引する第三国の企業や個人にも制裁を科すことで、制裁の実効性を高めようとする措置。", "名詞句", "The government threatened secondary sanctions against foreign firms that continued doing business with the blacklisted bank.", "国際情勢", "850"),
    ("economic coercion", "貿易制限や投資の停止など経済的手段を用いて、他国に政治的な譲歩や政策変更を迫る行為。", "名詞句", "Analysts described the sudden import ban as a clear case of economic coercion.", "国際情勢", "850"),
    ("trade bloc", "関税の撤廃や共通の通商政策などを通じて、加盟国間の貿易を優遇し合う目的で結成された国家連合。", "名詞句", "Smaller economies often seek membership in a trade bloc to gain better market access.", "国際情勢", "700"),
    ("tariff", "輸入品に課される税金で、国内産業の保護や貿易交渉の駆け引きの手段として使われることが多い。", "名詞", "The new tariff on imported steel sparked complaints from manufacturers overseas.", "国際情勢", "600"),
    ("trade war", "国同士が関税の引き上げや報復措置を繰り返し応酬し合う、貿易をめぐる対立状態。", "名詞句", "The trade war between the two economic giants disrupted global supply chains for years.", "国際情勢", "650"),
    ("decoupling", "これまで密接に結びついていた二国間、特に経済・技術面での相互依存関係を意図的に切り離していくこと。", "名詞", "Some policymakers are pushing for decoupling from a single dominant supplier of critical technology.", "国際情勢", "850"),
    ("de-risking", "完全な関係遮断ではなく、特定国への過度な依存によるリスクを減らしつつ経済関係は維持しようとする、より穏健な政策姿勢。", "名詞", "European leaders favored de-risking over full decoupling in their trade relationship with the rival power.", "国際情勢", "850"),
    ("chokepoint", "海峡や運河など、物流や資源供給が集中して通過するために、封鎖されると世界経済に大きな打撃を与えかねない地理的・戦略的要所。", "名詞", "The narrow strait is a critical chokepoint for global oil shipments.", "国際情勢", "800"),
    ("dual-use technology", "民生目的にも軍事目的にも転用できる技術や製品のことで、輸出規制の対象になりやすい。", "名詞句", "Certain semiconductors are classified as dual-use technology because they can power both smartphones and missile systems.", "国際情勢", "850"),
    ("price cap", "特定の商品、特に石油などの輸出価格に上限を設け、それを超える価格での取引に関連するサービス提供を制限する措置。", "名詞句", "A price cap on the country's oil exports aimed to limit its revenue without cutting off global supply entirely.", "国際情勢", "800"),
    ("frozen assets", "制裁や法的措置によって所有者が自由に使用・移転できなくなった資金や財産。", "名詞句", "Billions of dollars in frozen assets remain in Western banks pending a diplomatic resolution.", "国際情勢", "750"),
    ("sphere of influence", "ある大国が政治・経済・軍事面で強い影響力を及ぼし、事実上の勢力圏とみなしている地域。", "名詞句", "Historians debate whether the region still falls within a major power's sphere of influence.", "国際情勢", "800"),
    ("non-aligned", "冷戦期に米ソいずれの陣営にも公式には属さず、独自の立場を取った国家や運動を指す。現在でも特定の大国陣営に属さない立場を表すのに使われる。", "形容詞", "Several non-aligned countries abstained from the vote at the UN General Assembly.", "国際情勢", "800"),
    ("multipolar", "一つの超大国ではなく、複数の大国や地域大国が影響力を分け合い、勢力均衡が保たれている国際秩序の状態を表す。", "形容詞", "Many scholars argue the world is shifting toward a multipolar order.", "国際情勢", "850"),
    ("unipolar", "一つの超大国が他を圧倒する軍事・経済力を持ち、国際秩序を主導している状態を表す。", "形容詞", "The post-Cold War era was often described as a unipolar moment dominated by a single superpower.", "国際情勢", "850"),
    ("hegemon", "軍事・経済・文化などの面で他国を圧倒する影響力を持ち、地域や世界の秩序を主導する国家。", "名詞", "Some analysts warn that a rising regional hegemon could destabilize the balance of power.", "国際情勢", "850"),
    ("hegemony", "ある国家や勢力が他を圧倒する支配的な影響力を持つ状態、またはそのような支配体制そのもの。", "名詞", "The book examines how naval power helped establish the empire's hegemony.", "国際情勢", "800"),
    ("superpower", "軍事力・経済力・国際的影響力のいずれにおいても他国を大きく上回り、世界規模で行動できる国家。", "名詞", "Only a handful of countries have ever been considered a true superpower.", "国際情勢", "600"),
    ("middle power", "超大国ほどの圧倒的な力は持たないものの、地域あるいは国際問題において無視できない影響力を発揮する国家。", "名詞句", "As a middle power, the country often plays the role of mediator in regional disputes.", "国際情勢", "800"),
    ("proxy war", "大国同士が直接軍事衝突するのを避けつつ、それぞれが支援する現地勢力や第三国を通じて間接的に戦う紛争形態。", "名詞句", "The civil war became a proxy war as rival powers backed opposing factions.", "国際情勢", "750"),
    ("strategic autonomy", "安全保障や経済政策において、特定の同盟国や大国に過度に依存せず、自国・自地域で独自に意思決定できる能力を確保しようとする方針。", "名詞句", "European leaders have called for greater strategic autonomy in defense and technology.", "国際情勢", "850"),
    ("deterrence", "相手に攻撃や侵略を思いとどまらせるために、報復能力や防衛力を誇示し、行動を起こした場合のコストを高く見せる戦略。", "名詞", "Nuclear deterrence has shaped great-power relations for decades.", "国際情勢", "800"),
    ("containment", "ある国や勢力の拡大や影響力の伸長を、直接の軍事衝突を避けながら封じ込めようとする外交・安全保障戦略。", "名詞", "Cold War containment policy aimed to limit the spread of a rival ideology without direct conflict.", "国際情勢", "800"),
    ("escalation", "対立や紛争の規模・激しさが段階的に拡大していくこと。軍事的緊張の高まりを表す際によく使われる。", "名詞", "Diplomats warned that the border clash could trigger a dangerous escalation.", "国際情勢", "700"),
    ("de-escalation", "高まった軍事的・外交的緊張を段階的に緩和し、対立の激化を抑えようとする動き。", "名詞", "Both sides agreed to a series of de-escalation measures along the contested border.", "国際情勢", "750"),
    ("flashpoint", "小さなきっかけでも大規模な紛争や危機に発展しかねない、緊張が特に高まっている地域や問題。", "名詞", "The disputed islands remain a potential flashpoint between the two nations.", "国際情勢", "800"),
    ("ceasefire", "交戦していた当事者が一時的または恒久的に戦闘行為を停止することに合意すること。", "名詞", "A fragile ceasefire held for several weeks before fighting resumed.", "国際情勢", "650"),
    ("insurgency", "既存の政府や統治体制に対して、武装勢力が反乱やゲリラ戦を通じて抵抗・打倒を試みる運動。", "名詞", "The government struggled to put down a growing insurgency in the country's rural provinces.", "国際情勢", "800"),
    ("militia", "正規軍とは別に組織された、多くは民間人からなる武装集団。政府側・反政府側いずれにも存在しうる。", "名詞", "Local militias filled the security vacuum after the regular army withdrew.", "国際情勢", "750"),
    ("annexation", "ある国が他国の領土を、武力や一方的な宣言によって自国領に併合すること。国際法上、他国領土の一方的な併合は一般に認められていない。", "名詞", "The annexation was condemned by most of the international community as a violation of sovereignty.", "国際情勢", "800"),
    ("incursion", "他国の領土や領空・領海に、軍隊や武装勢力が一時的に侵入する行為。全面侵攻より限定的な軍事行動を指すことが多い。", "名詞", "Border guards reported a brief incursion by armed personnel overnight.", "国際情勢", "800"),
    ("buffer zone", "対立する勢力同士の直接衝突を防ぐために設けられる、非武装または中立とされる緩衝地帯。", "名詞句", "Peacekeepers were deployed to monitor the buffer zone separating the two armies.", "国際情勢", "800"),
    ("demilitarized zone", "条約や合意に基づき、軍隊の駐留や武器の配備が禁止された地域。略称DMZ。", "名詞句", "Tourists can visit an observation point near the demilitarized zone.", "国際情勢", "750"),
    ("arms race", "対立する国同士が、優位に立とうと競い合って軍備や兵器の開発・保有を拡大していく状態。", "名詞句", "Critics warn that new missile technology could spark a fresh arms race.", "国際情勢", "700"),
    ("nuclear proliferation", "核兵器やその製造技術が、これまで保有していなかった国や勢力に拡散していくこと。", "名詞句", "The treaty was designed to curb nuclear proliferation among non-nuclear states.", "国際情勢", "850"),
    ("asymmetric warfare", "軍事力に大きな差がある当事者間で行われる戦闘形態で、弱い側がゲリラ戦やテロなど非正規の戦術を用いることが多い。", "名詞句", "Insurgent groups often rely on asymmetric warfare to offset a conventional military's advantage.", "国際情勢", "850"),
    ("hybrid warfare", "通常の軍事行動に加え、サイバー攻撃・偽情報の拡散・経済的圧力などを組み合わせて相手を弱体化させる戦略。", "名詞句", "Officials accused the rival state of waging a hybrid warfare campaign combining cyberattacks and propaganda.", "国際情勢", "850"),
    ("gray-zone tactics", "明確な武力行使には至らないものの、威圧や既成事実化を狙って行われる、平時と有事の中間にあたる挑発的な行動。", "名詞句", "The coast guard's aggressive maneuvers were seen as gray-zone tactics short of outright conflict.", "国際情勢", "900"),
    ("disinformation", "特定の意図を持って、事実と異なる情報を意図的に流布すること。誤情報(misinformation)と異なり、発信者が虚偽と知りながら広める点が特徴。", "名詞", "The report traced a disinformation campaign back to state-linked social media accounts.", "国際情勢", "750"),
    ("propaganda", "特定の思想や立場への支持を広めるため、感情に訴えたり事実を偏った形で伝えたりする組織的な情報発信。", "名詞", "State media was accused of spreading propaganda to bolster public support for the war effort.", "国際情勢", "650"),
    ("influence operation", "世論やエリート層の認識・意思決定に働きかけることを目的とした、国家などによる組織的な情報工作・宣伝活動。", "名詞句", "Security agencies said the fake accounts were part of a broader influence operation.", "国際情勢", "850"),
    ("election interference", "外国政府や勢力が、投票結果や世論に影響を与える目的で他国の選挙過程に不正に介入する行為。", "名詞句", "The intelligence agency published a report on suspected election interference by a foreign actor.", "国際情勢", "800"),
    ("authoritarian", "権力が一人の指導者や少数の集団に集中し、市民の政治的自由や反対意見が厳しく制限されている統治形態を表す。", "形容詞", "Human rights groups criticized the increasingly authoritarian crackdown on independent media.", "国際情勢", "700"),
    ("autocracy", "一人の支配者が事実上ほぼ制約なく統治権力を握る政治体制。", "名詞", "The country has drifted from a fragile democracy toward outright autocracy over the past decade.", "国際情勢", "800"),
    ("regime change", "ある国の統治体制や政権を、内部の反乱・クーデター、あるいは外部からの介入によって根本的に交代させること。", "名詞句", "Some critics argue that foreign-imposed regime change often leads to prolonged instability.", "国際情勢", "750"),
    ("coup d'état", "軍部や少数の勢力が、憲法上の手続きによらず、武力や強制力を用いて政権を奪取すること。単にcoupとも言う。", "名詞句", "The president was ousted in a coup d'état led by senior military officers.", "国際情勢", "750"),
    ("junta", "クーデターなどによって権力を掌握した、軍人を中心とする統治集団。", "名詞", "The military junta suspended the constitution and postponed elections indefinitely.", "国際情勢", "800"),
    ("strongman", "権力を個人に集中させ、強権的な手法で統治する指導者を指す口語的な表現。", "名詞", "The regional strongman has ruled the country for over two decades.", "国際情勢", "750"),
    ("populist", "エリート層への不満を煽り、「庶民」対「既得権益層」という対立構図を強調して支持を集める政治手法や政治家の立場を表す。", "形容詞", "The populist leader campaigned on promises to challenge the political establishment.", "国際情勢", "700"),
    ("crackdown", "政府や当局が、抗議活動や反体制的な動き、犯罪などに対して行う厳しい取り締まり。", "名詞", "The government launched a sweeping crackdown on street protests.", "国際情勢", "700"),
    ("dissident", "支配的な政府や体制の政策・イデオロギーに公然と反対し、しばしば弾圧の対象となる人物。", "名詞", "The exiled dissident continued to criticize the regime from abroad.", "国際情勢", "750"),
    ("refugee crisis", "戦争や迫害、災害などにより多数の人々が母国を追われ、受け入れ国や国際社会の対応能力を超える規模に達した状況。", "名詞句", "The prolonged conflict triggered one of the largest refugee crises in recent history.", "国際情勢", "700"),
    ("asylum seeker", "迫害を逃れて他国に庇護を求めているが、まだ難民としての法的地位が正式に認められていない人。", "名詞句", "Thousands of asylum seekers were waiting for their claims to be processed at the border.", "国際情勢", "700"),
    ("displaced persons", "紛争や災害によって自宅や故郷を追われたが、国境を越えていないため難民とは区別される人々(国内避難民)。", "名詞句", "Aid agencies struggled to provide shelter for the growing number of displaced persons.", "国際情勢", "800"),
    ("humanitarian corridor", "紛争地域において、民間人の避難や救援物資の搬入を安全に行うために当事者間で合意される限定的な安全通路。", "名詞句", "A temporary humanitarian corridor allowed civilians to evacuate the besieged city.", "国際情勢", "850"),
    ("great-power competition", "世界的な影響力を持つ大国同士が、軍事・経済・技術など複数の分野で優位を争う構造的な対立関係。", "名詞句", "Analysts see the technology race as a new front in great-power competition.", "国際情勢", "850"),
    ("power projection", "自国の領土から離れた地域においても軍事力を展開し、影響力を行使できる能力。", "名詞句", "Aircraft carriers give a navy significant power projection far from its own shores.", "国際情勢", "850"),
    ("critical minerals", "先端技術製品や防衛関連製品の製造に不可欠でありながら、供給が特定の少数国に偏っている鉱物資源。", "名詞句", "Governments are racing to secure supplies of critical minerals used in batteries and defense systems.", "国際情勢", "800"),
    ("rare earth elements", "電子機器や電気自動車、防衛技術などに欠かせない一群の希少な金属元素で、生産が一部の国に集中しているため地政学上の争点になっている。", "名詞句", "The country holds a dominant share of global rare earth elements production.", "国際情勢", "800"),
    ("friend-shoring", "供給網の途絶リスクを減らすため、政治的・安全保障上信頼できる同盟国や友好国に生産拠点や調達先を移す動き。", "名詞", "Companies pursuing friend-shoring are shifting production to politically aligned countries.", "国際情勢", "900"),
    ("reshoring", "海外に移転していた生産拠点を、再び自国内に戻すこと。", "名詞", "Rising geopolitical risk has encouraged reshoring of semiconductor manufacturing.", "国際情勢", "850"),
    ("energy security", "手ごろな価格で安定的にエネルギー資源を確保し、供給途絶のリスクを最小限に抑えられている状態。", "名詞句", "The crisis renewed debate over the country's energy security and reliance on imported fuel.", "国際情勢", "750"),
    ("currency manipulation", "政府や中央銀行が、自国の輸出を有利にするなどの目的で、為替レートを人為的に操作すること。", "名詞句", "The country was accused of currency manipulation to keep its exports artificially cheap.", "国際情勢", "850"),
    ("de-dollarization", "国際貿易や外貨準備において、米ドルへの依存度を下げ、他の通貨や決済手段への移行を進める動き。", "名詞", "Some emerging economies are exploring de-dollarization to reduce their exposure to U.S. monetary policy.", "国際情勢", "900"),
    ("protectionism", "関税や輸入規制などを通じて自国産業を海外との競争から保護しようとする経済政策の立場。", "名詞", "Rising protectionism has slowed the growth of global trade in recent years.", "国際情勢", "750"),
    # --- インバウンド ---
    ("inbound tourism", "外国人が観光や商用で自国を訪れること、またその産業全体を指す言葉。日本では「訪日観光」とほぼ同義で使われる。", "名詞句", "Inbound tourism has become one of the fastest-growing sectors of the Japanese economy.", "インバウンド", "500"),
    ("overtourism", "観光客の急増により、交通機関の混雑やごみ問題、住民生活への悪影響など、地域社会が受け入れ能力を超えた負担を負う現象。", "名詞", "Kyoto's narrow streets are struggling with overtourism during the cherry blossom season.", "インバウンド", "650"),
    ("tax-free shopping", "外国人旅行者が一定の条件を満たした場合に消費税の支払いを免除されて買い物できる制度、またはその買い物自体を指す。", "名詞句", "Many department stores in Tokyo have dedicated counters for tax-free shopping.", "インバウンド", "500"),
    ("consumption tax", "日本国内での商品購入やサービス利用にかかる間接税。免税制度は、外国人旅行者がこの税の負担を免れる仕組みである。", "名詞句", "Foreign tourists can be exempted from consumption tax when they buy goods to take out of the country.", "インバウンド", "550"),
    ("tax exemption", "特定の条件を満たす人や取引に対して税金の支払いを免除すること。訪日客向けの免税制度はこの一例である。", "名詞句", "The tax exemption applies only to purchases over a certain amount made by non-resident travelers.", "インバウンド", "600"),
    ("tax refund counter", "免税手続きを一括して行うための専用窓口。パスポートの提示やレシートの確認などがここで行われる。", "名詞句", "After shopping, please bring your receipts to the tax refund counter on the seventh floor.", "インバウンド", "550"),
    ("tamper-evident bag", "開封すると跡が残る特殊な袋。免税で購入した消耗品を、出国まで開封しないことを保証するために使われる。", "名詞句", "Cosmetics bought tax-free must be sealed in a tamper-evident bag until you leave the country.", "インバウンド", "750"),
    ("consumable goods", "食品や化粧品、医薬品など、使用すると消費されてしまう免税対象の商品カテゴリー。一般物品とは異なる保管ルールが適用される。", "名詞句", "Consumable goods purchased tax-free must remain sealed and cannot be opened before departure.", "インバウンド", "700"),
    ("general goods", "家電や衣類、バッグなど、消耗品に分類されない免税対象の商品カテゴリー。開封して使用しても免税資格を失わない。", "名詞句", "Electronics and clothing are usually classified as general goods for tax-free purposes.", "インバウンド", "700"),
    ("minimum purchase amount", "免税手続きを受けるために必要な、一回あたりの最低購入金額。この金額に満たない買い物は免税の対象外となる。", "名詞句", "The minimum purchase amount for tax exemption is currently set at five thousand yen.", "インバウンド", "600"),
    ("cashless payment", "現金を使わず、クレジットカードや電子マネー、コード決済などで支払いを済ませる方法。訪日客の利便性向上のため急速に普及している。", "名詞句", "Cashless payment options have expanded rapidly at small shops to accommodate foreign visitors.", "インバウンド", "500"),
    ("QR code payment", "スマートフォンで二次元コードを読み取って決済する方式。中国など海外からの観光客に特に普及している支払い手段。", "名詞句", "The tourist scanned the QR code payment sign and paid for her lunch in seconds.", "インバウンド", "500"),
    ("contactless payment", "ICチップ搭載のカードやスマートフォンを端末にかざすだけで完了する決済方法。サインや暗証番号の入力が不要な場合が多い。", "名詞句", "Contactless payment made it easy for the visitor to buy a train ticket without cash.", "インバウンド", "550"),
    ("mobile wallet", "クレジットカード情報や電子マネーをスマートフォンに登録し、端末にかざして支払える仕組み。旅行者は自国のアプリをそのまま使えることもある。", "名詞句", "Some convenience stores now accept mobile wallets popular overseas, such as Alipay.", "インバウンド", "550"),
    ("point-of-sale terminal", "店舗のレジに設置される、支払いを処理するための端末。多言語対応や複数の決済手段への対応が求められている。", "名詞句", "The shop upgraded its point-of-sale terminal to accept both IC cards and foreign credit cards.", "インバウンド", "650"),
    ("multi-currency support", "一つの決済端末やサービスが複数の国の通貨での支払いや価格表示に対応していること。", "名詞句", "The hotel's booking system offers multi-currency support so guests can see prices in their own currency.", "インバウンド", "650"),
    ("omotenashi", "見返りを求めず相手の立場に立って先回りして気を配る、日本のもてなしの精神を表す言葉。接客業でしばしば海外に紹介される。", "名詞", "The concept of omotenashi is often cited as a reason why service in Japan feels so attentive.", "インバウンド", "600"),
    ("hospitality mindset", "客の立場に立ち、細やかな気配りをもって接しようとする心構え。単なる接客マニュアルを超えた姿勢を指す。", "名詞句", "Staff training focused on building a hospitality mindset rather than just memorizing scripted phrases.", "インバウンド", "650"),
    ("anticipatory service", "客が要求する前に必要を察し、先回りして提供するサービス。「おもてなし」の実践例としてよく挙げられる。", "名詞句", "Anticipatory service, like refilling a guest's water glass before they ask, is a hallmark of Japanese hospitality.", "インバウンド", "800"),
    ("concierge desk", "ホテルなどで宿泊客の観光案内や予約手配、道案内などを行う専用のカウンター。", "名詞句", "The concierge desk arranged a private tour guide for the family's visit to the old town.", "インバウンド", "600"),
    ("multilingual signage", "日本語だけでなく英語や中国語、韓国語など複数の言語で表示された案内板や標識。", "名詞句", "Multilingual signage at the station now includes directions in English, Chinese, and Korean.", "インバウンド", "600"),
    ("pictogram", "言葉を使わず、絵や記号だけで意味を伝える表示。言語が異なる旅行者にも直感的に理解してもらえる利点がある。", "名詞", "A pictogram showing a footbath symbol tells visitors where they can soak their feet for free.", "インバウンド", "650"),
    ("language barrier", "話す言語が異なることによって意思疎通が難しくなる状況。接客業では翻訳ツールなどで克服しようとする取り組みが進む。", "名詞句", "The staff used a translation app to overcome the language barrier with the visiting couple.", "インバウンド", "550"),
    ("barrier-free access", "段差や階段など、体の不自由な人や高齢者、大きな荷物を持つ旅行者の移動を妨げる障壁を取り除いた環境。", "名詞句", "The new tourist information center was designed with barrier-free access for wheelchair users.", "インバウンド", "600"),
    ("universal design", "年齢や身体能力、言語、文化的背景にかかわらず、できるだけ多くの人が使いやすいように作られた設計の考え方。", "名詞句", "The airport terminal was renovated based on universal design principles to welcome a diverse range of travelers.", "インバウンド", "700"),
    ("interpreter guide", "外国語での案内と通訳を兼ねて観光客を案内する仕事の人。単なる語学力だけでなく、地域の知識も求められる。", "名詞句", "The tour company hired an interpreter guide fluent in both French and Japanese history.", "インバウンド", "650"),
    ("licensed guide interpreter", "国家資格である通訳案内士の資格を持ち、外国人観光客に有償で通訳と案内を行うことを認められた専門家。", "名詞句", "To work legally as a paid tour guide for foreigners, she studied for years to become a licensed guide interpreter.", "インバウンド", "800"),
    ("inbound tour operator", "海外から日本を訪れる旅行者向けに、ツアーの企画や手配を専門に行う事業者。", "名詞句", "The inbound tour operator designed a week-long itinerary combining cities and rural experiences.", "インバウンド", "700"),
    ("destination marketing organization", "特定の地域や都市への観光客誘致を目的として、プロモーションや情報発信を行う組織。略称DMO。地方自治体や観光業者と連携することが多い。", "名詞句", "The local destination marketing organization launched an English-language campaign to attract more visitors.", "インバウンド", "850"),
    ("familiarization trip", "旅行会社の担当者やメディア関係者を招待し、実際に現地を体験してもらうことで将来の商品化や記事化につなげる視察旅行。業界では「ファムトリップ」とも呼ばれる。", "名詞句", "Travel agents from Southeast Asia joined a familiarization trip to sample the region's hot spring resorts.", "インバウンド", "850"),
    ("foreign independent traveler", "団体ツアーに参加せず、個人で旅程を組んで旅行する外国人観光客のこと。略称FIT。近年、日本ではこの層の受け入れ体制強化が課題となっている。", "名詞句", "The rise of the foreign independent traveler has pushed small inns to offer English-language booking sites.", "インバウンド", "800"),
    ("group tour", "添乗員に引率され、複数の旅行者がまとまって同じ日程で観光する旅行の形態。", "名詞句", "A large group tour from Taiwan arrived at the temple just before closing time.", "インバウンド", "500"),
    ("per-visitor spending", "一人の観光客が滞在中に消費する平均金額。国や地域の観光戦略で重要な指標として使われる。", "名詞句", "The prefecture aims to raise per-visitor spending by promoting longer stays in rural areas.", "インバウンド", "750"),
    ("inbound consumption", "訪日外国人旅行者が日本国内で行う買い物や宿泊、飲食などの消費活動の総称。", "名詞句", "Inbound consumption reached a record high as the number of foreign visitors recovered.", "インバウンド", "750"),
    ("economic ripple effect", "ある経済活動が、関連する他の産業や地域経済にも次々と影響を及ぼしていく波及効果のこと。観光消費の効果を説明する際によく用いられる。", "名詞句", "A single tourist's hotel stay can create an economic ripple effect that benefits local farmers and craftspeople.", "インバウンド", "800"),
    ("accommodation tax", "ホテルや旅館などの宿泊料金に上乗せして課される税金。観光インフラの整備費用などに充てられることが多い。", "名詞句", "Several major cities now charge an accommodation tax to fund tourism infrastructure.", "インバウンド", "700"),
    ("international tourist tax", "日本を出国する人から一律に徴収される税金。正式名称は国際観光旅客税で、観光振興のための財源として使われる。", "名詞句", "The international tourist tax of one thousand yen is added to the price of every international flight ticket departing Japan.", "インバウンド", "800"),
    ("tourism pollution", "観光客の増加によって引き起こされる、ごみの散乱や騒音、自然環境の破壊といった問題の総称。", "名詞句", "Local officials are considering entry limits to reduce tourism pollution at the popular gorge.", "インバウンド", "700"),
    ("carrying capacity", "ある観光地が、環境や地域社会に深刻な悪影響を与えることなく受け入れられる観光客数の上限。", "名詞句", "Researchers estimated the carrying capacity of the small island before the ferry company added more routes.", "インバウンド", "800"),
    ("local backlash", "観光客の増加やその振る舞いに対して、地域住民が不満や反発を示すこと。", "名詞句", "Complaints about noise and litter fueled a local backlash against short-term rental apartments.", "インバウンド", "750"),
    ("littering", "ごみを所定の場所以外に捨てること。観光地でのマナー違反として問題視されることが多い。", "名詞", "Signs in several languages now warn visitors that littering is subject to a fine.", "インバウンド", "500"),
    ("designated photo spot", "混雑や私有地への立ち入りを避けるため、観光地側があらかじめ撮影用に設けたスペース。", "名詞句", "The shrine set up a designated photo spot so visitors would stop blocking the main gate.", "インバウンド", "600"),
    ("photography etiquette", "撮影する際に周囲の人や場所に配慮するための望ましい振る舞い方。無断で人を撮ったり、立入禁止区域に入ったりしないことなどが含まれる。", "名詞句", "The pamphlet explains basic photography etiquette, such as asking permission before photographing local residents.", "インバウンド", "650"),
    ("sacred site", "神社や寺院など、宗教的・文化的に神聖とされる場所。観光客にも敬意ある行動が求められる。", "名詞句", "Visitors are asked to remain quiet and dress modestly when entering a sacred site.", "インバウンド", "600"),
    ("shrine etiquette", "神社を参拝する際に守るべき作法。鳥居をくぐる際のお辞儀や手水の使い方などが含まれる。", "名詞句", "The guide gave a short lesson on shrine etiquette before the group approached the torii gate.", "インバウンド", "550"),
    ("shoes-off custom", "家屋や旅館、一部の飲食店などに入る前に靴を脱ぐという、日本で広く行われている習慣。", "名詞句", "Staff gently reminded first-time guests about the shoes-off custom at the entrance of the ryokan.", "インバウンド", "550"),
    ("queueing culture", "順番を守って列に並ぶことを重視する社会的習慣。日本では特に徹底されており、外国人観光客が驚くこともある。", "名詞句", "Visitors are often impressed by Japan's strict queueing culture, even during rush hour.", "インバウンド", "600"),
    ("no-tipping custom", "サービスに対してチップを渡す習慣がなく、渡そうとするとかえって困惑させてしまうことがある日本の慣習。", "名詞句", "The waiter politely explained the no-tipping custom when the tourist tried to leave extra cash.", "インバウンド", "550"),
    ("trash sorting rules", "燃えるごみ、燃えないごみ、資源ごみなど、種類ごとに分別して捨てることを求める地域のルール。外国人観光客には分かりにくいことがある。", "名詞句", "A multilingual poster explains the trash sorting rules at the guesthouse's communal kitchen.", "インバウンド", "600"),
    ("quiet car", "電話での通話や大声での会話を控えるよう求められる、鉄道車両の一区画または車両全体。", "名詞句", "A conductor politely asked the group to lower their voices in the quiet car.", "インバウンド", "550"),
    ("dietary restriction", "宗教上の理由やアレルギー、健康上の理由などにより、特定の食品を避けなければならないこと。", "名詞句", "The restaurant added an English menu that clearly marks dishes for guests with dietary restrictions.", "インバウンド", "600"),
    ("halal-friendly", "イスラム教の戒律に沿った食材や調理法を用いており、ムスリムの旅行者でも安心して利用できることを表す言葉。", "形容詞", "More airport restaurants are becoming halal-friendly as the number of Muslim visitors grows.", "インバウンド", "700"),
    ("prayer room", "宗教上の礼拝を行うために設けられた専用の部屋。空港やショッピングモールなどに設置されることが増えている。", "名詞句", "The shopping mall opened a prayer room near the food court to serve Muslim visitors.", "インバウンド", "650"),
    ("Wi-Fi coverage", "特定の場所やエリアで無線インターネットに接続できる範囲。地図アプリを多用する旅行者にとって重要な要素。", "名詞句", "Poor Wi-Fi coverage in rural areas remains a common complaint among foreign travelers.", "インバウンド", "500"),
    ("foreign-friendly", "外国人にとって利用しやすいよう、言語対応や決済手段、文化的配慮などが整えられている様子。", "形容詞", "The inn markets itself as foreign-friendly, with an English-speaking staff member always on duty.", "インバウンド", "650"),
    ("room amenity kit", "客室に用意される歯ブラシやスリッパ、説明書などの備品一式。多言語での使用説明が添えられることもある。", "名詞句", "The hotel added multilingual instructions to its room amenity kit after guest feedback.", "インバウンド", "550"),
    ("peak season surcharge", "観光需要が特に高まる時期に、宿泊料金などに上乗せして請求される追加料金。", "名詞句", "Prices spike during cherry blossom week because of the peak season surcharge many hotels apply.", "インバウンド", "700"),
    ("tourist etiquette guide", "訪日観光客に向けて、公共の場でのマナーや現地の習慣をわかりやすく説明した案内資料。", "名詞句", "The city distributed a tourist etiquette guide covering everything from train manners to onsen customs.", "インバウンド", "600"),
    ("cultural sensitivity", "異なる文化的背景を持つ人々の価値観や習慣を理解し、敬意を持って配慮しようとする姿勢。", "名詞句", "Staff underwent cultural sensitivity training before the busy holiday season began.", "インバウンド", "750"),
    ("sustainable tourism", "環境や地域社会、文化資源への負荷を抑えながら、長期的に観光を維持していこうとする考え方。", "名詞句", "The region is investing in sustainable tourism to avoid the overcrowding seen elsewhere.", "インバウンド", "700"),
    # --- AI ---
    ("large language model (LLM)", "膨大なテキストデータで事前学習された、数十億〜数兆パラメータ規模の言語モデル。文章生成・要約・翻訳・対話など幅広いタスクをこなせる汎用性の高さが特徴で、GPTやClaudeなどが代表例。", "名詞句", "The company built its customer support bot on top of a large language model fine-tuned for technical troubleshooting.", "AI", "850"),
    ("foundation model", "大規模なデータで事前学習され、多様な下流タスクに転用できる基盤となるAIモデルの総称。単体で使うだけでなく、ファインチューニングや追加学習によって特定用途向けにカスタマイズされることが多い。", "名詞句", "Instead of training from scratch, the team adapted an open-source foundation model to their domain-specific data.", "AI", "850"),
    ("prompt engineering", "生成AIから望ましい出力を引き出すために、指示文(プロンプト)の書き方や構成を工夫する技術・手法。的確な例示や条件指定によってモデルの回答精度を高める。", "名詞句", "Good prompt engineering can dramatically improve the accuracy of the model's answers without changing the underlying weights.", "AI", "800"),
    ("prompt injection", "悪意のある指示を入力文に紛れ込ませ、AIモデルに開発者の意図しない挙動(機密情報の漏洩や制限の無視など)をさせようとする攻撃手法。", "名詞句", "The security team ran tests to see whether the chatbot was vulnerable to prompt injection through user-uploaded documents.", "AI", "900"),
    ("retrieval-augmented generation (RAG)", "生成AIが回答を作る際に、外部の文書データベースや検索エンジンから関連情報を取得し、それを踏まえて回答を生成する手法。モデルの知識を最新化し、事実に基づかない回答(ハルシネーション)を減らす効果がある。", "名詞句", "By adding retrieval-augmented generation, the assistant could cite the latest internal documentation instead of relying on outdated training data.", "AI", "900"),
    ("context window", "生成AIモデルが一度の処理で参照できる入力・出力テキストの最大範囲(トークン数)。この範囲を超えた情報はモデルが直接参照できない。", "名詞句", "We had to summarize the earlier conversation because it exceeded the model's context window.", "AI", "850"),
    ("tokenization", "テキストをモデルが処理できる最小単位(トークン)に分割する処理。単語そのものではなく、単語の一部やサブワード単位に分割されることが多い。", "名詞", "Poor tokenization of non-English text can make the model less efficient and less accurate for those languages.", "AI", "800"),
    ("hallucination", "生成AIが事実に基づかない、もっともらしいが誤った情報を自信満々に出力してしまう現象。学習データにない事柄について尋ねられた際に特に起こりやすい。", "名詞", "The report contained a hallucination — the model cited a research paper that doesn't actually exist.", "AI", "850"),
    ("fine-tuning", "既に学習済みの基盤モデルに対し、特定タスクやドメインの追加データで再学習を行い、性能や振る舞いを調整すること。ゼロから学習するより少ないデータ・計算量で済む。", "名詞", "We fine-tuned the base model on our internal support tickets to make its responses more domain-specific.", "AI", "800"),
    ("in-context learning", "モデルの重みを更新せず、プロンプト内に与えた例や指示だけを手がかりにタスクをこなす能力。ファインチューニングとは異なり、追加学習は行わない。", "名詞句", "Rather than fine-tuning, we relied on in-context learning by including a few examples directly in the prompt.", "AI", "900"),
    ("zero-shot learning", "そのタスクに関する例を一切与えられていない状態で、モデルが未知のタスクをこなす能力・手法。", "名詞句", "The model performed surprisingly well in a zero-shot setting, classifying categories it had never been explicitly trained on.", "AI", "850"),
    ("few-shot learning", "ごく少数の例(数個程度)だけをプロンプトに含めることで、モデルに新しいタスクのやり方を示し、こなさせる手法。", "名詞句", "With few-shot learning, we gave the model three example translations and it generalized the pattern to new sentences.", "AI", "850"),
    ("multimodal", "テキストだけでなく、画像・音声・動画など複数の異なる種類(モダリティ)の情報を同時に扱える、あるいは組み合わせて処理できることを表す形容詞。", "形容詞", "The new multimodal model can analyze a photo of a whiteboard and generate meeting notes from it.", "AI", "850"),
    ("function calling", "生成AIが会話の中で外部の関数やAPIを呼び出す必要があると判断した際に、その関数名と引数を構造化された形式で出力する仕組み。AIエージェントが外部ツールを操作する土台となる。", "名詞句", "Using function calling, the assistant can query the flight database directly instead of guessing at ticket prices.", "AI", "900"),
    ("multi-agent system", "複数のAIエージェントが役割分担しながら連携・協調(時に競合)して一つの目標を達成する仕組み。一つのAIに全工程を任せるより複雑なタスクを分業できる。", "名詞句", "They designed a multi-agent system where one agent researches the topic and another drafts the final report.", "AI", "900"),
    ("system prompt", "AIモデルに会話全体を通して守らせたい役割・トーン・制約などを、ユーザーの発言とは別に事前に与えておく指示文。", "名詞句", "The system prompt instructed the model to always respond in a formal tone and never reveal internal configuration.", "AI", "800"),
    ("sampling temperature", "生成AIが次の単語を選ぶ際のランダム性を制御するパラメータ。値を高くすると出力が多様で創造的になり、低くすると決まりきった無難な出力になりやすい。", "名詞句", "Lowering the sampling temperature made the model's answers more consistent, though slightly less creative.", "AI", "850"),
    ("vector embedding", "単語や文章、画像などを、その意味的な近さが反映されるように多次元の数値ベクトルへ変換したもの。似た意味を持つもの同士は、ベクトル空間上で近い位置に配置される。", "名詞句", "The search feature compares the vector embedding of the user's query against embeddings of every document in the database.", "AI", "850"),
    ("vector database", "embedding(ベクトル表現)を効率よく保存し、意味的に類似したベクトルを高速に検索できるよう設計されたデータベース。RAGの検索基盤としてよく使われる。", "名詞句", "They stored millions of document embeddings in a vector database to power the RAG pipeline's search step.", "AI", "900"),
    ("semantic search", "キーワードの一致ではなく、文章や単語の意味的な近さに基づいて関連情報を検索する手法。embeddingとベクトルデータベースを組み合わせて実現されることが多い。", "名詞句", "Semantic search returned relevant articles even when they didn't contain the exact words the user typed.", "AI", "850"),
    ("knowledge cutoff", "生成AIモデルの学習データがどの時点までの情報を含んでいるかを示す区切りの日付。それ以降に起きた出来事についてモデルは基本的に知らない。", "名詞句", "Because the model's knowledge cutoff was over a year old, it had no idea about the company's recent product launch.", "AI", "800"),
    ("jailbreak", "AIモデルに組み込まれた安全上の制約やガードレールを、巧妙な言い回しや設定で回避させ、本来拒否すべき出力をさせること。", "動詞", "Researchers published a paper describing a new way to jailbreak the model into ignoring its safety guidelines.", "AI", "850"),
    ("guardrail", "AIモデルが有害な出力、危険な行為、方針違反の回答などをしないよう設けられた制限・防護策の総称。プロンプト側の制御や出力のフィルタリングなど複数の層で実装される。", "名詞", "The team added an extra guardrail to prevent the assistant from giving specific medical dosage advice.", "AI", "800"),
    ("red teaming", "AIシステムの弱点や悪用可能な抜け穴を見つけるために、意図的に攻撃者の視点から挑発的な入力を試し、脆弱性を洗い出す評価手法。", "名詞句", "Before the launch, an external red teaming group spent two weeks trying to make the model produce unsafe content.", "AI", "900"),
    ("knowledge distillation", "大規模で高精度な「教師モデル」の出力や振る舞いを模倣させることで、より小さく軽量な「生徒モデル」を学習させる手法。推論コストを抑えつつ性能をある程度維持できる。", "名詞句", "Knowledge distillation let them ship a compact model on mobile devices that retained most of the larger model's accuracy.", "AI", "900"),
    ("quantization", "モデルの重みや計算を、32ビット浮動小数点数のような高精度な表現から、8ビット整数など少ないビット数の表現に変換し、メモリ使用量や推論速度を改善する技術。", "名詞", "After quantization, the model's memory footprint shrank by 75% with only a small drop in accuracy.", "AI", "900"),
    ("mixture of experts", "モデル内に複数の専門化された部分ネットワーク(エキスパート)を用意し、入力ごとにそのうち一部だけを選んで計算させることで、全体のパラメータ数を保ちながら計算コストを抑えるアーキテクチャ。", "名詞句", "The latest model uses a mixture of experts architecture, activating only a fraction of its parameters for each token.", "AI", "950"),
    ("emergent abilities", "モデルの規模(パラメータ数や学習データ量)がある閾値を超えたときに、それまで見られなかった能力が突如として現れる現象。", "名詞句", "Chain-of-thought reasoning is often cited as one of the emergent abilities that only appear once a model reaches a certain scale.", "AI", "900"),
    ("scaling law", "モデルの性能が、パラメータ数・学習データ量・計算資源の増加に伴ってどのように変化するかを示す経験的な法則。研究開発における投資判断の指針として使われる。", "名詞句", "According to the scaling law observed by the research team, doubling the training data yielded a predictable drop in loss.", "AI", "900"),
    ("synthetic data", "実世界から収集したデータではなく、AIモデルやシミュレーションによって人工的に生成された学習用データ。実データが少ない・入手困難な場合の補完に使われる。", "名詞句", "They generated synthetic data to augment the small dataset of rare defect images.", "AI", "800"),
    # --- フィジカルAI ---
    ("humanoid robot", "人間の身体の構造(頭部・胴体・二本の腕・二本の脚など)を模した形状を持つロボット。人間向けに設計された環境や道具をそのまま扱えることを目指して開発される。", "名詞句", "The startup unveiled a humanoid robot capable of walking up stairs and opening doors without a handle-specific redesign.", "フィジカルAI", "800"),
    ("actuator", "電気・油圧・空気圧などのエネルギーを機械的な動き(回転や直線運動)に変換する駆動装置。ロボットの関節や筋肉に相当する役割を果たす。", "名詞", "Each joint in the robotic arm is driven by a separate actuator that provides precise torque control.", "フィジカルAI", "800"),
    ("sim-to-real transfer", "シミュレーション環境で学習したロボットの制御方策やモデルを、現実世界のロボットにそのまま(あるいは微調整して)適用する技術・課題。シミュレーションと実世界の差(リアリティギャップ)をいかに埋めるかが鍵となる。", "名詞句", "The team trained the walking policy entirely in simulation and relied on sim-to-real transfer to deploy it on the physical robot.", "フィジカルAI", "900"),
    ("sensor fusion", "カメラ、LiDAR、IMU(慣性計測装置)など複数の異なるセンサーから得られたデータを統合し、単一のセンサーよりも正確で頑健な環境認識や状態推定を行う技術。", "名詞句", "Sensor fusion combined camera and LiDAR data to give the autonomous vehicle a more reliable picture of nearby obstacles.", "フィジカルAI", "900"),
    ("dexterous manipulation", "人間の手のように、対象物の形状や状態に応じて細かく力加減や指先の動きを調整しながら物を扱う、高度な物体操作。", "名詞句", "Dexterous manipulation of small, irregularly shaped objects remains one of the hardest problems in robotics.", "フィジカルAI", "900"),
    ("edge AI", "クラウドサーバーに頼らず、スマートフォンやロボット、IoT機器などの端末(エッジ)側でAIモデルの推論を直接実行する仕組み。通信遅延の低減やオフライン動作、プライバシー保護のために採用される。", "名詞句", "Running the vision model as edge AI let the drone avoid obstacles even without an internet connection.", "フィジカルAI", "850"),
    ("digital twin", "現実の機械・工場・都市などの物理的な対象を、センサーデータなどを用いてリアルタイムに反映した仮想空間上の再現モデル。シミュレーションによる予測や事前検証に活用される。", "名詞句", "Engineers tested the new assembly line on a digital twin before making any changes to the physical factory.", "フィジカルAI", "850"),
    ("teleoperation", "人間のオペレーターが遠隔地からロボットを直接操作すること。自律動作が難しい状況での作業や、自律AIの学習データ収集の手段としても使われる。", "名詞", "When the robot encountered an unfamiliar object, a human operator took over through teleoperation to complete the task safely.", "フィジカルAI", "850"),
    ("embodied AI", "仮想空間上だけで完結するのではなく、ロボットなど物理的な身体を通して現実世界を知覚し、行動しながら学習・機能するAIの分野。「フィジカルAI」とほぼ同義で使われる。", "名詞句", "Embodied AI research focuses on how an agent's physical interactions with the world shape its understanding, not just its access to text.", "フィジカルAI", "900"),
    ("robot learning", "強化学習や模倣学習などの機械学習手法を用いて、ロボット自身が試行錯誤やデモンストレーションを通して新しい動作や作業手順を獲得していく研究分野。", "名詞句", "Robot learning techniques allowed the arm to improve its grasping success rate after just a few hundred trial attempts.", "フィジカルAI", "900"),
    ("proprioception", "自分自身の関節の角度や姿勢、身体各部の位置関係を、外部の視覚情報に頼らずに感知する能力。ロボットでは関節角センサーなどによって実現される。", "名詞", "Even with the cameras covered, the robot maintained its balance thanks to proprioception from its joint sensors.", "フィジカルAI", "950"),
    ("world model", "AIエージェントが、自身を取り巻く環境がどのように変化・反応するかを内部的にシミュレートするために学習した予測モデル。行動の結果を事前に「頭の中で」予測し、計画に役立てる。", "名詞句", "By learning a world model, the agent could simulate several possible actions internally before deciding which one to actually execute.", "フィジカルAI", "900"),
    ("end effector", "ロボットアームの先端に取り付けられ、実際に対象物に働きかける部分。グリッパーや溶接トーチ、吸着パッドなど作業内容に応じて交換される。", "名詞句", "They swapped the end effector from a two-finger gripper to a suction cup for handling flat glass panels.", "フィジカルAI", "850"),
    ("degrees of freedom", "ロボットの関節や機構が独立して動ける方向・軸の数。数値が多いほど複雑で柔軟な動作が可能になる一方、制御は難しくなる。", "名詞句", "The robotic hand has twenty degrees of freedom, giving it enough dexterity to manipulate small tools.", "フィジカルAI", "900"),
    ("inverse kinematics", "ロボットアームの先端を目標の位置・姿勢に到達させるために、各関節がとるべき角度を逆算して求める計算手法。", "名詞句", "The control software solves inverse kinematics in real time to keep the end effector on the desired path.", "フィジカルAI", "950"),
    ("motion planning", "ロボットが障害物を避けながら、現在の状態から目標の状態まで到達するための、実行可能な一連の動作・経路を計算すること。", "名詞句", "The motion planning algorithm generated a collision-free path for the arm to reach into the cluttered shelf.", "フィジカルAI", "900"),
    ("LiDAR", "レーザー光を対象物に照射し、反射して戻ってくるまでの時間から周囲の物体までの距離を計測し、立体的な点群データを得るセンサー技術。自動運転車やロボットの環境認識に広く使われる。", "名詞", "The self-driving car relies on LiDAR to build a precise 3D map of its surroundings in real time.", "フィジカルAI", "800"),
    ("SLAM", "「Simultaneous Localization and Mapping」の略で、ロボットが未知の環境において、自分の現在位置を推定しながら同時に周囲の地図を作成していく技術。", "名詞", "The vacuum robot uses SLAM to build a map of the apartment while keeping track of where it has already cleaned.", "フィジカルAI", "900"),
    ("odometry", "車輪の回転数やセンサーの変化量などから、ロボットや車両が移動した距離・方向を推定する技術。誤差が蓄積しやすいため、他のセンサー情報と組み合わせて補正されることが多い。", "名詞", "Wheel odometry alone drifted over time, so the team combined it with visual tracking for more accurate positioning.", "フィジカルAI", "900"),
    ("haptic feedback", "振動や抵抗力などを通じて、触覚的な感覚を人間の操作者やロボット自身にフィードバックする仕組み。遠隔操作の際に対象物への接触感を伝えるのに使われる。", "名詞句", "Haptic feedback in the controller let the remote operator feel how tightly the robot's gripper was squeezing the object.", "フィジカルAI", "900"),
    ("gripper", "ロボットアームの先端に取り付けられ、物をつかんだり挟んだりするための装置。指のような形状のものや、吸着式・磁力式などさまざまな種類がある。", "名詞", "They redesigned the gripper with softer fingertips so it could pick up fragile fruit without bruising it.", "フィジカルAI", "750"),
    ("exoskeleton", "人間の身体に装着し、関節の動きをモーターなどで補助・増幅する外骨格型の装置。作業現場でのリハビリ支援や重労働の負担軽減などに使われる。", "名詞", "Warehouse workers wore a powered exoskeleton to reduce strain when lifting heavy boxes repeatedly.", "フィジカルAI", "800"),
    ("swarm robotics", "個々には単純な機能しか持たない多数の小型ロボットを協調させ、群れ全体として複雑なタスクをこなさせる研究分野。アリや蜂などの群知能から着想を得ている。", "名詞句", "The swarm robotics demo showed dozens of small drones forming a coordinated shape without any central controller.", "フィジカルAI", "900"),
    ("cobot", "「collaborative robot」の略で、安全柵などで隔離せずに人間のすぐそばで一緒に作業できるよう設計された産業用ロボット。人との接触を検知して自動的に停止する機能などを備える。", "名詞", "A cobot on the assembly line hands parts directly to the human worker standing beside it.", "フィジカルAI", "800"),
    ("servo motor", "指令された角度や速度を正確に保つよう、内部のセンサーでフィードバック制御を行うモーター。ロボットの関節駆動など精密な位置制御が必要な場面で広く使われる。", "名詞句", "Each finger of the robotic hand is controlled by its own small servo motor.", "フィジカルAI", "800"),
    ("bipedal locomotion", "二本の脚を使って歩行・走行する移動様式。人間型ロボットにとって、バランスを保ちながら安定して二足歩行を実現することは特に難しい制御課題とされる。", "名詞句", "Achieving stable bipedal locomotion on uneven terrain took the team years of iteration on the balance controller.", "フィジカルAI", "900"),
    # --- 人工衛星 ---
    ("low Earth orbit (LEO)", "高度約2,000km以下を周回する軌道帯の総称。地表に近いため通信の遅延が短く、地球観測衛星や衛星コンステレーションの多くがこの軌道を利用する。", "名詞句", "Most Starlink satellites operate in low Earth orbit at an altitude of around 550 kilometers.", "人工衛星", "750"),
    ("medium Earth orbit (MEO)", "高度約2,000km〜35,786kmの間に位置する軌道帯。GPSやGLONASSなどの測位衛星が多く配置され、LEOより広い範囲をカバーしつつ静止軌道より低い遅延を実現する。", "名詞句", "GPS satellites are positioned in medium Earth orbit at an altitude of about 20,200 kilometers.", "人工衛星", "800"),
    ("geostationary orbit (GEO)", "赤道上空高度約35,786kmにあり、地球の自転と同じ周期で公転するため地上から見ると常に同じ位置に静止して見える軌道。通信衛星や気象衛星に広く利用される。", "名詞句", "Weather satellites in geostationary orbit continuously monitor the same region of the Earth's surface.", "人工衛星", "800"),
    ("sun-synchronous orbit (SSO)", "衛星が地表の同じ地点を常に同じ現地太陽時刻に通過するよう設計された極軌道に近い軌道。太陽光の当たり方が一定になるため、地球観測衛星やリモートセンシング衛星で多用される。", "名詞句", "The Earth-imaging satellite was launched into a sun-synchronous orbit to ensure consistent lighting conditions in its photos.", "人工衛星", "850"),
    ("Molniya orbit", "遠地点を北半球高緯度地域上空に持つ高楕円軌道。ロシアが高緯度地域との通信のために開発した軌道で、対象地域上空に長時間留まる特性を持つ。", "名詞句", "Russia has historically relied on satellites in a Molniya orbit to provide communications coverage over its northern regions.", "人工衛星", "900"),
    ("geostationary transfer orbit (GTO)", "静止軌道へ投入する前段階として用いられる、近地点が低く遠地点が静止軌道高度に達する楕円軌道。打ち上げ後、衛星はこの軌道上でエンジンを噴射して静止軌道へ移行する。", "名詞句", "The rocket released the communications satellite into a geostationary transfer orbit before its own onboard thrusters raised it further.", "人工衛星", "850"),
    ("orbital inclination", "衛星の軌道面が地球の赤道面に対してなす角度。0度なら赤道上空を周回し、90度に近いほど極軌道に近づく、衛星の設計目的によって選択される重要なパラメータ。", "名詞句", "Engineers chose a high orbital inclination so the satellite could image both polar regions.", "人工衛星", "800"),
    ("orbital period", "衛星が地球を一周するのに要する時間。軌道高度が高いほど周期は長くなり、静止軌道ではちょうど地球の自転周期である約24時間となる。", "名詞句", "A satellite in low Earth orbit typically has an orbital period of about 90 minutes.", "人工衛星", "750"),
    ("station-keeping", "大気抵抗や重力の摂動などによって生じる軌道のずれを、スラスタの噴射によって定期的に修正し、割り当てられた軌道位置を維持する運用作業。", "名詞", "The satellite performs station-keeping maneuvers every few weeks to stay within its assigned orbital slot.", "人工衛星", "850"),
    ("satellite constellation", "共通の目的のために複数機の衛星を協調させて運用する衛星群。互いに軌道位置を分担し合うことで、単独の衛星よりも広い範囲や高頻度の観測・通信を実現する。", "名詞句", "The company plans to deploy a satellite constellation of several thousand spacecraft to provide global broadband coverage.", "人工衛星", "750"),
    ("mega-constellation", "数百機から数万機規模という極めて多数の衛星で構成される衛星コンステレーション。低軌道からのブロードバンド通信サービスなどを目的に近年急速に増加している。", "名詞", "Astronomers have raised concerns that mega-constellations could interfere with ground-based telescope observations.", "人工衛星", "850"),
    ("inter-satellite link", "衛星同士が地上局を経由せずに直接データをやり取りする通信リンク。レーザー通信などを用いることで、地上局のカバー範囲外でも衛星間でデータを中継できる。", "名詞句", "Laser-based inter-satellite links allow the constellation to relay data between satellites without routing through a ground station.", "人工衛星", "900"),
    ("ground station", "衛星との間で電波を送受信し、指令やデータのやり取りを行う地上の施設。アンテナや追跡装置、通信機器などから構成される。", "名詞句", "The ground station tracked the satellite as it passed overhead and downloaded the latest telemetry.", "人工衛星", "700"),
    ("uplink", "地上局から衛星へ向けて送信される電波信号、またはその通信経路。指令データや音声・映像コンテンツの送信などに用いられる。", "名詞", "Controllers sent a new set of commands to the spacecraft via the uplink.", "人工衛星", "700"),
    ("downlink", "衛星から地上局へ向けて送信される電波信号、またはその通信経路。観測データやテレメトリ、放送コンテンツなどが地上へ伝送される際に用いられる。", "名詞", "The imaging satellite compresses its data before transmitting it over the downlink to reduce bandwidth requirements.", "人工衛星", "700"),
    ("TT&C (tracking, telemetry, and command)", "衛星の追跡・遠隔測定・指令を合わせた略語で、衛星の位置や状態を把握しコマンドを送るための一連の運用機能を指す。ほぼすべての衛星に搭載される基本的なサブシステム。", "名詞(略語)", "The satellite's TT&C subsystem allows operators to monitor its health and send commands from the ground.", "人工衛星", "900"),
    ("telemetry", "衛星の温度、電力残量、姿勢などの内部状態を計測し、地上へ自動的に送信されるデータ。運用者はこれを監視して衛星の健全性を判断する。", "名詞", "Engineers analyzed the telemetry data to diagnose why the solar panel had stopped deploying.", "人工衛星", "700"),
    ("ground track", "衛星が軌道を周回する際に、その真下にあたる地表の位置を結んでできる軌跡。地球の自転により、周回のたびに少しずつ異なる経路を描く。", "名詞句", "Because Earth rotates beneath it, the satellite's ground track shifts slightly westward with each orbit.", "人工衛星", "800"),
    ("GNSS (global navigation satellite system)", "GPS、GLONASS、Galileo、BeiDouなど、衛星を用いて地上や上空の受信機の位置・時刻を測定する測位システムの総称。特定の一システムを指さない包括的な呼称。", "名詞(略語)", "Modern smartphones combine signals from multiple GNSS systems to improve positioning accuracy.", "人工衛星", "800"),
    ("pseudorange", "GNSS受信機が測位衛星からの電波を受信するまでの時間から算出した、衛星と受信機の見かけ上の距離。受信機の時計誤差を含むため「疑似」距離と呼ばれる。", "名詞", "The receiver calculates a pseudorange to each visible satellite before solving for its own position.", "人工衛星", "900"),
    ("satellite dish", "衛星からの電波を受信、または衛星へ電波を送信するために用いられる放物面(パラボラ)形状のアンテナ。家庭用の衛星放送受信機から地上局の大型アンテナまで規模は様々。", "名詞句", "A small satellite dish on the roof allows the household to receive dozens of television channels.", "人工衛星", "600"),
    ("multipath error", "衛星からの電波が建物や地面などに反射してから受信機に届くことで生じる測位誤差。都市部でGPSの精度が低下する主な原因の一つ。", "名詞句", "Multipath error caused by reflections off nearby buildings can degrade GPS accuracy in dense urban areas.", "人工衛星", "850"),
    ("ephemeris data", "衛星の将来の軌道位置を予測するために必要な軌道要素のデータ。GNSS衛星は自身の予測軌道情報を放送し、受信機はこれを用いて測位計算を行う。", "名詞句", "The GPS receiver uses ephemeris data broadcast by each satellite to calculate its precise position in orbit.", "人工衛星", "900"),
    ("remote sensing satellite", "地表や大気を光学センサーやレーダーなどで観測し、直接触れることなくデータを収集する衛星。農業、防災、環境監視など幅広い分野で利用される。", "名詞句", "A remote sensing satellite captured images showing the extent of the flooding along the river basin.", "人工衛星", "750"),
    ("Earth observation satellite", "地球の地表・海洋・大気の状態を継続的に観測することを目的とした人工衛星の総称。気象、災害監視、都市開発の把握など多様な用途に使われる。", "名詞句", "Earth observation satellites provide daily imagery that helps track deforestation across the region.", "人工衛星", "750"),
    ("synthetic aperture radar (SAR)", "衛星の移動を利用して仮想的に大きなアンテナ開口を合成し、高い分解能を得るレーダー観測技術。雲や夜間でも地表を観測できる利点を持つ。", "名詞句", "Because it uses synthetic aperture radar, the satellite can image the ground even through thick cloud cover.", "人工衛星", "900"),
    ("multispectral imaging", "可視光だけでなく赤外線など複数の波長帯で同時に地表を撮影する観測手法。植生の健康状態や土地利用の分析などに用いられる。", "名詞句", "Multispectral imaging allows analysts to distinguish healthy crops from stressed vegetation that looks similar in visible light.", "人工衛星", "850"),
    ("ground resolution", "衛星画像において地表の1ピクセルが表す実際の距離。数値が小さいほど細部まで識別できる高解像度の画像となる。", "名詞句", "The new imaging satellite offers a ground resolution of about 30 centimeters per pixel.", "人工衛星", "800"),
    ("swath width", "衛星センサーが一度の観測パスで撮影できる地表の幅。広いほど短時間で広範囲をカバーできるが、一般に解像度とはトレードオフの関係にある。", "名詞句", "A wider swath width lets the satellite cover more ground per orbit, though often at lower resolution.", "人工衛星", "850"),
    ("satellite bus", "電源、姿勢制御、通信、熱制御など、ミッション内容によらず衛星に共通して必要な基盤システムの総称。この上にミッション固有のペイロードが搭載される。", "名詞句", "The company builds a standardized satellite bus that customers can equip with different payloads depending on their mission.", "人工衛星", "850"),
    ("payload", "衛星が本来の目的を果たすために搭載する観測機器や通信機器などの一式。バス部分とは区別され、ミッションの価値そのものを担う。", "名詞", "The satellite's payload consists of a high-resolution camera and a hyperspectral imaging sensor.", "人工衛星", "700"),
    ("transponder", "衛星が受信した信号を増幅・周波数変換して地上へ送り返す通信中継装置。1機の通信衛星には通常複数のトランスポンダが搭載され、それぞれが異なる周波数帯域を担当する。", "名詞", "The broadcaster leases a transponder on the communications satellite to relay its television signal across the continent.", "人工衛星", "800"),
    ("solar array", "太陽光を電力に変換する太陽電池パネルの集合体。衛星の主要な電源であり、多くは打ち上げ後に軌道上で展開される。", "名詞句", "After reaching orbit, the satellite unfolded its solar array to begin generating power.", "人工衛星", "700"),
    ("reaction wheel", "内部の円盤(ホイール)の回転速度を変化させることで、その反作用によって衛星の姿勢を推進剤を使わずに制御する装置。", "名詞句", "The satellite uses reaction wheels to precisely point its camera at targets on the ground without expending fuel.", "人工衛星", "850"),
    ("thermal control system", "衛星が真空中の極端な温度変化から機器を守るための放熱・保温機構の総称。多層断熱材やラジエーター、ヒーターなどを組み合わせて機器を適正な温度範囲に保つ。", "名詞句", "The thermal control system keeps sensitive electronics within their operating range despite the extreme temperature swings in orbit.", "人工衛星", "850"),
    ("CubeSat", "10cm立方を基本単位とする規格化された超小型衛星。安価で開発・打ち上げが可能なため、大学や新興企業による宇宙開発の裾野を広げた。", "名詞", "The university team built a CubeSat to test a new type of miniature propulsion system in orbit.", "人工衛星", "750"),
    ("small satellite (smallsat)", "質量がおおむね数百kg以下の小型衛星の総称。CubeSatより幅広い規模を含み、開発期間の短さやコストの低さから近年急速に普及している。", "名詞句", "The rise of small satellites has dramatically lowered the cost of building and operating a space mission.", "人工衛星", "750"),
    ("nanosatellite", "質量がおおむね1〜10kg程度の極小型衛星の分類。CubeSat規格の多くはこの区分に該当し、複数機同時打ち上げによる相乗り輸送とよく組み合わされる。", "名詞", "The nanosatellite weighed just four kilograms but carried a fully functional Earth-imaging payload.", "人工衛星", "850"),
    ("rideshare launch", "1回のロケット打ち上げに複数の異なる衛星を同時搭載し、打ち上げ費用を分担する方式。小型衛星が低コストで軌道に到達する主要な手段となっている。", "名詞句", "The small satellite reached orbit aboard a rideshare launch that carried dozens of other spacecraft.", "人工衛星", "800"),
    ("space debris", "運用を終えた衛星や打ち上げ時に分離したロケット部品、衝突の破片など、軌道上を漂う不要な人工物の総称。稼働中の衛星や有人宇宙船に衝突する危険がある。", "名詞句", "Tracking systems monitor space debris to warn satellite operators of potential collisions.", "人工衛星", "750"),
    ("collision avoidance maneuver", "衛星がスペースデブリや他の衛星との衝突を避けるために、あらかじめ軌道をわずかに変更する運用操作。", "名詞句", "Operators performed a collision avoidance maneuver after tracking data showed a debris fragment on a close approach.", "人工衛星", "850"),
    ("conjunction assessment", "衛星と他の物体(デブリや他衛星)が軌道上で異常接近する可能性を事前に評価する解析作業。衝突回避マニューバを実施するかどうかの判断材料となる。", "名詞句", "The operations team runs a conjunction assessment daily to check whether any nearby object poses a collision risk.", "人工衛星", "900"),
    ("Kessler syndrome", "軌道上の物体密度が高まりすぎることで衝突が連鎖的にデブリを増加させ、やがてその軌道帯が使用不能になるという理論上のシナリオ。天文学者ドナルド・ケスラーが提唱した。", "名詞句", "Experts warn that uncontrolled growth of mega-constellations could increase the risk of a Kessler syndrome scenario in low Earth orbit.", "人工衛星", "900"),
    ("payload fairing", "打ち上げ時に衛星を大気圏通過中の空力加熱や振動から保護する、ロケット先端部の覆い。大気圏を抜けた後に分離・投棄される。", "名詞句", "The payload fairing separated and fell away once the rocket had climbed above the dense lower atmosphere.", "人工衛星", "800"),
    ("deployment sequence", "衛星が軌道に投入された後、太陽電池パネルやアンテナなどの可動部を所定の手順で展開していく一連の運用ステップ。", "名詞句", "Mission control confirmed that the satellite had completed its deployment sequence, with both solar panels fully extended.", "人工衛星", "800"),
    ("footprint (satellite coverage)", "通信衛星や放送衛星の電波が地上に届く範囲。静止衛星の場合、この範囲内の地域であれば同じ衛星から放送・通信サービスを受けられる。", "名詞", "The satellite's footprint covers most of East Asia, allowing broadcasters across the region to use the same signal.", "人工衛星", "800"),
    ("geostationary slot", "静止軌道上でITU(国際電気通信連合)によって各国・事業者に割り当てられる、特定の経度に対応した衛星配置位置。数が限られた貴重な資源として扱われる。", "名詞句", "The company applied for a geostationary slot over the Pacific to provide broadcast services to the region.", "人工衛星", "900"),
    ("Ku-band", "周波数帯の一つで、おおむね12〜18GHzの範囲を指す。衛星放送や衛星インターネットなどの通信によく用いられる周波数帯域。", "名詞句", "The satellite broadcasts television signals in the Ku-band, which allows for relatively small receiving dishes.", "人工衛星", "850"),
    ("end-of-life (satellite)", "衛星の設計寿命が尽きた、あるいは燃料が枯渇したことにより運用を終了する段階。この際、軌道上に放置せず適切な処分を行うことが国際的に求められている。", "名詞句", "At end-of-life, the operator commanded the satellite to lower its orbit so it would re-enter the atmosphere within a few years.", "人工衛星", "800"),
    ("deorbit", "運用を終えた衛星の軌道を意図的に下げ、大気圏に再突入させて燃焼処分すること、またはその軌道変更操作を指す動詞・行為。", "動詞", "Engineers plan to deorbit the aging satellite next year to reduce the amount of debris in low Earth orbit.", "人工衛星", "750"),
    ("graveyard orbit", "静止軌道より少し高い高度に設定された、運用を終えた静止衛星を移動させて留めておくための軌道。混雑した静止軌道帯を将来にわたって使用可能に保つ目的がある。", "名詞句", "Before running out of fuel entirely, the satellite was boosted into a graveyard orbit above the geostationary belt.", "人工衛星", "900"),
    ("geomagnetic storm", "太陽風の乱れによって地球磁気圏が一時的に大きく乱される現象。衛星の電子機器の誤作動や、大気の膨張による低軌道衛星への抵抗増加を引き起こすことがある。", "名詞句", "A severe geomagnetic storm caused several newly launched satellites to lose altitude and re-enter the atmosphere prematurely.", "人工衛星", "850"),
    ("single-event upset", "宇宙空間の高エネルギー粒子が衛星の半導体素子に衝突し、データの一時的な誤り(ビット反転など)を引き起こす現象。恒久的な故障とは異なり、多くは再起動などで復旧できる。", "名詞句", "Radiation-hardened components are designed to minimize the risk of a single-event upset corrupting the satellite's onboard computer.", "人工衛星", "900"),
    ("ITU filing", "衛星の軌道位置や使用周波数について、国際電気通信連合(ITU)に対して行う登録申請。他国・他事業者との干渉を防ぐための国際的な調整手続きの第一歩となる。", "名詞句", "The operator submitted an ITU filing to secure the frequency rights needed for its planned satellite constellation.", "人工衛星", "900"),
    ("frequency coordination", "複数の衛星や地上システムが同じ周波数帯を利用する際に、互いの電波干渉を避けるために事業者間・国家間で行われる調整プロセス。", "名詞句", "Frequency coordination between neighboring satellite operators is essential to prevent signal interference in overlapping coverage areas.", "人工衛星", "900"),
    # --- 電池 ---
    ("voltaic pile", "亜鉛板と銅板を交互に重ね食塩水などの電解液を挟んで作る、世界初の実用電池。1800年にイタリアの物理学者アレッサンドロ・ボルタが発明し、後の電池技術の基礎を築いた。", "名詞句", "The voltaic pile, invented in 1800, was the first device capable of producing a steady electric current.", "電池", "800"),
    ("battery", "化学反応によって電気エネルギーを生み出し、電気機器に電力を供給する装置。一次電池と二次電池に大別される。", "名詞", "The remote control stopped working because the battery had run out.", "電池", "500"),
    ("primary cell", "放電すると化学反応が不可逆的に進み、充電して繰り返し使うことができない電池。乾電池やアルカリ電池が代表例である。", "名詞句", "A primary cell like a standard alkaline battery cannot be recharged once it is depleted.", "電池", "650"),
    ("secondary cell", "放電後に外部から電流を流すことで化学反応を逆転させ、繰り返し充電して使用できる電池。リチウムイオン電池や鉛蓄電池が該当し、rechargeable batteryとも呼ばれる。", "名詞句", "Smartphones rely on a secondary cell so users can recharge the battery every day instead of replacing it.", "電池", "600"),
    ("lead-acid battery", "鉛の電極と希硫酸の電解液を用いた古典的な二次電池。19世紀半ばに発明されて以来、安価で大電流を取り出しやすいことから自動車のスターターバッテリーなどに今も広く使われている。", "名詞句", "Most gasoline cars still use a lead-acid battery to start the engine and power the electrical system.", "電池", "700"),
    ("dry cell", "電解液を糊状やペースト状にして液漏れしにくくした一次電池。マンガン電池やアルカリ電池はこの方式に含まれる。", "名詞句", "A dry cell is convenient because it can be used in any orientation without leaking liquid.", "電池", "600"),
    ("manganese battery", "正極に二酸化マンガンを用いた乾電池の一種。安価だが電流を取り出す能力はアルカリ電池より劣り、時計やリモコンなど消費電力の少ない機器に向く。", "名詞句", "A manganese battery is cheaper than an alkaline one but drains faster in high-power devices.", "電池", "700"),
    ("alkaline battery", "電解液に水酸化カリウムなどのアルカリ性溶液を用いた乾電池。マンガン電池より容量が大きく大電流にも強いため、家庭用電池として広く普及している。", "名詞句", "Alkaline batteries generally last longer than manganese ones in devices like digital cameras.", "電池", "600"),
    ("nickel-metal hydride battery", "ニッケル酸化物を正極、水素吸蔵合金を負極に用いた二次電池。ニッケルカドミウム電池の後継として1990年代に普及し、初期のハイブリッド車にも採用された。", "名詞句", "Many early hybrid vehicles, including the first Toyota Prius, used a nickel-metal hydride battery pack.", "電池", "750"),
    ("lithium-ion battery", "リチウムイオンが正極と負極の間を移動することで充放電を行う二次電池。エネルギー密度が高く軽量なため、1991年の実用化以降スマートフォンや電気自動車の主力電源となった。", "名詞句", "Electric vehicles use a lithium-ion battery because it packs more energy into less weight than older technologies.", "電池", "600"),
    ("NMC battery", "正極材にニッケル・マンガン・コバルトの複合酸化物を用いたリチウムイオン電池の一方式。エネルギー密度が高く、航続距離を重視する電気自動車で採用されることが多い。", "名詞句", "NMC batteries offer higher energy density than LFP cells, giving EVs a longer driving range.", "電池", "800"),
    ("LFP battery", "正極材にリン酸鉄リチウムを用いたリチウムイオン電池の一方式。エネルギー密度はNMCよりやや低いが、熱暴走しにくく安全性が高いうえコバルトを使わず低コストなため近年急速に採用が拡大している。", "名詞句", "LFP batteries are gaining popularity in EVs because they are cheaper and less prone to thermal runaway.", "電池", "800"),
    ("solid-state battery", "液体の電解液の代わりに固体電解質を用いる次世代電池。発火しにくく安全性が高いうえエネルギー密度も向上できるとされ、実用化が期待されている。", "名詞句", "Several automakers have promised to bring a solid-state battery to market by the end of the decade.", "電池", "750"),
    ("semi-solid-state battery", "電解液を完全な固体にはせず、ゲル状などの半固体電解質を用いる過渡的な電池技術。全固体電池への橋渡しとして一部のEVメーカーがすでに量産を始めている。", "名詞句", "A semi-solid-state battery retains some liquid electrolyte, making it easier to mass-produce than a fully solid design.", "電池", "850"),
    ("battery management system", "電池パック内の各セルの電圧・温度・充電状態を監視し、過充電や過放電、セル間のばらつきを防ぐ制御システム。略称BMS。", "名詞句", "The battery management system shuts down charging automatically if any cell overheats.", "電池", "800"),
    ("C-rate", "電池の充放電速度を表す単位。1Cは電池の定格容量をちょうど1時間で充電または放電する電流の大きさを指し、数値が大きいほど急速な充放電を意味する。", "名詞句", "Charging at a 2C rate fills the battery in about half an hour but generates more heat.", "電池", "800"),
    ("energy density", "単位質量または単位体積あたりに蓄えられるエネルギー量。値が高いほど同じ重さ・大きさでより長く機器を動かせるため、電池性能の重要な指標となる。", "名詞句", "Lithium-ion cells have a much higher energy density than lead-acid batteries of the same weight.", "電池", "700"),
    ("power density", "単位質量または単位体積あたりに取り出せる出力の大きさ。エネルギー密度が「どれだけ長く」使えるかを示すのに対し、こちらは「どれだけ瞬間的に強い力」を出せるかを示す。", "名詞句", "Capacitors have a high power density, allowing them to release energy very quickly.", "電池", "750"),
    ("cycle life", "電池が実用的な容量を保ったまま繰り返し充放電できる回数の目安。この回数を超えると容量が大きく低下し、実用に耐えなくなる。", "名詞句", "This EV battery is rated for a cycle life of about 2,000 charge cycles before significant capacity loss.", "電池", "700"),
    ("thermal runaway", "電池内部の温度上昇が化学反応をさらに加速させ、発熱が連鎖的に増大していく現象。制御できないと発火や爆発につながる危険な状態である。", "名詞句", "A punctured lithium-ion cell can enter thermal runaway within seconds, releasing intense heat and smoke.", "電池", "800"),
    ("battery degradation", "充放電の繰り返しや経年劣化によって、電池の容量や出力性能が徐々に低下していく現象。", "名詞句", "Battery degradation is accelerated by frequent fast charging and exposure to extreme temperatures.", "電池", "700"),
    ("fast charging", "通常より大きな電流を流すことで、電池を短時間で充電する方式。利便性は高いが、発熱や劣化を早める要因にもなる。", "名詞句", "Fast charging can restore an EV battery from 10% to 80% in about 20 minutes.", "電池", "650"),
    ("anode", "電池が放電する際に酸化反応が起こり電子を放出する電極。リチウムイオン電池では一般に黒鉛が使われる。充電時と放電時で正極・負極の呼び方が変わる点に注意が必要な用語である。", "名詞", "In a lithium-ion battery, the anode is typically made of graphite that stores lithium ions during charging.", "電池", "700"),
    ("cathode", "電池が放電する際に還元反応が起こり電子を受け取る電極。リチウムイオン電池では正極材の種類(NMC・LFPなど)によって電池の特性が大きく変わる。", "名詞", "The choice of cathode material largely determines a lithium-ion battery's energy density and cost.", "電池", "700"),
    ("electrolyte", "電池内部でイオンを移動させ、正極と負極の間の電気化学反応を仲立ちする物質。液体・ゲル・固体などの形態があり、電池の性能や安全性を左右する。", "名詞", "The liquid electrolyte in a conventional lithium-ion battery is flammable, which is why solid-state designs are considered safer.", "電池", "650"),
    ("separator", "電池内部で正極と負極が直接接触して短絡するのを防ぎつつ、イオンだけを通す薄い多孔質の膜。", "名詞", "If the separator is damaged, the positive and negative electrodes can short-circuit and trigger a fire.", "電池", "750"),
    ("charge", "電池に外部から電流を流し込み、化学エネルギーとして電力を蓄える動作。名詞では「充電」や「電荷」の意味でも使われる。", "動詞", "Please charge your phone overnight so it's ready for tomorrow's trip.", "電池", "550"),
    ("discharge", "電池に蓄えたエネルギーを外部へ放出し、機器に電力を供給する動作。名詞としては「放電」を意味する。", "動詞", "The battery will slowly discharge even when the device is turned off.", "電池", "600"),
    ("button cell", "腕時計や電卓などに使われる、円盤状で薄く小型の一次電池または二次電池。形状がボタンに似ていることからこう呼ばれ、コインセルともいう。", "名詞句", "The watch stopped ticking because its button cell needed to be replaced.", "電池", "650"),
    ("single cell", "電池パックを構成する最小単位となる、単一の電気化学セル。複数の単セルを直列・並列に接続することで、必要な電圧や容量を持つ電池パックが作られる。", "名詞句", "An EV battery pack is made up of thousands of single cells connected in series and parallel.", "電池", "650"),
    ("state of charge", "電池に現在どれだけの電気量が残っているかを、満充電時を100%として百分率で表した指標。略称SOC。", "名詞句", "The dashboard shows the state of charge so the driver knows how much range remains.", "電池", "750"),
    ("state of health", "電池が新品時と比べてどれだけ性能を維持しているかを示す指標。容量や内部抵抗の変化から算出され、劣化の進み具合を把握するのに使われる。略称SOH。", "名詞句", "After three years of use, the battery's state of health had dropped to about 90%.", "電池", "800"),
    ("dendrite", "充放電の繰り返しによって電極表面に生じる、樹木の枝のような金属の微細な結晶構造。成長してセパレータを突き破ると内部短絡や発火の原因になる。", "名詞", "Lithium dendrite growth is one of the main safety challenges researchers are trying to solve in next-generation batteries.", "電池", "850"),
    ("capacity fade", "充放電サイクルを重ねるにつれて、電池が保持できる最大電気量が徐々に減少していく現象。", "名詞句", "Capacity fade is one reason why an older smartphone's battery doesn't last as long as it did when new.", "電池", "800"),
    ("trickle charge", "満充電に近づいた電池に対し、過充電を避けるためごく小さな電流でゆっくり充電を続ける方式。", "名詞句", "Once the battery is nearly full, the charger switches to a trickle charge to top it off safely.", "電池", "750"),
    ("self-discharge", "電池を使用していない状態でも、内部の化学反応により少しずつ蓄えた電気が失われていく現象。", "名詞句", "Nickel-metal hydride batteries used to suffer from high self-discharge, losing power even when sitting on a shelf.", "電池", "700"),
    ("deep discharge", "電池の残量をほぼゼロに近い状態まで使い切ること。電池の種類によっては電極の劣化を早めたり、二度と充電できなくなったりする原因となる。", "名詞句", "Repeated deep discharge can permanently reduce the capacity of a lead-acid battery.", "電池", "750"),
    ("voltage", "電気を押し出す力の大きさを表す量。電池の場合、正極と負極の間の電位差として表れ、単位はボルト(V)。", "名詞", "A standard AA battery has a voltage of about 1.5 volts.", "電池", "600"),
    # --- エネルギー ---
    ("solar photovoltaic", "半導体に光が当たると電子が動き出す光電効果を利用して、太陽光を直接電力に変換する発電方式。太陽光発電、略してソーラーPVとも呼ばれる。", "名詞句", "The company installed rooftop solar photovoltaic panels to cut its electricity costs.", "エネルギー", "650"),
    ("wind power", "風の運動エネルギーで風車の羽根を回し、発電機を回転させて電力を得る再生可能エネルギー。", "名詞句", "Denmark generates a large share of its electricity from wind power.", "エネルギー", "550"),
    ("offshore wind", "海上に風力発電設備を設置して行う発電方式。陸上より安定して強い風が得られる一方、建設や送電のコストは高くなる。", "名詞句", "The UK has become one of the world's largest markets for offshore wind farms.", "エネルギー", "700"),
    ("onshore wind", "陸上に風力発電設備を設置して行う発電方式。洋上風力に比べて建設・維持コストが低いが、景観や騒音への配慮が課題となることがある。", "名詞句", "Onshore wind remains the cheapest source of new electricity generation in many countries.", "エネルギー", "650"),
    ("hydrogen economy", "化石燃料の代わりに水素を主要なエネルギー媒体として、発電・輸送・産業などに広く利用する社会の構想。", "名詞句", "Japan has been an early advocate of building a hydrogen economy to reduce its reliance on imported fossil fuels.", "エネルギー", "750"),
    ("fuel cell", "水素と酸素を化学反応させて直接電気と水を生み出す発電装置。電池のように蓄電するのではなく、燃料を供給し続ける限り発電を継続できる点が特徴。", "名詞句", "A hydrogen fuel cell produces electricity by combining hydrogen and oxygen, emitting only water as a byproduct.", "エネルギー", "650"),
    ("green hydrogen", "太陽光や風力など再生可能エネルギーで発電した電気を使い、水を電気分解して製造する水素。製造過程で二酸化炭素を排出しないことが特徴。", "名詞句", "Green hydrogen is produced by splitting water using electricity from renewable sources like wind and solar.", "エネルギー", "700"),
    ("smart grid", "通信技術やセンサーを活用し、電力の需給を細かく把握・制御しながら効率的に電力を配分する次世代の送配電網。", "名詞句", "A smart grid can automatically balance electricity supply and demand across a wide network in real time.", "エネルギー", "650"),
    ("grid-scale storage", "送配電網全体の需給調整を目的として、発電所や変電所規模で大量の電力を貯蔵する設備。大型蓄電池や揚水発電などが用いられる。", "名詞句", "Grid-scale storage helps smooth out the fluctuations caused by intermittent solar and wind generation.", "エネルギー", "750"),
    ("pumped-storage hydro", "電力需要が少ない時間帯に余った電力で水を高い位置のダムへ汲み上げ、需要が多い時間帯にその水を落として発電する揚水式水力発電。事実上、大規模な蓄電手段として機能する。", "名詞句", "Pumped-storage hydro remains the world's largest form of grid energy storage by capacity.", "エネルギー", "800"),
    ("feed-in tariff", "再生可能エネルギーで発電した電力を、政府が定めた固定価格で一定期間買い取ることを電力会社に義務付ける制度。導入初期の再エネ普及を後押しする政策として各国で採用された。", "名詞句", "Germany's feed-in tariff scheme helped kickstart its solar power industry in the early 2000s.", "エネルギー", "800"),
    ("carbon capture", "発電所や工場の排出ガスなどから二酸化炭素を分離・回収し、地下に貯留したり他の用途に利用したりする技術。", "名詞句", "Some power plants are being fitted with carbon capture equipment to reduce their net emissions.", "エネルギー", "700"),
    ("geothermal energy", "地下深くにあるマグマの熱を利用して蒸気を作り、タービンを回して発電する再生可能エネルギー。天候に左右されず安定して発電できる利点がある。", "名詞句", "Iceland relies heavily on geothermal energy for both electricity generation and heating.", "エネルギー", "600"),
    ("energy transition", "化石燃料中心のエネルギー供給体系から、再生可能エネルギーなど低炭素な電源へと社会全体が移行していく過程。", "名詞句", "The country's energy transition plan calls for phasing out coal-fired power plants by 2035.", "エネルギー", "650"),
    ("decarbonization", "経済活動や社会全体から二酸化炭素の排出を減らし、最終的にゼロに近づけていく取り組み。", "名詞", "Decarbonization of the power sector is considered the fastest way to cut a country's overall emissions.", "エネルギー", "700"),
    ("curtailment", "送電網の容量不足や需要とのミスマッチにより、発電できるにもかかわらず太陽光や風力の出力を意図的に抑制すること。", "名詞", "On sunny, low-demand days, grid operators sometimes order the curtailment of solar output to prevent overloading the network.", "エネルギー", "850"),
    ("demand response", "電力需給が逼迫した際に、電力会社が需要家に節電を促したり、契約に基づき自動で機器を制御したりして需要側を調整する仕組み。", "名詞句", "Demand response programs pay factories to reduce electricity use during peak hours instead of building new power plants.", "エネルギー", "750"),
    ("microgrid", "特定の地域や施設内で発電・蓄電・消費を完結できる小規模な電力網。主要な送配電網から切り離して単独運転することもでき、災害時の非常用電源としても注目されている。", "名詞", "The hospital's microgrid kept critical equipment running during the region-wide blackout.", "エネルギー", "700"),
    ("power purchase agreement", "発電事業者と電力の買い手との間で、一定期間にわたり決められた価格・数量で電力を売買することを取り決める長期契約。再エネ発電所の資金調達を支える重要な仕組み。略称PPA。", "名詞句", "The tech company signed a 15-year power purchase agreement to buy electricity from a new solar farm.", "エネルギー", "800"),
    ("virtual power plant", "家庭用蓄電池や電気自動車、太陽光パネルなど分散した小規模な発電・蓄電設備をIT技術で束ね、あたかも一つの発電所のように制御・運用する仕組み。", "名詞句", "By aggregating thousands of home batteries, the utility created a virtual power plant that can supply power during peak demand.", "エネルギー", "850"),
    ("renewable energy", "太陽光・風力・水力・地熱など、自然界で絶えず補充され枯渇しないエネルギー源。", "名詞句", "The government set a target of generating 50% of electricity from renewable energy by 2030.", "エネルギー", "550"),
    ("carbon neutral", "人間の活動による二酸化炭素の排出量と、植林や技術による吸収・除去量が釣り合い、実質的な排出量がゼロになっている状態を表す。", "形容詞", "The company pledged to make its manufacturing operations carbon neutral within the next decade.", "エネルギー", "600"),
    ("net zero", "温室効果ガス全体の排出量から、吸収・除去された量を差し引いた合計がゼロになっている状態。カーボンニュートラルとほぼ同義で使われることが多い。", "名詞句", "Many countries have set a legally binding target to reach net zero emissions by 2050.", "エネルギー", "650"),
    ("intermittency", "太陽光や風力といった再生可能エネルギーの発電量が、天候や時間帯によって変動し安定しない性質。大規模導入にあたっての課題の一つとされる。", "名詞", "Battery storage is often proposed as a way to offset the intermittency of solar and wind power.", "エネルギー", "800"),
    ("capacity factor", "発電設備が理論上の最大出力で稼働し続けた場合に得られる電力量に対し、実際にどれだけの割合の電力を発電できたかを表す指標。", "名詞句", "Offshore wind farms typically have a higher capacity factor than onshore ones because winds at sea are stronger and steadier.", "エネルギー", "800"),
    ("levelized cost of electricity", "発電設備の建設費・運転維持費・燃料費などを耐用年数全体で平準化し、発電した電力1単位あたりのコストとして算出した指標。異なる発電方式のコストを比較する際によく用いられる。略称LCOE。", "名詞句", "The levelized cost of electricity from solar has fallen dramatically over the past decade, making it competitive with fossil fuels.", "エネルギー", "850"),
    ("baseload power", "一日を通じて常に必要とされる最低限の電力需要を、安定的に供給し続ける発電のこと。原子力や地熱、石炭火力などが担うことが多い。", "名詞句", "Nuclear power plants are often used to provide baseload power because they can run continuously at a steady output.", "エネルギー", "750"),
]

PHRASES_BY_SCENE: dict[str, list[tuple[str, str]]] = {
    "国際情勢を語る英語": [
        ("The two countries are locked in an escalating trade war that's rattling global markets.", "両国は貿易戦争をエスカレートさせており、世界の市場を揺るがしている。"),
        ("Analysts say the region has become a flashpoint that could drag in several major powers.", "アナリストらは、その地域が複数の大国を巻き込みかねない一触即発の火種になっていると指摘している。"),
        ("The sanctions regime has crippled the country's access to international financial markets.", "その制裁の枠組みによって、その国は国際金融市場へのアクセスをほぼ断たれている。"),
        ("Western governments moved quickly to freeze the assets of individuals tied to the regime.", "西側諸国政府は、その政権とつながりのある個人の資産凍結に迅速に動いた。"),
        ("Some economists worry that de-dollarization could gradually erode the dollar's dominance in global trade.", "一部のエコノミストは、脱ドル化が世界貿易におけるドルの優位性を徐々に蝕みかねないと懸念している。"),
        ("The coup caught most foreign observers by surprise, even though tensions had been building for months.", "数か月前から緊張が高まっていたとはいえ、そのクーデターは海外の観測筋の多くにとって不意打ちだった。"),
        ("Refugees fleeing the conflict have overwhelmed camps along the border.", "紛争から逃れてきた難民たちで、国境沿いの難民キャンプは収容能力を超えている。"),
        ("The government imposed tighter export controls on advanced chips to slow its rival's military modernization.", "政府はライバル国の軍事近代化を遅らせるため、先端半導体に対する輸出規制を強化した。"),
        ("Critics argue the crackdown on dissent shows the regime is becoming more authoritarian, not less.", "批判派は、反対意見への締め付けはその政権がより権威主義的になっていることの表れだと主張している。"),
        ("The alliance is under pressure to increase defense spending in response to a more assertive rival.", "その同盟は、より攻勢的になったライバル国に対応するため、防衛費を増やすよう圧力を受けている。"),
        ("Officials warned that any miscalculation along the border could trigger a dangerous escalation.", "当局者は、国境付近でのちょっとした誤算が危険な事態のエスカレートにつながりかねないと警告した。"),
        ("The ceasefire is fragile, and both sides have accused each other of violations.", "停戦は不安定な状態にあり、双方が相手側の違反を非難し合っている。"),
        ("Semiconductor supply chains have become a central battleground in great-power competition.", "半導体のサプライチェーンは、大国間競争の中心的な戦場になっている。"),
        ("The junta has promised elections, but few expect them to happen anytime soon.", "軍事政権は選挙の実施を約束しているが、近いうちに実現すると考えている人はほとんどいない。"),
        ("Disinformation spread rapidly on social media in the days before the vote.", "投票の数日前、SNS上で偽情報が急速に拡散した。"),
        ("The country's growing reliance on a single supplier for rare earths has become a strategic vulnerability.", "希土類元素の供給を単一の国に大きく依存していることが、その国にとって戦略上の弱点になりつつある。"),
        ("Many governments are pursuing friend-shoring to reduce their exposure to geopolitical shocks.", "多くの政府が、地政学的なショックへの脆弱性を減らすためフレンドショアリングを進めている。"),
        ("The opposition claims the election was rigged, while international observers have called for an independent investigation.", "野党側はその選挙が不正操作されたと主張しており、国際監視団は独立調査を求めている。"),
        ("The strait remains one of the world's most important chokepoints for oil shipments.", "その海峡は今も世界の石油輸送における最重要チョークポイントの一つであり続けている。"),
        ("Energy security has climbed to the top of the political agenda since prices spiked.", "価格が急騰して以来、エネルギー安全保障が政治的アジェンダの最優先事項に躍り出た。"),
        ("The two blocs are competing for influence across the developing world.", "両陣営は、発展途上国世界における影響力をめぐって競い合っている。"),
        ("A prolonged power vacuum after the president's ouster has left the country dangerously unstable.", "大統領失脚後の長引く権力の空白によって、その国は危険なほど不安定な状態に陥っている。"),
        ("Foreign investors have grown wary of the country's increasingly protectionist trade policies.", "海外投資家たちは、その国の保護主義的傾向を強める貿易政策に対して警戒を強めている。"),
        ("Military analysts describe the buildup as a classic case of deterrence rather than preparation for attack.", "軍事アナリストたちは、この増強を攻撃の準備というより典型的な抑止行動だと説明している。"),
        ("The insurgency has proven far more resilient than the government initially expected.", "その反乱勢力は、政府が当初想定していたよりもはるかにしぶとく持ちこたえている。"),
        ("Sanctions evasion through third countries has undermined the effectiveness of the embargo.", "第三国を経由した制裁逃れによって、その禁輸措置の実効性が損なわれている。"),
        ("The two nuclear-armed rivals have so far managed to avoid direct confrontation.", "核保有国であるその二つのライバル国は、これまでのところ直接対決を回避してきている。"),
        ("Migrant crossings have surged, straining the asylum system in neighboring countries.", "移民の越境が急増し、近隣諸国の庇護制度に大きな負担がかかっている。"),
        ("The rare earth export ban was widely seen as retaliation for the new tariffs.", "その希土類の輸出禁止措置は、新たな関税への報復措置だと広く受け止められた。"),
        ("Cyberattacks attributed to state-backed hackers have become a routine feature of modern geopolitical rivalry.", "国家の支援を受けたとされるハッカーによるサイバー攻撃は、現代の地政学的対立においてもはや日常的なものになっている。"),
        ("The government's crackdown on independent journalists drew sharp condemnation abroad.", "独立系ジャーナリストに対する政府の弾圧は、海外から厳しい非難を招いた。"),
        ("Some analysts believe the world is moving toward a more multipolar order, with power spread among several major players.", "一部のアナリストは、世界が複数の大国に力が分散したより多極的な秩序へと向かっていると考えている。"),
        ("The peacekeeping force was deployed to monitor the buffer zone between the two armies.", "その平和維持部隊は、両軍の間にある緩衝地帯を監視するために派遣された。"),
        ("Currency traders are bracing for volatility if the central bank abandons its dollar peg.", "為替トレーダーたちは、その中央銀行がドルペッグ制を放棄すれば為替が乱高下すると身構えている。"),
        ("The country's strongman leader has consolidated power by sidelining rivals within his own party.", "その国の強権的指導者は、自党内のライバルを排除することで権力を固めてきた。"),
    ],
    "インバウンド接客の英語": [
        ("Would you like to apply for tax-free shopping today?", "本日、免税でのお買い物をご希望ですか?"),
        ("You'll need to show your passport to complete the tax exemption.", "免税の手続きには、パスポートの提示が必要です。"),
        ("This bag must stay sealed until you leave Japan.", "この袋は日本を出国するまで開封しないでください。"),
        ("We accept credit cards, QR code payments, and cash.", "クレジットカード、QRコード決済、現金でのお支払いに対応しております。"),
        ("Sorry, we don't have a tipping culture here, so please keep your change.", "申し訳ありませんが、当店にチップの習慣はありませんので、お釣りはそのままお受け取りください。"),
        ("Please take off your shoes before stepping onto the tatami mats.", "畳の上に上がる前に靴を脱いでください。"),
        ("This is a quiet car, so please switch your phone to silent mode.", "こちらは静かな車両ですので、携帯電話をマナーモードに設定してください。"),
        ("The number of foreign visitors to this shrine has tripled in five years.", "この神社を訪れる外国人観光客の数は5年で3倍に増えました。"),
        ("Please bow slightly before passing through the torii gate.", "鳥居をくぐる前に軽くお辞儀をしてください。"),
        ("We're seeing a real backlash from residents about overtourism in this neighborhood.", "この地域ではオーバーツーリズムに対する住民の反発が実際に起きています。"),
        ("Local officials are debating whether to introduce an accommodation tax next year.", "来年、宿泊税を導入するかどうかについて地元当局が議論しています。"),
        ("Inbound consumption has become a major pillar of our local economy.", "訪日外国人による消費は、地域経済の大きな柱になっています。"),
        ("Could you point me toward the tax refund counter?", "免税カウンターはどちらでしょうか?"),
        ("This menu is marked to show which dishes are halal-friendly.", "このメニューには、ハラール対応の料理が分かるように印がついています。"),
        ("We added multilingual signage throughout the station last spring.", "昨年の春、駅構内に多言語案内表示を追加しました。"),
        ("Please don't take photos of the geisha without asking first.", "芸者の写真を撮る前に、必ず声をかけて許可を得てください。"),
        ("We set up a designated photo spot so visitors stop blocking the entrance.", "参拝者が入り口をふさがないよう、専用の撮影スポットを設けました。"),
        ("Garbage here is sorted into burnable, non-burnable, and recyclables.", "こちらのごみは、可燃ごみ・不燃ごみ・資源ごみに分別されます。"),
        ("Our staff go through cultural sensitivity training every spring.", "当社のスタッフは毎年春に異文化理解の研修を受けています。"),
        ("The inn just installed a prayer room for Muslim guests.", "その旅館は最近、ムスリムの宿泊客のために礼拝室を設置しました。"),
        ("Many hotels are struggling to keep up with demand during peak season.", "多くのホテルが繁忙期の需要に対応しきれずにいます。"),
        ("There's a peak season surcharge added to the room rate in August.", "8月は宿泊料金にピークシーズン料金が加算されます。"),
        ("The destination marketing organization is running ads overseas to attract more visitors.", "その観光局は、より多くの旅行者を呼び込むため海外向けの広告を展開しています。"),
        ("We hired a licensed guide interpreter for the executives' tour.", "幹部の視察ツアーのために通訳案内士を雇いました。"),
        ("Independent travelers now outnumber group tours at most of our sites.", "現在、ほとんどの観光地で個人旅行者が団体旅行者の数を上回っています。"),
        ("Per-visitor spending has risen even as the total number of tourists leveled off.", "観光客の総数が横ばいになる一方で、一人当たりの消費額は上昇しています。"),
        ("The town is trying to protect its carrying capacity by limiting daily visitors.", "その町は一日あたりの訪問者数を制限することで、受け入れ能力を守ろうとしています。"),
        ("We explained the etiquette of removing your shoes before we even got inside.", "中に入る前に、靴を脱ぐマナーについて説明しておきました。"),
        ("Cashless payment is now accepted at almost every souvenir shop in the arcade.", "商店街のほぼすべての土産物店で、キャッシュレス決済が利用できるようになりました。"),
        ("The area is famous for its omotenashi, where staff anticipate your needs before you ask.", "この地域は、頼む前にスタッフが必要なことを察してくれる、おもてなしの文化で有名です。"),
        ("Please queue on the left side of the escalator, as is customary here.", "こちらの習慣に従い、エスカレーターの左側にお並びください。"),
        ("Littering near the shrine can result in a fine.", "神社周辺でごみを捨てると罰金が科されることがあります。"),
        ("We're rolling out a tourist etiquette guide in six languages this fall.", "この秋、6か国語対応の観光マナーガイドを配布する予定です。"),
        ("Foreign independent travelers tend to spend more time exploring local neighborhoods.", "個人で旅行する外国人観光客は、地元の街を探索する時間が長い傾向にあります。"),
        ("The economic ripple effect of inbound tourism reaches even small family farms.", "訪日観光の経済波及効果は、小さな家族経営の農家にまで及んでいます。"),
    ],
    "AI開発現場の英語": [
        ("We're seeing a lot of hallucinations whenever the model is asked about events after its knowledge cutoff.", "モデルは知識のカットオフ以降の出来事について聞かれると、かなりの頻度でハルシネーションを起こしています。"),
        ("Let's add retrieval-augmented generation so the assistant can pull answers from our latest documentation instead of guessing.", "アシスタントが当てずっぽうで答えるのではなく、最新のドキュメントから回答を引っ張ってこられるように、検索拡張生成(RAG)を導入しましょう。"),
        ("The context window fills up fast in long conversations, so we need a summarization step.", "長い会話だとコンテキストウィンドウがすぐ埋まってしまうので、要約するステップが必要です。"),
        ("Can you fine-tune the base model on our support tickets before the next demo?", "次のデモまでに、サポートチケットのデータでベースモデルをファインチューニングしておいてもらえますか。"),
        ("We caught someone trying a prompt injection through a PDF upload during red teaming.", "レッドチーミングの最中に、PDFのアップロードを使ったプロンプトインジェクションを試みる人がいるのを見つけました。"),
        ("If we quantize the model to 8-bit, we can run it on the edge device without a noticeable accuracy drop.", "モデルを8ビットに量子化すれば、精度をほとんど落とさずにエッジデバイス上で動かせます。"),
        ("Before we deploy any new guardrail, we run it through the full red teaming checklist.", "新しいガードレールを導入する前には、必ずレッドチーミングのチェックリストを一通り実行します。"),
        ("The mixture-of-experts architecture let us scale up the model without a proportional increase in inference cost.", "Mixture of expertsアーキテクチャのおかげで、推論コストを比例的に増やさずにモデルを大規模化できました。"),
        ("We noticed some sycophancy in the model's answers — it just agrees with whatever the user says.", "モデルの回答に迎合的な傾向が見られます。ユーザーの言うことにただ同調しているだけなんです。"),
        ("The model's embeddings put 'bank' the financial institution and 'bank' the riverbank surprisingly close together.", "このモデルのembeddingでは、金融機関の「bank」と川岸の「bank」が意外と近い位置に配置されています。"),
        ("We're building a multi-agent system where one agent plans the task and another executes it step by step.", "一方のエージェントがタスクを計画し、もう一方が段階的に実行する、マルチエージェントシステムを構築しています。"),
        ("We added a system prompt that explicitly forbids the assistant from giving legal advice.", "アシスタントが法律的な助言を行わないよう、明示的に禁止するシステムプロンプトを追加しました。"),
        ("Emergent abilities like this kind of multi-step reasoning only showed up once we scaled past a certain model size.", "こうした多段階の推論のような創発的能力は、モデルのサイズがある一定の規模を超えて初めて現れました。"),
        ("We're running low on real-world training examples, so we generated synthetic data to fill the gap.", "実世界の学習データが不足してきたので、それを補うために合成データを生成しました。"),
    ],
    "ロボット・フィジカルAI開発現場の英語": [
        ("The robot's gripper keeps slipping on smooth surfaces — I think we need better dexterous manipulation at the fingertips.", "ロボットのグリッパーがつるつるした面で滑ってしまうんです。指先でもっと器用な操作ができるようにする必要があると思います。"),
        ("We trained the walking policy in simulation for weeks, but sim-to-real transfer is still rough on real gravel.", "歩行方策をシミュレーション上で何週間も学習させましたが、実際の砂利道でのsim-to-real transferはまだうまくいっていません。"),
        ("Sensor fusion between the LiDAR and the cameras cut down our false obstacle detections significantly.", "LiDARとカメラのセンサーフュージョンによって、誤った障害物検知がかなり減りました。"),
        ("The humanoid lost its balance on the ramp — let's check whether the proprioception readings were lagging.", "ヒューマノイドがスロープでバランスを崩しました。プロプリオセプション(自己受容感覚)の読み取りに遅延がなかったか確認しましょう。"),
        ("Let's use teleoperation to collect demonstration data until the autonomous policy is reliable enough.", "自律方策が十分信頼できるようになるまでは、遠隔操作(テレオペレーション)でデモンストレーションデータを集めましょう。"),
        ("The end effector needs to be swapped out depending on whether we're picking boxes or handling cables.", "箱を持ち上げるのかケーブルを扱うのかによって、エンドエフェクタを交換する必要があります。"),
        ("Our digital twin of the warehouse lets us test new robot routes before touching the physical floor.", "倉庫のデジタルツインがあるおかげで、実際の現場を変更する前に新しいロボットの経路をテストできます。"),
        ("The inverse kinematics solver occasionally returns an unreachable pose — we need to add joint limit checks.", "逆運動学のソルバーが時々到達不可能な姿勢を返してくるので、関節の可動域チェックを追加する必要があります。"),
        ("Swarm robotics could let dozens of small robots cover the field faster than one large machine.", "群ロボティクス(スワームロボティクス)を使えば、大型機械一台よりも小型ロボット数十台の方が畑を速くカバーできるかもしれません。"),
        ("The cobot on line three stopped automatically the moment the technician's hand entered its workspace.", "3番ラインのコボットは、作業員の手が作業範囲に入った瞬間に自動的に停止しました。"),
        ("Odometry alone drifted too much over long runs, so we're fusing it with visual tracking for the delivery robot.", "オドメトリだけでは長時間の走行でずれが大きくなりすぎるので、配送ロボットには視覚追跡と組み合わせています。"),
    ],
    "人工衛星を語る英語": [
        ("Our satellite constellation now provides continuous coverage even at high latitudes.", "私たちの衛星コンステレーションは、高緯度地域でも途切れることのないカバレッジを提供できるようになりました。"),
        ("The rocket successfully deployed all sixty satellites into low Earth orbit.", "ロケットは60機の衛星すべてを低軌道へ無事に投入しました。"),
        ("We lost contact with the ground station during the storm, but telemetry resumed an hour later.", "嵐の間、地上局との交信が途絶えましたが、1時間後にはテレメトリが再開しました。"),
        ("GPS accuracy can drop to several meters in dense urban canyons due to multipath error.", "都市部の高層ビルに囲まれた場所では、マルチパス誤差のせいでGPSの精度が数メートルまで低下することがあります。"),
        ("The satellite is scheduled to perform a collision avoidance maneuver later tonight.", "その衛星は今夜遅くに衝突回避マニューバを実施する予定です。"),
        ("Space debris tracking has become a critical part of satellite operations as orbits get more crowded.", "軌道が混雑するにつれ、スペースデブリの追跡は衛星運用において欠かせない業務になっています。"),
        ("Once the payload fairing separated, we could finally see the satellite on the live feed.", "フェアリングが分離すると、ようやくライブ映像で衛星の姿を見ることができました。"),
        ("This CubeSat was built entirely by undergraduate students in less than two years.", "このキューブサットは、学部生だけの手によって2年足らずで完成させたものです。"),
        ("The imaging satellite can revisit the same location every three days thanks to its sun-synchronous orbit.", "この観測衛星は太陽同期軌道のおかげで、同じ地点を3日おきに再撮影できます。"),
        ("A single geostationary satellite can cover roughly a third of the Earth's surface.", "静止衛星は1機だけで、地球表面のおよそ3分の1をカバーできます。"),
        ("We're still waiting for ITU approval on the frequency filing before we can launch.", "打ち上げ前に、周波数申請に対するITUの承認をまだ待っている状況です。"),
        ("The satellite's reaction wheels saturated, so it briefly lost fine pointing control.", "衛星のリアクションホイールが飽和状態になり、精密な指向制御を一時的に失いました。"),
        ("After ten years of service, the satellite will be moved into a graveyard orbit next month.", "10年間の運用を終え、この衛星は来月、墓場軌道へ移動させられる予定です。"),
        ("Downlink bandwidth is the bottleneck now that our sensors capture so much more data than before.", "センサーが以前よりはるかに多くのデータを取得するようになった今、ダウンリンクの帯域幅がボトルネックになっています。"),
        ("Amateur satellite trackers spotted the new constellation shell just days after launch.", "打ち上げからわずか数日で、アマチュアの衛星観測者たちが新しいコンステレーションのシェルを発見しました。"),
        ("The mega-constellation's inter-satellite links let data hop between satellites without ever touching a ground station.", "このメガコンステレーションの衛星間リンクによって、データは地上局を経由せずに衛星から衛星へと中継されます。"),
        ("Engineers are worried that a severe geomagnetic storm could drag several satellites out of orbit.", "技術者たちは、強い磁気嵐が数機の衛星を軌道から引きずり落としかねないと懸念しています。"),
        ("The satellite's solar array failed to deploy fully, cutting available power by nearly half.", "衛星の太陽電池パネルが完全には展開せず、利用可能な電力がほぼ半分に減ってしまいました。"),
        ("This transponder is leased exclusively to a broadcaster covering the entire footprint over Southeast Asia.", "このトランスポンダは、東南アジア全域をフットプリントとしてカバーする放送事業者に独占的にリースされています。"),
        ("We had to redesign the thermal control system after the first prototype overheated during eclipse season.", "最初の試作機が食(しょく)の時期に過熱してしまったため、熱制御システムを再設計せざるを得ませんでした。"),
        ("The new SAR satellite can image the same flood zone at night or through heavy cloud cover.", "この新しいSAR衛星は、夜間でも厚い雲を通しても同じ洪水被害地域を撮影できます。"),
        ("A single-event upset flipped a bit in the onboard computer, but the watchdog timer reset it automatically.", "シングルイベントアップセットによって搭載コンピュータのビットが反転しましたが、ウォッチドッグタイマーが自動的にリセットしてくれました。"),
        ("Rideshare launches have made it possible for a small startup to put a satellite in orbit for a fraction of the old cost.", "ライドシェア打ち上げのおかげで、小さなスタートアップでも従来よりはるかに低いコストで衛星を軌道に投入できるようになりました。"),
        ("The satellite operator filed a conjunction assessment alert after debris came within two kilometers of one of its spacecraft.", "デブリが自社の衛星の2キロメートル以内まで接近したため、衛星運用会社はコンジャンクションアセスメントの警報を発しました。"),
        ("Our ground station tracks the satellite for about eight minutes each pass before it drops below the horizon.", "私たちの地上局は、衛星が地平線の下に沈むまでの約8分間、パスごとにそれを追尾します。"),
        ("At end-of-life, most operators are now required to deorbit their satellites within twenty-five years.", "運用終了時には、現在ほとんどの事業者が25年以内に衛星をデオービットさせることを求められています。"),
        ("GNSS receivers combine ephemeris data from at least four satellites to compute a precise position.", "GNSS受信機は、少なくとも4機の衛星から得たエフェメリスデータを組み合わせて正確な位置を算出します。"),
        ("The nanosatellite's swath width is narrower than a large observation satellite, but its images are surprisingly sharp.", "このナノサットのスワス幅は大型観測衛星より狭いものの、画像の精細さは驚くほどです。"),
        ("Every geostationary slot over the busiest orbital arcs is already claimed by an operator or under negotiation.", "混雑する軌道弧上の静止衛星スロットは、すでにどこかの事業者に割り当てられているか、交渉が進められています。"),
        ("Once station-keeping fuel runs low, operators have to decide whether to extend the mission or retire the satellite.", "ステーションキーピング用の燃料が少なくなると、運用者はミッションを延長するか衛星を退役させるかを判断しなければなりません。"),
    ],
    "電池技術を語る英語": [
        ("EVs use lithium-ion batteries because they offer a much better energy-to-weight ratio than older chemistries.", "電気自動車がリチウムイオン電池を使うのは、旧来の電池方式よりもはるかに優れた重量あたりのエネルギー量を持っているからです。"),
        ("The battery has degraded to about 85% of its original capacity after five years of daily fast charging.", "5年間毎日急速充電を続けた結果、その電池は元の容量の約85%まで劣化しています。"),
        ("If a solid-state battery ever reaches mass production, it could dramatically shorten EV charging times.", "もし全固体電池が量産段階に達すれば、電気自動車の充電時間を劇的に短縮できるかもしれません。"),
        ("Some engineers doubt solid-state batteries will be commercially viable before the early 2030s.", "一部のエンジニアは、全固体電池が商業的に実用化されるのは2030年代前半より前にはならないだろうと懐疑的です。"),
        ("LFP batteries are less energy-dense than NMC, but they're safer and don't rely on cobalt.", "LFP電池はNMC電池よりエネルギー密度は低いものの、より安全でコバルトに依存しません。"),
        ("Never let a lithium-ion battery sit fully discharged for a long time, or it may never charge again.", "リチウムイオン電池を完全放電した状態で長時間放置してはいけません。二度と充電できなくなることがあります。"),
        ("The battery management system cut off charging the moment it detected an abnormal temperature rise.", "バッテリーマネジメントシステムは異常な温度上昇を検知した瞬間に充電を遮断しました。"),
        ("A punctured cell can trigger thermal runaway within seconds, so battery packs need robust physical protection.", "損傷したセルは数秒で熱暴走を引き起こすことがあるため、電池パックには頑丈な物理的保護が必要です。"),
        ("Charging at a high C-rate generates more heat and accelerates long-term capacity fade.", "高いC-rateで充電すると発熱が増え、長期的な容量低下を早めてしまいます。"),
        ("The voltaic pile Volta built in 1800 was crude, but it proved that a continuous electric current was possible.", "ボルタが1800年に作ったボルタ電堆は原始的なものでしたが、連続した電流を得られることを初めて証明しました。"),
        ("Dendrite growth on the anode is one of the biggest safety hurdles researchers face with next-generation batteries.", "負極上でのデンドライトの成長は、次世代電池の開発において研究者が直面する最大の安全上の課題の一つです。"),
        ("We keep the state of charge between 20% and 80% to extend the pack's cycle life.", "電池パックのサイクル寿命を延ばすため、充電状態を20%から80%の間に保つようにしています。"),
        ("A lead-acid battery is heavier and less efficient than lithium-ion, but it's still cheap and reliable for starting engines.", "鉛蓄電池はリチウムイオン電池より重く効率も劣りますが、エンジン始動用としては今なお安価で信頼性が高いです。"),
        ("Most household button cells are either alkaline or lithium primary cells, so don't try to recharge them.", "家庭用のボタン電池のほとんどはアルカリまたはリチウムの一次電池なので、充電しようとしてはいけません。"),
        ("Self-discharge in nickel-metal hydride batteries used to be so bad that a fully charged pack could go flat in a few weeks.", "かつてのニッケル水素電池は自己放電がひどく、満充電しても数週間で空になってしまうことがありました。"),
        ("The separator failed, causing an internal short circuit that started the fire.", "セパレータが破損して内部短絡が起き、それが出火の原因になりました。"),
        ("Battery recyclers are getting better at recovering lithium, cobalt, and nickel from old EV packs.", "電池リサイクル業者は、廃棄されたEV用電池パックからリチウムやコバルト、ニッケルを回収する技術を向上させています。"),
    ],
    "エネルギー技術を語る英語": [
        ("The country plans to phase out coal and cover most of its electricity needs with wind and solar by 2040.", "その国は石炭火力を段階的に廃止し、2040年までに電力需要の大半を風力と太陽光で賄う計画です。"),
        ("Offshore wind has a higher capacity factor than onshore wind because sea winds blow more steadily.", "洋上風力は海上の風がより安定して吹くため、陸上風力より稼働率(キャパシティファクター)が高くなります。"),
        ("Without enough grid-scale storage, a power system with lots of solar and wind can struggle to balance supply and demand.", "大規模な蓄電設備が十分でなければ、太陽光や風力の比率が高い電力システムは需給のバランスを保つのに苦労します。"),
        ("Green hydrogen could decarbonize industries like steelmaking that are hard to electrify directly.", "グリーン水素は、直接電化するのが難しい製鉄業のような産業の脱炭素化に役立つ可能性があります。"),
        ("The feed-in tariff guaranteed a fixed price for solar power, which is what convinced many homeowners to install panels.", "固定価格買取制度によって太陽光発電の価格が保証されたことが、多くの住宅所有者がパネルを設置する決め手になりました。"),
        ("Curtailment has increased in this region because the transmission lines can't carry all the solar power generated at midday.", "この地域では出力抑制が増えていますが、それは送電線が真昼に発電される太陽光の全量を送りきれないためです。"),
        ("Utilities use demand response programs to shave peak load instead of building expensive new power plants.", "電力会社は高額な新規発電所を建設する代わりに、デマンドレスポンスの仕組みでピーク需要を削減しています。"),
        ("A microgrid let the university keep its labs running even after the main grid went down in the storm.", "マイクログリッドのおかげで、嵐で主要な送電網が停止した後も大学の研究室は稼働を続けられました。"),
        ("The levelized cost of electricity from utility-scale solar has dropped below that of new coal plants in most markets.", "ユーティリティ規模の太陽光発電の均等化発電原価は、多くの市場で新設の石炭火力発電所を下回るまでに下がりました。"),
        ("Pumped-storage hydro still accounts for the vast majority of the world's grid energy storage capacity.", "揚水式水力発電は今なお、世界の系統用蓄電容量の大部分を占めています。"),
        ("Some analysts argue that a truly reliable grid needs baseload power, not just intermittent renewables.", "アナリストの中には、本当に信頼できる電力網には間欠的な再生可能エネルギーだけでなくベースロード電源が必要だと主張する人もいます。"),
        ("Signing a long-term power purchase agreement gave the developer enough certainty to secure financing for the wind farm.", "長期の電力購入契約を結んだことで、開発事業者はその風力発電所の資金調達に必要な確実性を得ることができました。"),
        ("Aggregating thousands of home batteries into a virtual power plant lets a utility respond to demand spikes almost instantly.", "何千もの家庭用蓄電池を束ねて仮想発電所を構成することで、電力会社は需要急増にほぼ瞬時に対応できるようになります。"),
    ],
}


def main() -> int:
    with db() as conn:
        w_existing = {
            r["english"].lower()
            for r in conn.execute("SELECT english FROM words").fetchall()
        }
        w_added = w_skipped = 0
        for en, ja, pos, ex, domain, level in WORDS:
            if en.lower() in w_existing:
                w_skipped += 1
                continue
            conn.execute(
                "INSERT INTO words (english, japanese, part_of_speech, "
                "example, domain, level) VALUES (?, ?, ?, ?, ?, ?)",
                (en, ja, pos, ex, domain, level),
            )
            w_existing.add(en.lower())
            w_added += 1

        ph_existing = {
            r["english"].lower()
            for r in conn.execute("SELECT english FROM phrases").fetchall()
        }
        ph_added = ph_skipped = 0
        for scene, items in PHRASES_BY_SCENE.items():
            for en, ja in items:
                if en.lower() in ph_existing:
                    ph_skipped += 1
                    continue
                conn.execute(
                    "INSERT INTO phrases (english, japanese, scene) "
                    "VALUES (?, ?, ?)",
                    (en, ja, scene),
                )
                ph_existing.add(en.lower())
                ph_added += 1

    print(f"words:   +{w_added} (skipped {w_skipped})")
    print(f"phrases: +{ph_added} (skipped {ph_skipped})")
    with db() as conn:
        print("totals -> words:",
              conn.execute("SELECT COUNT(*) FROM words").fetchone()[0],
              "phrases:",
              conn.execute("SELECT COUNT(*) FROM phrases").fetchone()[0])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
