# ruff: noqa: E501
"""知的財産（デザイン）・知的財産（商標）新設(2026-09-09・authored by Claude)。ユーザー指摘「知的財産（デザイン）を忘れていました」を受け、既存の知的財産4分野(一般/著作権/特許/米国)に続く5・6番目のIPドメインとして追加。既存4分野との重複回避を各エージェントに指示済み。

No app / OpenAI API calls — hand-written、inserted directly into SQLite.
Duplicates skipped by english (lowercased) against the full live `words` table.

Run:  python scripts/add_ip_design_trademark_2026_09_09.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.database import db  # noqa: E402

WORDS: list[tuple[str, str, str, str, str, str]] = [
    ("registered design", "意匠を所轄の特許庁・知的財産庁等の登録簿に出願し、審査を経て登録することによって発生する意匠権、またはその登録された意匠自体を指す語。登録前の審査の厳格さ(新規性等を実体的に審査するか、方式面のみを審査するかなど)は国・地域によって異なる。登録意匠。", "名詞句", "Once granted, a registered design gives its owner the exclusive right to stop others from making, offering, or selling products with the same overall appearance.", "知的財産（デザイン）", "720"),
    ("unregistered design right", "意匠を特許庁等に出願・登録しなくても、一定の要件を満たせば法律上当然に発生する意匠関連の権利の総称。代表例は英国の意匠権(design right、CDPA1988第3部)で、物品の形状・輪郭(shape or configuration)のみを保護対象とし、表面の模様・装飾は対象外である点で登録意匠と異なる。存続期間は、意匠が最初に記録・製作された年の年末から15年、または物品が最初に販売・貸与された年の年末から10年のいずれか早い方までとされ、末期5年間は第三者からの実施許諾請求に応じる義務(license of right)を負う。無登録意匠権。", "名詞句", "Because UK unregistered design right protects only shape and configuration, a manufacturer who copies just the surface pattern of a rival's product may not infringe it.", "知的財産（デザイン）", "800"),
    ("design registration", "意匠権を取得するために、特許庁等の官庁に出願し、所定の手続を経て登録簿に記載してもらう一連の行政手続。権利それ自体を指す registered design と異なり、この語は「登録するという行為・制度」の側面に焦点を当てる。意匠登録。", "名詞", "Design registration in the EU is largely a formal process: the office checks the paperwork but does not substantively examine novelty or individual character before granting the right.", "知的財産（デザイン）", "730"),
    ("design novelty", "登録意匠が保護を受けるための要件の一つで、その意匠が出願(または優先権主張)前に、国内外を問わず既に公衆に利用可能となっていた先行意匠(prior design)と同一でないこと、または細部にのみ相違し実質的に同一と評価される意匠が存在しないことを指す。特許の新規性(novelty)が発明の技術内容の同一性を問うのに対し、意匠の新規性は意匠(外観)同士の視覚的な同一性を問う点で判断の対象と手法が異なる。意匠の新規性。", "名詞句", "A design fails the novelty requirement if an identical design, or one differing only in immaterial details, was disclosed anywhere in the world before the filing date.", "知的財産（デザイン）", "800"),
    ("individual character", "登録意匠が保護を受けるための要件の一つで、その意匠が既存の意匠(先行意匠)と比較して、知識のあるユーザー(informed user)に異なる全体的印象(overall impression)を与えることを指す。EU意匠法(共同体意匠規則第6条)に特有の概念で、新規性(design novelty)とは別の独立した要件として審査される。個性。", "名詞句", "For a design to be registered in the EU, it must have both novelty and individual character compared to earlier designs.", "知的財産（デザイン）", "830"),
    ("informed user", "EU意匠法において、登録意匠の新規性・個性、および侵害の有無を判断する際の基準となる仮想の人物像。対象製品を本来の目的で実際に使用する者であり、当該分野に既に存在する意匠の蓄積(先行意匠)についてある程度の認識を持つが、専門の設計者やその分野の当業者(person skilled in the art)ほどの専門知識は持たないとされる、商標法上の平均的消費者(average consumer)と特許法上の当業者との中間に位置づけられる基準人。知識のあるユーザー。", "名詞句", "The informed user is more attentive to design details than an average consumer, but less expert than the designer who actually created the product.", "知的財産（デザイン）", "810"),
    ("overall impression", "登録意匠の新規性・個性の判断や侵害訴訟において、二つの意匠を個々の特徴ごとに分解して比較するのではなく、知識のあるユーザー(informed user)の目から見て、それぞれの意匠が全体として与える視覚的な印象を比較するという判断手法。全体的印象。", "名詞句", "Even if two designs share several individual features, they will not infringe each other's rights as long as they create a different overall impression on an informed user.", "知的財産（デザイン）", "800"),
    ("degree of freedom", "EU意匠法(共同体意匠規則第6条2項)において、個性(individual character)の有無を判断する際に考慮される要素の一つで、当該製品の意匠を創作するにあたって設計者がどの程度自由に形状等を選択できたかを指す。製品の技術的機能や法令上の要求によって設計の自由度が強く制約されている分野では、意匠間のわずかな相違でも異なる全体的印象を生じさせやすいと評価され、逆に自由度が高い分野ではより大きな相違が要求される。設計の自由度。", "名詞句", "Because the shape of a bottle cap is heavily constrained by its technical function, courts may find that even small differences give it individual character due to the designer's low degree of freedom.", "知的財産（デザイン）", "850"),
    ("design infringement", "権利者の許諾を得ずに、登録意匠と同一または(知識のあるユーザーに異なる全体的印象を与えない程度に)類似する意匠を用いた製品を製造・販売・輸入・使用する等の行為。米国では通常観察者テスト(ordinary observer test)、EUでは知識のあるユーザーを基準とした全体的印象の比較によって判断されるなど、侵害の有無を判断する具体的な基準は法域によって異なる。意匠権侵害。", "名詞句", "Design infringement does not require the accused product to be identical to the registered design — a product that produces the same overall impression on an informed user is enough.", "知的財産（デザイン）", "750"),
    ("functionality exclusion", "製品の外観上の特徴のうち、専らその技術的機能によって定まるもの(features solely dictated by technical function)を意匠による保護の対象から除外する法理。EU共同体意匠規則第8条1項に規定され、2018年のCJEU DOCERAM事件判決は、ある特徴が専ら技術的機能によって定まるか否かは、他に同じ機能を果たす代替的な意匠が存在するかにかかわらず、その特徴の選択を決定づけた要因が技術的機能のみであったかという客観的事情に基づき判断すべきであるとした。機能性による保護除外。", "名詞句", "The functionality exclusion prevents a company from using design rights to monopolize a shape that exists only because of engineering necessity, not aesthetic choice.", "知的財産（デザイン）", "860"),
    ("must-fit exception", "EU共同体意匠規則第8条2項に規定される保護除外の一つで、ある製品を他の製品に機械的に接続・挿入・取り付けるために、寸法・形状を正確に再現しなければならない外観上の特徴について、意匠による保護を否定するもの。プラグとコンセントの接合部分などが典型例とされる。ただし同条3項は、モジュール式製品の部品同士の組み合わせを可能にする特徴についてはこの除外の例外を認めており、これはレゴ(LEGO)ブロックを念頭に置いた規定であることから「レゴ例外」と俗称される。マストフィット除外。", "名詞句", "The must-fit exception denies design protection to the precise dimensions of a connector, because those dimensions are dictated by the need to interlock with another product.", "知的財産（デザイン）", "870"),
    ("must-match exception", "英国の無登録意匠権(CDPA1988第213条3項(b)(ii))に見られる保護除外の一つで、ある物品の外観上の特徴が、それが構成部分として組み込まれる別の物品全体の外観に依存する(その物品と見た目を合わせなければならない)場合に、当該特徴を意匠保護の対象から除外するもの。自動車の交換用ボディパネルなど、修理用の交換部品(スペアパーツ)に関して特に問題となり、部品メーカーが完成品と見た目の一致する交換部品を製造できるようにすることで、完成品メーカーによる交換部品市場の独占を防ぐことを目的とする。マストマッチ除外。", "名詞句", "Because of the must-match exception, an independent manufacturer can produce a replacement car body panel that matches the original vehicle's appearance without infringing design right.", "知的財産（デザイン）", "880"),
    ("repair clause", "自動車のボディパネルなど、外観がその物品全体の見た目に依存する複合製品(complex product)の交換部品(スペアパーツ)について、当該複合製品を元の外観に復元する修理目的でのみ用いられる場合には、たとえ意匠登録されていても意匠権の行使を制限する条項。EU共同体意匠規則(2002年)は登録共同体意匠についてのみ暫定的にこれを認めていたが、加盟国ごとに国内意匠法上の扱いが分かれ不統一であったため、2024年に採択された新指令(Directive (EU) 2024/2823)により、2032年までの経過期間を経て全加盟国で修理条項が義務化されることとなった。修理条項。", "名詞句", "The repair clause allows independent workshops to fit design-protected replacement parts, such as bumpers and headlights, as long as the parts are used solely to restore the vehicle's original appearance.", "知的財産（デザイン）", "870"),
    ("complex product", "EU共同体意匠規則第3条(c)において、分解及び再組立てを可能にする複数の構成部品から成る製品と定義される概念。自動車がその典型例とされ、複合製品を構成する部品の意匠については、通常使用時に見える部分に限って独立した意匠保護が認められるなど、単一の一体的な製品とは異なる特別な取扱いを受ける。マストフィット除外(must-fit exception)や修理条項(repair clause)は、いずれもこの複合製品の構成部品を念頭に置いた規定である。複合製品。", "名詞句", "A car qualifies as a complex product because it is made of parts, such as headlights and wing mirrors, that can be individually removed and replaced.", "知的財産（デザイン）", "830"),
    ("Hague System", "一つの国際出願を、単一の言語で世界知的所有権機関(WIPO)国際事務局に提出することにより、複数の指定締約国・地域において最大100件までの意匠についてまとめて保護を求めることができる国際登録制度。1925年のハーグ協定に起源を持ち、現行の主要な枠組みは1999年のジュネーブ改正協定(Geneva Act)である。米国は1999年の署名国であったが、批准書の寄託は2015年2月13日で、実際にこの制度の利用が可能になったのは2015年5月13日からである。ハーグ制度、意匠の国際登録制度。", "名詞句", "Thanks to the Hague System, a company can seek design protection in dozens of countries by filing a single international application with WIPO, instead of filing separately in each country.", "知的財産（デザイン）", "780"),
    ("Locarno Classification", "工業意匠の登録に関する国際的な分類制度で、1968年のロカルノ協定によって設けられ、世界知的所有権機関(WIPO)が管理する。意匠が用いられる物品を「クラス」及び「サブクラス」に分類するもので、2026年時点の最新版は2025年1月1日に発効した第15版である。この分類はあくまで検索・行政上の便宜のためのものであり、同一クラスに属するか否かが意匠の類否や保護範囲の広狭を法的に決定するものではないとされる。ロカルノ分類。", "名詞句", "Design offices use the Locarno Classification to sort applications by product category, such as furniture or packaging, making prior-design searches far more efficient.", "知的財産（デザイン）", "780"),
    ("Design Law Treaty", "意匠出願の方式面(必要書類・手続の期限等)を締約国間で調和させることを目的として、2024年11月22日にサウジアラビアのリヤドで開催されたWIPO外交会議において採択された条約(通称リヤドデザイン法条約)。商標分野のシンガポール条約や特許分野の特許法条約(PLT)の意匠版に相当し、意匠の実体的な保護要件(新規性の基準や保護期間など)を統一するものではない。発効には15か国の批准・加入が必要とされ、2024年11月の採択時点ではまだ発効していない。意匠法条約。", "名詞句", "The Design Law Treaty aims to reduce the paperwork burden of filing a design application abroad, much as the Singapore Treaty did for trademarks.", "知的財産（デザイン）", "830"),
    ("design application", "意匠登録を受けるために特許庁等へ提出する出願書類一式。通常、意匠を表す図面または写真、保護を求める物品の名称(indication of product)、出願人・創作者の情報などから構成される。特許出願(patent application)が発明の技術内容を文章で説明する明細書やクレームを必須とするのに対し、多くの国の意匠出願は原則として意匠を表す図面・写真のみで足り、技術内容を説明する文章記載を要しない点で簡素である。意匠出願。", "名詞句", "A design application typically consists of nothing more than a set of drawings or photographs and a short indication of the product they represent.", "知的財産（デザイン）", "720"),
    ("priority claim", "パリ条約に基づき、ある締約国で最初にした意匠出願の出願日を、他の締約国における後の出願の新規性・個性等の判断基準日として遡って主張すること。意匠に関する優先期間は最初の出願から6か月と定められており、特許・実用新案の優先期間である12か月よりも短い点に注意を要する。優先権主張。", "名詞句", "Because the priority period for designs is only six months, applicants must decide much sooner than patent applicants whether to seek protection abroad.", "知的財産（デザイン）", "780"),
    ("grace period", "意匠の創作者自身、またはその承継人が、出願前の一定期間内に行った公開については、新規性・個性を喪失させる先行意匠として扱わないとする制度。多くの国・地域で12か月間と定められているが、その利用に必要な手続は法域によって差があり、EU・英国・米国・メキシコなどは特別な届出を要しないのに対し、日本・中国・韓国などは国際公開後30日以内の宣言書及び証拠書類の提出を求めるなど、より厳格な手続を課している。グレースピリオド、新規性喪失の例外期間。", "名詞句", "Thanks to the grace period, a designer who exhibits a prototype at a trade show can still file a valid design application up to twelve months later.", "知的財産（デザイン）", "790"),
    ("partial design", "物品や画像全体ではなく、その一部分についてのみ意匠登録を受ける制度、またはそのようにして登録された意匠。日本では1998年の意匠法改正で導入された「部分意匠」制度がこれに当たり、米国では意匠特許の図面において保護を求めない部分を破線(broken lines)で示すことによって同様の効果を実現する。全体の外観をそのまま模倣されなくても、特徴的な一部分だけを模倣された場合に権利行使できる点にメリットがある。部分意匠。", "名詞句", "Filing a partial design application lets a company protect just the distinctive curve of a smartphone's edge, without having to claim the entire device.", "知的財産（デザイン）", "760"),
    ("broken lines", "米国の意匠特許の図面において、保護を求めるクレームされた意匠の一部ではないことを示すために用いられる破線。物品の環境を示すために必要な部分や、部分意匠として権利化しない部分の輪郭などを表す際に用いられ、実線(solid lines)で描かれた部分のみが権利範囲を構成する。明細書には破線で示された部分がクレームされた意匠の一部を成さない旨の説明を付す必要がある。2013年以降、原則として出願後に実線を破線に、またはその逆に変更してクレーム範囲を変更する補正は認められていない。破線。", "名詞句", "By drawing the phone case in solid lines and the phone itself in broken lines, the applicant claims only the case's design, not the phone's appearance.", "知的財産（デザイン）", "800"),
    ("graphical user interface design", "コンピュータの画面やディスプレイパネル上に表示されるアイコンやレイアウトなどの画像デザイン(GUI)を意匠として保護する考え方、またはその保護対象。米国では、画面や表示パネルに具現化され、それと不可分な状態で示される限りにおいて意匠特許の対象となり得る。日本でも2019年の意匠法改正により、物品に記録されていない画像や、機器に依存しないクラウド上の画像についても意匠登録が可能となった。EUも2024年の意匠制度改革で「製品」の定義を拡張し、画面表示のような非物理的なデザインを明確に対象に含めた。GUIデザイン、画像意匠。", "名詞句", "Apple has obtained design patents covering the Cover Flow animation used to flip through album artwork, showing that even a GUI's motion can be protected as a design.", "知的財産（デザイン）", "820"),
    ("ornamental design", "実用的な機能ではなく、専ら視覚を通じて美感を起こさせる装飾的な外観を意味する語で、意匠(登録意匠・意匠特許)による保護の対象となる基本的な性質を表す。米国の意匠特許出願のクレームも「the ornamental design for [物品名], as shown」という定型文で記載され、この語が保護対象の本質を端的に表す。装飾的意匠。", "名詞句", "A shape is protectable as an ornamental design only if it results from a deliberate aesthetic choice, not merely from technical necessity.", "知的財産（デザイン）", "730"),
    ("term of design protection", "意匠権が存続する期間。特許や商標と異なり国際条約による統一基準がなく、法域ごとに大きく異なる点に注意を要する。EUの登録共同体意匠は出願日から5年ごとの更新により最長25年、無登録共同体意匠は最初の公開から3年、日本の意匠権は2020年施行の改正法により出願日から25年(改正前は登録日から20年)、米国の意匠特許は登録日から15年(2015年5月13日以降の出願)とされる。意匠保護期間。", "名詞句", "Unlike copyright, which typically lasts for the author's lifetime plus decades, the term of design protection is measured in years from filing or registration, not from the creator's death.", "知的財産（デザイン）", "800"),
    ("registered Community design", "欧州連合知的財産庁(EUIPO)への単一の出願・登録によって、EU加盟国全域に均一な効力を持つ意匠権を発生させる制度、またはそれによって登録された意匠。2003年1月1日から出願受付が開始され、同年4月1日から権利として発効した。新規性・個性等の実体審査は行わず方式審査のみで登録される点、及び出願日から5年ごとの更新により最長25年まで存続する点が特徴。登録共同体意匠(RCD)。", "名詞句", "A single registered Community design filed with EUIPO gives its owner protection across all EU member states, without having to register separately in each country.", "知的財産（デザイン）", "780"),
    ("unregistered Community design", "登録の手続を経ることなく、意匠がEU域内で最初に公衆に利用可能となった時点から自動的に発生する、EU域内で統一的な効力を持つ意匠権。保護期間は最初の公開から3年間と、登録共同体意匠(最長25年)に比べて大幅に短い。保護の範囲も限定的で、権利者が保護できるのは他者による「模倣(コピー)」に対してのみであり、独立して同様の意匠を創作した者に対しては、その者が権利者の意匠を知らなかったと合理的に考えられる限り、独自創作の抗弁が認められる。無登録共同体意匠(UCD)。", "名詞句", "Fashion companies that release short-lived seasonal collections often rely on the unregistered Community design instead of registering every garment, since the three-year term is usually long enough.", "知的財産（デザイン）", "830"),
    ("deferment of publication", "意匠の出願人が、出願日(優先権主張がある場合は優先日)から一定期間、その意匠の内容の公開を延期するよう請求できる制度。EUの登録共同体意匠及びハーグ制度のいずれも最長30か月まで延期を認めており、これにより出願人は製品の市場投入前に意匠の内容を競合他社に知られることなく出願日を確保できる。ただしハーグ制度では、指定締約国によっては延期期間がより短く制限される場合や、延期そのものが認められない場合もある。公開の延期。", "名詞句", "By requesting deferment of publication, a company can secure a filing date for a new product's design months before revealing it to competitors at a trade show.", "知的財産（デザイン）", "840"),
    ("multiple design application", "複数の異なる意匠を一つの出願手続にまとめて含める出願形式。個別に出願するよりも出願・維持コストを抑えられる利点がある。ハーグ制度は一つの国際出願で最大100件までの意匠を含めることを認めており、日本も2019年の意匠法改正以前は一意匠一出願の原則を採っていたが、改正後は複数の意匠をまとめて出願することが可能となった。複数意匠一括出願。", "名詞句", "A multiple design application lets a furniture maker file an entire season's line of chair designs in a single procedure instead of filing each chair separately.", "知的財産（デザイン）", "800"),
    ("design search", "意匠出願の前や、他者の意匠権を侵害していないかの確認、あるいは既存の意匠登録の有効性を争うために、既に公開・登録されている意匠(先行意匠)を調査する作業。世界知的所有権機関(WIPO)が提供する無償の検索サービスであるGlobal Design Databaseは、ハーグ制度による国際登録に加え、参加各国・地域の意匠庁が保有するデータも横断的に検索できる。意匠調査。", "名詞句", "Before launching a new product, a company should conduct a design search to make sure its packaging does not resemble an existing registered design.", "知的財産（デザイン）", "750"),
    ("prior design", "ある意匠の出願日(または優先日)より前に、世界のどこかで公衆が利用可能な状態に置かれていた意匠。新規性(design novelty)や個性(individual character)の有無を判断する際の比較対象となる。特許法における先行技術(prior art)に相当する意匠法上の概念であるが、対象が技術内容ではなくあくまで意匠(外観)である点が異なる。先行意匠。", "名詞句", "An examiner comparing a new application against prior design will look for images that create the same or a very similar overall impression.", "知的財産（デザイン）", "810"),
    ("design around", "既存の登録意匠や意匠特許の権利範囲に含まれないように、製品の外観を意図的に変更して設計する実務。特許のクレームを回避する同種の実務(特許発明の構成要素を一部変更して文言侵害を免れる設計変更)と共通する発想だが、意匠の場合は権利範囲が文言ではなく知識のあるユーザー(informed user)に与える全体的印象(overall impression)によって画されるため、テキスト上のクレーム限定をすり抜けるような手法は通用せず、実際に視覚的に異なる印象を与える程度まで外観を変える必要がある。意匠権の回避設計。", "動詞句/名詞句", "Competitors often try to design around a popular registered design by subtly reshaping the product just enough to create a different overall impression.", "知的財産（デザイン）", "800"),
    ("cumulative protection", "同一の対象物について、意匠権・著作権・商標(トレードドレスを含む)といった複数の異なる知的財産権が重畳的に成立し得るという考え方、またはその状態。EUでは2019年のCJEU Cofemel事件判決が、著作権による保護を受けるための要件は「作者自身の自由な創作的選択を反映した独創性」のみであり、意匠として登録されている(または登録可能である)ことは著作権保護を妨げも要求もしないと判示し、意匠権と著作権の重畳的成立を明確に認めた。重畳的保護。", "名詞句", "Because of cumulative protection, a chair's shape can be simultaneously covered by a registered design and, if original enough, by copyright as well.", "知的財産（デザイン）", "870"),
    ("article of manufacture", "米国特許法第171条が意匠特許の保護対象と定める、人の手によって原材料から作り出された物品を意味する語。また同法第289条が定める意匠特許侵害の損害賠償(全利益の吐き出し、total profits remedy)の算定基準としても用いられ、2016年の連邦最高裁判決Samsung Electronics Co. v. Apple Inc.は、この「物品」は製品全体だけでなく、その構成部品(コンポーネント)を指す場合もあり得ると判断した。同事件は差し戻し後の2018年の陪審評決で、結局スマートフォン本体全体が算定基準となる物品であるとされ、サムスンに約5億3,300万ドルの支払いが命じられた。物品。", "名詞句", "The Supreme Court held that the term article of manufacture in section 289 can refer to a single component of a product, not only to the product as a whole.", "知的財産（デザイン）", "880"),
    ("total profits remedy", "米国特許法第289条が定める、意匠特許侵害の場合に特有の損害賠償制度で、侵害者がその意匠(または紛らわしい模造品)を適用した物品の製造・販売から得た利益の全額を、原告に賠償として支払わせることができるもの。通常の実用特許侵害の損害賠償(第284条、逸失利益や合理的実施料に基づく算定)とは異なり、利益と侵害との因果関係の割合的な立証(寄与度の按分)を要しない点に特徴がある。1885年前後の一連のカーペット意匠訴訟(Dobson事件)で、原告が侵害による損害の内訳を立証できなかったために名目的損害(6セント)しか認められなかったことへの議会の対応として、1887年の法律により導入された。全利益吐き出し(全利益賠償)。", "名詞句", "The total profits remedy lets a design patent owner recover every dollar of profit the infringer made from selling the infringing product, without having to apportion how much of that profit was due to the design.", "知的財産（デザイン）", "900"),
    ("ordinary observer test", "米国における意匠特許侵害の判断基準で、通常の注意力を持つ一般的な観察者(ordinary observer)が、当該意匠に通常払う程度の注意を払って見た場合に、被疑侵害品の意匠が特許意匠と実質的に同一であると誤認して購入してしまうほど類似しているかを問うもの。1871年の連邦最高裁判決Gorham Co. v. Whiteに由来し、2008年のEgyptian Goddess, Inc. v. Swisa連邦巡回区控訴裁判所大法廷判決以降は、先行意匠を踏まえた観察者の視点から判断するとされつつ、意匠特許侵害を判断する唯一の基準として確立している。通常観察者テスト。", "名詞句", "Under the ordinary observer test, the question is not whether an expert could spot subtle differences, but whether an ordinary buyer would be deceived into thinking the two designs are the same.", "知的財産（デザイン）", "870"),
    ("point of novelty test", "かつて米国の意匠特許侵害訴訟において、通常観察者テスト(ordinary observer test)に加えて要求されていた第二の要件で、被疑侵害品が、特許意匠を先行意匠から区別する新規な特徴(新規性のポイント)を専有しているかを問うもの。約25年間にわたり連邦巡回区控訴裁判所の判例法として定着していたが、2008年のEgyptian Goddess, Inc. v. Swisa大法廷判決により、独立した必須要件としては廃止され、通常観察者テストのみが意匠特許侵害の唯一の基準とされた。新規性のポイントテスト(廃止済み)。", "名詞句", "Before 2008, a plaintiff had to satisfy the point of novelty test in addition to the ordinary observer test, making design patent infringement noticeably harder to prove.", "知的財産（デザイン）", "870"),
    ("invalidity action", "既に登録された意匠登録の有効性を、新規性や個性の欠如などを理由に事後的に争う手続。EUの登録共同体意匠については、登録前の実体審査を経ていないため、利害関係人であればいつでもEUIPOの無効部(Invalidity Division)に対して申し立てることができる。日本ではこれに相当する手続を「意匠登録の無効審判」と呼び、特許庁の審判部が審理する。無効審判。", "名詞句", "Because EUIPO does not check novelty before registering a design, competitors who believe a registration is invalid must bring an invalidity action after the fact.", "知的財産（デザイン）", "830"),
    ("Design Directive", "1998年に採択されたEU指令(Directive 98/71/EC)で、EU加盟各国が個別に有する国内意匠法の実体的な保護要件(新規性・個性の定義等)を調和させることを目的とする。単一の統一的な権利を創設する共同体意匠規則(Regulation (EC) No 6/2002)とは異なり、指令は各加盟国が自国の国内法を整備する際の基準を示すにとどまる。2024年に採択された新指令(Directive (EU) 2024/2823)がこれを置き換えることとなり、旧指令は2027年12月9日に廃止される予定である。意匠指令。", "名詞句", "The Design Directive did not create a single EU-wide design right; it merely required each member state to align its own national design law with common minimum standards.", "知的財産（デザイン）", "850"),
    ("EUIPO", "欧州連合の商標及び登録共同体意匠の登録・管理を所管する欧州連合の機関。1994年にスペインのアリカンテに「域内市場調和庁(OHIM)」として設立され、当初はEU商標(当時の共同体商標)の登録業務を担っていたが、後に登録共同体意匠の導入に伴いその登録業務も所管するようになった。2016年3月23日、名称が現在の「欧州連合知的財産庁(EUIPO)」に変更された。無登録共同体意匠のように登録を要しない権利や、各加盟国の国内意匠権は本庁の所管ではない。欧州連合知的財産庁。", "名詞", "EUIPO handles the registration of both EU trademarks and registered Community designs from its headquarters in Alicante, Spain.", "知的財産（デザイン）", "760"),
    ("Community design court", "EU共同体意匠規則第80条以下に基づき、各加盟国が国内に指定する、登録共同体意匠及び無登録共同体意匠に関する侵害訴訟及び有効性を争う訴訟(反訴を含む)を専属的に管轄する第一審・第二審の国内裁判所。各加盟国はできるだけ少数の裁判所をこの裁判所として指定することとされ、その判決はEU域内全体に及ぶ効力を持つ。共同体意匠裁判所。", "名詞句", "Even though a Community design court is a national court of a single member state, its ruling on the validity of a registered Community design has effect throughout the entire EU.", "知的財産（デザイン）", "870"),
    ("single claim requirement", "米国特許規則37 C.F.R. §1.153が定める、意匠特許出願には一つのクレームしか含めることができず、また一つのクレームを含めなければならないとする規則。クレームは「The ornamental design for [物品名], as shown」(または記載を要する場合は「as shown and described」)という定型文で記載される。複数の独立クレーム・従属クレームを含み得る実用特許出願とは対照的な、意匠特許出願特有の形式的な要件である。単一クレーム要件。", "名詞句", "Because of the single claim requirement, a design patent application cannot present several alternative embodiments the way a utility patent application can with multiple claims.", "知的財産（デザイン）", "800"),
    ("surface ornamentation", "米国の意匠特許が保護し得る意匠の類型の一つで、物品の立体的な形状・輪郭(configuration)そのものではなく、その表面に施された平面的な模様・柄を指す。意匠特許は、この表面装飾のみを保護対象とする場合、形状のみを保護対象とする場合、その両者を組み合わせて保護対象とする場合のいずれも認められる。保護を受けるためには、その模様が明確で再現可能な一定のパターン(a definite, preconceived pattern)でなければならず、偶然の結果にすぎないもの(例えば無作為に変化するレーザー光の模様)は対象とならない。表面装飾。", "名詞句", "A design patent can protect the surface ornamentation printed on a fabric even if the shape of the garment itself is entirely ordinary.", "知的財産（デザイン）", "820"),
    ("word mark", "図形やロゴのデザイン、文字の書体・色彩といった視覚的な装飾要素を伴わず、文字・単語・数字などの構成そのものを保護対象として登録される商標の類型。ロゴのデザインを変更しても、文字列自体が同一であれば保護が及び続ける点に特徴がある。ワードマーク、標準文字商標。", "名詞", "Registering the company name as a word mark protects the letters themselves, no matter what font or color scheme is later used to display them.", "知的財産（商標）", "780"),
    ("device mark", "文字を伴わない、あるいは文字と組み合わされたロゴ・図形・記号など、視覚的なデザインそのものを保護対象として登録される商標の類型。文字列の構成のみを保護するワードマークと対をなす概念で、書体・配色・図案の具体的な表現が権利範囲を画する。デバイスマーク、図形商標。", "名詞", "Nike registers the swoosh as a device mark, separate from the word mark that covers the name \"Nike\" itself.", "知的財産（商標）", "780"),
    ("service mark", "商品ではなく、運送・金融・飲食・情報提供などのサービス(役務)の提供者を識別するために用いられる標章。米国等一部の法域では商品を対象とする商標(トレードマーク)と法律上区別された概念として登録されるが、多くの国では両者を包括して「商標」として扱う。サービスマーク、役務商標。", "名詞", "Because FedEx sells shipping services rather than a physical product, its name is registered in the United States as a service mark.", "知的財産（商標）", "760"),
    ("certification mark", "特定の一事業者の出所を示すのではなく、原産地・原材料・製法・品質・技能などが一定の基準を満たしていることを認証するために用いられ、その基準を満たす者であれば所属団体を問わず誰でも使用できる標章。基準を管理・認証する団体自身は原則としてその商品・サービスを自ら提供しない点で、通常の商標と性質が異なる。認証マーク、証明商標。", "名詞", "The UL mark is a certification mark showing that an independent laboratory has tested the product and found it to meet its electrical safety standards.", "知的財産（商標）", "800"),
    ("collective mark", "協同組合や業界団体、労働組合などの構成員が、その団体に所属していることや、共通の基準を満たす商品・サービスを提供していることを示すために、団体自身ではなく構成員が共同で使用する標章。単一の主体ではなく複数の構成員が使用主体となる点で通常の商標と異なる。団体商標。", "名詞", "Only real estate agents who are dues-paying members of the National Association of Realtors are permitted to use the collective mark REALTOR.", "知的財産（商標）", "800"),
    ("sound mark", "音声・音楽・効果音など、視覚ではなく聴覚によって認識される要素からなる商標。文字や図形を前提とする通常の商標審査とは異なる課題があり、多くの国で五線譜による表記や録音データの提出が登録出願時に求められる。音商標、サウンドマーク。", "名詞", "NBC's three-note chime, first used in 1930, is one of the oldest registered sound marks in the United States.", "知的財産（商標）", "820"),
    ("color mark", "特定の色彩そのものが、商品や包装、店舗の内外装などに継続的かつ排他的に使用された結果、出所識別力を獲得した場合に、その色彩自体を保護対象として登録される商標。単独の色彩には本来的な識別力がないとされるため、多くの法域で使用による後天的識別力(secondary meaning)の立証が登録の条件となる。色彩(単色)商標。", "名詞", "In Qualitex Co. v. Jacobson Products Co. (1995), the U.S. Supreme Court held that the green-gold color of dry-cleaning press pads could be registered as a color mark once it had acquired secondary meaning.", "知的財産（商標）", "850"),
    ("three-dimensional mark", "商品や容器そのものの立体的な形状を保護対象として登録される商標の類型。製品の技術的機能に由来する形状は機能性の法理によって登録が拒絶されるため、専ら出所識別のためのデザイン的な特徴を備えた形状であることが求められる。立体商標、3Dマーク。", "名詞", "The contoured shape of the classic Coca-Cola bottle is registered as a three-dimensional mark in many countries.", "知的財産（商標）", "830"),
    ("trademark application", "特許庁等の登録官庁に対して、特定の商品・役務について商標としての保護を求めて提出する出願書類、またはその手続き。出願人・商標の態様・指定商品役務・使用開始日(法域による)などの情報を含む。商標出願。", "名詞", "Before launching the new product line, the company filed a trademark application covering clothing, bags, and footwear.", "知的財産（商標）", "720"),
    ("trademark registration", "商標出願が審査を経て登録官庁の登録簿に記載され、正式に商標権として成立すること、またはその登録自体を指す語。登録により、指定商品・役務について当該商標を排他的に使用する権利が生じる。商標登録。", "名詞", "Trademark registration gives the owner the exclusive right to use the mark on the goods listed in the certificate, and to sue infringers.", "知的財産（商標）", "720"),
    ("trademark clearance search", "新しい商標を採用・出願する前に、既存の登録商標や係属中の出願、未登録の使用例などと同一・類似の商標が存在しないかを事前に調査すること。これを怠って商標を採用すると、後に侵害訴訟や登録拒絶のリスクを負うことになる。商標クリアランス調査、事前調査。", "名詞", "Before spending millions on a new brand campaign, the company commissioned a trademark clearance search to make sure the name was available.", "知的財産（商標）", "780"),
    ("Nice Classification", "商標登録の出願にあたって、指定する商品・役務を統一的な基準で分類するための国際的な分類制度。1957年のニース協定に基づきWIPOが管理しており、商品を対象とする第1類から第34類、役務を対象とする第35類から第45類までの計45の区分から構成される。ニース分類、国際分類。", "名詞", "Software is generally classified under Class 9 of the Nice Classification, while software-as-a-service is often filed under Class 42.", "知的財産（商標）", "800"),
    ("trademark class", "ニース分類において区分された45の商品・役務カテゴリーのうちの一つ。商標出願では、保護を求める商品・役務が属する区分(第1類~第45類)を指定しなければならず、同じ商標であっても指定する区分が異なれば、併存して別々の主体に登録が認められることがある。商標の区分、指定区分。", "名詞", "Apple Corps (the Beatles' record label) and Apple Inc. were able to coexist for years partly because their marks were registered in very different trademark classes.", "知的財産（商標）", "760"),
    ("opposition proceeding", "商標出願が審査を通過し、登録前の公告段階に至った際に、第三者がその商標の登録に異議を唱え、登録すべきでない理由を主張して争う行政手続き。登録後に争う取消(cancellation)手続きとは異なり、登録が確定する前の段階で行われる。登録異議申立て、異議申立手続。", "名詞", "The brewery filed an opposition proceeding against the rival's application, arguing that the new mark was confusingly similar to its own long-established beer label.", "知的財産（商標）", "820"),
    ("cancellation proceeding", "既に登録が完了している商標について、第三者がその登録の有効性を争い、登録の取消しを求める行政手続き。登録前に争う登録異議申立て(opposition)とは異なり、いったん成立した権利を事後的に覆すための手段である。登録取消審判、取消手続。", "名詞", "A competitor initiated a cancellation proceeding, claiming that the registered mark had never actually been used in commerce.", "知的財産（商標）", "820"),
    ("trademark renewal", "商標権の存続期間が満了する前に、登録官庁に対して更新手続きを行い、権利を継続して存続させること。多くの国で更新の際に継続使用の証明や宣誓書の提出、更新手数料の納付が求められ、これを怠ると権利は失効する。商標権の更新。", "名詞", "Because trademark rights can, in theory, last forever, owners only need to file for trademark renewal periodically rather than reapplying from scratch.", "知的財産（商標）", "750"),
    ("non-use cancellation", "登録された商標が、法律で定められた一定期間(多くの国で3年~5年)にわたって指定商品・役務について実際に使用されていないことを理由に、第三者からの請求によってその登録を取り消す制度。休眠中の登録によって新規参入者の商標選択の余地が不当に狭められるのを防ぐことを目的とする。不使用取消審判。", "名詞", "A startup that could not register its preferred name because of a decade-old, unused registration successfully filed for non-use cancellation.", "知的財産（商標）", "830"),
    ("genuine use requirement", "登録された商標について、単に権利として保有するだけでなく、指定商品・役務について実際に、かつ名目的ではない真摯な商業目的での使用が継続されていることを要求する法理・制度。この要件を満たさない登録は、不使用取消しの対象となりうる。真正な使用の要件、実質的使用の要件。", "名詞", "EU trademark law's genuine use requirement means that token sales made only to preserve a registration will not be enough to defeat a revocation action.", "知的財産（商標）", "850"),
    ("trademark notice", "商品や広告に付される「®」や「™」、「SM」などの記号によって、その標章が商標として主張・登録されていることを需要者や競合他社に知らせる表示。「®」は連邦登録が完了した商標にのみ使用が認められるのに対し、「™」「SM」は未登録であってもコモンロー上の権利を主張する目的で自由に使用できる。商標表示。", "名詞", "Using the ® symbol on a mark that has not actually been registered can itself constitute a form of consumer deception.", "知的財産（商標）", "740"),
    ("spectrum of distinctiveness", "商標として保護されるための識別力の強さを、弱いものから強いものへと連続的に位置づけた分類の枠組み。一般名称・記述的商標・示唆的商標・恣意的商標・造語商標の5段階に区分されるのが代表的で、1976年の米国第二巡回区控訴裁判所判決Abercrombie & Fitch Co. v. Hunting World, Inc.で確立された。識別力の連続体、商標の識別力スペクトラム(アバクロンビー分類)。", "名詞", "Under the spectrum of distinctiveness, a made-up word like \"Kodak\" receives far stronger protection than a merely descriptive term like \"Cold and Creamy\" for ice cream.", "知的財産（商標）", "880"),
    ("generic term", "商品やサービスそのものの種類・カテゴリーを表す一般的な名称であり、特定の出所を示す機能を持たないために、いかなる者による使用によっても商標としての保護を受けることができない語。識別力のスペクトラムの中で最も弱い(保護されない)分類に位置づけられる。一般名称、普通名称。", "名詞", "\"Computer\" is a generic term for a class of devices, so no single company could ever claim exclusive trademark rights over the word itself.", "知的財産（商標）", "800"),
    ("descriptive mark", "商品・サービスの品質・特徴・用途・産地・成分などをそのまま直接的に説明する語からなる商標。原則としてそれ自体には識別力がないとして登録が拒絶されるが、長期間の使用を通じて需要者がその語を特定の出所と結びつけて認識するようになった場合(後天的識別力・secondary meaningの獲得)には、登録が認められることがある。記述的商標。", "名詞", "\"Cold and Creamy\" would likely be treated as a descriptive mark for ice cream and could be registered only upon proof of secondary meaning.", "知的財産（商標）", "820"),
    ("suggestive mark", "商品・サービスの特徴を直接的に説明するのではなく、需要者が想像力や連想を働かせることによって初めてその特徴を思い浮かべることができるような商標。識別力のスペクトラムにおいて、記述的商標よりも強く保護され、後天的識別力の立証なしに本来的な識別力があるものとして登録が認められる。示唆的商標。", "名詞", "\"Netflix\" is often cited as a suggestive mark because it hints at internet-delivered films without directly describing the service.", "知的財産（商標）", "840"),
    ("arbitrary mark", "既存の一般的な単語をそのまま用いながらも、指定する商品・サービスとは何の意味的な関連性も持たない形で使用される商標。単語自体は辞書に載っている既知の語であるという点で完全な造語(fanciful mark)とは異なるが、指定商品との関連性がないため本来的に強い識別力を持つとされる。恣意的商標。", "名詞", "\"Apple\" is a classic arbitrary mark when used for computers, since the word has no logical connection to electronics.", "知的財産（商標）", "840"),
    ("fanciful mark", "商標として使用するためだけに新たに作り出された、辞書に存在しない完全な造語からなる商標。既存の単語を借用する恣意的商標とも異なり、指定商品・サービスとの間に一切の既存の意味的連想が生じないため、識別力のスペクトラムの中で最も強い本来的識別力を持つとされる。造語商標。", "名詞", "\"Kodak,\" \"Exxon,\" and \"Xerox\" were all coined from scratch as fanciful marks with no prior meaning in any language.", "知的財産（商標）", "840"),
    ("inherently distinctive", "商標が、使用による後天的な識別力の獲得を待つことなく、その語や図案自体の性質によって最初から出所識別力を備えていると法的に認められること。造語商標・恣意的商標・示唆的商標がこれに該当し、記述的商標や一般名称と対比される。本来的識別力を有する、本来的識別力がある。", "形容詞", "Because a fanciful mark is considered inherently distinctive, its owner can register it and sue for infringement without ever having to prove secondary meaning.", "知的財産（商標）", "850"),
    ("secondary meaning", "本来はそれ自体に識別力を持たない記述的な語句や、単純な図形・色彩などが、長期間かつ排他的な使用と広告を通じて、需要者の間で特定の出所を示すものとして認識されるようになること。この後天的に獲得された識別力が立証されれば、本来は登録できないはずの標章も商標として保護されうる。後天的識別力、二次的意味の獲得。", "名詞", "After decades of exclusive use, the descriptive phrase \"American Airlines\" acquired enough secondary meaning to function as a strong, protectable trademark.", "知的財産（商標）", "830"),
    ("likelihood of confusion", "後発の商標の使用や登録が、需要者に商品・サービスの出所について誤認・混同を生じさせる、あるいは生じさせるおそれがあると法的に判断されること。商標の類似性、指定商品・役務の関連性、需要者の注意力、先行商標の識別力の強さなど複数の要素を総合的に考慮して判断される、商標侵害の中核的な判断基準。混同のおそれ。", "名詞", "Courts weigh factors such as the similarity of the marks and the relatedness of the goods when deciding whether there is a likelihood of confusion.", "知的財産（商標）", "800"),
    ("reverse confusion", "通常の混同とは逆に、後から市場に参入した資本力の大きい企業が、先行する小規模な商標権者の商標と同一・類似の商標を大々的な広告により普及させた結果、需要者がかえって先行権者の商品を後発企業の商品の模倣品や無許諾の派生品であると誤認してしまう現象。1977年の米国第十巡回区控訴裁判所判決Big O Tire Dealers, Inc. v. Goodyear Tire & Rubber Co.で確立された法理。逆混同。", "名詞", "In a case of reverse confusion, consumers might wrongly assume that the small original trademark owner is the one copying the giant newcomer.", "知的財産（商標）", "900"),
    ("initial interest confusion", "商品・サービスの購入時点では需要者が真の出所を正しく認識しており最終的な混同が生じていなくても、購入に至る過程の初期段階で他人の商標を利用して需要者の注意や関心を不当に引き寄せる行為を、商標侵害として捉える法理。インターネット検索結果やメタタグ、キーワード広告などをめぐる紛争で特に問題となる。初期関心混同。", "名詞", "The court in Brookfield Communications v. West Coast Entertainment (1999) held that hiding a competitor's trademark in website metatags could create initial interest confusion, even if visitors quickly realized they were on the wrong site.", "知的財産（商標）", "910"),
    ("trademark infringement", "権利者の許諾を得ずに、登録された商標、または一定の要件を満たす未登録商標と同一・類似の標章を、混同のおそれを生じさせる態様で商業的に使用すること。権利者は差止め、損害賠償、悪意による侵害の場合は増額賠償などを求めて提訴することができる。商標権侵害。", "名詞", "The court found trademark infringement because the defendant's logo was close enough to the plaintiff's registered mark to create a likelihood of confusion among ordinary consumers.", "知的財産（商標）", "780"),
    ("trademark dilution", "著名な商標について、たとえ需要者の間に混同が生じなくても、その商標が持つ強い識別力や評判が、無関係な商品・サービスへの使用によって弱められたり、傷つけられたりすること。混同のおそれを要件とする通常の侵害とは別個の、著名商標に特有の保護法理。商標の希釈化。", "名詞", "Even if no one would think a car company made these candy bars, using the Rolls-Royce name for candy could still amount to trademark dilution.", "知的財産（商標）", "870"),
    ("dilution by blurring", "著名な商標が、無関係な商品・サービスに他者によって使用され続けることで、需要者の頭の中でその商標が唯一の出所と強く結び付いていたはずの結び付きが徐々に薄れ、識別力そのものが弱められていく現象。商標希釈化の二類型のうちの一つ。ブラーリングによる希釈化。", "名詞", "If dozens of unrelated companies started calling their products \"Kodak,\" the name's power to instantly evoke a single photography brand would suffer from dilution by blurring.", "知的財産（商標）", "900"),
    ("dilution by tarnishment", "著名な商標が、低品質な商品や、性的・違法・不快なイメージを伴う文脈で他者によって使用されることにより、その商標が本来持っていた高級感や信頼といった肯定的なイメージが傷つけられ、評判が損なわれる現象。商標希釈化の二類型のうちの一つ。ターニッシュメントによる希釈化。", "名詞", "A famous children's toy brand suing over its name being used for an adult-themed product would likely frame the case as dilution by tarnishment.", "知的財産（商標）", "900"),
    ("genericide", "商標が広く使われすぎた結果、商品・サービスの出所を示す標章としての機能を失い、その商品カテゴリー自体を指す一般名称として扱われるようになってしまい、商標としての保護を失う現象。「アスピリン」「エスカレーター」「サーモス」等がかつて商標だったが一般名称化した例として知られる。ジェネリサイド、商標の一般名称化。", "名詞", "The word \"aspirin\" was once a trademark, but it fell victim to genericide and is now a generic term for the drug itself.", "知的財産（商標）", "850"),
    ("passing off", "英国やカナダ、オーストラリアなど英連邦系のコモンロー諸国において、登録の有無を問わず、ある事業者が自らの商品・サービスを、既に確立された評判(グッドウィル)を持つ他者の商品・サービスであるかのように誤認させ、その評判にただ乗りする行為を規制するコモンロー上の不法行為。米国の不正競争防止法制における対応する概念と類似するが、独立した訴訟原因として扱われる点に特徴がある。パッシングオフ、詐称通用。", "名詞", "In the famous \"Jif Lemon\" case, Reckitt & Colman successfully sued a rival for passing off after it copied the distinctive lemon-shaped bottle.", "知的財産（商標）", "880"),
    ("trademark exhaustion", "商標権者、またはその許諾を得た者によって、ある特定の商品が適法に市場に置かれた(最初の販売がなされた)後は、その商標権者はもはやその特定の商品のその後の転売や流通を、商標権に基づいてコントロールすることができなくなるという法理。並行輸入(parallel import)が多くの法域で適法とされる法的根拠となっている。商標権の消尽。", "名詞", "Under the doctrine of trademark exhaustion, once a retailer buys genuine branded sneakers, the manufacturer generally cannot stop that retailer from reselling them.", "知的財産（商標）", "900"),
    ("trademark assignment", "商標権を、対価と引き換えに、あるいは無償で、他者へ完全に移転すること。多くの法域で、商標権はその商標が象徴するグッドウィル(営業上の信用)と一体として譲渡されなければならず、グッドウィルを伴わない商標のみの移転(裸の譲渡)は無効または欺瞞的とされる。商標権の譲渡。", "名詞", "The trademark assignment agreement specified that the buyer would acquire not only the registered mark but also the associated goodwill of the business.", "知的財産（商標）", "800"),
    ("naked licensing", "商標権者が、ライセンシーに商標の使用を許諾しながら、ライセンシーが提供する商品・サービスの品質について実質的な監督・管理を一切行わないこと。商標は出所と品質の一貫性を保証する機能を担うため、このような品質管理を欠いた「裸の」ライセンスを続けると、その商標は放棄(abandonment)されたとみなされ、権利そのものを失う結果を招きうる。裸のライセンス、ネイキッド・ライセンシング。", "名詞", "In Eva's Bridal Ltd. v. Halanick Enterprises (2011), the Seventh Circuit held that the mark had been abandoned because the licensor engaged in naked licensing, exercising no quality control over the licensee's store.", "知的財産（商標）", "900"),
    ("coexistence agreement", "類似する、あるいは同一の商標を保有する複数の当事者が、互いに訴訟を提起することなく、それぞれの商標を特定の地域・商品分野・態様に限定して並行して使用し続けることを合意する契約。商標クリアランス調査の結果、抵触する先行商標が見つかった場合の実務的な解決策の一つとして用いられる。共存合意、共存契約。", "名詞", "Rather than litigating for years, the two companies signed a coexistence agreement limiting each side's use of the similar mark to a different product category.", "知的財産（商標）", "850"),
    ("prior use", "ある商標について、他者による出願や登録に先立って、実際に商業上その商標を使用していたという事実、およびそれに基づいて主張される優先的な権利。多くの英米法系の国では、登録の先後だけでなく、この実際の使用開始時期が商標の優先順位を決める重要な要素となる。先使用、商標の先使用。", "名詞", "Even though the rival filed its trademark application first, the local bakery's decades of prior use of the name gave it superior common-law rights in that market.", "知的財産（商標）", "820"),
    ("first-to-use rule", "同一・類似の商標について複数の者が権利を主張する場合に、登録出願の先後ではなく、実際に商業上その商標の使用を開始した時期の先後によって権利の優劣を決する原則。米国のコモンロー上の商標権はこの原則に基づいており、これは特許制度において出願日の先後のみで権利を決する先願主義(first-to-file system)とは対照的な考え方である。先使用主義。", "名詞", "Under the first-to-use rule that governs U.S. common-law trademark rights, a business that used a name in a local market years before a national competitor registered it can still retain rights there.", "知的財産（商標）", "850"),
    ("trademark abandonment", "商標権者が、その商標の使用を将来にわたって再開する意図なく中止したこと、またはネイキッド・ライセンシング(naked licensing)や商標としての管理を怠ったことなどにより、その商標が果たすべき出所識別機能を実質的に喪失したと判断されること。放棄が認定されると、当該商標に対する権利は消滅し、他者が自由に使用・登録できるようになる。商標権の放棄。", "名詞", "A company that stops using a mark for several consecutive years, with no plan to resume, risks a court finding trademark abandonment.", "知的財産（商標）", "840"),
    ("trademark squatting", "ある商標がまだ特定の国・地域で登録されていないことに乗じて、その商標の正当な保有者や将来の市場参入者を妨害したり、高額な対価と引き換えに権利を買い取らせたりする目的で、無関係の第三者が先回りしてその商標を出願・登録する行為。特に先願主義を厳格に採用する国で問題となりやすい。商標の悪意による先取り、トレードマーク・スクワッティング。", "名詞", "Before Tesla could sell cars in China, it had to deal with trademark squatting by a local businessman who had registered the \"Tesla\" name years earlier.", "知的財産（商標）", "830"),
    ("trademark watch", "自社の商標と同一・類似する新たな商標出願や登録が、国内外の商標公報等に現れていないかを継続的に監視するサービス、またはその活動。類似商標の登録異議申立てや使用の差止めなど、早期の対応を可能にすることを目的とする。商標監視(サービス)、ウォッチングサービス。", "名詞", "The brand's legal team subscribed to a trademark watch service so it could file an opposition proceeding as soon as a confusingly similar mark was published.", "知的財産（商標）", "780"),
    ("house mark", "企業が製造・販売する多様な商品群・ブランド群全体に共通して付す、企業自体を示す基幹的な商標。個々の商品ラインに付される個別の製品ブランド(サブブランド)とは異なり、企業全体への信頼や評判を集約する役割を果たす。ハウスマーク、基幹商標。", "名詞", "Toyota functions as a house mark, while individual models like the Corolla and Camry serve as separate product marks beneath it.", "知的財産（商標）", "780"),
    ("family of marks", "共通の識別可能な要素(接頭辞・接尾辞・特徴的な語幹など)を含む一連の複数の商標を、同一の事業者が意図的に採用・使用し、需要者がその共通要素自体を、当該事業者に由来する一群の商品・サービスを示すものとして認識するに至った場合に認められる、商標の集合体。個々の商標を単発で比較するのではなく、共通要素を含む一群として保護が主張される。商標のファミリー。", "名詞", "McDonald's has built a family of marks around the \"Mc\" prefix, including McNuggets, McCafé, and McFlurry.", "知的財産（商標）", "830"),
    ("slogan mark", "企業や商品のキャッチフレーズ・スローガンそのものを、商品・サービスの出所を示す標章として登録する商標の類型。単なる宣伝文句や称賛的な表現にとどまる場合には識別力を欠くとして登録が拒絶されることが多く、需要者がそのフレーズを特定の出所と結びつけて認識するに至っていることの立証が求められる場合がある。スローガン商標。", "名詞", "Nike registered \"Just Do It\" as a slogan mark, giving the company exclusive rights to use the phrase in connection with athletic apparel.", "知的財産（商標）", "800"),
]


def main() -> None:
    with db() as conn:
        existing = set()
        for r in conn.execute("SELECT english FROM words").fetchall():
            existing.add(r["english"].lower())
        inserted = 0
        skipped = 0
        for english, japanese, pos, example, domain, level in WORDS:
            if english.lower() in existing:
                skipped += 1
                continue
            conn.execute(
                "INSERT INTO words (english, japanese, part_of_speech, "
                "example, domain, level) VALUES (?, ?, ?, ?, ?, ?)",
                (english, japanese, pos, example, domain, level),
            )
            existing.add(english.lower())
            inserted += 1
        print("inserted=" + str(inserted) + " skipped=" + str(skipped))


if __name__ == "__main__":
    main()
