# ruff: noqa: E501
"""Academic vocabulary across many fields (大学教養〜学士〜修博). Authored by
Claude — no app/OpenAI API calls. Dedupe on english; back-fill empty examples.
Levels are set explicitly per field (大学教養=800 / 学士=900 / E資格=900 /
論文=990); relevel.py is NOT required for this batch.

Run: python scripts/add_academic.py   (then build_audio for audio)
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.database import db  # noqa: E402

# domain -> (level, [(english, japanese, example), ...])
FIELDS: dict[str, tuple[str, list[tuple[str, str, str]]]] = {
    "生物学": ("800", [
        ("cell", "細胞", "All living things are made of cells."),
        ("mitosis", "有糸分裂", "Mitosis produces two identical cells."),
        ("meiosis", "減数分裂", "Meiosis halves the chromosome number."),
        ("chromosome", "染色体", "Humans have 46 chromosomes."),
        ("gene", "遺伝子", "A gene carries hereditary information."),
        ("allele", "対立遺伝子", "Each parent passes on one allele."),
        ("genotype", "遺伝子型", "The genotype determines traits."),
        ("phenotype", "表現型", "Eye color is a visible phenotype."),
        ("enzyme", "酵素", "Enzymes speed up biochemical reactions."),
        ("photosynthesis", "光合成", "Plants make sugar by photosynthesis."),
        ("respiration", "呼吸（細胞）", "Cellular respiration releases energy."),
        ("homeostasis", "恒常性", "The body maintains homeostasis."),
        ("metabolism", "代謝", "Metabolism converts food into energy."),
        ("organism", "生物・有機体", "A bacterium is a single-celled organism."),
        ("membrane", "膜", "The cell membrane controls what enters."),
        ("nucleus", "核", "The nucleus holds the cell's DNA."),
        ("ribosome", "リボソーム", "Ribosomes build proteins."),
        ("mitochondria", "ミトコンドリア", "Mitochondria produce energy."),
        ("chloroplast", "葉緑体", "Chloroplasts capture light energy."),
        ("evolution", "進化", "Evolution explains species change over time."),
        ("natural selection", "自然選択", "Natural selection favors fit traits."),
        ("mutation", "突然変異", "A mutation can alter a gene."),
        ("ecosystem", "生態系", "A forest is a complex ecosystem."),
        ("organelle", "細胞小器官", "Each organelle has a specific job."),
        ("tissue", "組織", "Muscle tissue contracts to move bones."),
        ("heredity", "遺伝", "Heredity passes traits to offspring."),
        ("species", "種", "A new species can arise over time."),
        ("microbe", "微生物", "Microbes live almost everywhere."),
    ]),
    "AI": ("900", [
        ("machine learning", "機械学習", "Machine learning finds patterns in data."),
        ("deep learning", "深層学習", "Deep learning uses many-layered networks."),
        ("neural network", "ニューラルネットワーク", "A neural network mimics neurons."),
        ("supervised learning", "教師あり学習", "Supervised learning uses labeled data."),
        ("unsupervised learning", "教師なし学習", "Unsupervised learning finds structure."),
        ("reinforcement learning", "強化学習", "Reinforcement learning learns from rewards."),
        ("gradient descent", "勾配降下法", "Gradient descent minimizes the loss."),
        ("backpropagation", "誤差逆伝播", "Backpropagation updates the weights."),
        ("overfitting", "過学習", "Overfitting hurts test performance."),
        ("regularization", "正則化", "Regularization reduces overfitting."),
        ("activation function", "活性化関数", "ReLU is a common activation function."),
        ("convolution", "畳み込み", "Convolution extracts image features."),
        ("transformer", "トランスフォーマー", "Transformers power modern language models."),
        ("attention", "注意機構", "Attention weights the most relevant tokens."),
        ("embedding", "埋め込み表現", "Word embeddings capture meaning."),
        ("loss function", "損失関数", "The loss function measures error."),
        ("epoch", "エポック", "Training ran for fifty epochs."),
        ("hyperparameter", "ハイパーパラメータ", "We tuned each hyperparameter."),
        ("classification", "分類", "Spam detection is a classification task."),
        ("regression", "回帰", "Regression predicts a numeric value."),
        ("clustering", "クラスタリング", "Clustering groups similar samples."),
        ("reward", "報酬", "The agent maximizes its reward."),
        ("policy", "方策", "The policy maps states to actions."),
        ("agent", "エージェント", "The agent interacts with its environment."),
        ("tensor", "テンソル", "Data is stored as multi-dimensional tensors."),
        ("inference", "推論", "Inference runs the trained model."),
        ("dataset", "データセット", "We split the dataset into train and test."),
        ("bias", "バイアス", "Model bias can cause unfair outcomes."),
        ("dropout", "ドロップアウト", "Dropout randomly disables neurons."),
        ("fine-tuning", "ファインチューニング", "Fine-tuning adapts a pretrained model."),
    ]),
    "物理": ("900", [
        ("velocity", "速度（ベクトル）", "Velocity has both speed and direction."),
        ("acceleration", "加速度", "Acceleration is the change in velocity."),
        ("momentum", "運動量", "Momentum is mass times velocity."),
        ("kinetic energy", "運動エネルギー", "A moving car has kinetic energy."),
        ("potential energy", "位置エネルギー", "Height gives an object potential energy."),
        ("friction", "摩擦", "Friction slows the sliding box."),
        ("electric field", "電場", "Charges create an electric field."),
        ("magnetic field", "磁場", "A current produces a magnetic field."),
        ("quantum", "量子", "Quantum effects matter at small scales."),
        ("relativity", "相対性理論", "Relativity links space and time."),
        ("wavelength", "波長", "Red light has a long wavelength."),
        ("frequency", "周波数", "Higher frequency means higher pitch."),
        ("amplitude", "振幅", "Amplitude sets the wave's height."),
        ("entropy", "エントロピー", "Entropy tends to increase over time."),
        ("thermodynamics", "熱力学", "Thermodynamics studies heat and energy."),
        ("equilibrium", "平衡", "The forces are in equilibrium."),
        ("torque", "トルク・回転力", "Torque turns the wheel."),
        ("inertia", "慣性", "Inertia keeps an object in motion."),
        ("photon", "光子", "Light is made of photons."),
        ("oscillation", "振動", "The pendulum's oscillation is steady."),
        ("refraction", "屈折", "Refraction bends light in water."),
        ("interference", "干渉", "Two waves can cause interference."),
        ("vector", "ベクトル", "Force is a vector quantity."),
        ("scalar", "スカラー", "Temperature is a scalar quantity."),
        ("density", "密度", "Lead has a high density."),
        ("displacement", "変位", "Displacement is the change in position."),
    ]),
    "化学": ("900", [
        ("atom", "原子", "An atom is the basic unit of matter."),
        ("molecule", "分子", "Water is a simple molecule."),
        ("ion", "イオン", "An ion carries an electric charge."),
        ("covalent bond", "共有結合", "Atoms share electrons in a covalent bond."),
        ("ionic bond", "イオン結合", "Salt is held by ionic bonds."),
        ("catalyst", "触媒", "A catalyst speeds up a reaction."),
        ("oxidation", "酸化", "Rust forms by oxidation."),
        ("reduction", "還元", "Reduction is the gain of electrons."),
        ("pH", "水素イオン指数", "A pH below 7 is acidic."),
        ("mole", "モル", "One mole contains 6.02×10^23 particles."),
        ("concentration", "濃度", "Dilution lowers the concentration."),
        ("solvent", "溶媒", "Water is a common solvent."),
        ("solute", "溶質", "Sugar is the solute in the drink."),
        ("compound", "化合物", "Water is a compound of H and O."),
        ("element", "元素", "Gold is a chemical element."),
        ("isotope", "同位体", "Carbon-14 is an isotope of carbon."),
        ("valence", "原子価", "Carbon has a valence of four."),
        ("polymer", "重合体・ポリマー", "Plastic is a synthetic polymer."),
        ("organic", "有機の", "Organic chemistry studies carbon compounds."),
        ("inorganic", "無機の", "Salt is an inorganic compound."),
        ("titration", "滴定", "Titration finds the concentration."),
        ("equilibrium", "化学平衡", "The reaction reached equilibrium."),
        ("precipitate", "沈殿（物）", "A white precipitate formed."),
        ("reagent", "試薬", "Add the reagent slowly."),
        ("synthesis", "合成", "The synthesis produced a new compound."),
    ]),
    "地学": ("900", [
        ("geology", "地質学", "Geology studies the Earth's structure."),
        ("mineral", "鉱物", "Quartz is a common mineral."),
        ("sediment", "堆積物", "Rivers carry sediment downstream."),
        ("tectonic plate", "プレート", "Tectonic plates move very slowly."),
        ("earthquake", "地震", "An earthquake shook the city."),
        ("volcano", "火山", "The volcano erupted suddenly."),
        ("magma", "マグマ", "Magma rises toward the surface."),
        ("erosion", "侵食", "Erosion wore down the cliffs."),
        ("fossil", "化石", "The fossil is millions of years old."),
        ("stratum", "地層", "Each stratum records a time period."),
        ("crust", "地殻", "The crust is the Earth's outer layer."),
        ("mantle", "マントル", "The mantle lies below the crust."),
        ("seismic wave", "地震波", "Seismic waves reveal the interior."),
        ("glacier", "氷河", "The glacier carved the valley."),
        ("weathering", "風化", "Weathering breaks down rock."),
        ("ore", "鉱石", "Iron is extracted from ore."),
        ("crystal", "結晶", "The crystal has a regular shape."),
        ("plateau", "高原・台地", "The plateau rises above the plain."),
        ("aquifer", "帯水層", "Wells draw water from the aquifer."),
        ("lava", "溶岩", "Lava flowed down the slope."),
        ("epicenter", "震央", "The epicenter was offshore."),
        ("geyser", "間欠泉", "The geyser erupts every hour."),
    ]),
    "地理": ("900", [
        ("latitude", "緯度", "Latitude measures distance from the equator."),
        ("longitude", "経度", "Longitude is measured east or west."),
        ("equator", "赤道", "The equator circles the middle of Earth."),
        ("hemisphere", "半球", "Japan is in the northern hemisphere."),
        ("continent", "大陸", "Africa is a large continent."),
        ("peninsula", "半島", "Italy is a long peninsula."),
        ("basin", "盆地・流域", "The river drains a wide basin."),
        ("delta", "三角州", "The delta forms where the river meets the sea."),
        ("tributary", "支流", "The stream is a tributary of the river."),
        ("watershed", "分水嶺・流域", "Rain in this watershed flows north."),
        ("biome", "生物群系", "A desert is a dry biome."),
        ("tundra", "ツンドラ", "The tundra has frozen ground."),
        ("savanna", "サバンナ", "Lions roam the African savanna."),
        ("monsoon", "モンスーン", "The monsoon brings heavy rain."),
        ("urbanization", "都市化", "Urbanization is reshaping the region."),
        ("demographics", "人口統計", "The town's demographics are changing."),
        ("terrain", "地形", "The terrain is steep and rocky."),
        ("topography", "地形・起伏", "The map shows the topography."),
        ("climate", "気候", "The climate here is mild."),
        ("strait", "海峡", "A narrow strait separates the islands."),
        ("archipelago", "群島", "Japan is an archipelago."),
        ("plain", "平野", "Crops grow well on the plain."),
    ]),
    "法律": ("900", [
        ("jurisprudence", "法理学", "Jurisprudence studies legal theory."),
        ("tort", "不法行為", "A tort is a civil wrong."),
        ("precedent", "判例・先例", "The court followed the precedent."),
        ("negligence", "過失", "The driver was sued for negligence."),
        ("breach", "違反・不履行", "A breach of contract led to a lawsuit."),
        ("sovereignty", "主権", "The nation guards its sovereignty."),
        ("legislation", "立法・法律", "New legislation was passed."),
        ("ratify", "批准する", "The senate will ratify the treaty."),
        ("clause", "条項", "Read the contract's final clause."),
        ("statutory", "法定の・制定法の", "There is a statutory time limit."),
        ("plaintiff", "原告", "The plaintiff sought damages."),
        ("defendant", "被告", "The defendant denied the charge."),
        ("testimony", "証言", "Her testimony was convincing."),
        ("verdict", "評決", "The jury delivered its verdict."),
        ("appeal", "上訴・控訴", "They filed an appeal."),
        ("constitution", "憲法", "The law violated the constitution."),
        ("liable", "法的責任がある", "The firm is liable for the damage."),
        ("indemnity", "補償・賠償", "The clause provides an indemnity."),
        ("jurisdiction", "管轄権", "The case is outside our jurisdiction."),
        ("arbitration", "仲裁", "They chose arbitration over a trial."),
    ]),
    "経済学": ("900", [
        ("supply", "供給", "Higher prices increase supply."),
        ("demand", "需要", "Demand falls when prices rise."),
        ("equilibrium price", "均衡価格", "The market sets an equilibrium price."),
        ("deflation", "デフレ", "Deflation lowers the general price level."),
        ("GDP", "国内総生産", "GDP measures a country's output."),
        ("fiscal policy", "財政政策", "Fiscal policy uses taxes and spending."),
        ("monetary policy", "金融政策", "The central bank sets monetary policy."),
        ("elasticity", "弾力性", "Demand elasticity varies by good."),
        ("marginal cost", "限界費用", "Marginal cost rises with output."),
        ("utility", "効用", "Consumers maximize their utility."),
        ("surplus", "余剰・黒字", "The budget ran a surplus."),
        ("deficit", "赤字・不足", "The trade deficit widened."),
        ("subsidy", "補助金", "Farmers received a subsidy."),
        ("tariff", "関税", "A tariff raises import prices."),
        ("monopoly", "独占", "A monopoly faces no competition."),
        ("oligopoly", "寡占", "A few firms form an oligopoly."),
        ("externality", "外部性", "Pollution is a negative externality."),
        ("macroeconomics", "マクロ経済学", "Macroeconomics studies the whole economy."),
        ("microeconomics", "ミクロ経済学", "Microeconomics studies individual markets."),
        ("opportunity cost", "機会費用", "Time spent here has an opportunity cost."),
        ("aggregate demand", "総需要", "Aggregate demand drives short-run output."),
        ("incentive", "誘因・インセンティブ", "Taxes change people's incentives."),
        ("scarcity", "希少性", "Scarcity forces hard choices."),
        ("equity", "公平・株式", "The policy aims at greater equity."),
    ]),
    "機械工学": ("900", [
        ("stress", "応力", "Stress is force per unit area."),
        ("strain", "ひずみ", "Strain measures deformation."),
        ("fatigue", "疲労（金属）", "Metal fatigue caused the crack."),
        ("tolerance", "公差", "The part is machined to tight tolerance."),
        ("bearing", "軸受・ベアリング", "The bearing reduces friction."),
        ("gear", "歯車", "The gear transmits motion."),
        ("shaft", "シャフト・軸", "The shaft connects the motor."),
        ("lubrication", "潤滑", "Lubrication protects moving parts."),
        ("kinematics", "運動学", "Kinematics describes motion."),
        ("hydraulics", "油圧", "Hydraulics lift the heavy load."),
        ("pneumatics", "空気圧", "Pneumatics drive the cylinder."),
        ("combustion", "燃焼", "Combustion powers the engine."),
        ("viscosity", "粘度", "Oil's viscosity changes with heat."),
        ("yield strength", "降伏強度", "The steel exceeded its yield strength."),
        ("machining", "機械加工", "Machining shapes the metal part."),
        ("actuator", "アクチュエータ", "The actuator moves the valve."),
        ("flange", "フランジ", "Bolts secure the flange."),
        ("vibration", "振動", "Vibration can loosen the bolts."),
        ("alloy", "合金", "Steel is an alloy of iron and carbon."),
        ("rigidity", "剛性", "The frame needs high rigidity."),
        ("thermal expansion", "熱膨張", "Heat causes thermal expansion."),
        ("damper", "ダンパー・制振器", "A damper absorbs the shock."),
    ]),
    "電気電子": ("900", [
        ("voltage", "電圧", "Voltage drives the current."),
        ("current", "電流", "Current flows through the wire."),
        ("resistance", "抵抗", "Resistance limits the current."),
        ("capacitance", "静電容量", "Capacitance stores electric charge."),
        ("inductance", "インダクタンス", "A coil has inductance."),
        ("impedance", "インピーダンス", "Impedance opposes AC current."),
        ("transistor", "トランジスタ", "A transistor switches signals."),
        ("diode", "ダイオード", "A diode allows one-way current."),
        ("amplifier", "増幅器", "The amplifier boosts the signal."),
        ("oscillator", "発振器", "An oscillator generates a waveform."),
        ("rectifier", "整流器", "A rectifier converts AC to DC."),
        ("conductor", "導体", "Copper is a good conductor."),
        ("insulator", "絶縁体", "Rubber is an insulator."),
        ("waveform", "波形", "The oscilloscope shows the waveform."),
        ("modulation", "変調", "Modulation encodes the signal."),
        ("bandwidth", "帯域幅", "The channel has limited bandwidth."),
        ("circuit", "回路", "The circuit was short-circuited."),
        ("semiconductor", "半導体", "Silicon is a semiconductor."),
        ("transformer", "変圧器", "A transformer changes the voltage."),
        ("grounding", "接地・アース", "Proper grounding prevents shocks."),
        ("frequency", "周波数", "The signal's frequency is 50 hertz."),
        ("capacitor", "コンデンサ", "The capacitor smooths the voltage."),
    ]),
    "ソフトウェア工学": ("900", [
        ("algorithm", "アルゴリズム", "A good algorithm runs fast."),
        ("data structure", "データ構造", "A tree is a useful data structure."),
        ("compiler", "コンパイラ", "The compiler reports a syntax error."),
        ("runtime", "実行時・ランタイム", "The bug appears at runtime."),
        ("recursion", "再帰", "Recursion calls the function itself."),
        ("concurrency", "並行性", "Concurrency improves throughput."),
        ("thread", "スレッド", "Each thread runs in parallel."),
        ("deadlock", "デッドロック", "Two threads caused a deadlock."),
        ("refactor", "リファクタリング（する）", "We refactor the messy code."),
        ("repository", "リポジトリ", "Push the code to the repository."),
        ("encapsulation", "カプセル化", "Encapsulation hides internal data."),
        ("inheritance", "継承", "The subclass uses inheritance."),
        ("polymorphism", "多態性", "Polymorphism lets one name act differently."),
        ("abstraction", "抽象化", "Abstraction hides complexity."),
        ("latency", "遅延", "Network latency slows the app."),
        ("throughput", "スループット", "We measured the system's throughput."),
        ("scalability", "拡張性", "Scalability handles more users."),
        ("deployment", "デプロイ・配備", "The deployment failed at midnight."),
        ("dependency", "依存関係", "Update the library dependency."),
        ("framework", "フレームワーク", "We built it on a web framework."),
        ("interface", "インターフェース", "The interface defines the methods."),
        ("middleware", "ミドルウェア", "Middleware handles the requests."),
        ("immutable", "不変の", "Use an immutable object here."),
        ("asynchronous", "非同期の", "The call is asynchronous."),
    ]),
    "生化学": ("900", [
        ("amino acid", "アミノ酸", "Proteins are chains of amino acids."),
        ("peptide", "ペプチド", "A peptide is a short amino-acid chain."),
        ("substrate", "基質", "The enzyme binds its substrate."),
        ("glucose", "グルコース・ブドウ糖", "Cells use glucose for energy."),
        ("lipid", "脂質", "Lipids form cell membranes."),
        ("nucleotide", "ヌクレオチド", "DNA is built from nucleotides."),
        ("hormone", "ホルモン", "Insulin is a hormone."),
        ("coenzyme", "補酵素", "A coenzyme helps the enzyme work."),
        ("hydrolysis", "加水分解", "Hydrolysis breaks the bond with water."),
        ("fermentation", "発酵", "Fermentation makes bread rise."),
        ("glycolysis", "解糖", "Glycolysis breaks down glucose."),
        ("biosynthesis", "生合成", "Biosynthesis builds large molecules."),
        ("denature", "変性させる", "Heat can denature a protein."),
        ("pathway", "経路", "The metabolic pathway has many steps."),
        ("catalyze", "触媒する", "Enzymes catalyze reactions."),
        ("oxidative", "酸化的な", "Oxidative stress damages cells."),
        ("carbohydrate", "炭水化物", "Rice is rich in carbohydrate."),
        ("protein folding", "タンパク質折りたたみ", "Protein folding sets its shape."),
        ("ATP", "ATP（アデノシン三リン酸）", "ATP stores cellular energy."),
        ("antioxidant", "抗酸化物質", "Antioxidants protect cells."),
    ]),
    "保健": ("900", [
        ("nutrition", "栄養", "Good nutrition supports growth."),
        ("immunity", "免疫", "Vaccines build immunity."),
        ("hygiene", "衛生", "Hand hygiene prevents disease."),
        ("cardiovascular", "心血管の", "Exercise improves cardiovascular health."),
        ("respiratory", "呼吸器の", "Smoking harms the respiratory system."),
        ("chronic", "慢性の", "She has a chronic illness."),
        ("acute", "急性の", "He had an acute infection."),
        ("prevention", "予防", "Prevention is better than cure."),
        ("rehabilitation", "リハビリ・回復", "Rehabilitation followed the surgery."),
        ("deficiency", "欠乏（症）", "Vitamin deficiency causes fatigue."),
        ("contagious", "伝染性の", "The flu is highly contagious."),
        ("sanitation", "公衆衛生・衛生設備", "Clean water needs good sanitation."),
        ("dosage", "用量", "Follow the recommended dosage."),
        ("obesity", "肥満", "Obesity raises health risks."),
        ("metabolic", "代謝の", "He has a metabolic disorder."),
        ("wellbeing", "健康・幸福", "Sleep supports mental wellbeing."),
        ("epidemic", "流行（病）", "An epidemic spread through the city."),
        ("vaccination", "予防接種", "Vaccination protects the community."),
        ("disorder", "障害・不調", "An eating disorder needs care."),
        ("screening", "検診・スクリーニング", "Early screening saves lives."),
    ]),
    "医療": ("900", [
        ("diagnosis", "診断", "The diagnosis was confirmed by tests."),
        ("prognosis", "予後", "The prognosis is good."),
        ("pathology", "病理学", "Pathology examines diseased tissue."),
        ("anatomy", "解剖学", "Medical students study anatomy."),
        ("physiology", "生理学", "Physiology studies body functions."),
        ("anesthesia", "麻酔", "She was put under anesthesia."),
        ("antibiotic", "抗生物質", "Antibiotics treat bacterial infections."),
        ("inflammation", "炎症", "Ice reduces inflammation."),
        ("benign", "良性の", "The tumor was benign."),
        ("malignant", "悪性の", "A malignant tumor can spread."),
        ("biopsy", "生検", "A biopsy confirmed the disease."),
        ("transfusion", "輸血", "He needed a blood transfusion."),
        ("immunology", "免疫学", "Immunology studies the immune system."),
        ("lesion", "病変", "The scan revealed a small lesion."),
        ("chronic", "慢性の", "She manages a chronic condition."),
        ("relapse", "再発", "The patient suffered a relapse."),
        ("dehydration", "脱水", "Dehydration can be dangerous."),
        ("infection", "感染", "The wound developed an infection."),
        ("symptom", "症状", "Fever is a common symptom."),
        ("dosage", "投与量", "The doctor adjusted the dosage."),
    ]),
    "論文用語": ("990", [
        ("hypothesis", "仮説", "We tested our main hypothesis."),
        ("methodology", "方法論", "The methodology section explains the design."),
        ("abstract", "要旨・抄録", "Read the abstract for a summary."),
        ("empirical", "経験的・実証的な", "We need empirical evidence."),
        ("qualitative", "定性的な", "We ran a qualitative study."),
        ("quantitative", "定量的な", "Quantitative data were analyzed."),
        ("correlation", "相関", "There is a strong correlation."),
        ("significant", "有意な", "The result was statistically significant."),
        ("variable", "変数", "We controlled the key variables."),
        ("sample", "標本・サンプル", "The sample size was small."),
        ("control group", "対照群", "The control group took a placebo."),
        ("peer review", "査読", "The paper passed peer review."),
        ("citation", "引用", "Every claim needs a citation."),
        ("bibliography", "参考文献", "List the sources in the bibliography."),
        ("thesis", "論文・主張", "She defended her thesis."),
        ("dissertation", "学位論文", "His dissertation took three years."),
        ("paradigm", "パラダイム", "The field underwent a paradigm shift."),
        ("framework", "枠組み", "We propose a new framework."),
        ("replicate", "再現する", "Other labs could replicate the result."),
        ("validity", "妥当性", "We assessed the test's validity."),
        ("reliability", "信頼性", "The measure showed high reliability."),
        ("aggregate", "集計する・総計", "We aggregate the responses."),
        ("infer", "推論する", "We infer a causal link."),
        ("synthesize", "統合する", "The review synthesizes prior work."),
        ("ambiguous", "曖昧な", "The wording is ambiguous."),
        ("rigorous", "厳密な", "The study used a rigorous method."),
    ]),
}


def main() -> int:
    with db() as conn:
        existing = {
            r["english"].lower()
            for r in conn.execute("SELECT english FROM words").fetchall()
        }
        added = filled = 0
        per_field: dict[str, int] = {}
        for domain, (level, items) in FIELDS.items():
            for en, ja, ex in items:
                if en.lower() in existing:
                    conn.execute(
                        "UPDATE words SET example = ? WHERE "
                        "LOWER(english)=LOWER(?) AND COALESCE(example,'')=''",
                        (ex, en),
                    )
                    filled += 1
                    continue
                conn.execute(
                    "INSERT INTO words (english, japanese, part_of_speech, "
                    "example, domain, level) VALUES (?, ?, ?, ?, ?, ?)",
                    (en, ja, "", ex, domain, level),
                )
                existing.add(en.lower())
                added += 1
                per_field[domain] = per_field.get(domain, 0) + 1
    print(f"words: +{added} (例文補充 {filled})")
    print("内訳:", per_field)
    with db() as conn:
        print("単語総数:",
              conn.execute("SELECT COUNT(*) FROM words").fetchone()[0])
    return 0


if __name__ == "__main__":
    sys.exit(main())
